"""The Ring Sea vessels for the Voth city (owner, 2026-10-09: "import new ship models from ring sea"): the Voth
watercraft of kits/ringsea, run as that kit runs them, sealed inside a script of their own so its globals (TAU, clamp,
reseed, KIT, TEX, MAT, ...) meet nothing of the city page's (the same seal as foreign.py).

    ringsea_fragment() -> JS text: window.RINGSEA = { keys: [...], dims: {key: {L, B, H}},
                                                       make(key) -> {group, deckY} | null, tick(t) }

* The kit's own order: its head (the per-type tally), 10-core.js (rng, noise), core/materials 20-textures.js,
  and 22-materials.js (TEX, MAT: the vessels' 'ancient', 'bronze' and 'rust' keys), 30-kit.js,
  40-44 (the vessel core, its textures, hull, rig and parts), then the vessel fragments. The material library binding
  (45x pack, 45y) is left out: the vessels keep their procedural maps, as the kit's ?mat=proc shows them.
* Each vessel is built once (its builder reseeds, so it is the kit's vessel exactly) and every later make() is a
  clone sharing its geometry and materials. The vessel frame: origin amidships on the waterline, bow +x, starboard
  +z; the caller turns it (a heading h along (sin h, cos h) is rotation.y = h - pi/2).
* tick(t) drives the sails' flutter (the kit's one uniform, RS_U.uTime). The oars, swell and under-way motion are
  the kit scene's, not built here.

The files are read live from the repo at build time, never copied.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
RS_SRC = os.path.join(ROOT, 'kits', 'ringsea', 'src')
CORE_MAT = os.path.join(ROOT, 'core', 'materials')
NL = '\n'

KIT_FILES = ['10-core.js', '12-stats.js', '20-textures.js', '22-materials.js', '30-kit.js', '40-rs-core.js', '41-rs-tex.js',
             '42-rs-hull.js', '43-rs-rig.js', '44-rs-parts.js']
VESSELS = ['77-rs-voth-hulk.js', '81-rs-voth-junk.js', '83-rs-voth-ferry.js', '84-rs-voth-taxi.js', '85-rs-voth-barge.js',
           '86-rs-voth-pleasure.js', '87-rs-voth-dhow.js']


def _read(p):
    with open(p, encoding='utf-8') as f:
        return f.read()


def _path(f):
    for d in (RS_SRC, CORE_MAT):
        p = os.path.join(d, f)
        if os.path.exists(p):
            return p
    raise FileNotFoundError(f)


def _head_js():
    """the JS of the kit's 00-head.html: everything after its last <script>"""
    h = _read(os.path.join(RS_SRC, '00-head.html'))
    return h[h.rindex('<script>') + len('<script>'):].replace('</script>', '')


def ringsea_fragment():
    body = [_head_js()]
    for f in sorted(KIT_FILES) + VESSELS:
        p = _path(f)
        body.append('/* ---- %s ---- */' % os.path.relpath(p, ROOT).replace(os.sep, '/') + NL + _read(p))
    js = NL.join(body).replace("const ERRS=document.getElementById('errs');", '')
    return ''.join([
        '/* GENERATED by settlements/streetlab/ringsea.py: the Voth watercraft of kits/ringsea, as that kit builds them */', NL,
        'var RINGSEA = { keys: [], dims: {}, make: function () { return null; }, tick: function () {} };', NL,
        '(function(){', NL,
        '  /* the kit runs against a window of its own: its error hooks and probes stay in here */', NL,
        '  var __own = { addEventListener: function(){}, onerror: null };', NL,
        '  var window = new Proxy(globalThis.window, { get: function (t, k) { if (k in __own) return __own[k]; var v = t[k]; return typeof v === "function" && !/^[A-Z]/.test(String(k)) ? v.bind(t) : v; },', NL,
        '    set: function (t, k, v) { __own[k] = v; return true; }, has: function (t, k) { return k in __own || k in t; } });', NL,
        '  var scene = new THREE.Group(), renderer = { capabilities: { getMaxAnisotropy: function(){ return 4; } } };', NL,
        '  var ERRS = { style: {}, textContent: "" };', NL,
        js, NL,
        '  function reportErr(m) { if (typeof console !== "undefined") console.error("RINGSEA: " + m); }', NL,
        '  var made = {};', NL,
        '  RINGSEA.keys = RS.order.slice();', NL,
        '  RS.order.forEach(function (k) { var D = RS.defs[k]; RINGSEA.dims[k] = { L: D.L, B: D.B, H: D.H, name: D.name }; });', NL,
        '  RINGSEA.make = function (key) {', NL,
        '    var D = RS.defs[key]; if (!D) return null;', NL,
        '    if (!made[key]) { try { var r = D.build(); made[key] = { group: r.group, deckY: r.deckY }; } catch (e) { reportErr(key + ": " + (e.stack || e)); made[key] = { error: String(e) }; } }', NL,
        '    var M = made[key]; if (!M.group) return null;', NL,
        '    var g = M.group.clone(); g.userData = { kind: "vessel", key: key, deckY: M.deckY }; return { group: g, deckY: M.deckY };', NL,
        '  };', NL,
        '  RINGSEA.tick = function (t) { RS_U.uTime.value = t; };', NL,
        '})();', NL])


if __name__ == '__main__':
    print('%d KB' % (len(ringsea_fragment()) // 1024))
