// Beach City: entry point for beachcity.html. Fan work — Steven Universe belongs to Rebecca Sugar and Cartoon
// Network, nothing from the show is used, and every shape is this project's own. The ground, the streets and
// the houses are generated by tools/make-beachcity.py and drawn by the engine Chicago and New York share; the
// temple, the beach house, the lighthouse, the shops and Funland are landmarks.js; the surf, the boardwalk, the
// people, Mayor Dewey's van and the gulls are life.js; and what turns up every minute or two is events.js.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {boot} from '../core/shell.js';
import {build} from '../engine/build.js';
import {sceneRows} from '../core/layout.js';
import {landmarks} from './landmarks.js';
import {life} from './life.js';
import {events} from './events.js';
import {details} from './details.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({
  lines:[
    'Fan work. Steven Universe belongs to Rebecca Sugar and Cartoon Network; every shape here is this project\'s own geometry.',
    'Beach City is on the Delmarva peninsula, facing the Atlantic.',
    'The temple is cut into the cliff at the tip of Lighthouse Park. Steven\'s house is built over its door.',
    'The Big Donut has the biggest donut in Delmarva on its roof.',
    'Funland is out on a pier in Rehoboth Bay, on the north side of town. You can see the wheel from everywhere.',
    'The lighthouse is on the tip of the park, above the temple, at the end of a path across the grass.',
    'The boardwalk runs along the ocean beach on the south side of town, with the shops facing onto it.',
    'After dark the lighthouse turns, the signs light up and the wheel is a ring of lamps.',
    'Every minute or two something turns up: a ship in the shape of a hand, a giant eye, a pink lion. The Events button fires one now.',
    "Mayor Dewey's van goes round and round the town. Click it.",
  ],
  prefix:'finding Beach City… ',labels:{'map-data':'reading the coast',ground:'laying the beach',buildings:'building the town',details:'',
    landmarks:'cutting the temple',el:'',traffic:'',ui:'opening the boardwalk',shore:'letting the surf in',dressing:'painting the doors',events:'keeping watch'}});

// The layout the tests check: everything built, as it stands before anything moves.
function fingerprint(api){
  const {THREE,ctx,scene}=api;
  ctx.lotList=sceneRows(THREE,scene,{skip:o=>o.userData.noFingerprint||o.isSprite||o.isSky});
}

(async()=>{
  // the plan of the town, which the models need before the engine calls them
  const C0=await fetch('data/cities/beachcity.json').then(r=>r.json()).catch(()=>({}));
  const plan=await fetch(C0.plan||'data/cities/beachcity-plan.json').then(r=>r.json()).catch(e=>{report('town plan',e);return null;});
  const ctx=window._iz={defaultCity:'beachcity',plan,models:[landmarks],
    extras:[{name:'dressing',fn:details},{name:'shore',fn:life},{name:'events',fn:events},{name:'fingerprint',fn:fingerprint}]};
  boot(()=>build(ctx));
})();
