// Rivendell: entry point for rivendell.html. Fan work — Tolkien's world belongs to the Tolkien Estate, nothing
// from any book, film or game is used, and every shape is this project's own. Made after Tolkien's text and his
// own drawings of the place. The ground and the plan of the valley are generated by tools/make-rivendell.py;
// the engine is the one Chicago and New York share, and it draws the sky, the light and the paths. The rest is
// here: the look of the ground (ground.js), the river and the falls (water.js), the woods (woods.js), the house
// and everything else built (landmarks.js), and what moves (life.js).
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {boot} from '../core/shell.js';
import {build} from '../engine/build.js';
import {sceneRows} from '../core/layout.js';
import {landmarks} from './landmarks.js';
import {ground} from './ground.js';
import {water} from './water.js';
import {woods} from './woods.js';
import {life} from './life.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({
  lines:[
    'Fan work. Tolkien\'s world belongs to the Tolkien Estate; every shape here is this project\'s own geometry.',
    '"They came to the edge of a steep fall in the ground so suddenly that Gandalf\'s horse nearly slipped."',
    'The moor is "the colour of heather and crumbling rock, with patches and slashes of grass-green".',
    'Firs on the rims, and lower down "the trees changed to beech and oak".',
    '"A narrow bridge of stone without a parapet, as narrow as a pony could well walk on."',
    'The valley runs east and west. The house is on the north side, and its windows look south across the ravine.',
    'Every stream on the moor comes over the rim. There are a great many streams.',
    'Tolkien drew the house with a square tower, a steep red roof and a loggia of columns and curved arches.',
    'The Hall of Fire has a fire in it all the year round, with carven pillars on either side of the hearth.',
    'The Season button moves between Tolkien\'s summer and the film\'s autumn.',
  ],
  prefix:'finding Rivendell… ',labels:{'map-data':'reading the moor',ground:'cutting the cleft',buildings:'',details:'',
    landmarks:'building the house',el:'',traffic:'',ui:'lighting the lanterns',rivground:'colouring the rock',rivwater:'letting the water in',rivwoods:'planting the woods',life:'lighting the lanterns'}});

// The season: 0 is Tolkien's summer, 1 the film's autumn; the ground and the woods both follow it.
function season(api){
  const {ctx}=api;
  const set=v=>{ctx.rivSeason=v;if(ctx.rivGround)ctx.rivGround.setSeason(v);if(ctx.rivWoods)ctx.rivWoods.setSeason(v);};
  const m=/(^|&)autumn(&|$)/.test(api.HASH0||'');set(m?1:0);
  api.onUI(({ui,mkBtn})=>{
    const b=mkBtn(m?'Season: autumn':'Season: summer',ui,()=>{const v=ctx.rivSeason>0.5?0:1;set(v);b.textContent=v?'Season: autumn':'Season: summer';});
    b.title='Tolkien\'s summer, or the film\'s autumn';});
}
// The layout the tests check: everything built, as it stands before anything moves.
function fingerprint(api){
  const {THREE,ctx,scene}=api;
  ctx.lotList=sceneRows(THREE,scene,{skip:o=>o.userData.noFingerprint||o.isSprite||o.isSky});
}

(async()=>{
  // the plan of the valley, which the models need before the engine calls them
  const C0=await fetch('data/cities/rivendell.json').then(r=>r.json()).catch(()=>({}));
  const valley=await fetch(C0.valley||'data/cities/rivendell-valley.json').then(r=>r.json()).catch(e=>{report('valley plan',e);return null;});
  const ctx=window._iz={defaultCity:'rivendell',valley,models:[landmarks],
    extras:[{name:'rivground',fn:ground},{name:'rivwater',fn:water},{name:'rivwoods',fn:woods},{name:'life',fn:life},{name:'season',fn:season},{name:'fingerprint',fn:fingerprint}]};
  boot(()=>build(ctx));
})();
