// Arrakeen: entry point for arrakeen.html. Fan work — Dune belongs to the Herbert estate, nothing from any
// book, film or game is used, and every shape is this project's own. The basin, the Shield Wall, the dune
// sea and the city are generated by tools/make-arrakeen.py; the engine is the one Chicago and New York share.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {build} from '../engine/build.js';
import {landmarks} from './landmarks.js';
import {life} from './life.js';
import {desert} from './desert.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({prefix:'raising Arrakeen… ',labels:{'map-data':'reading the basin',ground:'laying the rock',buildings:'building the town',details:'planting the garden',landmarks:'raising the Residency',el:'',traffic:'',ui:'opening the windtraps'}});
const ctx=window._iz={defaultCity:'arrakeen',models:[landmarks],
  extras:[{name:'life',fn:life},{name:'desert',fn:desert}]};
requestAnimationFrame(()=>setTimeout(()=>{build(ctx).catch(e=>{report('build',e);const l=document.getElementById('loading');if(l)l.remove();});},30));
