// Rivendell: entry point for rivendell.html. Fan work — Tolkien's world belongs to the Tolkien Estate,
// nothing from any book, film or game is used, and every shape is this project's own. The cleft, the moor
// and the Bruinen are generated by tools/make-rivendell.py; the engine is the one Chicago and New York share.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {build} from '../engine/build.js';
import {landmarks} from './landmarks.js';
import {life} from './life.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({prefix:'finding Rivendell… ',labels:{'map-data':'reading the moor',ground:'cutting the cleft',buildings:'raising the halls',details:'planting the valley',landmarks:'opening the Hall of Fire',el:'',traffic:'',ui:'lighting the lanterns'}});
const ctx=window._iz={defaultCity:'rivendell',models:[landmarks],extras:[{name:'life',fn:life}]};
requestAnimationFrame(()=>setTimeout(()=>{build(ctx).catch(e=>{report('build',e);const l=document.getElementById('loading');if(l)l.remove();});},30));
