// Isengard: entry point for isengard.html. Fan work — Tolkien's world belongs to the Tolkien Estate, nothing from
// any book, film or game is used, and every shape is this project's own. The valley of Nan Curunir, the Isen and
// the eaves of Fangorn are generated by tools/make-isengard.py; the engine is the one Chicago and New York share.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {boot} from '../core/shell.js';
import {build} from '../engine/build.js';
import {landmarks} from './landmarks.js';
import {hosts} from '../middleearth/hosts.js';
import {mode} from './mode.js';
import {works} from './works.js';
import {isen} from './isen.js';
import {treegarth} from './treegarth.js';
import {fangorn} from './fangorn.js';
import {events} from './events.js';
import {dam} from './dam.js';
import {details} from './details.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({
  lines:[
    'Fan work. Tolkien\'s world belongs to the Tolkien Estate; every shape here is this project\'s own geometry.',
    'A mile from rim to rim, and one way in: a tunnel under an arch in the southern wall, with doors of iron at either end.',
    'Five hundred feet of black rock: four piers welded into one, opening at the top into horns as sharp as spear-points.',
    'The plain was green once, with orchards. Now it is paved, and bored with shafts, and the domes over them smoke.',
    'The Isen comes in under the wall at the north-east, through a grating, and goes out beside the gate.',
    'Press Saruman to see what the Ents made of it afterwards.',
    'Fangorn is on the hills to the east. Its eaves are ragged where the furnaces have been fed.',
  ],
  prefix:'raising Isengard… ',labels:{'map-data':'reading Nan Curunir',ground:'cutting the valley',buildings:'building the forges',details:'felling the valley',landmarks:'raising Orthanc',el:'',traffic:'',ui:'opening the doors',isen:'letting in the Isen',works:'lighting the furnaces',treegarth:'planting the Treegarth',fangorn:'growing Fangorn',events:'watching from the walls',dam:'damming the Isen',details:'hanging the White Hand'}});
const ctx=window._iz={defaultCity:'isengard',models:[landmarks],extras:[{name:'isen',fn:isen},{name:'dam',fn:dam},{name:'fangorn',fn:fangorn},{name:'works',fn:works},{name:'treegarth',fn:treegarth},{name:'details',fn:details},{name:'hosts',fn:hosts},{name:'mode',fn:mode},{name:'events',fn:events}]};
boot(()=>build(ctx));
