// The Shire: entry point for shire.html. Fan work — Tolkien's world belongs to the Tolkien Estate, no asset from
// any book, film or game is used, and every shape is this project's own. Made after Tolkien's text and his
// watercolour of Hobbiton. The ground and the plan are generated by tools/make-shire.py; the engine draws the
// sky and the light; the rest is here: the patchwork and the lanes (ground.js), the Water (water.js), hedges,
// trees and livestock (country.js), the holes (holes.js), the houses, the mill, the Grange and the Green Dragon
// (buildings.js), the work in the fields (fields.js), what moves (life.js), and Bilbo's party (party.js). Film
// details - the Party Tree and its pond, Sam's yellow door, the double-arched bridge, Gandalf's cart - sit beside Tolkien's where both exist.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {boot} from '../core/shell.js';
import {build} from '../engine/build.js';
import {sceneRows} from '../core/layout.js';
import {ground} from './ground.js';
import {water} from './water.js';
import {country} from './country.js';
import {holes} from './holes.js';
import {buildings} from './buildings.js';
import {life} from './life.js';
import {party} from './party.js';
import {fields} from './fields.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({
  lines:[
    'Fan work. Tolkien\'s world belongs to the Tolkien Estate; every shape here is this project\'s own geometry.',
    '"In a hole in the ground there lived a hobbit."',
    '"It had a perfectly round door like a porthole, painted green, with a shiny yellow brass knob in the exact middle."',
    'The Water is "no more than a winding black ribbon, bordered with leaning alder-trees".',
    'The mill at the foot of the Hill is the mill at Sarehole, where Tolkien lived as a boy.',
    'Tolkien called the Shire "more or less a Warwickshire village of about the period of Queen Victoria\'s Diamond Jubilee".',
    'Sam Gamgee\'s door at No. 3 Bagshot Row is yellow, as it is in the films.',
    '"a Party of Special Magnificence"',
    'The Green Dragon is a mile south-east of the bridge, on the Bywater Road.',
    'The Shire is forty leagues from the Far Downs to the Brandywine Bridge. This is a few miles of it.',
    'Every field has a hedge round it, and from any height the country is a net of dark lines.',
  ],
  prefix:'finding the Shire… ',labels:{'map-data':'reading the Westfarthing',ground:'rolling the hills',buildings:'',details:'',landmarks:'',el:'',traffic:'',
    ui:'lighting the lamps',shireground:'ploughing the fields',shirewater:'filling the Water',country:'planting the hedges',holes:'digging the holes',shirebuildings:'building the mill',life:'opening the Green Dragon',party:'putting up the pavilions',fields:'bringing in the harvest'}});

// Clicking a building or Bag End: the engine only looks at its own landmarks, so these are ours.
function cards(api){
  const {THREE,ctx,camera}=api;const el=api.renderer&&api.renderer.domElement;if(!el)return;
  let down=null;el.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});
  el.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;
    const ray=new THREE.Raycaster(),ndc=new THREE.Vector2(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight)*2+1);ray.setFromCamera(ndc,camera);
    const ts=[];api.scene.traverse(o=>{if(o.isMesh&&o.name==='terrain')ts.push(o);});const hit=ray.intersectObjects(ts,false)[0];if(!hit)return;
    const c=(ctx.shireCards||[]).map(k=>({k,d:Math.hypot(k.x-hit.point.x,k.z-hit.point.z)-(k.r||12)})).sort((a,b)=>a.d-b.d)[0];
    if(c&&c.d<8&&api.showCard)setTimeout(()=>api.showCard(c.k.info),0);});
}
// The viewpoints, worked out from the plan rather than written into the city file, so that regenerating the
// ground (which moves the Hill, the holes and everything on them) never leaves a camera inside a hillside.
function views(api){
  const {C,ctx,groundH,toLatLon}=api;const V=ctx.plan;if(!V)return;
  const S=V.sites,be=V.holes.find(h=>h.bagEnd),row=V.holes.filter(h=>h.row==='Bagshot Row'),bm=row[Math.floor(row.length/2)]||be;
  const f=h=>[Math.sin(h.face),Math.cos(h.face)];
  const at=(x,z,up)=>{const [la,lo]=toLatLon(x,z);return [la,lo,groundH(x,z)+up];};
  const abs=(x,z,y)=>{const [la,lo]=toLatLon(x,z);return [la,lo,y];};
  const out={};
  out['The Hill: Hobbiton-across-the-Water']=[at(S.bridge.x-20,S.bridge.z+60,26),abs(S.hill.x,S.hill.z+80,S.hill.y-30)];
  {const [fx,fz]=f(be);out['Bag End']=[at(be.x+fx*21,be.z+fz*21,4.2),abs(be.x,be.z,be.y+1.2)];
   out["From Bag End's door"]=[abs(be.x+fx*3.4,be.z+fz*3.4,be.y+1.5),abs(be.x+fx*300,be.z+fz*300,be.y-45)];}
  {const [fx,fz]=f(bm);out['Bagshot Row']=[at(bm.x+fx*34,bm.z+fz*34,5),abs(bm.x,bm.z,bm.y+1)];}
  out['The Party Field']=[at(S.partyTree.x+20,S.partyTree.z-115,22),abs(S.partyTree.x,S.partyTree.z,S.partyTree.y+10)];
  out["Bilbo's party"]=[at(S.partyTree.x+62,S.partyTree.z-52,7),abs(S.partyTree.x-10,S.partyTree.z-4,S.partyTree.y+6)];
  {const sam=V.holes.find(h=>h.sam);if(sam){const [fx,fz]=f(sam);out['No. 3 Bagshot Row']=[at(sam.x+fx*12,sam.z+fz*12,2.4),abs(sam.x,sam.z,sam.y+1)];}}
  out['The mill and the bridge']=[at(S.mill.x-10,S.mill.z+34,4),abs(S.mill.x-6,S.mill.z,S.mill.y+3.5)];
  // the Green Dragon from across the road, where its front is: the inn is turned 0.55 rad (buildings.js)
  {const G=S.greenDragon,c=Math.cos(0.55),sn=Math.sin(0.55),P=(u,w)=>[G.x+c*u-sn*w,G.z+sn*u+c*w];const [cx,cz]=P(7,27);
   out['The Green Dragon']=[at(cx,cz,6),abs(G.x,G.z,G.y+4)];}
  // the nearest farm to the bridge, from across its yard; and the nearest harvest field, with the stooks in it
  {const fm=(V.farms||[]).filter(f=>f.length>2).sort((a,b)=>Math.hypot(a[0],a[1])-Math.hypot(b[0],b[1]))[0];
   if(fm){const [x,z,r]=fm,c=Math.cos(r),sn=Math.sin(r),P=(u,w)=>[x+c*u-sn*w,z+sn*u+c*w];const [cx,cz]=P(2,52),[tx,tz]=P(6,10);
     out['A farm']=[at(cx,cz,9),at(tx,tz,1.5)];}}
  {const st=(V.work&&V.work.stooks)||[];let b=-1,bd=1e9;for(let i=0;i<st.length;i+=3){const d=Math.hypot(st[i]-300,st[i+1]+100);if(d<bd){bd=d;b=i;}}
   if(b>=0){const x=st[b],z=st[b+1],th=st[b+2],ax=Math.cos(th),az=Math.sin(th);out['Harvest']=[at(x-ax*30+Math.sin(th)*20,z-az*30-Math.cos(th)*20,5),at(x+ax*10,z+az*10,1)];}}
  out['Bywater Pool']=[at(S.pool.x+30,S.pool.z+200,22),abs(S.pool.x,S.pool.z,S.pool.y)];
  out['The Great East Road']=[at(200,1620,14),at(1400,1450,4)];
  out['Over Hobbiton']=[abs(420,260,420),abs(-100,-300,130)];
  out['The Westfarthing from above']=[abs(0,2400,2600),abs(0,100,0)];
  C.views=out;
}
function fingerprint(api){ctx0.lotList=sceneRows(api.THREE,api.scene,{skip:o=>o.userData.noFingerprint||o.isSprite});}
let ctx0=null;

(async()=>{
  const C0=await fetch('data/cities/shire.json').then(r=>r.json()).catch(()=>({}));
  const plan=await fetch(C0.plan||'data/cities/shire-plan.json').then(r=>r.json()).catch(e=>{report('plan',e);return null;});
  const ctx=ctx0=window._iz={defaultCity:'shire',plan,
    extras:[{name:'shireground',fn:ground},{name:'shirewater',fn:water},{name:'country',fn:country},{name:'holes',fn:holes},
      {name:'shirebuildings',fn:buildings},{name:'fields',fn:fields},{name:'life',fn:life},{name:'party',fn:party},{name:'views',fn:views},{name:'fingerprint',fn:fingerprint},{name:'cards',fn:a=>a.onUI(()=>cards(a))}]};
  boot(()=>build(ctx));
})();
