// ================================================================= FURNITURE: placed from the catalog (core/furnish), not drawn by the world
// (forked from kits/scyvoi/src/91f-furnish.js). Everything in the arcology that is not the arcology itself (beds, bunks,
// lockers, tables, benches, consoles, lamps, crates, the gibbet by Ruephus's door) is a master-catalog piece, placed as
// data and built by the catalog's own code through KratorFurniture (38-furniture-bundle.js, generated by build.py).
//
// THE FRAME. Pieces are laid out level in the HULL frame (12-nr-world.js), drawn into a batch in that frame, and the batch's
// meshes carry NR_HULL, so a bed stands square on its listing deck. A record (core/furnish) keeps:
//   x y z ry       the WORLD position and heading (the heading ignores the hull's 0.8/0.4 degree list and trim)
//   lx ly lz lry   the HULL frame: the exact pose is NR_HULL applied to these
// A builder calls, in its current frame (the def's, under the hull):
//   FURNISH(key, lx, ly, lz, lry, {v, seed, setting})     a piece standing at (lx, ly, lz), its front turned lry
// and the furnishing pass (70) calls FURNISH_H(key, hx, hy, hz, hry, o, ctx) with hull coordinates directly.
// Pieces the interiors kit places as TEMPLATES (the cabins, the deck buildings' rooms: 70-nr-interiors.js) are records
// here too, but drawn instanced by that pass. A key the catalog lacks is counted, not thrown (SVF.missing).
KratorFurniture.setDetail(.5);
const SVF=KFURN.create(Object.assign(KFURN.flags(true),{
 catalog:KFURN.catalogOf(KratorFurniture),interiors:KratorInteriors,
 seed:(o,ctx)=>((ctx.seed||1)*100+(ctx.list?ctx.list.length:0)+1)>>>0,
 draw:(rec,ctx,o)=>{if(ctx.instanced)return;   /* a template's piece: drawn by the instanced pass */
  KratorFurniture.setDetail(ctx.detail||.5);
  const r=SVF.batch.place(rec.key,rec.lx,rec.ly,rec.lz,rec.lry,{variant:rec.variant,seed:rec.seed,wealth:ctx.wealth,building:rec.building,setting:rec.setting});
  if(r.error)reportErr('furniture '+rec.key+': '+r.error);
  for(const L of (r.lights||[])){const w=nrH2W(L.x,L.y,L.z);nrHalo(w,/fire|brazier|stove|forge|hearth|kiln/.test(rec.key));}}}));
SVF.lightCount=0;
/* a light the furniture carries, as a halo (91n-night.js): fires big and warm, lamps small */
function nrHalo(w,fire){const k=Math.round(w[0]/.6)+','+Math.round(w[1]/.6)+','+Math.round(w[2]/.6);if(HALOKEY.has(k))return;HALOKEY.add(k);
 const c=hc(fire?0xff8a30:0xffc878);HALOS.push({x:w[0],y:w[1],z:w[2],r:c.r,g:c.g,b:c.b,big:!!fire});SVF.lightCount++;}
function svfNewBatch(){KFURN.useBatch(SVF,KratorFurniture,KratorInteriors);SVF.placed=[];SVF.missing={};SVF.cfg.tags=SVTAGS;SVF.lightCount=0;}
function svfWealth(rec){const w=rec&&rec.tags&&rec.tags.wealth;return w==='rich'?.85:w==='poor'?.25:w==='middle'?.5:.45;}
const _fv=new THREE.Vector3(),_fd=new THREE.Vector3(),_fm3=new THREE.Matrix3();
function FURNISH(key,lx,ly,lz,lry,o){o=o||{};if(!CURREC){reportErr('FURNISH '+key+' outside a builder');return null;}
 if(PLACE_DRY)return null;lry=lry||0;
 _fv.set(lx,ly||0,lz).applyMatrix4(CM);_fm3.setFromMatrix4(CM);_fd.set(Math.sin(lry),0,Math.cos(lry)).applyMatrix3(_fm3);
 const h=nrW2H(_fv.x,_fv.y,_fv.z),hd=nrW2H(_fd.x+NR_HULL.t[0],_fd.y+NR_HULL.t[1],_fd.z+NR_HULL.t[2]);
 const c=CURREC,seed=(DEFS[c.key].seed*7+(c.v|0)*131+(((Math.round(lx*10)*73856093)^(Math.round(lz*10)*19349663))>>>0)%9973)>>>0;
 return FURNISH_H(key,h[0],h[1],h[2],Math.atan2(hd[0],hd[2]),o,{building:c.tid,list:c.furniture,seed,wealth:o.wealth!=null?o.wealth:svfWealth(c),room:o.room||null});}
/* in the HULL frame, outside any builder: (hx, hy, hz) and the heading hry about the hull's up */
function FURNISH_H(key,hx,hy,hz,hry,o,ctx){o=o||{};ctx=ctx||{};
 if(!KratorFurniture.has(key)){if(!ctx.dry)SVF.missing[key]=(SVF.missing[key]||0)+1;return null;}
 const w=nrH2W(hx,hy,hz);
 return SVF.place(key,w[0],w[1],w[2],nrHeadingW(hry),Object.assign({setting:'indoor'},o),[+hx.toFixed(3),+hy.toFixed(3),+hz.toFixed(3),+hry.toFixed(4)],ctx);}
function FURNISH_HANG(key,lx,topY,lz,lry,o){const A=KratorFurniture.FURN_BY_KEY[key];if(!A){if(!PLACE_DRY)SVF.missing[key]=(SVF.missing[key]||0)+1;return null;}
 const dm=KratorFurniture.entryDims(A,(o&&o.v)|0);return FURNISH(key,lx,topY-dm.h,lz,lry,o);}
/* the height of a catalog piece (a table top), its declared h, or the fallback */
function svfH(key,v,dflt){const A=KratorFurniture.FURN_BY_KEY[key];return A?KratorFurniture.entryDims(A,v|0).h:dflt;}
/* ---- DETAIL MAPS on the furniture (after settlements/girder/src/48-detail.js): a library set per render family, projected
   triplanar from the piece's own position (the furniture meshes carry no UVs); f_<family> in materials.json */
function svfDetail(mt){const fam=mt.userData.family,L=KMAT.mode==='lib'&&fam?KMAT.packed('noahs-regret','f_'+fam):null;if(!L||!L.map||mt.isMeshBasicMaterial)return false;
 const T=KMAT.textures(L,{aniso:TEXANISO}),gain=1/Math.max(.05,Math.pow(L.mean==null?.5:L.mean,2.2)),tile=1/((L.scale&&L.scale[0])||1);
 mt.map=T.map;mt.normalMap=null;
 matHook(mt,'fdet|'+fam,sh=>{sh.uniforms.uDetTile={value:tile};sh.uniforms.uDetGain={value:gain};
  sh.vertexShader=sh.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vDetP;varying vec3 vDetN;').replace('#include <uv_vertex>','#include <uv_vertex>\nvDetP=position;vDetN=normal;');
  sh.fragmentShader=sh.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vDetP;varying vec3 vDetN;uniform float uDetTile;uniform float uDetGain;')
   .replace('#include <map_fragment>',['#ifdef USE_MAP','vec3 dW=pow(abs(normalize(vDetN))+1e-4,vec3(4.0));dW/=(dW.x+dW.y+dW.z);vec3 dP=vDetP*uDetTile;',
    'vec4 texelColor=texture2D(map,dP.zy)*dW.x+texture2D(map,dP.xz)*dW.y+texture2D(map,dP.xy)*dW.z;texelColor=mapTexelToLinear(texelColor);',
    'diffuseColor.rgb*=texelColor.rgb*uDetGain;','#endif'].join('\n'));});
 return true;}
/* make a flushed furniture group ready: linear colours, detail maps, the deck cut, shadows; carry the hull frame */
function svfPrepare(g,hullFrame){if(hullFrame){g.matrixAutoUpdate=false;g.matrix.fromArray(NR_HULL.m16);g.matrixWorldNeedsUpdate=true;}
 g.userData.furniture=true;g.traverse(m=>{if(!m.isMesh)return;const f=m.material.userData.family;
  m.castShadow=f!=='glow'&&f!=='glass';m.receiveShadow=true;KFURN.linearColours(m.geometry);
  if(!m.material.map)svfDetail(m.material);if(!m.material.userData.nrCut){m.material.userData.nrCut=1;nrCutHook(m.material,f!=='glass'&&f!=='glow');}});return g;}
// ---- the batch becomes meshes once per world build, after every def is placed and the rooms are furnished
const svfBuildWorld=buildWorld;
buildWorld=function(){svTagsReset();svfNewBatch();const t0=performance.now();const W0=svfBuildWorld();
 if(typeof nrInteriors==='function'){try{nrInteriors();}catch(e){reportErr('interiors: '+(e.stack||e));}}
 const g=SVF.group=svfPrepare(SVF.batch.flush(HULLG),true);
 if(window._build)window._build.furniture={placed:SVF.placed.length,tris:Math.round(SVF.batch.tris),missing:Object.assign({},SVF.missing),lights:SVF.lightCount,ms:Math.round(performance.now()-t0)};
 if(typeof nightRebuild==='function')nightRebuild();
 return W0;};
