#!/usr/bin/env python3
"""Build dist/fauna.html (the Fauna kit sheet) and dist/krator-fauna.js (the bundle alone).

The kit's own files stay at the top of this folder, where other builds read them through fauna_bundle.py
(as the catalog's furniture is read through furniture_bundle.py); src/ holds only the page around them:

  src/00-head.html          page head, toolbar, error panel, three.js r128 loader
  kits/catalog/krator-asset-engine.js   the catalog's page engine (scene, camera, orbit/WASD, ground, frame
                            loop), read by path, unchanged
  <bundle>                  fauna_bundle.bundle(): ONE closure exposing only KratorFauna (GENERATED)
  src/80-sky-hash.js        h3(), which KratorSky reads (VENDORED from kits/catalog/src)
  src/81-sky.js             KratorSky, the standard sky (VENDORED from settlements/iziz/src)
  src/90-sheet.js           lays out every animal, variant and breed through the public API; Idle, Graze, Walk
  src/92-hover.js           hover inspector (name, tags, traits, yields, life), toggled with T
  src/93-polygon.js         polygon tool (click the ground for world x,z), toggled with P
  src/99-tail.html

Everything between head and tail goes into ONE <script>, so a top-level name declared in two files would
clobber or throw: build.py refuses that (the bundle counts as declaring only KratorFauna), refuses an animal key
registered twice, and runs `node --check` on the script when node exists. Deterministic: build-manifest.json
holds a sha1 per input.

Usage:  python3 build.py [--no-checks] [--vendor-check] [--groups livestock,mounts --out scratch/x.html]
        (--groups builds a page with only those species files; --out writes it elsewhere and leaves dist/ alone)
"""
import hashlib, json, os, re, subprocess, sys

# Port lint (GODOT-PLAN.md, Phase 0): a fragment PORT.md tags [G data] must not touch the browser.
import os as _os, subprocess as _sp, sys as _sys
_cp = _os.path.join(_os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))), 'tools', 'check_port.py')
if _os.path.isfile(_cp) and '--no-checks' not in _sys.argv and \
        _sp.call([_sys.executable, _cp, '--quiet', _os.path.dirname(_os.path.abspath(__file__))]) != 0:
    _sys.exit('build.py: the port lint failed (tools/check_port.py); fix the fragment or retag it in PORT.md')

try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(HERE, 'src')
DIST = os.path.join(HERE, 'dist')
OUT = 'fauna'
ENGINE = os.path.join(ROOT, 'kits', 'catalog', 'krator-asset-engine.js')
BUNDLE = '50-fauna-bundle.js'              # virtual: generated by fauna_bundle.py, never written to src/
sys.path.insert(0, HERE)
import fauna_bundle  # noqa: E402

VENDORED = {'81-sky.js': os.path.join(ROOT, 'settlements', 'iziz', 'src', '81-sky.js'),
            '80-sky-hash.js': os.path.join(ROOT, 'kits', 'catalog', 'src', '80-sky-hash.js')}

RE_DECL = re.compile(r'^(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)', re.M)
RE_DECL_MULTI = re.compile(r'^(?:const|let|var)\s+[^;\n]*?,\s*([A-Za-z_$][\w$]*)\s*=', re.M)
RE_VEH = re.compile(r'^ANIMAL\(\{\s*key\s*:\s*[\'"]([^\'"]+)[\'"]', re.M)


def read(p):
    with open(p, encoding='utf-8', newline='') as fh:
        return fh.read()


def check(parts):
    errs, decl = [], {}
    for name, body in parts:
        if not name.endswith('.js'):
            continue
        names = ['KratorFauna'] if name == BUNDLE else \
            [m.group(1) for rx in (RE_DECL, RE_DECL_MULTI) for m in rx.finditer(body)]
        for n in names:
            decl.setdefault(n, set()).add(name)
    for n, fs in sorted(decl.items()):
        if len(fs) > 1:
            errs.append('top-level name `%s` declared in more than one file: %s' % (n, ', '.join(sorted(fs))))
    keys = {}
    for f in fauna_bundle.files():
        for k in RE_VEH.findall(read(os.path.join(HERE, f))):
            keys.setdefault(k, []).append(f)
    for k, fs in sorted(keys.items()):
        if len(fs) > 1:
            errs.append('ANIMAL key %r registered more than once: %s' % (k, ', '.join(fs)))
    return errs


def vendor_check():
    drift = 0
    for f, up in sorted(VENDORED.items()):
        if not os.path.exists(up):
            print('vendor-check: %s: upstream %s missing' % (f, os.path.relpath(up, ROOT)))
            continue
        same = read(up) == read(os.path.join(SRC, f))
        drift += not same
        print('vendor-check: %-14s %s (%s)' % (f, 'identical' if same else 'DRIFTED', os.path.relpath(up, ROOT)))
    return drift


def main():
    if '--vendor-check' in sys.argv:
        sys.exit(1 if vendor_check() else 0)
    frags = sorted(f for f in os.listdir(SRC) if f[0].isdigit())
    head = [f for f in frags if f.endswith('.html') and f < '50']
    tail = [f for f in frags if f.endswith('.html') and f >= '50']
    js = [f for f in frags if f.endswith('.js')]
    groups = sys.argv[sys.argv.index('--groups') + 1].split(',') if '--groups' in sys.argv else None
    bundle = fauna_bundle.bundle(groups)
    parts = [('krator-asset-engine.js', read(ENGINE)), (BUNDLE, bundle)] + [(f, read(os.path.join(SRC, f))) for f in js]
    if '--no-checks' not in sys.argv:
        errs = check(parts)
        if errs:
            print('BUILD RULES FAILED:')
            for e in errs:
                print('  -', e)
            sys.exit(1)
    script = ''.join('/* ---------- %s ---------- */\n%s%s' % (n, b, '' if b.endswith('\n') else '\n') for n, b in parts)
    html = (''.join(read(os.path.join(SRC, f)) for f in head) + '<script>\n' + script +
            ''.join(read(os.path.join(SRC, f)) for f in tail))
    os.makedirs(DIST, exist_ok=True)
    out = os.path.abspath(sys.argv[sys.argv.index('--out') + 1]) if '--out' in sys.argv else os.path.join(DIST, OUT + '.html')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8', newline='') as fh:
        fh.write(html)
    scratch = '--out' in sys.argv   # a scratch page: dist/krator-fauna.js and the manifest are left alone
    if not scratch:
        with open(os.path.join(DIST, 'krator-fauna.js'), 'w', encoding='utf-8', newline='') as fh:
            fh.write(bundle)
    manifest = {n: hashlib.sha1(b.encode()).hexdigest()[:12] for n, b in parts}
    for f in fauna_bundle.files():
        manifest['bundle:kits/fauna/' + f] = hashlib.sha1(read(os.path.join(HERE, f)).encode()).hexdigest()[:12]
    for f in head + tail:
        manifest[f] = hashlib.sha1(read(os.path.join(SRC, f)).encode()).hexdigest()[:12]
    if not scratch:
        with open(os.path.join(HERE, 'build-manifest.json'), 'w', encoding='utf-8') as fh:
            json.dump(manifest, fh, indent=1, sort_keys=True)
    chk = out + '.syntax.js' if scratch else os.path.join(HERE, '.syntax-%s.js' % OUT)
    with open(chk, 'w', encoding='utf-8') as fh:
        fh.write(script)
    try:
        r = subprocess.run(['node', '--check', chk], capture_output=True, text=True)
        if r.returncode:
            print(r.stdout + r.stderr)
            sys.exit(1)
        syntax = '  syntax OK (node)'
    except FileNotFoundError:
        syntax = '  syntax NOT CHECKED (no node)'
    print('built %s (%d files, %.0f KB; bundle %.0f KB)%s' % (os.path.relpath(out, HERE), len(parts) + len(head) + len(tail),
                                                             os.path.getsize(out) / 1024, len(bundle.encode()) / 1024, syntax))
    ki = os.path.join(HERE, 'KNOWN_ISSUES.md')
    if os.path.exists(ki):
        opened = [l.rstrip() for l in open(ki, encoding='utf-8') if l.startswith('- [ ]')]
        if opened:
            print('\nOPEN ISSUES (%d) - KNOWN_ISSUES.md:' % len(opened))
            for l in opened:
                print('  ' + l[6:])


if __name__ == '__main__':
    main()
