// Minas Tirith: entry point for minastirith.html. Fan work — Tolkien's world belongs to the Tolkien Estate,
// nothing from any book, film or game is used, and every shape is this project's own. The city, the Pelennor
// and Mindolluin are generated by tools/make-minastirith.py; the engine is the one Chicago and New York share.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {build} from '../engine/build.js';
import {landmarks} from './landmarks.js';
import {hosts} from '../mordor/hosts.js';
import {life} from './life.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({prefix:'raising Minas Tirith… ',labels:{'map-data':'reading the townlands',ground:'cutting the seven circles',buildings:'building the tiers',details:'planting the Pelennor',landmarks:'raising the White Tower',el:'',traffic:'launching the boats',ui:'opening the windows'}});
// The Tower, the Court and the Great Gate are this city's own. The hosts are Mordor's, and so is the war:
// the same module marches them up the Causeway that marches them across Gorgoroth.
const ctx=window._iz={defaultCity:'minastirith',models:[landmarks],extras:[{name:'life',fn:life},{name:'hosts',fn:hosts}]};
requestAnimationFrame(()=>setTimeout(()=>{build(ctx).catch(e=>{report('build',e);const l=document.getElementById('loading');if(l)l.remove();});},30));
