// ---------- the City: entry point for blame.html ----------
// Fan work after Tsutomu Nihei's Blame! (Kodansha, 1997-2003). Nothing from the manga or the 2017 film is used:
// every shape is generated by city.js and sphere.js from data/cities/blame.json.
//
// This page is about one thing, which is how big the City is, and it has three ways of showing it:
//
//   the block     four layers of the City and the Megastructure between them, 48 km square and 25 km high,
//                 with Killy standing on a platform in the top one - the only thing in it whose size you
//                 already know. Orbit it from 3 m or from 90 km.
//   the section   a cut through the block, the way an architect draws one: everything on your side of a plane
//                 taken away, the solid it passes through filled in and hatched, and the heights ruled up the
//                 side. The Megastructure is black. See mats.js for how the fill works.
//   the City      the whole thing, as Nihei sized it: a shell round the Sun as wide as Jupiter's orbit, in a
//                 scene of its own (sphere.js), and in section too.
//
// "Pull back" joins them up: from Killy's shoulder to the solar system in six steps, a power of ten or so at a
// time, with a line at each about what you are looking at.
//
// Like the habitat and the Backrooms, this page does not run on the shared engine - there is no terrain, no
// sky and no "up" that is not a floor with a ceiling over it - so it brings its own renderer and camera, and
// shares the core modules (diagnostics, the menu, the wireframe) with everything else.
import {report,LOAD,configureLoading,installErrorHandlers,stage,section} from '../core/diag.js';
import {installMenagerie} from '../core/menagerie.js';
import {createWire,installWireUI} from '../core/wire.js';
import {createRenderer,trackResize,installContextLoss,mkBtn as mkBtn0,runHooks,runLoop,finishLoading,boot} from '../core/shell.js';
import {readHash,writeHash as mergeHash} from '../core/hash.js';
import {BIND,FAST,trackKeys,trackPointers} from '../core/input.js';
import {makeMats,cloudTexture,dotTexture,ribTexture} from './mats.js';
import {buildCity} from './city.js';
import {createSphere} from './sphere.js';

installErrorHandlers();window.LOAD=LOAD;
configureLoading({
  lines:[
    'Fan work. Blame! is Tsutomu Nihei\'s; nothing from the manga or the film is used here.',
    'Nihei trained as an architect before he drew manga. The City is what a building does with nobody to stop it.',
    'The Builders never stopped building. They lost the people who could tell them what to build.',
    'Nihei\'s figure for the City: a sphere about as wide as the orbit of Jupiter. 1.6 billion kilometres.',
    'Between one layer and the next is the Megastructure, kilometres thick and almost impossible to damage.',
    'Four layers are built here. The City has thousands.',
    'One room Killy walks through is as wide as Jupiter.',
    'In the manga a lift ride takes a month and gets one page.',
    'Killy is 1.75 m tall. Everything else is measured against him.',
    'The Plain has weather. It is nine kilometres from its floor to its ceiling.',
  ],
  prefix:'climbing… ',labels:{config:'reading the specification',city:'letting the Builders loose',sphere:'closing it round the Sun',ui:'finding Killy'}});

const ctx=window._iz={};
const getJSON=u=>fetch(u).then(r=>{if(!r.ok)throw new Error(u+': HTTP '+r.status);return r.json();});
const clamp=(v,a,b)=>v<a?a:v>b?b:v;
const nf=(v,d)=>v.toLocaleString('en-GB',{maximumFractionDigits:d||0,minimumFractionDigits:d||0});
// a length, in whatever unit reads best
function len(m){
  const a=Math.abs(m);
  if(a<10)return nf(m,2)+' m';if(a<1000)return nf(m)+' m';
  if(a<1e5)return nf(m/1000,a<1e4?1:0)+' km';
  const km=m/1000;if(km<1e6)return nf(km)+' km';if(km<1e9)return nf(km/1e6,km<1e7?1:0)+' million km';
  return nf(km/1e9,1)+' billion km';
}
function px(v){if(v>=10)return nf(v)+' px';if(v>=0.1)return nf(v,1)+' px';
  const e=Math.floor(Math.log10(v)),mant=v/Math.pow(10,e);return nf(mant,1)+'×10'+sup(e)+' px';}
const SUP={'-':'⁻','0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹'};
const sup=n=>String(n).split('').map(c=>SUP[c]||c).join('');

async function build(){
  if(!window.THREE){document.getElementById('loading').textContent=
    'three.js did not load (vendor/three/three.min.js). Check the site mounts and reload.';return;}
  const THREE=window.THREE,V3=THREE.Vector3;
  await stage('config');
  const C=await getJSON('data/cities/blame.json');
  const Q=new URLSearchParams(location.search),HASH=readHash();
  if(+Q.get('seed'))C.seed=+Q.get('seed');
  if(C.seed!==1997)document.getElementById('seedtag').textContent='seed '+C.seed;

  // ---- the renderer ----
  // A logarithmic depth buffer, because the same frame can hold Killy's hand at 30 cm and the far wall of the
  // Plain at 40 km; a linear one runs out of precision about a million times too early.
  const renderer=createRenderer(THREE,{pixelCap:1.75,logDepth:true});
  renderer.localClippingEnabled=true;
  installContextLoss(renderer);
  const scene=new THREE.Scene();
  scene.fog=new THREE.FogExp2(0x9a9ea3,0.0001);
  // light from above, grey from below: inside the City there is no sun, only the glow of the ceiling and what
  // bounces off the floor
  scene.add(new THREE.HemisphereLight(0xdfe4ea,0x24272b,0.78));
  const key=new THREE.DirectionalLight(0xffffff,0.34);key.position.set(0.35,1,0.22);scene.add(key);
  const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,0.03,3e6);
  const scam=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,0.5,3e5);
  const animHooks=[];

  await stage('city');
  const mats=makeMats(THREE);
  const tex={cloud:cloudTexture(THREE),dot:dotTexture(THREE),ribs:ribTexture(THREE)};
  let city=null;
  section('city',()=>{city=buildCity({THREE,C,scene,mats,tex});});
  if(!city)return;
  mats.U.uBlockHalf.value=city.HALF;
  {const ls=city.stack.filter(t=>t.kind==='layer');mats.U.uFloor.value.fromArray(ls.map(t=>t.y0));mats.U.uCeil.value.fromArray(ls.map(t=>t.y1));}
  const {L,TOP,HALF}=city,K=city.killy;
  ctx.lotList=city.rows;
  ctx.details={top:city.count.top,seed:C.seed,instances:city.count.instances,lights:city.count.lights,cables:city.count.cables,stack:TOP};

  await stage('sphere');
  let sph=null;
  section('sphere',()=>{sph=createSphere(THREE,C);});

  // ---- the camera: a point you look at, how far away you are, and from which way ----
  const S={mode:'city',section:false,axis:'z',at:0.5,side:1,find:true,fly:false,flySpeed:40};
  const ctl={city:{t:new V3(),d:10,yaw:0,pitch:0.1,dmin:0.6,dmax:900000},
             sphere:{t:new V3(),d:2600,yaw:0.6,pitch:0.35,dmin:20,dmax:30000}};
  const cur=()=>ctl[S.mode],cam=()=>S.mode==='city'?camera:scam;
  const offs=(s,out)=>{const cp=Math.cos(s.pitch);return out.set(s.d*cp*Math.sin(s.yaw),s.d*Math.sin(s.pitch),s.d*cp*Math.cos(s.yaw));};
  const ov3=new V3();
  function place(c,s){c.position.copy(s.t).add(offs(s,ov3));c.lookAt(s.t);}
  // ---- what is solid: the Megastructure ----
  // Inside a slab or a trunk every direction is the inside of a solid, which draws as the section's black fill
  // and nothing else - so the camera is never left there. solidAt() is the test; the holes through the slabs
  // (the great shaft, the light wells) are not solid, and neither is the half a section has cut away.
  const slabs=city.stack.filter(t=>t.kind==='slab');
  function holeAt(p){for(const sl of slabs)if(p.y>=sl.y0&&p.y<=sl.y1)return (sl.holes||[]).some(([hx,hz,r])=>Math.hypot(p.x-hx,p.z-hz)<r);return false;}
  function solidAt(p){
    if(S.section&&plane.distanceToPoint(p)<0)return false;
    for(const t of city.trunks)if(Math.abs(p.x-t.x)<t.w/2&&Math.abs(p.z-t.z)<t.d/2)return true;
    if(Math.abs(p.x)>=HALF||Math.abs(p.z)>=HALF)return false;
    for(const sl of slabs)if(p.y>sl.y0&&p.y<sl.y1)return !(sl.holes||[]).some(([hx,hz,r])=>Math.hypot(p.x-hx,p.z-hz)<r);
    return false;
  }
  // An orbit camera that would be inside the solid is brought in along its line to the point it is looking at,
  // to the last clear place before the solid - the way a third-person camera behaves against a wall. If the
  // point it looks at is itself inside the solid there is nowhere clear to go, and it is left alone.
  const cv3=new V3(),tv3=new V3();
  function unbury(c,s){
    if(!solidAt(c.position)||solidAt(s.t))return;
    tv3.copy(s.t);cv3.copy(c.position);const L=cv3.distanceTo(tv3),n=Math.min(600,Math.ceil(L/15));
    let lo=0,hi=1;                                  // lo: clear (at the target), hi: solid (at the camera)
    for(let i=n-1;i>=0;i--){const f=i/n;if(!solidAt(ov3.copy(tv3).lerp(cv3,f))){lo=f;hi=(i+1)/n;break;}}
    for(let k=0;k<20;k++){const m=(lo+hi)/2;if(solidAt(ov3.copy(tv3).lerp(cv3,m)))hi=m;else lo=m;}
    const f=Math.max(0,lo-Math.min(0.5,3/Math.max(L,1)));
    c.position.copy(tv3).lerp(cv3,f);c.lookAt(s.t);
  }

  // ---- the views ----
  const col=C.column,sp=C.spire,sh=C.shaft;
  const phi=Math.atan2(col.x-K.x,col.z-K.z);            // the way Killy is looking
  const H=L.hanging,P=L.plain,Wk=L.works,A=L.arcade;
  const aim=(ty,cy,d)=>Math.asin(clamp((cy-ty)/d,-1,1));
  const voidT=[K.x+Math.sin(phi)*900,K.y+120,K.z+Math.cos(phi)*900];
  const bs=city.builders.sites.find(x=>x.near)||city.builders.sites[0],tr=city.trunks[0];
  const VIEWS=[
    {name:'Killy',t:[K.x,K.eye-0.15,K.z],d:3.4,yaw:phi+Math.PI+0.4,pitch:0.08,card:'hanging'},
    {name:'The platform',t:[K.x-1.5,K.y+1,K.z+0.5],d:38,yaw:phi+Math.PI+0.9,pitch:0.42},
    {name:'Across the void',t:voidT,d:925,yaw:phi+Math.PI+0.03,pitch:aim(voidT[1],K.eye+3,925)},
    {name:'The column',t:[col.x,H.y0+1700,col.z],d:7600,yaw:phi+Math.PI+0.45,pitch:0.06},
    {name:'The great shaft',t:[sh.x,H.y0-6000,sh.z],d:6073,yaw:2.2,pitch:1.505},
    {name:'The Plain',t:[sp.x,P.y0+5600,sp.z],d:10500,yaw:0.5,pitch:aim(P.y0+5600,P.y0+3900,10500),card:'plain'},
    {name:'The Plain, from the floor',t:[sp.x,P.y0+3000,sp.z],d:24000,yaw:-0.4,pitch:aim(P.y0+3000,P.y0+140,24000),card:'plain'},
    {name:'The Works',t:[2000,Wk.y0+1250,-6000],d:5200,yaw:0.3,pitch:0.02,card:'works'},
    {name:'The Arcade',t:[575,A.y0+900,-7000],d:7000,yaw:0,pitch:aim(A.y0+900,A.y0+260,7000),card:'arcade'},
    {name:'A Builder at work',t:[bs.x,bs.y+3,bs.z],d:26,yaw:phi+Math.PI+0.2,pitch:0.3,card:'builders',
     // it walks, so the view is wherever it has got to
     dyn(v){const b=city.builders.builders.find(k=>k.site===bs);if(b){const p=b.root.position;v.t=[p.x,p.y+bs.size*0.5,p.z];}}},
    {name:'A trunk',t:[tr.x+tr.w/2,P.y0+3500,tr.z],d:9000,yaw:1.2,pitch:0.05,card:'trunk'},
    {name:'The block',t:[0,TOP/2,0],d:92000,yaw:0.75,pitch:0.3,section:false},
    {name:'The stack',t:[0,TOP/2,0],d:420000,yaw:0.7,pitch:0.1,section:false},
    {name:'The block in section',t:[0,TOP/2,K.z],d:36000,yaw:0,pitch:0.03,section:{axis:'z',z:K.z+10}},
    {name:'The City',mode:'sphere',t:[0,0,0],d:2700,yaw:0.6,pitch:0.32,section:false},
    {name:'The City in section',mode:'sphere',t:[0,0,0],d:2400,yaw:0.35,pitch:0.62,section:true},
  ];
  const CARDS={
    builders:{h:'A Builder',p:'The Builders never stopped. They lost the people who could tell them what to build, so they build what they build: this one is putting up a wall, a course at a time, on a tower across from the platform. There are Builders at work in every layer.',sub:'Walk its wall with it: it lays a course, turns round at the end, steps up and comes back.'},
    trunk:{h:'A trunk',p:'A column of Megastructure two kilometres across that goes through every layer and every slab of the block, and on past both ends of it. Three of them hold up this sample. In the section they are the black verticals the black floors hang from.',sub:'Where it meets a floor it stands on a plinth; where it meets a ceiling there is a haunch.'}};
  const CITYV=VIEWS.findIndex(v=>v.name==='The City');
  const cardFor=k=>{if(CARDS[k])return CARDS[k];const l=L[k];return l?{h:l.name,p:l.note,sub:len(l.h)+' from floor to ceiling. The Megastructure under it is '+len(city.stack[city.stack.indexOf(l)-1].h)+' thick.'}:null;};

  // ---- flying between them ----
  let anim=null;
  function snap(s){return {t:s.t.clone(),d:s.d,yaw:s.yaw,pitch:s.pitch};}
  function setState(s,v){s.t.set(v.t[0],v.t[1],v.t[2]);s.d=v.d;s.yaw=v.yaw;s.pitch=v.pitch;}
  // A section has a side: the half that is kept. It is chosen when the cut is made - the far half from where
  // you are, or from where a view is taking you - and then it stays put, whatever the camera does, until you
  // flip it. (It used to follow the camera, which meant that crossing the plane swapped the whole scene for
  // the other half in one frame.)
  function chooseSide(pos){const c=cutAt(),here=S.axis==='z'?pos.z:pos.x;S.side=here>c?-1:1;}
  const destPos=v=>{const o={t:new V3(...v.t),d:v.d,yaw:v.yaw,pitch:v.pitch};return o.t.add(offs(o,new V3()));};
  function applySection(v){
    if(v.section===undefined)return;
    if(v.section===false){setSection(false);return;}
    if(v.section===true){setSection(true);return;}
    S.axis=v.section.axis;S.at=clamp((v.section.z+HALF)/(2*HALF),0,1);chooseSide(destPos(v));S.section=true;syncUI();
  }
  const fade=document.getElementById('fade');
  function go(v,T,done){
    anim=null;
    const mode=v.mode||'city';
    if(mode!==S.mode){
      fade.classList.add('on');
      setTimeout(()=>{S.mode=mode;setState(cur(),v);applySection(v);syncUI();
        fade.classList.remove('on');if(done)setTimeout(done,450);},420);
      return;
    }
    const s=cur(),from=snap(s);
    const dl=Math.abs(Math.log(v.d/s.d)),dt=s.t.distanceTo(new V3(...v.t));
    if(T===undefined)T=clamp(1.1+0.32*dl+0.3*Math.log(1+dt/Math.max(v.d,s.d)),1.1,6);
    applySection(v);
    anim={from,to:v,t0:performance.now(),T:Math.max(1,T*1000),done};
  }
  function step(now){
    const a=anim,s=cur();let u=clamp((now-a.t0)/a.T,0,1);const e=u*u*(3-2*u);
    const d0=a.from.d,d1=a.to.d;s.d=Math.exp(Math.log(d0)+(Math.log(d1)-Math.log(d0))*e);
    // Where the distance changes by orders of magnitude, the point you look at moves in step with the zoom
    // rather than with the clock - otherwise pulling back from Killy loses him off the edge before the zoom
    // has got going.
    const big=Math.abs(Math.log(d1/d0))>1.5;
    const ut=big?(Math.log(s.d)-Math.log(d0))/(Math.log(d1)-Math.log(d0)):e;
    s.t.set(a.from.t.x+(a.to.t[0]-a.from.t.x)*ut,a.from.t.y+(a.to.t[1]-a.from.t.y)*ut,a.from.t.z+(a.to.t[2]-a.from.t.z)*ut);
    let dy=a.to.yaw-a.from.yaw;dy=Math.atan2(Math.sin(dy),Math.cos(dy));
    s.yaw=a.from.yaw+dy*e;s.pitch=a.from.pitch+(a.to.pitch-a.from.pitch)*e;
    if(u>=1){anim=null;if(a.done)a.done();}
  }

  // ---- the section ----
  const plane=new THREE.Plane(new V3(0,0,-1),0);
  const cutAt=()=>-HALF+2*HALF*S.at;
  function sectionPlane(){
    const c=cutAt(),sgn=S.side;
    plane.normal.set(S.axis==='x'?sgn:0,0,S.axis==='z'?sgn:0);plane.constant=-sgn*c;
  }

  // ---- the input ----
  // the site's controls (src/core/input.js): drag to orbit (in flight, to turn the head), right or Shift-drag to
  // pan, the wheel or a pinch to zoom (in flight, the wheel is speed); F flies, X cuts, C flips the cut, K finds
  // Killy, P pulls back
  const el=renderer.domElement;
  const stopTour=()=>{if(tour)endTour();};
  const tv=new V3(),rv=new V3(),uv=new V3();
  function pan(dx,dy){const s=cur(),c=cam();const k=2*s.d*Math.tan(c.fov*Math.PI/360)/innerHeight;
    rv.setFromMatrixColumn(c.matrix,0);uv.setFromMatrixColumn(c.matrix,1);
    s.t.addScaledVector(rv,-dx*k).addScaledVector(uv,dy*k);}
  trackPointers(el,{
    down:()=>{stopTour();anim=null;},
    drag:(dx,dy,{pan:p})=>{const s=cur();
      if(p)pan(dx,dy);
      else if(S.fly&&S.mode==='city'){
        // flying: turn the head, not the world - the camera stays where it is and the point it looks at moves
        const P0=s.t.clone().add(offs(s,ov3));s.yaw-=dx*0.004;s.pitch=clamp(s.pitch+dy*0.004,-1.52,1.52);s.t.copy(P0).sub(offs(s,ov3));}
      else{s.yaw-=dx*0.005;s.pitch=clamp(s.pitch+dy*0.005,-1.52,1.52);}},
    pinch:(ratio,dx,dy)=>{const s=cur();s.d=clamp(s.d*ratio,s.dmin,s.dmax);pan(dx,dy);},
    wheel:(dy)=>{stopTour();anim=null;const s=cur();
      if(S.fly&&S.mode==='city'){S.flySpeed=clamp(S.flySpeed*Math.exp(-dy*0.0015),0.5,300000);return;}
      s.d=clamp(s.d*Math.exp(dy*0.0014),s.dmin,s.dmax);}});
  const keys=trackKeys({onKey:(k,e,held)=>{
    if(held){stopTour();anim=null;return;}
    if(k===BIND.cut){setSection(!S.section);return;}
    if(k===BIND.cutSide){if(S.section)S.side=-S.side;return;}
    if(k==='k'){toggleFind();return;}
    if(k==='p'){tour?endTour():startTour();return;}
    if(k===BIND.close){views.classList.remove('open');vb.setAttribute('aria-expanded','false');}}});

  // ---- the panels ----
  await stage('ui');
  const ui=document.getElementById('ui'),views=document.getElementById('views'),card=document.getElementById('card');
  const mkBtn=(label,parent,fn)=>mkBtn0(label,parent,()=>fn(),{stop:true});
  const vb=mkBtn('Views',ui,()=>{const o=!views.classList.contains('open');views.classList.toggle('open',o);vb.setAttribute('aria-expanded',String(o));
    const m=document.getElementById('menagerie');if(o&&m)m.classList.remove('open');});
  vb.setAttribute('aria-expanded','false');
  let cardTimer=0;
  function showCard(c){if(!c){card.classList.remove('on');return;}
    card.innerHTML='';const h=document.createElement('h2');h.textContent=c.h;const p=document.createElement('p');p.textContent=c.p;
    const s=document.createElement('p');s.className='sub';s.textContent=c.sub;card.append(h,p,s);card.classList.add('on');
    clearTimeout(cardTimer);cardTimer=setTimeout(()=>card.classList.remove('on'),11000);}
  card.addEventListener('click',()=>card.classList.remove('on'));
  const addGroup=(name,list)=>{const h=document.createElement('div');h.className='sub';h.textContent=name;views.appendChild(h);
    for(const v of list)mkBtn(v.name,views,()=>{stopTour();if(v.dyn)v.dyn(v);go(v);showCard(v.card?cardFor(v.card):null);
      views.classList.remove('open');vb.setAttribute('aria-expanded','false');});};
  addGroup('Where Killy is',VIEWS.slice(0,5).concat([VIEWS[9]]));
  addGroup('The other layers',VIEWS.slice(5,9).concat([VIEWS[10]]));
  addGroup('All of it',VIEWS.slice(11));

  const secB=mkBtn('Section',ui,()=>setSection(!S.section));secB.title='Cut it open (X): the solid is filled in and hatched, the Megastructure black';
  const axB=mkBtn('Cut: across',ui,()=>{S.axis=S.axis==='z'?'x':'z';chooseSide(camera.position);syncUI();});axB.title='Which way the cut runs';
  const flipB=mkBtn('Flip',ui,()=>{S.side=-S.side;});flipB.title='Keep the other half (C)';
  const slider=document.createElement('input');slider.type='range';slider.min='0';slider.max='1000';slider.value='500';
  slider.setAttribute('aria-label','Where the cut is');slider.style.cssText='pointer-events:auto;width:min(220px,40vw);align-self:center;accent-color:#c8321f';
  slider.addEventListener('input',()=>{S.at=+slider.value/1000;});ui.appendChild(slider);
  const flyB=document.createElement('button');   // fly mode is not offered in the fictional scenes: no button, no key
  const findB=mkBtn('Find Killy',ui,()=>toggleFind());findB.title='Ring Killy wherever he is, and say how big he is on screen (K)';
  const tourB=mkBtn('Pull back',ui,()=>tour?endTour():startTour());tourB.title='From Killy\'s shoulder to the whole City, a power of ten at a time (P)';
  const cityB=mkBtn('The City',ui,()=>{stopTour();go(S.mode==='city'?VIEWS[CITYV]:VIEWS[0]);});
  function setSection(on){on=!!on;if(on&&!S.section)chooseSide(camera.position);S.section=on;syncUI();}
  function toggleFind(){S.find=!S.find;syncUI();}
  function syncUI(){
    secB.setAttribute('aria-pressed',String(S.section));
    const showCut=S.section&&S.mode==='city';axB.style.display=showCut?'':'none';slider.style.display=showCut?'':'none';flipB.style.display=showCut?'':'none';
    flyB.setAttribute('aria-pressed',String(S.fly));flyB.style.display=S.mode==='city'?'':'none';
    axB.textContent=S.axis==='z'?'Cut: across':'Cut: along';slider.value=String(Math.round(S.at*1000));
    findB.setAttribute('aria-pressed',String(S.find));findB.style.display=S.mode==='city'?'':'none';
    cityB.textContent=S.mode==='city'?'The City':'Back to Killy';cityB.setAttribute('aria-pressed',String(S.mode==='sphere'));
    tourB.textContent=tour?'Stop':'Pull back';tourB.setAttribute('aria-pressed',String(!!tour));
  }
  const wire=createWire({THREE,scene,animHooks});
  installWireUI({ui,mkBtn,wire,hash:location.hash.slice(1)});
  installMenagerie({ui,mkBtn}).catch(e=>report('menagerie',e));
  const hud=document.createElement('div');hud.id='timebar';document.getElementById('side').appendChild(hud);

  // ---- pull back: Killy to the Sun in six steps ----
  const capEl=document.getElementById('caption');
  let tour=null;
  const STEPS=[
    {v:{t:[K.x,K.eye-0.2,K.z],d:3.2,yaw:phi+Math.PI+0.5,pitch:0.1,section:false},T:0.01,hold:3200,
     cap:['1.75 m','Killy. The one thing here whose size you already know.']},
    {v:{t:[K.x,K.y,K.z],d:48,yaw:phi+Math.PI+0.95,pitch:0.45},T:3.2,hold:3400,
     cap:['40 m','The platform: the top of a tank, on the roof of a tower. Nobody built it for him to stand on.']},
    {v:{t:[K.x,K.y-700,K.z],d:2600,yaw:phi+Math.PI+1.2,pitch:0.12},T:4,hold:3800,
     cap:['1.5 km','The tower is fourteen hundred and fifty metres tall. In the Hanging, that is small.']},
    {v:{t:[K.x+300,H.y0+H.h/2,K.z-900],d:13000,yaw:phi+Math.PI+0.7,pitch:0.08},T:4.5,hold:4200,
     cap:['3.6 km floor to ceiling','The Hanging, one layer of the City. Under the floor, 1.6 km of Megastructure.']},
    // out through the open side of the Hanging, so as not to go through a slab on the way...
    {v:{t:[K.x,H.y0+H.h/2,K.z],d:40000,yaw:0.02,pitch:-0.015},T:4.5,hold:600,cap:null},
    // ...and then the cut, once there is something to see it from
    {v:{t:[0,TOP/2,K.z],d:36000,yaw:0.02,pitch:0.03},after:{axis:'z',z:K.z+10},T:2.6,hold:6000,
     cap:['25 km','Four layers, cut open, and the Megastructure between them. The City has thousands. Killy is in the circle.']},
    {v:{t:[0,TOP/2,0],d:420000,yaw:0.6,pitch:0.1,section:false},T:5,hold:5200,
     cap:['400 km','And on: seventeen blocks of it, above and below, drawn fainter as they go. At the scale of the whole City this is still a hundred-thousandth of a pixel.']},
    {v:{mode:'sphere',t:[0,0,0],d:160,yaw:0.5,pitch:0.25,section:false},T:0,hold:0,cap:null},
    {v:{mode:'sphere',t:[0,0,0],d:2600,yaw:0.62,pitch:0.32,section:false},T:6,hold:4400,
     cap:['1.6 billion km','The City: a shell round the Sun as wide as the orbit of Jupiter. At this scale the block you were in would be a hundred-thousandth of a pixel thick.']},
    {v:{mode:'sphere',t:[0,0,0],d:2400,yaw:0.35,pitch:0.62,section:true},T:3.5,hold:6500,
     cap:['In section','Out from where the Earth was, layer on layer. How deep it goes, the manga never says.']},
  ];
  function caption(c){if(!c){capEl.classList.remove('on');return;}
    capEl.innerHTML='';const b=document.createElement('b');b.textContent=c[0];const s=document.createElement('span');s.textContent=c[1];
    capEl.append(b,s);capEl.classList.add('on');}
  function startTour(){
    views.classList.remove('open');card.classList.remove('on');
    const tk={i:0,timer:0};tour=tk;syncUI();
    const next=()=>{if(tour!==tk)return;
      if(tk.i>=STEPS.length){endTour();return;}
      const s=STEPS[tk.i++];
      if(s.T===0.01){const m=s.v.mode||'city';const run=()=>{setState(cur(),s.v);applySection(s.v);caption(s.cap);tk.timer=setTimeout(next,s.hold);};
        if(m!==S.mode)go(s.v,0,()=>{caption(s.cap);tk.timer=setTimeout(next,s.hold);});else run();return;}
      go(s.v,s.T,()=>{if(tour!==tk)return;if(s.after)applySection(Object.assign({},s.v,{section:s.after}));if(s.cap)caption(s.cap);tk.timer=setTimeout(next,s.hold);});
      if(s.T>0)caption(null);
    };
    next();
  }
  function endTour(){if(!tour)return;clearTimeout(tour.timer);tour=null;caption(null);syncUI();}

  // ---- the overlay: the rule up the side of the section, Killy's ring, the scale bar ----
  const ov=document.getElementById('overlay'),g2=ov.getContext('2d');
  let ow=0,oh=0;
  function sizeOverlay(){const r=Math.min(devicePixelRatio,2);ow=innerWidth;oh=innerHeight;ov.width=ow*r;ov.height=oh*r;g2.setTransform(r,0,0,r,0,0);}
  sizeOverlay();
  const pv=new V3();
  function proj(c,x,y,z){pv.set(x,y,z).project(c);return {x:(pv.x+1)/2*ow,y:(1-pv.y)/2*oh,ok:pv.z>-1&&pv.z<1&&Math.abs(pv.x)<1.2&&Math.abs(pv.y)<1.2};}
  const INK='rgba(236,236,232,0.92)',DIM='rgba(236,236,232,0.6)',RED='#d8392a';
  function label(x,y,a,b,align){g2.textAlign=align||'left';g2.font='600 11px Georgia,serif';g2.fillStyle=INK;
    g2.save();g2.shadowColor='rgba(0,0,0,0.85)';g2.shadowBlur=4;
    g2.fillText(a,x,y);if(b){g2.font='11px Georgia,serif';g2.fillStyle=DIM;g2.fillText(b,x,y+14);}g2.restore();}
  function scaleBar(mpp,unitScale){
    // a bar about 150 px long, at a round length
    const want=150*mpp*unitScale,p10=Math.pow(10,Math.floor(Math.log10(want)));
    const n=[1,2,5,10].map(k=>k*p10).reduce((a,b)=>Math.abs(b-want)<Math.abs(a-want)?b:a);
    const w=n/(mpp*unitScale),x=16,y=oh-(parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--barh'))||56)-26;
    g2.fillStyle='rgba(0,0,0,0.45)';g2.fillRect(x-6,y-18,w+12,30);
    g2.strokeStyle=INK;g2.lineWidth=1.5;g2.beginPath();g2.moveTo(x,y-5);g2.lineTo(x,y+5);g2.moveTo(x,y);g2.lineTo(x+w,y);g2.moveTo(x+w,y-5);g2.lineTo(x+w,y+5);g2.stroke();
    g2.fillStyle=INK;for(let i=1;i<4;i++){g2.fillRect(x+w*i/4-0.5,y-3,1,6);}
    label(x,y-8,len(n),null);
  }
  function drawCity(){
    const s=ctl.city,c=camera;
    // Killy's ring
    if(S.find){
      const a=proj(c,K.x,K.y+0.9,K.z);
      if(a.ok){
        const top=proj(c,K.x,K.y+1.75,K.z),bot=proj(c,K.x,K.y,K.z),h=Math.abs(top.y-bot.y);
        if(h<14){
          g2.strokeStyle=RED;g2.lineWidth=2;g2.beginPath();g2.arc(a.x,a.y,15,0,Math.PI*2);g2.stroke();
          g2.lineWidth=1;g2.beginPath();g2.moveTo(a.x+11,a.y-11);g2.lineTo(a.x+38,a.y-38);g2.lineTo(a.x+46,a.y-38);g2.stroke();
          label(a.x+50,a.y-40,'KILLY · 1.75 m','is '+px(h)+' tall from here');
        }
      }
    }
    if(S.section){
      // the heights, ruled up the left of the cut
      const cz=cutAt();const at=y=>S.axis==='z'?proj(c,s.t.x,y,cz):proj(c,cz,y,s.t.z);
      const X=26;let prev=null;
      g2.strokeStyle=INK;g2.lineWidth=1;
      const ys=[0,...city.stack.map(t=>t.y1)];
      const pts=ys.map(y=>at(y));
      g2.beginPath();g2.moveTo(X,pts[0].y);g2.lineTo(X,pts[pts.length-1].y);g2.stroke();
      for(const p of pts){g2.beginPath();g2.moveTo(X-5,p.y);g2.lineTo(X+5,p.y);g2.stroke();}
      city.stack.forEach((t,i)=>{
        const y0=pts[i].y,y1=pts[i+1].y,gap=Math.abs(y0-y1),m=(y0+y1)/2;
        if(gap<13)return;
        const a=t.kind==='slab'?'MEGASTRUCTURE':t.name.toUpperCase(),b=t.kind==='slab'?len(t.h):len(t.h)+' floor to ceiling';
        label(X+12,gap>30?m-3:m+4,a,gap>30?b:null);
      });
      if(pts.length){const tot=pts[pts.length-1];label(X-8,tot.y-34,len(TOP)+' of the City, cut','and thousands more layers above and below');}
      void prev;
    }
    const d=camera.position.distanceTo(s.t);scaleBar(2*d*Math.tan(camera.fov*Math.PI/360)/oh,1);
  }
  function drawSphere(){
    const s=ctl.sphere,c=scam;
    for(const l of sph.labels){if(l.section&&!S.section)continue;const a=proj(c,l.pos.x,l.pos.y,l.pos.z);if(!a.ok)continue;
      g2.fillStyle=INK;g2.beginPath();g2.arc(a.x,a.y,2.5,0,Math.PI*2);g2.fill();
      const dx=l.dx||8,dy=l.dy===undefined?-4:l.dy;label(a.x+dx,a.y+dy,l.text,l.sub,dx<0?'right':'left');}
    // the skin, labelled at its edge
    const e=proj(c,0,sph.R,0);if(e.ok)label(e.x+10,e.y-10,'THE SKIN','1.6 billion km across');
    const d=scam.position.distanceTo(s.t);scaleBar(2*d*Math.tan(scam.fov*Math.PI/360)/oh,1e9);
  }

  // ---- the address ----
  function writeHash(){
    // #view= and #tour only say how the page was opened: once the camera has moved they would take it back
    const s=cur();
    mergeHash({at:[S.mode,s.t.x.toFixed(1),s.t.y.toFixed(1),s.t.z.toFixed(1),s.d.toPrecision(5),s.yaw.toFixed(3),s.pitch.toFixed(3)].join(','),
      cut:S.section?S.axis+','+S.at.toFixed(4)+','+S.side:null,find:S.find?null:'0',view:null,tour:null},['at','cut','find']);
  }
  {const at=(HASH.get('at')||'').split(',');
   const n=at.slice(1).map(Number);
   setState(ctl.city,VIEWS[0]);setState(ctl.sphere,VIEWS[CITYV]);
   if((at[0]==='city'||at[0]==='sphere')&&n.length===6&&n.every(Number.isFinite)){S.mode=at[0];setState(cur(),{t:n.slice(0,3),d:n[3],yaw:n[4],pitch:n[5]});}
   const cu=(HASH.get('cut')||'').split(',');if(cu[0]==='x'||cu[0]==='z'){S.axis=cu[0];S.at=clamp(+cu[1]||0.5,0,1);S.section=true;
     if(cu[2]==='1'||cu[2]==='-1')S.side=+cu[2];else{const st=cur();chooseSide(st.t.clone().add(offs(st,new V3())));}}
   if(HASH.get('find')==='0')S.find=false;
   const vi=+HASH.get('view');if(HASH.has('view')&&VIEWS[vi]){const v=VIEWS[vi];if(v.dyn)v.dyn(v);S.mode=v.mode||'city';setState(cur(),v);applySection(v);}
   if(HASH.has('tour'))setTimeout(startTour,600);}
  syncUI();

  trackResize(renderer,[camera,scam],sizeOverlay);
  finishLoading({hintMs:15000});

  // ---- the frame ----
  const fogC=new THREE.Color(),fogT=new THREE.Color(),OUT=new THREE.Color(0x0c0d0f),SLAB=new THREE.Color(0x1b1c1e);
  let fogD=0.0001,hashAt=0;
  runLoop((now,dt)=>{
    if(anim)step(now);
    else if(keys.size&&S.fly&&S.mode==='city'){const s=cur(),sp=S.flySpeed*(keys.has('shift')?5:1)*dt,t0=s.t.clone(),c0=s.t.clone().add(offs(s,new V3())),f3=offs(s,ov3).normalize().negate();
      const rx=-f3.z,rz=f3.x,rl=Math.hypot(rx,rz)||1;
      if(keys.has('w'))s.t.addScaledVector(f3,sp);if(keys.has('s'))s.t.addScaledVector(f3,-sp);
      if(keys.has('d')){s.t.x+=rx/rl*sp;s.t.z+=rz/rl*sp;}if(keys.has('a')){s.t.x-=rx/rl*sp;s.t.z-=rz/rl*sp;}
      if(keys.has('e'))s.t.y+=sp;if(keys.has('q'))s.t.y-=sp;
      // flying does not go through the Megastructure: a move that would end inside it is not made
      if(!solidAt(c0)&&solidAt(s.t.clone().add(offs(s,new V3()))))s.t.copy(t0);}
    else if(keys.size){const s=cur(),sp=s.d*0.7*(keys.has(BIND.fast)?FAST:1)*dt;
      const fx=-Math.sin(s.yaw),fz=-Math.cos(s.yaw);
      if(keys.has('w')){s.t.x+=fx*sp;s.t.z+=fz*sp;}if(keys.has('s')){s.t.x-=fx*sp;s.t.z-=fz*sp;}
      if(keys.has('a')){s.t.x+=fz*sp;s.t.z-=fx*sp;}if(keys.has('d')){s.t.x-=fz*sp;s.t.z+=fx*sp;}
      if(keys.has('e'))s.t.y+=sp;if(keys.has('q'))s.t.y-=sp;}
    g2.clearRect(0,0,ow,oh);
    if(S.mode==='city'){
      place(camera,ctl.city);
      if(S.section)sectionPlane();
      if(!S.fly)unbury(camera,ctl.city);
      camera.updateMatrixWorld();
      // the air: the fog of whichever layer the camera is in, eased so that crossing a slab is not a cut
      const p=camera.position;
      if(S.section)sectionPlane();
      // inside the block, unless the section has taken away the half you are in - then you are outside it
      const inBox=Math.abs(p.x)<HALF&&Math.abs(p.z)<HALF&&p.y>0&&p.y<TOP,inB=inBox&&(!S.section||plane.distanceToPoint(p)>=0);
      let tgt=0.0000035;fogT.copy(OUT);
      if(inB){const l=city.layerAt(p.y);if(l&&l.kind==='layer'){fogT.set(l.fog[0]);tgt=l.fog[1];}
        else if(l&&holeAt(p)){
          // in a hole through a slab - the great shaft, or a light well: the air of whichever layer is nearer
          const i=city.stack.indexOf(l),n=city.stack[p.y>(l.y0+l.y1)/2?i+1:i-1]||city.stack[i-1];fogT.set(n.fog[0]);tgt=n.fog[1];}
        else{fogT.copy(SLAB);tgt=0.0004;}}
      if(S.section)tgt*=0.3;
      const k=1-Math.exp(-dt*5);fogC.lerp(fogT,k);fogD+=(tgt-fogD)*k;
      scene.fog.color.copy(fogC);scene.fog.density=fogD;renderer.setClearColor(fogC);
      city.air.visible=!inB;city.ghosts.visible=!inB;for(const m of city.air.children)if(m.userData.veil)m.visible=!S.section;
      mats.U.uCutOn.value=S.section?1:0;mats.U.uCut.value.set(plane.normal.x,plane.normal.y,plane.normal.z,plane.constant);
      renderer.clippingPlanes=S.section?[plane]:[];
      city.builders.update(now);city.figures.userData.update(now/1000);
      runHooks(animHooks,now);
      drawCity();
      renderer.render(scene,camera);
      const l=inB?city.layerAt(p.y):null,d=p.distanceTo(new V3(K.x,K.y+0.9,K.z)),kh=1.75/(2*d*Math.tan(camera.fov*Math.PI/360))*oh;
      const blockOff=Math.round((p.y-TOP/2)/city.STEP);
      const inShaft=inB&&city.layerAt(p.y)&&city.layerAt(p.y).kind==='slab'&&holeAt(p);
      const where=inShaft?(Math.hypot(p.x-C.shaft.x,p.z-C.shaft.z)<C.shaft.r?'IN THE GREAT SHAFT':'IN A LIGHT WELL')+' · '+len(city.stack.find(t=>t.kind==='layer'&&t.y0>=p.y).y0-p.y)+' below the floor above':!inB?(inBox?'IN THE CUT-AWAY HALF':Math.abs(p.x)<HALF&&Math.abs(p.z)<HALF&&blockOff?(Math.abs(blockOff)+(Math.abs(blockOff)===1?' BLOCK ':' BLOCKS ')+(blockOff>0?'ABOVE':'BELOW')+' THE SAMPLE'):'OUTSIDE THE BLOCK'):l.kind==='slab'?'INSIDE THE MEGASTRUCTURE':l.name.toUpperCase()+' · '+len(p.y-l.y0)+' over the floor';
      hud.textContent=(S.fly?'FLYING '+len(S.flySpeed*(keys.has('shift')?5:1))+'/s · ':'')+where+' · frame '+len(2*ctl.city.d*Math.tan(camera.fov*Math.PI/360)*camera.aspect)+' across · Killy '+px(kh);
    }else{
      place(scam,ctl.sphere);scam.updateMatrixWorld();
      renderer.clippingPlanes=[];sph.update(scam,S.section);
      drawSphere();
      renderer.setClearColor(0x030305);renderer.render(sph.scene,scam);
      const w=2*ctl.sphere.d*Math.tan(scam.fov*Math.PI/360)*scam.aspect*1e9;
      hud.textContent='THE CITY · 1.6 billion km across · frame '+len(w)+' across ('+nf(w/1.496e11,1)+' AU)';
    }
    if(now-hashAt>1200){hashAt=now;writeHash();}
  });
}

boot(build);
