#!/usr/bin/env python3
"""Generate the Shiganshina District and its stretch of Wall Maria as a city data file the OSM engine can read.

    python3 tools/make-shiganshina.py

Fan work from Hajime Isayama's Attack on Titan, which belongs to its author and publishers; nothing from the manga,
the anime or any game is used. Every shape here is generated from the published description, and the geometry is this
project's own.

What the story says of the place, taken as a plan:

  humanity lives inside three concentric walls, fifty metres high; the outermost is Wall Maria
  where a road leaves the wall there is a district: a town walled in its own semicircle bulging outward from the
  main wall, so that the Titans, drawn to people, come to the district first and the wall behind it holds
  Shiganshina is Wall Maria's southern district: its outer gate faces the plains, its inner gate opens into Wall
  Maria; a canal runs through it, in by the outer wall and out by the inner, and the boats evacuate along it
  inside the wall: farmland, villages, and the Forest of Giant Trees; outside: grassland, forest, and the Titans

Scale: 12 km east to west, 10 km north to south, terrain every 20 m. The district is 1.8 km across at its wall.
Wall Maria runs east-west across the map at z = 0 (a chord of a circle 480 km across, so as good as straight here).
"""
import json
import math
import os
import random
from lib.geo import q, flat, rect

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "cities", "shiganshina-osm.json")
R = random.Random(845)

HX, HZ = 6000.0, 5000.0
STEP = 20
ORIGIN = (48.0, 10.0)
WALL_H = 50.0
WALL_T = 12.0                    # thickness at the top
DIST_W = 700.0                   # the district's wall is a U: straight sides 2 x DIST_W apart out from Wall Maria,
DIST_L = 650.0                   # DIST_L long, closed by a half-circle; the outer gate at the far end of it
DIST_R = DIST_L + DIST_W         # how far out the outer gate is
GATE_W = 26.0                    # the gates' openings
CANAL_X = 260.0                  # the canal comes in by the outer wall east of the gate, runs north to the inner wall
FOREST = (-3200.0, -2600.0, 1100.0)   # the Forest of Giant Trees, inside Wall Maria to the north-west


def inside(x, z, pad=0.0):
    """Inside the district's U (pad metres in from its wall)."""
    if z <= pad:
        return False
    if z < DIST_L:
        return abs(x) < DIST_W - pad
    return math.hypot(x, z - DIST_L) < DIST_W - pad


def u_path(n=72):
    """The district wall's line: out along the west side, round the end, back along the east side."""
    pts = [(-DIST_W, 0.0), (-DIST_W, DIST_L)]
    for i in range(1, n):
        a = math.pi - math.pi * i / n
        pts.append((math.cos(a) * DIST_W, DIST_L + math.sin(a) * DIST_W))
    pts += [(DIST_W, DIST_L), (DIST_W, 0.0)]
    return pts


def ground(x, z):
    """Rolling grassland, a little lower outside; the canal cut through the district."""
    h = 8 + 4 * math.sin(x / 1700.0) * math.cos(z / 1300.0) + 2.5 * math.sin((x + z) / 900.0)
    if z > 0 and not inside(x, z):
        h -= min(4.0, max(0.0, z - 100) / 500.0)
    if -1400 < z < DIST_R + 400 and abs(x - CANAL_X) < 40:
        if abs(x - CANAL_X) < 9:
            return 3.0                            # the canal's bed, the water at 4.6
        h = max(h, 7.0)                           # its banks, above the water
    return h


def main():
    lat0, lon0 = ORIGIN
    mlat, mlon = 111132.0, 111320.0 * math.cos(math.radians(lat0))
    out = {"attribution": "Shiganshina: fan geometry generated by tools/make-shiganshina.py; no manga, anime or game assets used",
           "units": "decimetres east (x) and south (z) of origin", "origin": [lat0, lon0],
           "bounds": [round(lat0 - HZ / mlat, 5), round(lon0 - HX / mlon, 5), round(lat0 + HZ / mlat, 5), round(lon0 + HX / mlon, 5)]}
    nx = int(2 * HX) // STEP + 2
    nz = int(2 * HZ) // STEP + 2
    out["terrain"] = {"step": STEP, "nx": nx, "nz": nz, "x0": q(-HX), "z0": q(-HZ), "datum": 0.0,
                      "h": [int(round(ground(-HX + i * STEP, -HZ + j * STEP) * 10)) for j in range(nz) for i in range(nx)]}
    # the canal: water from outside the district wall up to the inner wall, and on north into Wall Maria
    cw = 16.0
    canal = [(CANAL_X - cw / 2, -1400), (CANAL_X + cw / 2, -1400), (CANAL_X + cw / 2, DIST_R + 400), (CANAL_X - cw / 2, DIST_R + 400)]
    out["water"] = [{"o": flat(canal), "i": [], "n": "The Canal", "y": 4.6}]
    out["lake"], out["islands"], out["marina"], out["beach"], out["pier"] = [], [], [], [], []
    out["waterways"] = [{"n": "The Canal", "p": flat([(CANAL_X, -1400), (CANAL_X, DIST_R + 400)])}]
    out["shiganshina"] = {"wallH": WALL_H, "wallT": WALL_T, "distR": DIST_R, "distW": DIST_W, "distL": DIST_L, "gateW": GATE_W,
                          "canalX": CANAL_X, "hx": HX, "forest": FOREST, "path": [[round(x, 1), round(z, 1)] for x, z in u_path()],
                          "canalOut": round(DIST_L + math.sqrt(DIST_W ** 2 - CANAL_X ** 2), 1)}

    # ---------- roads ----------
    roads = []

    def road(pts, cls, w, name=""):
        r = {"c": cls, "w": round(w, 1), "p": flat(pts)}
        if name:
            r["n"] = name
        roads.append(r)

    road([(0, -4800), (0, -800), (0, DIST_R + 1400), (300, HZ - 200)], "primary", 12, "The Main Street")
    # the town's streets: lanes parallel to the main street, cross streets every 110 m, each a little crooked
    XS = [-560, -420, -280, -140, 140, 400, 540]
    ZS = list(range(110, int(DIST_R) - 40, 110))
    for x0 in XS:
        pts = [(x0 + R.uniform(-6, 6), z) for z in range(30, int(DIST_R), 40) if inside(x0, z, 30)]
        if len(pts) > 1:
            road(pts, "residential", 6)
    for z0 in ZS:
        pts = [(x, z0 + R.uniform(-5, 5)) for x in range(-int(DIST_W), int(DIST_W) + 1, 40) if inside(x, z0, 30)]
        if len(pts) > 1:
            road(pts, "secondary" if z0 in (330, 770) else "residential", 8 if z0 in (330, 770) else 6)
    # the wall road, forty metres in from the wall all round
    wp = []
    for (x, z) in u_path(96):
        d = math.hypot(x, z - DIST_L) if z > DIST_L else None
        if z > DIST_L:
            k = (DIST_W - 40) / DIST_W
            wp.append((x * k, DIST_L + (z - DIST_L) * k))
        else:
            wp.append((math.copysign(DIST_W - 40, x), max(40.0, z)))
    road(wp, "residential", 7, "The Wall Road")
    out["shiganshina"]["streetsZ"] = ZS
    # the farm roads inside Wall Maria, and the road on to the next district
    road([(0, -800), (-2400, -2000), (-5800, -2600)], "secondary", 7)
    road([(0, -800), (2600, -2400), (5800, -3800)], "secondary", 7)
    for k in range(10):
        x = -5400 + k * 1200
        road([(x, -300), (x + R.uniform(-300, 300), -4800)], "track", 4)
    out["roads"] = roads

    # ---------- the ground ----------
    def half_disc(r, n=64):
        return [(math.cos(math.pi * i / n) * r, math.sin(math.pi * i / n) * r) for i in range(n + 1)]
    areas = [{"k": "plaza", "n": "The Market Square", "o": flat(rect(0, 380, 110, 80)), "i": []},
             {"k": "residential", "n": "Shiganshina", "o": flat(u_path()), "i": []},
             {"k": "wood", "n": "The Forest of Giant Trees", "o": flat([(FOREST[0] + math.cos(i / 40 * math.tau) * FOREST[2], FOREST[1] + math.sin(i / 40 * math.tau) * FOREST[2] * 0.8) for i in range(40)]), "i": []}]
    for k in range(70):
        x = R.uniform(-5600, 5600)
        z = R.uniform(-4700, -500)
        if math.hypot(x - FOREST[0], z - FOREST[1]) < FOREST[2] + 200:
            continue
        areas.append({"k": "farmland", "n": "", "o": flat(rect(x, z, R.uniform(300, 700), R.uniform(200, 500), R.uniform(-0.3, 0.3))), "i": []})
    for k in range(12):                                    # the woods outside, where the Titans come from
        x = R.uniform(-5600, 5600)
        z = R.uniform(DIST_R + 900, HZ - 300)
        areas.append({"k": "wood", "n": "", "o": flat([(x + math.cos(i / 16 * math.tau) * R.uniform(250, 450), z + math.sin(i / 16 * math.tau) * R.uniform(200, 380)) for i in range(16)]), "i": []})
    out["areas"] = areas
    out["rail"], out["stations"] = [], []

    # ---------- the buildings: the town in its half-ring, the villages inside Wall Maria ----------
    buildings = []

    def put(ring, h, kind=None, colour=None, name=None, roof=None, minh=None):
        b = {"p": flat(ring), "h": round(h, 1)}
        for k_, v in (("t", kind), ("c", colour), ("n", name), ("r", roof)):
            if v:
                b[k_] = v
        if minh is not None:
            b["m"] = round(minh, 1)
        buildings.append(b)

    PLASTER = ["#e8e0cc", "#ded4bc", "#efe8d8", "#d8ccb0", "#e4d8c0", "#c8b898", "#d8c8a8"]
    STONE = ["#a89c88", "#b4a890", "#9a8e7a"]

    def clear(x, z, pad=0.0):
        if not inside(x, z, 45 + pad) or z < 30 + pad:
            return False                              # behind Wall Maria, or against the district's own wall
        if abs(x) < 16 + pad and z < DIST_R:          # the main street
            return False
        if abs(x - CANAL_X) < 20 + pad:              # the canal and its towpaths
            return False
        for x0 in (-560, -420, -280, -140, 140, 400, 540):
            if abs(x - x0) < 8 + pad:
                return False
        for z0 in range(110, int(DIST_R) - 40, 110):
            if abs(z - z0) < 9 + pad:
                return False
        if abs(x) < 70 and 330 < z < 430:             # the market square
            return False
        return True

    houses = 0
    # houses in terraces along both sides of every lane and cross street, gable to gable
    for z in range(20, int(DIST_R), 1):
        pass
    for x0 in [-700, -560, -420, -280, -140, 0, 140, 400, 540, 700]:
        for side in (-1, 1):
            x = x0 + side * 15
            z = 40.0
            while z < DIST_R:
                w = R.uniform(7, 12)
                if clear(x, z):
                    put(rect(x, z, R.uniform(10, 13), w), R.uniform(8, 14), "house", PLASTER[R.randrange(len(PLASTER))], roof="g")
                    houses += 1
                z += w + R.uniform(0.2, 1.0)
    for z0 in range(110, int(DIST_R) - 40, 110):
        for side in (-1, 1):
            z = z0 + side * 16
            x = -DIST_W
            while x < DIST_W:
                w = R.uniform(7, 12)
                if clear(x, z) and all(abs(x - x0) > 22 for x0 in (-560, -420, -280, -140, 0, 140, 400, 540)):
                    put(rect(x, z, w, R.uniform(10, 13)), R.uniform(8, 14), "house", PLASTER[R.randrange(len(PLASTER))], roof="g")
                    houses += 1
                x += w + R.uniform(0.2, 1.0)
    put(rect(-90, 380, 34, 18), 16, "church", STONE[0], name="The Church", roof="g")
    put(rect(150, 140, 46, 26, 0.3), 14, "military", STONE[1], name="The Garrison Headquarters", roof="g")
    put(rect(-200, 120, 30, 20, 0.5), 11, "civic", STONE[2], name="The Town Hall", roof="g")
    # the villages and farms inside Wall Maria
    for k in range(9):
        vx, vz = R.uniform(-5200, 5200), R.uniform(-4500, -1200)
        if math.hypot(vx - FOREST[0], vz - FOREST[1]) < FOREST[2] + 300:
            continue
        for j in range(R.randint(8, 18)):
            x, z = vx + R.uniform(-140, 140), vz + R.uniform(-110, 110)
            put(rect(x, z, R.uniform(8, 13), R.uniform(7, 11), R.uniform(0, math.pi)), R.uniform(5, 9), "house", PLASTER[R.randrange(len(PLASTER))], roof="g")
            houses += 1
        put(rect(vx + 30, vz - 40, 18, 32), 9, "barn", "#8a6a4a", roof="g")
    out["buildings"] = buildings

    # ---------- trees: the giant ones in their forest, ordinary woods outside ----------
    trees = []
    for k in range(260):
        a, d = R.uniform(0, math.tau), math.sqrt(R.random()) * FOREST[2]
        trees.append({"x": q(FOREST[0] + math.cos(a) * d), "z": q(FOREST[1] + math.sin(a) * d * 0.8), "r": q(R.uniform(14, 22))})
    for k in range(900):
        x, z = R.uniform(-5800, 5800), R.uniform(-4800, HZ - 100)
        if abs(z) < 120 or (z > 0 and inside(x, z, -120)):
            continue
        if math.hypot(x - FOREST[0], z - FOREST[1]) < FOREST[2] + 50:
            continue
        trees.append({"x": q(x), "z": q(z), "r": q(R.uniform(3, 7))})
    out["trees"] = trees
    out["pois"] = [{"n": "The Outer Gate", "x": 0, "z": q(DIST_R), "k": "gate", "ang": 0},
                   {"n": "The Inner Gate", "x": 0, "z": 0, "k": "gate", "ang": 0}]
    t = out["terrain"]
    with open(OUT, "w") as f:
        json.dump(out, f, separators=(",", ":"))
    print(f"wrote {OUT}: {os.path.getsize(OUT)/1e6:.1f} MB; buildings {len(buildings)} ({houses} houses); roads {len(roads)}; "
          f"terrain {t['nx']}x{t['nz']} at {t['step']} m, {min(t['h'])/10:.0f} m to {max(t['h'])/10:.0f} m")


if __name__ == "__main__":
    main()
