// GENERATED by tools/build-page.py from src/chicago/stages/ (9 files, sources e651ec06122fbb40).
// Do not edit: change the stage files and run ./sitectl build.
import {report,section,stage,LOAD} from '../core/diag.js';
import {createLcg,makeNoise,clamp,smooth,hash3,mkRng} from '../core/rng.js';
import {DATA_FN,dataValue,resolveCity} from '../core/data.js';
import {createEnv} from '../core/env.js';
export async function build(ctx){
// ===== stages/00-start.js =====
// ---------- start: three.js check, the city file, projection, randomness, where things are ----------
if(!window.THREE){document.getElementById('loading').textContent='three.js did not load (vendor/three/three.min.js). Check the site mounts and reload.';return;}
const THREE=window.THREE;
const CITY_ID=(()=>{const v=new URLSearchParams(location.search).get('city')||'';return /^[a-z0-9-]{1,40}$/.test(v)?v:'chicago';})();
ctx.cityId=CITY_ID;
const C=await fetch('data/cities/'+CITY_ID+'.json').then(r=>{if(!r.ok)throw new Error('data/cities/'+CITY_ID+'.json: HTTP '+r.status);return r.json();});
const SEED_DEFAULT=C.defaultSeed||1871;
const SEED0=(()=>{try{const v=parseInt(new URLSearchParams(location.search).get('seed')||new URLSearchParams(location.hash.slice(1)).get('seed'),10);return v>0&&v<2147483647?v:SEED_DEFAULT;}catch(e){return SEED_DEFAULT;}})();
const LCG=createLcg(SEED0);const rnd=LCG.rnd,rr=LCG.rr,pick=LCG.pick;
const {vn,fbm}=makeNoise(rnd);
const xr=mkRng(20261017),xrr=(a,b)=>a+(b-a)*xr();
const animHooks=[];
// projection: metres east (x) and south (z) of the origin; good to a few metres across downtown
const [LAT0,LON0]=C.origin,M_LAT=111132,M_LON=111320*Math.cos(LAT0*Math.PI/180);
const lonX=lon=>(lon-LON0)*M_LON,latZ=lat=>-(lat-LAT0)*M_LAT;
const P=([lat,lon])=>[lonX(lon),latZ(lat)];
const toLatLon=(x,z)=>[LAT0-z/M_LAT,LON0+x/M_LON];
ctx.project=P;ctx.toLatLon=toLatLon;
// the map rectangle, in metres
const B=(()=>{const [s,w,n,e]=C.bounds;return {x0:lonX(w),x1:lonX(e),z0:latZ(n),z1:latZ(s)};})();B.w=B.x1-B.x0;B.d=B.z1-B.z0;B.cx=(B.x0+B.x1)/2;B.cz=(B.z0+B.z1)/2;
const inMap=(x,z,m)=>x>B.x0+(m||0)&&x<B.x1-(m||0)&&z>B.z0+(m||0)&&z<B.z1-(m||0);
// geometry helpers
function segDist(px,pz,ax,az,bx,bz){const dx=bx-ax,dz=bz-az,L=dx*dx+dz*dz;let t=L?((px-ax)*dx+(pz-az)*dz)/L:0;t=Math.max(0,Math.min(1,t));return Math.hypot(px-ax-t*dx,pz-az-t*dz);}
function pathDist(x,z,pts){let d=Infinity;for(let i=0;i+1<pts.length;i++)d=Math.min(d,segDist(x,z,pts[i][0],pts[i][1],pts[i+1][0],pts[i+1][1]));return d;}
function inPoly(x,z,poly){let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const [xi,zi]=poly[i],[xj,zj]=poly[j];if((zi>z)!==(zj>z)&&x<(xj-xi)*(z-zi)/(zj-zi)+xi)c=!c;}return c;}
function segHit(a,b,c,d){const r=[b[0]-a[0],b[1]-a[1]],s=[d[0]-c[0],d[1]-c[1]],den=r[0]*s[1]-r[1]*s[0];if(Math.abs(den)<1e-9)return null;
  const t=((c[0]-a[0])*s[1]-(c[1]-a[1])*s[0])/den,u=((c[0]-a[0])*r[1]-(c[1]-a[1])*r[0])/den;if(t<0||t>1||u<0||u>1)return null;return {x:a[0]+t*r[0],z:a[1]+t*r[1],r,s};}
// water: the lake is everything east of the shore line; rivers are thick polylines
const SHORE=C.shore.map(P);
const LAKE_POLY=[[SHORE[0][0],B.z0-2000],...SHORE,[SHORE[SHORE.length-1][0],B.z1+2000],[B.x1+2000,B.z1+2000],[B.x1+2000,B.z0-2000]];   // shore north to south, then round the east side
const RIVERS=C.rivers.map(r=>({name:r.name,width:r.width,pts:r.path.map(P)}));
const PIER=(()=>{const b=P(C.pier.base),e=P(C.pier.end),w=P(C.pier.wheel);return {x0:b[0],x1:e[0],z:b[1],width:C.pier.width,wheelX:w[0],wheelR:C.pier.wheelR,length:e[0]-b[0]};})();
function onPier(x,z){return x>=PIER.x0-40&&x<=PIER.x1&&Math.abs(z-PIER.z)<=PIER.width/2;}
function inLake(x,z){return inPoly(x,z,LAKE_POLY)&&!onPier(x,z);}
function riverAt(x,z,pad){for(const r of RIVERS)if(pathDist(x,z,r.pts)<=r.width/2+(pad||0))return r;return null;}
const inRiver=(x,z)=>!!riverAt(x,z,0);
const inWater=(x,z)=>inLake(x,z)||inRiver(x,z);
// streets: named lists plus the regular Chicago grid filled in around them
const range=(r,a,b)=>r.length>4?[r[4],r[5]]:[a,b];
const STREETS=[];   // {name,w,major,a:[x,z],b:[x,z]} straight segments; diagonals are split into segments
for(const s of C.streetsNS){const [lat0,lat1]=range(s,-90,90);const x=lonX(s[1]);STREETS.push({name:s[0],w:s[2],major:!!s[3],a:[x,Math.max(B.z0,latZ(lat1))],b:[x,Math.min(B.z1,latZ(lat0))],axis:'x',at:x});}
for(const s of C.streetsEW){const [lon0,lon1]=range(s,-180,180);const z=latZ(s[1]);STREETS.push({name:s[0],w:s[2],major:!!s[3],a:[Math.max(B.x0,lonX(lon0)),z],b:[Math.min(B.x1,lonX(lon1)),z],axis:'z',at:z});}
{const F=C.fill,nsX=STREETS.filter(s=>s.axis==='x').map(s=>s.at),ewZ=STREETS.filter(s=>s.axis==='z').map(s=>s.at);
 for(let x=Math.ceil(B.x0/F.ns)*F.ns;x<=B.x1;x+=F.ns)if(!nsX.some(v=>Math.abs(v-x)<F.ns*0.6))STREETS.push({name:'',w:F.street,major:false,a:[x,B.z0],b:[x,B.z1],axis:'x',at:x,fill:true});
 for(let z=Math.ceil(B.z0/F.ew)*F.ew;z<=B.z1;z+=F.ew)if(!ewZ.some(v=>Math.abs(v-z)<F.ew*0.45))STREETS.push({name:'',w:F.street,major:false,a:[B.x0,z],b:[B.x1,z],axis:'z',at:z,fill:true});}
const DIAGONALS=C.diagonals.map(([name,w,path])=>({name,w,major:true,pts:path.map(P)}));
for(const d of DIAGONALS)for(let i=0;i+1<d.pts.length;i++)STREETS.push({name:d.name,w:d.w,major:true,a:d.pts[i],b:d.pts[i+1],axis:'d'});
function streetAt(x,z){for(const s of STREETS)if(segDist(x,z,s.a[0],s.a[1],s.b[0],s.b[1])<=s.w/2)return s;return null;}
// parks, beaches, districts
const PARKS=C.parks.map(p=>{if(p.poly){const pts=p.poly.map(P),xs=pts.map(q=>q[0]),zs=pts.map(q=>q[1]);return {name:p.name,pts,x0:Math.min(...xs),x1:Math.max(...xs),z0:Math.min(...zs),z1:Math.max(...zs)};}   // a rectangle, or a polygon for parks like Wicker Park's triangle
  const [la0,lo0,la1,lo1]=p.rect;return {name:p.name,x0:lonX(lo0),x1:lonX(lo1),z0:latZ(la1),z1:latZ(la0)};});
function parkAt(x,z){for(const p of PARKS)if(x>=p.x0&&x<=p.x1&&z>=p.z0&&z<=p.z1&&(!p.pts||inPoly(x,z,p.pts)))return p;return null;}
const BEACHES=C.beaches.map(b=>({name:b.name,w:b.width,pts:b.path.map(P)}));
const DIST={},DIST_BOX=[];
for(const k in C.districts){if(k==='_')continue;const [name,col,base,tall,box]=C.districts[k];DIST[k]={key:k,name,color:parseInt(col.slice(1),16),base,tall};
  if(box)DIST_BOX.push([DIST[k],lonX(box[1]),lonX(box[3]),latZ(box[2]),latZ(box[0])]);}
function districtAt(x,z){for(const [d,x0,x1,z0,z1] of DIST_BOX)if(x>=x0&&x<=x1&&z>=z0&&z<=z1)return d;return DIST.outer;}
const SKY_C=P(C.skylineCentre);
const EL=(()=>{const e=C.el;return {north:latZ(e.north),south:latZ(e.south),east:lonX(e.east),west:lonX(e.west),height:e.height,trains:e.trains,cars:e.cars,
  blue:e.blue?{height:e.blue.height,trains:e.blue.trains,cars:e.blue.cars,pts:e.blue.path.map(P),stations:e.blue.stations.map(([la,lo,name])=>[...P([la,lo]),name])}:null};})();
const TRAILS=(C.trails||[]).map(t=>({name:t.name,info:t.info,height:t.height,width:t.width,pts:t.path.map(P)}));
ctx.districtAt=districtAt;ctx.inWater=inWater;ctx.streets=STREETS.length;
// ===== stages/01-scene.js =====
// ---------- scene: renderer, camera, the sun's day, sky ----------
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,1,24000);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
document.body.appendChild(renderer.domElement);
const {ENV,setEnv}=createEnv();   // the shared uniforms; setEnv gives materials world-unit UV tiling
const updatePx=()=>{ENV.izPx.value=innerHeight*renderer.getPixelRatio()/(2*Math.tan(camera.fov*Math.PI/360));};updatePx();
const ambient=new THREE.AmbientLight(0x9fb4c8,0.35);scene.add(ambient);
const hemi=new THREE.HemisphereLight(0xbfd8f0,0x5a5048,0.55);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xfff2dc,1.1);scene.add(sun);scene.add(sun.target);
sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);{const sc=sun.shadow.camera;sc.left=-700;sc.right=700;sc.top=700;sc.bottom=-700;sc.near=1;sc.far=6000;sc.updateProjectionMatrix();}
sun.shadow.bias=-0.0008;sun.shadow.normalBias=2;
scene.fog=new THREE.FogExp2(0xb9cbe0,0.00013);
// the clock: DAY real seconds per city day
let DAY=240;const HOUR0=10.5;let clockPaused=false,pausedAt=0,clockOffset=0;
function hourNow(now){return ((HOUR0+((now/1000)/(DAY/24)))%24+24)%24;}
function setHour(h){const now=performance.now(),cur=clockPaused?pausedAt:now-clockOffset,tot=HOUR0+(cur/1000)/(DAY/24);let day=Math.floor(tot/24);if(day*24+h<HOUR0)day+=1;const t=(day*24+h-HOUR0)*(DAY/24)*1000;if(clockPaused)pausedAt=t;else clockOffset=now-t;}
window.setHour=setHour;
const nightF=h=>1-smooth(5.6,7.4,h)+smooth(17.6,19.6,h);   // ~1 at night, 0 by day (Chicago, spring)
const windowF=h=>smooth(16.5,18.5,h)*(1-smooth(23,25,h))+0.12*nightF(h);
// the sun: rises in the east over the lake (+x), sets in the west
function sunAt(h){const f=(h-6)/12,E=Math.sin(Math.PI*f)*0.95,az=Math.PI*(1-f);return new THREE.Vector3(Math.cos(az)*Math.cos(E),Math.sin(E),Math.sin(az)*0.35*Math.cos(E)).normalize();}
// sky: a gradient dome, coloured by the hour
const SKY={day:{top:0x2f6fd0,hor:0xbcd3ee},dusk:{top:0x2a3a78,hor:0xf0a060},night:{top:0x050a1c,hor:0x16243c}};
const skyM=new THREE.ShaderMaterial({uniforms:{top:{value:new THREE.Color()},hor:{value:new THREE.Color()},sunDir:{value:new THREE.Vector3(0,1,0)},sunA:{value:1}},side:THREE.BackSide,depthWrite:false,fog:false,
  vertexShader:'varying vec3 vP;void main(){vP=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',
  fragmentShader:'uniform vec3 top;uniform vec3 hor;uniform vec3 sunDir;uniform float sunA;varying vec3 vP;void main(){float t=clamp(vP.y*1.6,0.0,1.0);vec3 c=mix(hor,top,pow(t,0.6));float d=max(dot(vP,sunDir),0.0);c+=vec3(1.0,0.85,0.6)*(pow(d,600.0)*1.2+pow(d,8.0)*0.18)*sunA;gl_FragColor=vec4(c,1.0);}'});
const sky=new THREE.Mesh(new THREE.SphereGeometry(11000,32,16),skyM);sky.userData.noShadow=true;scene.add(sky);
const tmpC=new THREE.Color(),tmpC2=new THREE.Color();
function lerpSky(h){const n=nightF(h),dusk=Math.max(0,1-Math.abs(h-18.6)/1.6,1-Math.abs(h-6.3)/1.4);
  const mixTo=(a,b,k)=>tmpC.set(a).lerp(tmpC2.set(b),k);
  skyM.uniforms.top.value.copy(mixTo(SKY.day.top,SKY.night.top,n)).lerp(tmpC2.set(SKY.dusk.top),dusk*0.7);
  skyM.uniforms.hor.value.copy(mixTo(SKY.day.hor,SKY.night.hor,n)).lerp(tmpC2.set(SKY.dusk.hor),dusk);
  scene.fog.color.copy(skyM.uniforms.hor.value);renderer.setClearColor(skyM.uniforms.hor.value);
  const S=sunAt(h);skyM.uniforms.sunDir.value.copy(S);skyM.uniforms.sunA.value=S.y>-0.05?1:0;
  sun.position.copy(S).multiplyScalar(2500).add(sun.target.position);sun.intensity=1.15*Math.max(0,Math.min(1,S.y*4))*(1-0.85*n);
  sun.color.setHSL(0.09,0.6,0.5+0.45*Math.min(1,S.y*3));hemi.intensity=0.55*(1-0.75*n);ambient.intensity=0.35*(1-0.5*n)+0.12*n;
  ENV.izHour.value=h;ENV.izNight.value=n;ENV.izDay.value=1-n;ENV.izSunDir.value.copy(S);}
let hourCur=HOUR0;
animHooks.push(now=>{hourCur=hourNow(clockPaused?pausedAt:now-clockOffset);ctx.hour=hourCur;ENV.izTime.value=now/1000;lerpSky(hourCur);});
lerpSky(HOUR0);
// ===== stages/02-ground.js =====
// ---------- ground: the painted map (sidewalks, streets, crosswalks, parks, beaches), the lake shore, the river's real course, bridges, the pier, The 606, trees ----------
await stage('ground');
const PX=4096/Math.max(B.w,B.d),GW=Math.round(B.w*PX),GD=Math.round(B.d*PX),pxX=v=>(v-B.x0)*PX,pxZ=v=>(v-B.z0)*PX;
const gcv=document.createElement('canvas');gcv.width=GW;gcv.height=GD;const g2=gcv.getContext('2d');
const polyPath=(pts,close)=>{g2.beginPath();pts.forEach(([x,z],i)=>i?g2.lineTo(pxX(x),pxZ(z)):g2.moveTo(pxX(x),pxZ(z)));if(close)g2.closePath();};
const strokePath=(pts,w,col,cap)=>{g2.strokeStyle=col;g2.lineWidth=Math.max(1,w*PX);g2.lineCap=cap||'round';g2.lineJoin='round';polyPath(pts,false);g2.stroke();};
const fillRectM=(x0,z0,w,d,col)=>{g2.fillStyle=col;g2.fillRect(pxX(x0),pxZ(z0),w*PX,d*PX);};
const WATER='#2f6690';
function paintWater(){g2.fillStyle=WATER;polyPath(LAKE_POLY,true);g2.fill();for(const r of RIVERS)strokePath(r.pts,r.width,WATER);}
section('ground',()=>{
  g2.fillStyle='#4f5a44';g2.fillRect(0,0,GW,GD);   // yards and lawns of the low city (downtown is paved over by its buildings)
  // sidewalks first (a pale band either side), then the asphalt over them
  for(const s of STREETS)strokePath([s.a,s.b],s.w+(s.major?10:7),'#a7a399','butt');
  for(const s of STREETS)if(!s.major)strokePath([s.a,s.b],s.w,'#4b4c50','butt');
  for(const p of PARKS){g2.fillStyle='#5f8a48';if(p.pts){polyPath(p.pts,true);g2.fill();}else g2.fillRect(pxX(p.x0),pxZ(p.z0),(p.x1-p.x0)*PX,(p.z1-p.z0)*PX);
    const R=mkRng(Math.round(p.x0*7+p.z0));g2.fillStyle='rgba(30,70,30,0.35)';for(let k=0;k<(p.x1-p.x0)*(p.z1-p.z0)/900;k++){const x=p.x0+R()*(p.x1-p.x0),z=p.z0+R()*(p.z1-p.z0);if(p.pts&&!inPoly(x,z,p.pts))continue;g2.beginPath();g2.arc(pxX(x),pxZ(z),1.5+R()*3,0,7);g2.fill();}
    // a path round the edge and one across
    g2.strokeStyle='rgba(214,204,178,0.8)';g2.lineWidth=Math.max(1,3*PX);if(p.pts){polyPath(p.pts,true);g2.stroke();}else{g2.strokeRect(pxX(p.x0+6),pxZ(p.z0+6),(p.x1-p.x0-12)*PX,(p.z1-p.z0-12)*PX);g2.beginPath();g2.moveTo(pxX(p.x0),pxZ(p.z0));g2.lineTo(pxX(p.x1),pxZ(p.z1));g2.stroke();}}
  for(const b of BEACHES)strokePath(b.pts,b.w*2,'#dccda4');
  for(const s of STREETS)if(s.major)strokePath([s.a,s.b],s.w,'#35373b','butt');
  g2.setLineDash([12*PX*4,12*PX*4]);for(const s of STREETS)if(s.major)strokePath([s.a,s.b],0.4,'rgba(210,180,80,0.22)','butt');g2.setLineDash([]);
  // crosswalks: zebra bars across each approach where two major streets meet
  const majors=STREETS.filter(s=>s.major&&s.axis!=='d');let nx=0;
  for(const a of majors)if(a.axis==='x')for(const b of majors)if(b.axis==='z'){const x=a.at,z=b.at;if(z<Math.min(a.a[1],a.b[1])||z>Math.max(a.a[1],a.b[1])||x<Math.min(b.a[0],b.b[0])||x>Math.max(b.a[0],b.b[0])||!inMap(x,z,40)||inWater(x,z))continue;nx++;
    g2.fillStyle='rgba(235,232,220,0.85)';for(const sd of [-1,1]){const zc=z+sd*(b.w/2+3),xc=x+sd*(a.w/2+3);
      for(let k=-a.w/2+1;k<a.w/2;k+=2.6)g2.fillRect(pxX(x+k),pxZ(zc-2),Math.max(1,1.3*PX),4*PX);
      for(let k=-b.w/2+1;k<b.w/2;k+=2.6)g2.fillRect(pxX(xc-2),pxZ(z+k),4*PX,Math.max(1,1.3*PX));}}
  ctx.crossings=nx;
  fillRectM(PIER.x0-40,PIER.z-PIER.width/2,PIER.length+40,PIER.width,'#a19b90');
  for(const r of RIVERS)strokePath(r.pts,r.width+12,'#c9c2b4');   // the river walls: a pale edge along both banks
  paintWater();   // the lake and the river win over anything painted across them
  fillRectM(PIER.x0,PIER.z-PIER.width/2,PIER.length,PIER.width,'#a19b90');
});
const groundTex=new THREE.CanvasTexture(gcv);groundTex.anisotropy=8;
const ground=new THREE.Mesh(new THREE.PlaneGeometry(B.w,B.d),new THREE.MeshLambertMaterial({map:groundTex}));ground.rotation.x=-Math.PI/2;ground.position.set(B.cx,0,B.cz);ground.receiveShadow=true;ground.userData.noShadow=true;scene.add(ground);
// water surfaces: the lake as its real outline, each river as a ribbon that follows its bends
const waterM=new THREE.MeshPhongMaterial({color:0x2c6390,specular:0x9fc4e0,shininess:90,transparent:true,opacity:0.92});
{const shape=new THREE.Shape();LAKE_POLY.forEach(([x,z],i)=>{const cx=Math.max(B.x0,Math.min(B.x1+1500,x)),cz=Math.max(B.z0-1500,Math.min(B.z1+1500,z));i?shape.lineTo(cx,-cz):shape.moveTo(cx,-cz);});   // shape is in x,y; rotated flat, y becomes -z
 const lake=new THREE.Mesh(new THREE.ShapeGeometry(shape),waterM);lake.rotation.x=-Math.PI/2;lake.position.y=0.15;lake.receiveShadow=true;scene.add(lake);
 for(const r of RIVERS){const pos=[],idx=[],L=r.pts;for(let i=0;i<L.length;i++){const a=L[Math.max(0,i-1)],b=L[Math.min(L.length-1,i+1)];let dx=b[0]-a[0],dz=b[1]-a[1];const n=Math.hypot(dx,dz)||1;dx/=n;dz/=n;const h=r.width/2+2;
     pos.push(L[i][0]-dz*h,0.2,L[i][1]+dx*h,L[i][0]+dz*h,0.2,L[i][1]-dx*h);if(i)idx.push((i-1)*2,(i-1)*2+1,i*2,(i-1)*2+1,i*2+1,i*2);}
   const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();
   const m=new THREE.Mesh(g,waterM.clone());m.material.side=THREE.DoubleSide;scene.add(m);}}
animHooks.push(now=>{waterM.shininess=70+25*Math.sin(now*0.0011);});
const stoneM=new THREE.MeshLambertMaterial({color:0xbdb5a6}),steelM=new THREE.MeshLambertMaterial({color:0x6b6f75});
// the pier: a slab with its sheds and the Festival Hall at the end
{const slab=new THREE.Mesh(new THREE.BoxGeometry(PIER.length,4,PIER.width),stoneM);slab.position.set(PIER.x0+PIER.length/2,2,PIER.z);slab.castShadow=slab.receiveShadow=true;scene.add(slab);
 const shedM=new THREE.MeshLambertMaterial({color:0xd8d2c4});for(let k=0;k<5;k++){const shed=new THREE.Mesh(new THREE.BoxGeometry(140,12,34),shedM);shed.position.set(PIER.x0+140+k*160,10,PIER.z+(k%2?20:-20));shed.castShadow=true;scene.add(shed);}
 const hall=new THREE.Mesh(new THREE.BoxGeometry(80,26,86),new THREE.MeshLambertMaterial({color:0xc9b8a0}));hall.position.set(PIER.x1-45,17,PIER.z);hall.castShadow=true;scene.add(hall);}
// bridges: wherever a street crosses a river, a deck along the street, as long as the crossing is wide
const bridges=[];
function bridge(x,z,ang,w,len){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=-ang;
  const deck=new THREE.Mesh(new THREE.BoxGeometry(len,2.4,w),steelM);deck.position.y=4.2;deck.castShadow=deck.receiveShadow=true;g.add(deck);
  for(const s of [-1,1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(len,3.2,1.2),steelM);rail.position.set(0,7,s*(w/2-0.6));g.add(rail);
    const tower=new THREE.Mesh(new THREE.BoxGeometry(7,13,7),stoneM);tower.position.set(s*(len/2-3),6.5,w/2+3);g.add(tower);}
  scene.add(g);bridges.push({x,z,ang,w,len});}
section('bridges',()=>{
  for(const s of STREETS)for(const r of RIVERS)for(let i=0;i+1<r.pts.length;i++){const h=segHit(s.a,s.b,r.pts[i],r.pts[i+1]);if(!h||!inMap(h.x,h.z,30))continue;
    const rl=Math.hypot(...h.r),sl=Math.hypot(...h.s),sin=Math.abs(h.r[0]*h.s[1]-h.r[1]*h.s[0])/(rl*sl);if(sin<0.45)continue;   // a street running along the bank is not a crossing
    if(bridges.some(b=>Math.hypot(b.x-h.x,b.z-h.z)<25))continue;
    bridge(h.x,h.z,Math.atan2(h.r[1],h.r[0]),s.w+2,r.width/sin+18);}
  ctx.details=Object.assign(ctx.details||{},{bridges:bridges.length});});
function onBridge(x,z){for(const b of bridges){const dx=x-b.x,dz=z-b.z,c=Math.cos(b.ang),s=Math.sin(b.ang),u=dx*c+dz*s,v=-dx*s+dz*c;if(Math.abs(u)<=b.len/2&&Math.abs(v)<=b.w/2)return true;}return false;}
// The 606: the old Bloomingdale rail embankment, a raised trail with railings and its own trees
const TRAIL_INFO=[];
section('trails',()=>{const pathM=new THREE.MeshLambertMaterial({color:0x5a5a5e}),wallM=new THREE.MeshLambertMaterial({color:0x9a8e7e});
  for(const t of TRAILS)for(let i=0;i+1<t.pts.length;i++){const [ax,az]=t.pts[i],[bx,bz]=t.pts[i+1],len=Math.hypot(bx-ax,bz-az),ang=Math.atan2(bz-az,bx-ax),g=new THREE.Group();g.position.set((ax+bx)/2,0,(az+bz)/2);g.rotation.y=-ang;
    const body=new THREE.Mesh(new THREE.BoxGeometry(len,t.height,t.width),wallM);body.position.y=t.height/2;body.castShadow=body.receiveShadow=true;g.add(body);
    const path=new THREE.Mesh(new THREE.BoxGeometry(len,0.2,t.width*0.35),pathM);path.position.y=t.height+0.1;g.add(path);
    for(const s of [-1,1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(len,1.1,0.2),steelM);rail.position.set(0,t.height+0.55,s*(t.width/2-0.1));g.add(rail);}
    g.userData.info={name:t.name,info:t.info};TRAIL_INFO.push(g);scene.add(g);}
  ctx.details=Object.assign(ctx.details||{},{trails:TRAILS.length});});
// trees: parks, Michigan Avenue, The 606, and the parkway trees that line Chicago's residential streets
const PARK_FEATURES=C.landmarks.map(l=>{const [x,z]=P(l.at);return [x,z,Math.max(l.w||20,l.d||0)*0.6+(l.gap||0)*0.6+(l.kind==='pavilion'?110:l.kind==='fieldhouse'||l.kind==='pool'?18:25)];});   // plazas, lawns and fountains stay open
section('trees',()=>{const trunkM=new THREE.MeshLambertMaterial({color:0x5a4030}),leafM=new THREE.MeshLambertMaterial({color:0x3f7a3a}),leaf2M=new THREE.MeshLambertMaterial({color:0x4f8a3a});
  const spots=[],street=[];
  for(const p of PARKS){const R=mkRng(Math.round(p.x1*3+p.z1));const n=Math.floor((p.x1-p.x0)*(p.z1-p.z0)/1300);
    for(let k=0;k<n;k++){const x=p.x0+6+R()*(p.x1-p.x0-12),z=p.z0+6+R()*(p.z1-p.z0-12);if(p.pts&&!inPoly(x,z,p.pts))continue;if(!streetAt(x,z)&&!inWater(x,z)&&!PARK_FEATURES.some(f=>Math.hypot(f[0]-x,f[1]-z)<f[2]))spots.push([x,z,7+R()*7]);}}
  const mich=lonX(-87.6245);for(let z=latZ(41.9008);z<=latZ(41.8674);z+=24)for(const s of [-1,1]){const x=mich+s*22;if(!inWater(x,z)&&!parkAt(x,z))spots.push([x,z,7]);}
  for(const t of TRAILS)for(let i=0;i+1<t.pts.length;i++){const [ax,az]=t.pts[i],[bx,bz]=t.pts[i+1],L=Math.hypot(bx-ax,bz-az);for(let s=10;s<L;s+=18)for(const sd of [-1,1]){const u=s/L,nx=-(bz-az)/L,nz=(bx-ax)/L;spots.push([ax+(bx-ax)*u+nx*sd*4,az+(bz-az)*u+nz*sd*4,5+((s*7)%3),t.height]);}}
  // parkway trees: every 14 m along both sides of the low-rise streets, skipping corners, water and the tall districts
  const R=mkRng(606);for(const s of STREETS){if(s.major||s.axis==='d')continue;const L=Math.hypot(s.b[0]-s.a[0],s.b[1]-s.a[1]),dx=(s.b[0]-s.a[0])/L,dz=(s.b[1]-s.a[1])/L;
    for(let u=7;u<L;u+=14)for(const sd of [-1,1]){const x=s.a[0]+dx*u-dz*sd*(s.w/2+2.5),z=s.a[1]+dz*u+dx*sd*(s.w/2+2.5);if(R()<0.22)continue;const d=districtAt(x,z);if(d.tall>30||!inMap(x,z,30)||inWater(x,z)||parkAt(x,z))continue;
      if(STREETS.some(o=>o!==s&&o.axis!==s.axis&&segDist(x,z,o.a[0],o.a[1],o.b[0],o.b[1])<o.w/2+9))continue;street.push([x,z,6+R()*6]);}}
  const put=(list,kind)=>{const n=list.length;const tr=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.35,0.55,1,5),trunkM,n),lf=new THREE.InstancedMesh(kind?new THREE.IcosahedronGeometry(1,0):new THREE.SphereGeometry(1,7,5),kind?leaf2M:leafM,n),d=new THREE.Object3D();
    list.forEach(([x,z,h,y0],i)=>{y0=y0||0;d.position.set(x,y0+h*0.25,z);d.scale.set(1,h*0.5,1);d.updateMatrix();tr.setMatrixAt(i,d.matrix);d.position.set(x,y0+h*0.72,z);d.scale.set(h*0.4,h*0.36,h*0.4);d.updateMatrix();lf.setMatrixAt(i,d.matrix);});
    tr.castShadow=lf.castShadow=true;tr.frustumCulled=lf.frustumCulled=false;scene.add(tr,lf);return [tr,lf];};
  put(spots,0);put(street,1);ctx.trees=spots.length+street.length;});
// ===== stages/03-blocks.js =====
// ---------- blocks: towers downtown; outside it, Chicago's residential blocks: two rows of narrow lots either side of an alley, houses set back behind their yards, garages on the alley, shopfronts on the commercial streets ----------
await stage('blocks');
// window textures: the facade (light ground, dark panes) and what glows at night (only the panes)
function winTex(glow,cols,rows){const cv=document.createElement('canvas');cv.width=cv.height=64;const g=cv.getContext('2d');g.fillStyle=glow?'#000':'#f2f0ec';g.fillRect(0,0,64,64);
  const R=mkRng(glow?5:9),cw=64/cols,rh=64/rows;for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const lit=R()<0.55;g.fillStyle=glow?(lit?`rgb(${230+R()*25},${200+R()*40},${140+R()*60})`:'#000'):`rgb(${40+R()*30},${52+R()*30},${70+R()*30})`;g.fillRect(i*cw+cw*0.2,j*rh+rh*0.15,cw*0.55,rh*0.62);}
  const t=new THREE.CanvasTexture(cv);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t;}
const facadeTex=winTex(false,4,4),glowTex=winTex(true,4,4),houseTex=winTex(false,2,1),houseGlow=winTex(true,2,1);
const bldMats={};   // one material per district: colour × window map, tiled in world units (a window bay every 4 m)
function bldMat(d){if(bldMats[d.key])return bldMats[d.key];const m=new THREE.MeshLambertMaterial({color:d.color,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});m.color.multiplyScalar(1.15);setEnv(m,{K:0.25,id:'bld'+d.key});bldMats[d.key]=m;return m;}
const brickM=new THREE.MeshLambertMaterial({color:0xffffff,map:houseTex,emissiveMap:houseGlow,emissive:0x000000});setEnv(brickM,{K:0.28,id:'brick'});bldMats._brick=brickM;   // houses: two windows per 3.6 m bay, one per storey
const trimM=new THREE.MeshLambertMaterial({color:0xffffff}),roofM=new THREE.MeshLambertMaterial({color:0x4a4644}),garageM=new THREE.MeshLambertMaterial({color:0x5e5a54});
const shopM=new THREE.MeshLambertMaterial({color:0x1e2a34,emissive:0x000000}),awningM=new THREE.MeshLambertMaterial({color:0xffffff}),tankM=new THREE.MeshLambertMaterial({color:0x6a5040});
const BRICK=['#8a4b3a','#9c5a45','#7a4535','#b07a5a','#c9b79a','#a39a8a','#6e5a4e','#b58e6a','#d2c3a8','#8c7b6a','#a8624a','#c2a888'].map(h=>new THREE.Color(h));
const AWNING=['#1f5f3a','#7a1f24','#1f3f6a','#c8a030','#2a2a2a','#a04a20','#3a6a7a'].map(h=>new THREE.Color(h));
const lots=[];   // {x,z,w,dpt,h,ry,kind,district}
const boxG=new THREE.BoxGeometry(1,1,1);boxG.translate(0,0.5,0);
const prismG=(()=>{const g=new THREE.BufferGeometry(),v=[-0.5,0,-0.5, 0.5,0,-0.5, 0,1,-0.5, -0.5,0,0.5, 0.5,0,0.5, 0,1,0.5],idx=[0,2,1, 3,4,5, 0,1,4, 0,4,3, 0,3,5, 0,5,2, 1,2,5, 1,5,4];g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();return g.toNonIndexed();})();
prismG.computeVertexNormals();
// instances grouped into 700 m tiles, each with bounds from its own instances, so the camera and the shadow pass can skip what is out of view;
// small details (trim, roofs, garages, shopfronts) are also hidden beyond `far` metres from the camera
const CHUNKS=[];
function chunker(geo,mat,shadow,far){const tiles=new Map(),d=new THREE.Object3D(),TS=700;
  return {n:0,add(x,y,z,sx,sy,sz,ry,col){const k=Math.floor(x/TS)+','+Math.floor(z/TS);let t=tiles.get(k);if(!t){t={m:[],c:[],x0:1e9,x1:-1e9,y1:0,z0:1e9,z1:-1e9,s:0};tiles.set(k,t);}
      d.position.set(x,y,z);d.rotation.set(0,ry||0,0);d.scale.set(sx,sy,sz);d.updateMatrix();t.m.push(...d.matrix.elements);t.c.push(col||null);
      t.x0=Math.min(t.x0,x);t.x1=Math.max(t.x1,x);t.z0=Math.min(t.z0,z);t.z1=Math.max(t.z1,z);t.y1=Math.max(t.y1,y+sy);t.s=Math.max(t.s,sx,sz);this.n++;},
    build(){for(const t of tiles.values()){const n=t.c.length,g=new THREE.BufferGeometry();if(geo.index)g.setIndex(geo.index);for(const k in geo.attributes)g.setAttribute(k,geo.attributes[k]);
        const cx=(t.x0+t.x1)/2,cz=(t.z0+t.z1)/2;g.boundingSphere=new THREE.Sphere(new THREE.Vector3(cx,t.y1/2,cz),Math.hypot(t.x1-t.x0,t.z1-t.z0,t.y1)/2+t.s);
        const im=new THREE.InstancedMesh(g,mat,n);im.instanceMatrix.array.set(t.m);if(t.c[0]){for(let i=0;i<n;i++)im.setColorAt(i,t.c[i]||BRICK[0]);}
        im.castShadow=!!shadow;im.receiveShadow=true;im.userData.far=far||0;scene.add(im);CHUNKS.push(im);}}};}
const BODY=chunker(boxG,brickM,true),TRIM=chunker(boxG,trimM,true,1500),ROOF=chunker(prismG,roofM,true,2200),GARAGE=chunker(boxG,garageM,false,900),SHOP=chunker(boxG,shopM,false,1200),AWN=chunker(boxG,awningM,false,900),TANK=chunker(new THREE.CylinderGeometry(1,1,1,10).translate(0,0.5,0),tankM,true,2000);
function skyline(d,x,z){const dist=Math.hypot(x-SKY_C[0],z-SKY_C[1]),f=Math.pow(Math.max(0,1-dist/1900),1.4),n=0.35+0.65*fbm(x*0.004+3,z*0.004+9);return d.base+(d.tall-d.base)*f*n;}
const lmFoot=C.landmarks.filter(l=>l.kind!=='pier').map(l=>{const [x,z]=P(l.at);return {x,z,r:Math.max(l.w||40,(l.d||0)+(l.gap||0))*0.6+14};});
const nearLandmark=(x,z,r)=>lmFoot.some(f=>Math.hypot(f.x-x,f.z-z)<f.r+r);
const DIAG_SEGS=STREETS.filter(s=>s.axis==='d');
const FOCUS=(C.focus||[]).map(f=>{const [x,z]=P(f.at);return {name:f.name,x,z,r:f.radius};});
const focusAt=(x,z)=>FOCUS.find(f=>Math.hypot(f.x-x,f.z-z)<f.r)||null;
const dry=(x,z)=>!inWater(x,z)&&!parkAt(x,z)&&!onPier(x,z)&&!DIAG_SEGS.some(s=>segDist(x,z,s.a[0],s.a[1],s.b[0],s.b[1])<=s.w/2+5);   // diagonals (Milwaukee, Lake Shore Drive) cut through the grid
const fits=(pts,r)=>pts.every(([x,z])=>inMap(x,z,20)&&dry(x,z)&&!riverAt(x,z,8))&&!nearLandmark(pts[0][0],pts[0][1],r);
section('blocks',()=>{
  const xs=[...new Map(STREETS.filter(s=>s.axis==='x').map(s=>[Math.round(s.at),s])).values()].sort((a,b)=>a.at-b.at);
  const zs=[...new Map(STREETS.filter(s=>s.axis==='z').map(s=>[Math.round(s.at),s])).values()].sort((a,b)=>a.at-b.at);
  const covers=(s,v)=>v>=Math.min(s.a[s.axis==='x'?1:0],s.b[s.axis==='x'?1:0])-1&&v<=Math.max(s.a[s.axis==='x'?1:0],s.b[s.axis==='x'?1:0])+1;   // a street with a range only bounds blocks inside it
  let houses=0,shops=0,alleys=0;
  for(let i=0;i+1<xs.length;i++)for(let j=0;j+1<zs.length;j++){
    const cx0=(xs[i].at+xs[i+1].at)/2,cz0=(zs[j].at+zs[j+1].at)/2;
    let W=xs[i],E=xs[i+1],N=zs[j],S=zs[j+1];
    if(!covers(W,cz0)||!covers(N,cx0))continue;
    let ii=i+1;while(ii<xs.length-1&&!covers(xs[ii],cz0))ii++;E=xs[ii];
    let jj=j+1;while(jj<zs.length-1&&!covers(zs[jj],cx0))jj++;S=zs[jj];
    const walk=3.5;   // sidewalk
    let x0=W.at+W.w/2+walk,x1=E.at-E.w/2-walk,z0=N.at+N.w/2+walk,z1=S.at-S.w/2-walk;
    if(x1-x0<24||z1-z0<24)continue;
    const cx=(x0+x1)/2,cz=(z0+z1)/2;if(!inMap(cx,cz,60))continue;
    const d=districtAt(cx,cz),H=skyline(d,cx,cz),foc=focusAt(cx,cz);
    if(H>30){   // downtown: towers alone or in pairs, midrises two to four
      const n=H>90?1+(rnd()<0.35?1:0):2+Math.floor(rnd()*3),cols=n>=3?2:n,rows=Math.ceil(n/cols);
      for(let k=0;k<n;k++){const ci=k%cols,rj=Math.floor(k/cols);const w=(x1-x0)/cols,dd=(z1-z0)/rows,gx=x0+ci*w,gz=z0+rj*dd;
        const inset=H>90?Math.min(w,dd)*0.1:1+rnd()*2,w2=w-2*inset,d2=dd-2*inset;if(w2<7||d2<7)continue;const lx=gx+w/2,lz=gz+dd/2;
        if(!fits([[lx,lz],[gx+inset,gz+inset],[gx+w-inset,gz+inset],[gx+inset,gz+dd-inset],[gx+w-inset,gz+dd-inset]],Math.max(w2,d2)*0.35))continue;
        let h=H*(0.55+0.9*rnd());if(k>0&&H>90)h*=0.35;h=Math.max(8,Math.min(h,d.tall*1.1));
        lots.push({x:lx,z:lz,w:w2,dpt:d2,h,ry:0,kind:h>120?'tower':'midrise',district:d,fixed:false});}
      continue;}
    // a residential block, long in u; the alley runs down its middle along u; houses face the two long sides, shops face any major street
    const longZ=(z1-z0)>=(x1-x0),U0=longZ?z0:x0,U1=longZ?z1:x1,V0=longZ?x0:z0,V1=longZ?x1:z1,SA=longZ?W:N,SB=longZ?E:S,E0=longZ?N:W,E1=longZ?S:E;
    const at=(u,v)=>longZ?[v,u]:[u,v],Vm=(V0+V1)/2,alleyW=5;
    const shopH=()=>foc?11+rnd()*7:7.5+rnd()*5;
    const shopAt=(u,v,w,depth,face,end)=>{   // (u,v) is the footprint centre; w runs along the street, depth away from it; face points at the street
      const [x,z]=at(u,v),[sx,sz]=(longZ!==!!end)?[depth,w]:[w,depth],h=shopH();
      if(!fits([[x,z],[x-sx/2,z-sz/2],[x+sx/2,z-sz/2],[x-sx/2,z+sz/2],[x+sx/2,z+sz/2]],2))return false;
      const col=BRICK[Math.floor(rnd()*BRICK.length)];BODY.add(x,0,z,sx,h,sz,0,col);TRIM.add(x,h,z,sx+0.6,0.9,sz+0.6,0,new THREE.Color(col).multiplyScalar(0.7));
      // the storefront glass and an awning on the street face
      const [fx,fz]=face;const ox=x+fx*(sx/2+0.2),oz=z+fz*(sz/2+0.2),gw=(fx?sz:sx)-0.8;
      SHOP.add(ox,0.3,oz,fx?0.5:gw,3.8,fz?0.5:gw,0);if(rnd()<0.7)AWN.add(x+fx*(sx/2+1),4.2,z+fz*(sz/2+1),fx?2:gw,0.35,fz?2:gw,0,AWNING[Math.floor(rnd()*AWNING.length)]);
      if(foc&&rnd()<0.25)TANK.add(x+(rnd()-0.5)*sx*0.4,h+2.5,z+(rnd()-0.5)*sz*0.4,2.4,4,2.4,0);
      lots.push({x,z,w:sx,dpt:sz,h,ry:0,kind:'shop',district:d,fixed:false});shops++;return true;};
    // ends that meet a major street become shop rows facing it
    const band0=E0.major?24:0,band1=E1.major?24:0;
    for(const [on,uc,faceU] of [[band0,U0+12,-1],[band1,U1-12,1]]){if(!on)continue;for(let v=V0;v<V1-6;){const w=Math.min(V1-v,7.6+rnd()*4.5);shopAt(uc,v+w/2,w,22,longZ?[0,faceU]:[faceU,0],true);v+=w;}}
    // the alley
    if(V1-V0>50){const [ax,az]=at((U0+band0+U1-band1)/2,Vm),len=U1-U0-band0-band1;g2.fillStyle='#57585b';if(longZ)g2.fillRect(pxX(ax-alleyW/2),pxZ(az-len/2),alleyW*PX,len*PX);else g2.fillRect(pxX(ax-len/2),pxZ(az-alleyW/2),len*PX,alleyW*PX);alleys++;}
    // the two long rows
    for(const [side,street] of [[-1,SA],[1,SB]]){const front=side<0?V0:V1,back=V1-V0>50?Vm+side*(alleyW/2):Vm,faceV=side;const depthMax=Math.abs(front-back);
      for(let u=U0+band0;u<U1-band1-6;){const w=Math.min(U1-band1-u,7.6+rnd()*(street.major?4:3.2)),uc=u+w/2;u+=w;
        if(street.major){shopAt(uc,front-side*11,w,22,longZ?[faceV,0]:[0,faceV]);continue;}
        // a house: front yard, the house, a back yard, a garage on the alley
        const setback=3.5+rnd()*2.5,depth=Math.min(depthMax-setback-9,14+rnd()*8);if(depth<8)continue;
        const vc=front-side*(setback+depth/2),[x,z]=at(uc,vc),ww=w-1.2,[sx,sz]=longZ?[depth,ww]:[ww,depth];
        if(!fits([[x,z],[x-sx/2,z-sz/2],[x+sx/2,z-sz/2],[x-sx/2,z+sz/2],[x+sx/2,z+sz/2]],1))continue;
        const storeys=rnd()<0.55?2:rnd()<0.7?3:1,h=storeys*3.4+0.8,col=BRICK[Math.floor(rnd()*BRICK.length)];
        BODY.add(x,0,z,sx,h,sz,0,col);
        if(rnd()<0.42){ROOF.add(x,h,z,ww,2.2+ww*0.18,depth,longZ?Math.PI/2:0);}   // a frame house: gable to the street
        else TRIM.add(x,h,z,sx+0.4,0.7,sz+0.4,0,new THREE.Color(col).multiplyScalar(0.75));   // a two- or three-flat: flat roof with a cornice
        if(depthMax>30&&rnd()<0.6){const [gx,gz]=at(uc,back-side*(-3.5)),[gsx,gsz]=longZ?[6,Math.min(ww,6.5)]:[Math.min(ww,6.5),6];if(fits([[gx,gz]],0))GARAGE.add(gx,0,gz,gsx,3,gsz,0);}
        lots.push({x,z,w:sx,dpt:sz,h,ry:0,kind:'house',district:d,fixed:false});houses++;}}}
  groundTex.needsUpdate=true;
  ctx.lots=lots.length;ctx.lotList=lots;
  // downtown geometry: towers get setbacks, everything gets a roof box now and then; water tanks on the old loft buildings
  const byD={};for(const l of lots)if(l.kind==='tower'||l.kind==='midrise')(byD[l.district.key]=byD[l.district.key]||[]).push(l);
  const dm=new THREE.Object3D();let total=0;
  for(const key in byD){const L=byD[key],parts=[];
    for(const l of L){if(l.kind==='tower'){const tiers=2+Math.floor(rnd()*2);let y=0,w=l.w,dd=l.dpt;for(let t=0;t<tiers;t++){const hh=l.h*(t===tiers-1?0.35:0.65/(tiers-1));parts.push([l.x,y,l.z,w,hh,dd]);y+=hh;w*=0.78;dd*=0.78;}}
      else parts.push([l.x,0,l.z,l.w,l.h,l.dpt]);
      if(rnd()<0.5)parts.push([l.x+(rnd()-0.5)*l.w*0.3,l.h,l.z+(rnd()-0.5)*l.dpt*0.3,Math.max(3,l.w*0.25),2+rnd()*3,Math.max(3,l.dpt*0.25)]);
      if(l.kind==='midrise'&&l.h<80&&/rivernorth|westloop|southloop|noblesquare/.test(key)&&rnd()<0.3)TANK.add(l.x+(rnd()-0.5)*l.w*0.4,l.h+3,l.z+(rnd()-0.5)*l.dpt*0.4,3,5,3,0);}
    const im=new THREE.InstancedMesh(boxG,bldMat(DIST[key]),parts.length),tint=new THREE.Color();
    parts.forEach((p,i)=>{dm.position.set(p[0],p[1],p[2]);dm.scale.set(p[3],p[4],p[5]);dm.updateMatrix();im.setMatrixAt(i,dm.matrix);
      const k=hash3(p[0],p[2],5);tint.setHSL(0.55+0.5*hash3(p[0],p[2],6),k<0.5?0.05:0.25,0.62+0.5*hash3(p[0],p[2],7));im.setColorAt(i,tint);});   // every building its own shade: glass, stone, brick
    im.castShadow=im.receiveShadow=true;im.userData.district=key;scene.add(im);total+=parts.length;}
  for(const c of [BODY,TRIM,ROOF,GARAGE,SHOP,AWN,TANK])c.build();
  ctx.details=Object.assign(ctx.details||{},{towers:total,houses,shops,alleys,garages:GARAGE.n,tanks:TANK.n});
});
// detail tiles fade in with distance (checked a few times a second)
{let t=0;const c=new THREE.Vector3();animHooks.push(now=>{if(now-t<300)return;t=now;for(const im of CHUNKS){if(!im.userData.far)continue;c.copy(im.geometry.boundingSphere.center);im.visible=camera.position.distanceTo(c)-im.geometry.boundingSphere.radius<im.userData.far;}});}
// windows and shopfronts come on at dusk
animHooks.push(()=>{const w=windowF(hourCur);for(const k in bldMats)bldMats[k].emissive.setRGB(w,w*0.92,w*0.8);shopM.emissive.setRGB(w*0.55,w*0.48,w*0.3);});
// ===== stages/04-landmarks.js =====
// ---------- landmarks: parametric massing for the buildings everyone knows ----------
await stage('landmarks');
const LANDMARKS=[];   // meshes with userData.info, for the click card
const glassM=new THREE.MeshLambertMaterial({color:0x4a6a8a,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(glassM,{K:0.25,id:'lmglass'});
const darkM=new THREE.MeshLambertMaterial({color:0x2c3038,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(darkM,{K:0.25,id:'lmdark'});
const lmMats=[glassM,darkM];
function lmMat(hex){if(!hex)return glassM;const m=new THREE.MeshLambertMaterial({color:parseInt(hex.slice(1),16),map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(m,{K:0.25,id:'lm'+hex});lmMats.push(m);return m;}
const chromeM=new THREE.MeshPhongMaterial({color:0xdde4ea,specular:0xffffff,shininess:120});
function reg(mesh,L){mesh.userData.info=L;mesh.castShadow=mesh.receiveShadow=true;LANDMARKS.push(mesh);scene.add(mesh);return mesh;}
function box(x,y,z,w,h,d,m){const b=new THREE.Mesh(boxG,m);b.position.set(x,y,z);b.scale.set(w,h,d);return b;}
function group(L,parts){const g=new THREE.Group();for(const p of parts){p.castShadow=p.receiveShadow=true;p.userData.info=L;g.add(p);}g.userData.info=L;LANDMARKS.push(g);scene.add(g);return g;}
const KINDS={
  bundle(L){const m=darkM,t=L.w/3,H=L.h,levels=[[0,0,1],[1,0,.92],[2,0,.62],[0,1,.62],[1,1,1],[2,1,.83],[0,2,.46],[1,2,.62],[2,2,.46]];   // nine tubes, the taller ones at the core
    return group(L,levels.map(([i,j,f])=>box(L.x-L.w/2+t*(i+.5),0,L.z-L.w/2+t*(j+.5),t-0.6,H*f,t-0.6,m)).concat([box(L.x-8,H,L.z-8,2,80,2,steelM),box(L.x+8,H,L.z+8,2,70,2,steelM)]));},
  taper(L){const g=new THREE.Mesh(new THREE.CylinderGeometry(1,1.6,1,4,1),darkM);g.geometry.translate(0,0.5,0);g.rotation.y=Math.PI/4;g.position.set(L.x,0,L.z);g.scale.set(L.w*0.72,L.h,L.d*0.72);
    const g2=group(L,[g,box(L.x-9,L.h,L.z,1.6,110,1.6,steelM),box(L.x+9,L.h,L.z,1.6,110,1.6,steelM)]);   // X-braces: four thin diagonals a side
    for(const s of [-1,1])for(let k=0;k<5;k++){const br=box(L.x+s*(L.w*0.36-k*L.w*0.03),k*L.h/5,L.z,1.2,L.h/5*1.06,L.d*0.7,steelM);br.rotation.z=s*0.22;br.userData.info=L;g2.add(br);}return g2;},
  setbacks(L){const H=L.h,steps=[[1,1,0.3],[0.8,0.85,0.35],[0.62,0.7,0.35]];let y=0;const parts=[];for(const [fw,fd,fh] of steps){parts.push(box(L.x+(1-fw)*L.w/2*0.5,y,L.z,L.w*fw,H*fh,L.d*fd,glassM));y+=H*fh;}
    if(L.spire)parts.push(box(L.x,H,L.z,2,L.spire,2,chromeM));return group(L,parts);},
  box(L){return reg(box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),L);},
  stacked(L){const parts=[];const stems=[[0,-L.d/3,0.62],[0,0,1],[0,L.d/3,0.8]];for(const [dx,dz,f] of stems){let y=0;for(let k=0;k<7;k++){const hh=L.h*f/7;const fr=new THREE.Mesh(new THREE.CylinderGeometry(0.5*(k%2?0.8:1.1),0.5*(k%2?1.1:0.8),1,4,1),glassM);fr.geometry.translate(0,0.5,0);fr.rotation.y=Math.PI/4;fr.position.set(L.x+dx,y,L.z+dz);fr.scale.set(L.w*0.85,hh,L.d/3*1.05);parts.push(fr);y+=hh;}}return group(L,parts);},
  crown(L){const parts=[box(L.x,0,L.z,L.w,L.h*0.7,L.d,glassM),box(L.x,L.h*0.7,L.z,L.w*0.8,L.h*0.16,L.d*0.8,glassM),box(L.x,L.h*0.86,L.z,L.w*0.55,L.h*0.14,L.d*0.55,glassM),box(L.x,L.h,L.z,1.5,L.h*0.2,1.5,chromeM)];return group(L,parts);},
  twin(L){const parts=[];for(const s of [-1,1]){const c=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,24,1),lmMat('#c9c2b4'));c.geometry.translate(0,0.5,0);c.position.set(L.x+s*L.gap/2,0,L.z);c.scale.set(L.w/2,L.h,L.w/2);parts.push(c);
      for(let k=0;k<12;k++){const r=new THREE.Mesh(new THREE.TorusGeometry(1,0.04,4,24),darkM);r.rotation.x=Math.PI/2;r.position.set(L.x+s*L.gap/2,L.h*(0.3+k*0.058),L.z);r.scale.setScalar(L.w/2*1.04);parts.push(r);}}return group(L,parts);},
  slab(L){return group(L,[box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),box(L.x,L.h,L.z,L.w*0.25,L.tower||20,L.d*0.4,lmMat(L.color))]);},
  deco(L){const m=lmMat(L.color),parts=[];const steps=[[1,1,0.5],[0.7,0.8,0.25],[0.45,0.55,0.18]];let y=0;for(const [fw,fd,fh] of steps){parts.push(box(L.x,y,L.z,L.w*fw,L.h*fh,L.d*fd,m));y+=L.h*fh;}parts.push(box(L.x,y,L.z,4,L.h*0.09,4,chromeM));return group(L,parts);},
  crowncyl(L){const c=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,20,1),new THREE.MeshLambertMaterial({color:0xe8f0ff,emissive:0x8fb4e0,emissiveIntensity:0.5,transparent:true,opacity:0.8}));c.geometry.translate(0,0.5,0);c.position.set(L.x,L.h*0.89,L.z);c.scale.set(L.w*0.36,L.h*0.11,L.w*0.36);
    return group(L,[box(L.x,0,L.z,L.w,L.h*0.89,L.d,lmMat(L.color)),c]);},
  gothic(L){const m=lmMat(L.color),parts=[box(L.x,0,L.z,L.w,L.h*0.72,L.d,m),box(L.x,L.h*0.72,L.z,L.w*0.7,L.h*0.28,L.d*0.7,m)];for(let k=0;k<8;k++){const a=k/8*Math.PI*2;parts.push(box(L.x+Math.cos(a)*L.w*0.34,L.h*0.72,L.z+Math.sin(a)*L.d*0.34,2.4,L.h*0.36,2.4,m));}return group(L,parts);},
  clocktower(L){const m=lmMat(L.color);return group(L,[box(L.x,0,L.z,L.w,L.h*0.6,L.d,m),box(L.x,L.h*0.6,L.z+L.d*0.2,L.w*0.5,L.h*0.3,L.w*0.5,m),box(L.x,L.h*0.9,L.z+L.d*0.2,L.w*0.3,L.h*0.1,L.w*0.3,m)]);},
  diamond(L){const top=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),glassM);top.geometry.translate(0,0.5,0);top.position.set(L.x,L.h*0.78,L.z);top.rotation.z=0;top.scale.set(L.w,L.h*0.22,L.d*0.5);
    const wedge=new THREE.Mesh(new THREE.CylinderGeometry(0,1,1,4,1),glassM);wedge.geometry.translate(0,0.5,0);wedge.rotation.y=Math.PI/4;wedge.position.set(L.x,L.h*0.78,L.z);wedge.scale.set(L.w*0.75,L.h*0.22,L.d*0.75);
    return group(L,[box(L.x,0,L.z,L.w,L.h*0.78,L.d,glassM),wedge]);},
  ypoint(L){const parts=[];for(let k=0;k<3;k++){const a=k/3*Math.PI*2+0.5;const wing=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,16,1,false,0,Math.PI*0.55),darkM);wing.geometry.translate(0,0.5,0);wing.rotation.y=a;wing.position.set(L.x,0,L.z);wing.scale.set(L.w*0.55,L.h,L.w*0.55);parts.push(wing);}
    const core=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,12,1),darkM);core.geometry.translate(0,0.5,0);core.position.set(L.x,0,L.z);core.scale.set(L.w*0.22,L.h,L.w*0.22);parts.push(core);return group(L,parts);},
  watertower(L){const m=lmMat(L.color);const parts=[box(L.x,0,L.z,L.w*2.2,L.h*0.3,L.w*2.2,m),box(L.x,L.h*0.3,L.z,L.w,L.h*0.6,L.w,m)];const cap=new THREE.Mesh(new THREE.ConeGeometry(0.7,1,4),m);cap.geometry.translate(0,0.5,0);cap.position.set(L.x,L.h*0.9,L.z);cap.scale.set(L.w,L.h*0.1,L.w);parts.push(cap);return group(L,parts);},
  bean(L){   // Cloud Gate: a polished bean that mirrors the park and the skyline, raised on its two ends over the omphalos arch
    const g=new THREE.SphereGeometry(1,64,36),v=g.attributes.position;
    for(let k=0;k<v.count;k++){let x=v.getX(k),y=v.getY(k),z=v.getZ(k);
      if(y<0)y*=0.55;                                            // a flatter underside
      x*=1+0.12*Math.max(0,y);                                  // the top swells a little past the ends
      const arch=Math.max(0,1-Math.abs(x)/0.55);if(y<0)y+=arch*arch*0.62*(-y+0.2)*1.2;   // the arch under the middle
      v.setXYZ(k,x,y,z);}
    g.computeVertexNormals();
    const rt=new THREE.WebGLCubeRenderTarget(256,{format:THREE.RGBFormat,generateMipmaps:true,minFilter:THREE.LinearMipmapLinearFilter});
    const cube=new THREE.CubeCamera(1,4000,rt);cube.position.set(L.x,6,L.z);scene.add(cube);
    const beanM=new THREE.MeshPhongMaterial({color:0xdfe4ea,specular:0xffffff,shininess:220,envMap:rt.texture,combine:THREE.MixOperation,reflectivity:0.9});
    const b=new THREE.Mesh(g,beanM);b.position.set(L.x,L.h*0.5,L.z);b.scale.set(L.w/2,L.h*0.5,L.d/2);
    const plaza=box(L.x,0,L.z,L.w*3,0.3,L.d*4,new THREE.MeshLambertMaterial({color:0x9e988c}));
    const grp=group(L,[plaza,b]);b.castShadow=true;
    let lastR=-1e9;animHooks.push(now=>{if(now-lastR<2500||camera.position.distanceTo(b.position)>900)return;lastR=now;b.visible=false;cube.update(renderer,scene);b.visible=true;});   // the reflection refreshes every few seconds while you are near
    return grp;},
  fountain(L){const parts=[];for(let k=0;k<3;k++){const r=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,28,1),stoneM);r.geometry.translate(0,0.5,0);r.position.set(L.x,k*2.2,L.z);r.scale.set(L.w/2*(1-k*0.3),2.2,L.w/2*(1-k*0.3));parts.push(r);}
    const jet=new THREE.Mesh(new THREE.CylinderGeometry(0.6,2.5,1,10,1),waterM);jet.geometry.translate(0,0.5,0);jet.position.set(L.x,6,L.z);jet.scale.set(1,30,1);parts.push(jet);const g=group(L,parts);animHooks.push(now=>{jet.scale.y=18+14*Math.max(0,Math.sin(now*0.0007));});return g;},
  lowrise(L){return reg(box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),L);},
  stadium(L){const parts=[];const ring=new THREE.Mesh(new THREE.CylinderGeometry(1,1.1,1,32,1,true),stoneM);ring.geometry.translate(0,0.5,0);ring.position.set(L.x,0,L.z);ring.scale.set(L.w/2,L.h,L.d/2);ring.material=stoneM.clone();ring.material.side=THREE.DoubleSide;parts.push(ring);
    for(const s of [-1,1])for(let k=0;k<12;k++){parts.push(box(L.x+s*(L.w/2+8),0,L.z-L.d*0.4+k*L.d*0.8/11,3,L.h*0.55,3,stoneM));}return group(L,parts);},
  wavy(L){const parts=[box(L.x,0,L.z,L.w,L.h,L.d,glassM)],slabM=lmMat('#e8ecee');   // Aqua: floor plates whose balconies swell and recede
    for(let k=0,y=12;y<L.h;k++,y+=7.5){const t=y*0.045;const e=[2+2*Math.sin(t+L.x*0.01),2+2*Math.sin(t*1.3+1.7),2+2*Math.sin(t*0.8+3.1),2+2*Math.sin(t*1.1+4.6)];
      parts.push(box(L.x+(e[1]-e[3])/2,y,L.z+(e[2]-e[0])/2,L.w+e[1]+e[3],0.5,L.d+e[0]+e[2],slabM));}return group(L,parts);},
  pavilion(L){const parts=[box(L.x,0,L.z,26,14,30,stoneM)];   // Pritzker: the stage, steel ribbons over it, and the trellis over the lawn to the east
    for(let k=0;k<9;k++){const r=new THREE.Mesh(new THREE.TorusGeometry(10+k*1.6,0.35,3,18,Math.PI*(0.7+0.05*k)),chromeM);r.position.set(L.x+2-k*0.8,18+k*1.8,L.z+(k-4)*3.2);r.rotation.set(0.3*(k%3-1),Math.PI/2+0.25*(k-4),0.6+0.1*k);r.scale.set(1,1.4,3);parts.push(r);}
    for(let k=1;k<=6;k++){const arc=new THREE.Mesh(new THREE.TorusGeometry(46,0.4,3,24,Math.PI),steelM);arc.position.set(L.x+10+k*16,0,L.z);arc.rotation.y=Math.PI/2;arc.scale.set(1,0.5,1);parts.push(arc);}
    for(let k=-2;k<=2;k++){const rib=box(L.x+56,22.5-Math.abs(k)*2,L.z+k*18,96,0.6,0.6,steelM);parts.push(rib);}
    return group(L,parts);},
  crownfountain(L){const faceM=new THREE.MeshLambertMaterial({color:0xdfe8ee,emissive:0x8fb0c8,emissiveIntensity:0.35,transparent:true,opacity:0.9});const parts=[];
    for(const s of [-1,1])parts.push(box(L.x,0,L.z+s*L.gap/2,15,L.h,L.w,faceM));
    const pool=box(L.x,0,L.z,22,0.3,L.gap-L.w,new THREE.MeshPhongMaterial({color:0x1c2a38,specular:0xb0c8e0,shininess:120}));parts.push(pool);
    const g=group(L,parts);animHooks.push(now=>{const k=0.25+0.2*Math.sin(now*0.0004);faceM.emissiveIntensity=k+0.4*windowF(hourCur);});return g;},
  dome(L){const m=lmMat(L.color),parts=[];const hall=new THREE.Mesh(new THREE.CylinderGeometry(L.w/2,L.w/2,L.h*0.6,12,1),m);hall.geometry.translate(0,L.h*0.3,0);hall.position.set(L.x,0,L.z);parts.push(hall);
    const dm=new THREE.Mesh(new THREE.SphereGeometry(L.w*0.34,20,10,0,Math.PI*2,0,Math.PI/2),new THREE.MeshLambertMaterial({color:0xb87a4a}));dm.position.set(L.x,L.h*0.6,L.z);parts.push(dm);return group(L,parts);},
  flatiron(L){   // a wedge: the sharp end points up Milwaukee Avenue to the six-way corner
    const m=lmMat(L.color),sh=new THREE.Shape();sh.moveTo(-L.w/2,-L.d/2);sh.lineTo(L.w/2,-L.d/2);sh.lineTo(-L.w/2,L.d/2);sh.closePath();
    const g=new THREE.ExtrudeGeometry(sh,{depth:L.h,bevelEnabled:false});g.rotateX(-Math.PI/2);const body=new THREE.Mesh(g,m);body.position.set(L.x,0,L.z);body.rotation.y=-0.55;
    const cap=new THREE.Mesh(new THREE.ExtrudeGeometry(sh,{depth:0.9,bevelEnabled:false}).rotateX(-Math.PI/2),lmMat('#6a4030'));cap.position.set(L.x,L.h,L.z);cap.rotation.y=-0.55;cap.scale.set(1.04,1,1.04);
    return group(L,[body,cap]);},
  fieldhouse(L){   // a Park District fieldhouse: brick hall with a hipped tile roof and a lower gym wing
    const m=lmMat(L.color),tile=new THREE.MeshLambertMaterial({color:0x8a5a3a});const hip=new THREE.Mesh(new THREE.ConeGeometry(0.72,1,4,1),tile);hip.geometry.translate(0,0.5,0);hip.rotation.y=Math.PI/4;
    hip.position.set(L.x,L.h,L.z);hip.scale.set(L.w,L.h*0.45,L.d);
    return group(L,[box(L.x,0,L.z,L.w,L.h,L.d,m),hip,box(L.x-L.w*0.62,0,L.z,L.w*0.45,L.h*0.7,L.d*0.8,m),box(L.x,0,L.z+L.d/2+1.5,L.w*0.25,3,3,stoneM)]);},
  pool(L){const deck=box(L.x,0,L.z,L.w+8,0.3,L.d+8,new THREE.MeshLambertMaterial({color:0xd8d2c4})),w=box(L.x,0.1,L.z,L.w,0.35,L.d,new THREE.MeshPhongMaterial({color:0x3aa0c8,specular:0xffffff,shininess:80}));
    const fence=[];for(const s of [-1,1]){fence.push(box(L.x,0,L.z+s*(L.d/2+4),L.w+8,2,0.15,steelM),box(L.x+s*(L.w/2+4),0,L.z,0.15,2,L.d+8,steelM));}return group(L,[deck,w,...fence]);},
  church(L){   // a Polish cathedral church: long nave, gabled front, twin towers with lanterns
    const m=lmMat(L.color),roof=new THREE.MeshLambertMaterial({color:0x5a6a62}),parts=[box(L.x,0,L.z,L.w,L.h*0.35,L.d,m)];
    const nave=new THREE.Mesh(prismG,roof);nave.position.set(L.x,L.h*0.35,L.z);nave.scale.set(L.w,L.h*0.16,L.d);parts.push(nave);
    for(const s of [-1,1]){const tx=L.x+s*(L.w/2-4),tz=L.z-L.d/2+4;parts.push(box(tx,0,tz,8.5,L.h*0.78,8.5,m),box(tx,L.h*0.78,tz,6,L.h*0.1,6,m));
      const cap=new THREE.Mesh(new THREE.ConeGeometry(3.6,L.h*0.14,8),roof);cap.position.set(tx,L.h*0.88+L.h*0.07,tz);parts.push(cap);
      const cross=box(tx,L.h*1.02,tz,0.4,3,0.4,chromeM);parts.push(cross);}
    return group(L,parts);},
  domechurch(L){const m=lmMat(L.color),copper=new THREE.MeshLambertMaterial({color:0x5f9a84}),parts=[box(L.x,0,L.z,L.w,L.h*0.42,L.d,m)];
    const drum=new THREE.Mesh(new THREE.CylinderGeometry(L.w*0.28,L.w*0.28,L.h*0.16,20),m);drum.position.set(L.x,L.h*0.42+L.h*0.08,L.z+L.d*0.12);parts.push(drum);
    const dome=new THREE.Mesh(new THREE.SphereGeometry(L.w*0.3,24,12,0,Math.PI*2,0,Math.PI/2),copper);dome.position.set(L.x,L.h*0.58,L.z+L.d*0.12);dome.scale.y=1.25;parts.push(dome);
    const lantern=new THREE.Mesh(new THREE.CylinderGeometry(1.4,1.6,L.h*0.1,8),copper);lantern.position.set(L.x,L.h*0.58+L.w*0.37+L.h*0.05,L.z+L.d*0.12);parts.push(lantern);
    for(const s of [-1,1])parts.push(box(L.x+s*(L.w/2-3),0,L.z-L.d/2+3,6,L.h*0.55,6,m));return group(L,parts);},
  pier(L){const parts=[];const wheel=new THREE.Group();const rim=new THREE.Mesh(new THREE.TorusGeometry(PIER.wheelR,1.2,6,48),steelM);wheel.add(rim);
    for(let k=0;k<12;k++){const a=k/12*Math.PI*2;const sp=box(0,0,0,1,PIER.wheelR*2,1,steelM);sp.position.set(0,0,0);sp.rotation.z=a;sp.geometry=new THREE.BoxGeometry(1,1,1);sp.scale.set(0.8,PIER.wheelR*2,0.8);wheel.add(sp);
      const car=new THREE.Mesh(new THREE.SphereGeometry(2.4,8,6),new THREE.MeshLambertMaterial({color:0xe8f0ff}));car.position.set(Math.cos(a)*PIER.wheelR,Math.sin(a)*PIER.wheelR,0);wheel.add(car);}
    wheel.position.set(PIER.wheelX,PIER.wheelR+6,PIER.z);wheel.rotation.y=Math.PI/2;wheel.userData.info=L;parts.push(wheel);
    for(const s of [-1,1]){const leg=box(PIER.wheelX,4,PIER.z+s*10,3,PIER.wheelR+2,3,steelM);leg.rotation.x=s*0.16;parts.push(leg);}
    const g=group(L,parts);animHooks.push(now=>{wheel.rotation.x=now*0.00012;});return g;},
};
section('landmarks',()=>{for(const L of C.landmarks){[L.x,L.z]=P(L.at);const f=KINDS[L.kind];if(!f){report('landmark '+L.name,new Error('unknown kind '+L.kind));continue;}try{f(L);}catch(e){report('landmark '+L.name,e);}}
  // warning beacons on the tallest roofs
  const beacons=[];for(const L of C.landmarks)if(L.h>250){const b=new THREE.Mesh(new THREE.SphereGeometry(2,8,6),new THREE.MeshBasicMaterial({color:0xff2020}));b.position.set(L.x,L.h+(L.kind==='bundle'?80:L.kind==='taper'?110:L.spire||8),L.z);scene.add(b);beacons.push(b);}
  animHooks.push(now=>{const on=(now%1600)<800;for(const b of beacons)b.visible=on||hourCur<6||hourCur>18;});
  ctx.details.landmarks=LANDMARKS.length;});
animHooks.push(()=>{const w=windowF(hourCur);for(const m of lmMats)m.emissive.setRGB(w,w*0.92,w*0.8);});
// ===== stages/05-el.js =====
// ---------- the L: the Loop's elevated tracks on their columns, and the trains that circle them ----------
await stage('el');
section('el',()=>{
  const H=EL.height,W=EL.east-EL.west,D=EL.south-EL.north,cx=(EL.east+EL.west)/2,cz=(EL.north+EL.south)/2;
  const rail=(x,z,w,d)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(w,1.2,d),steelM);b.position.set(x,H,z);b.castShadow=true;scene.add(b);};
  rail(cx,EL.north,W+12,12);rail(cx,EL.south,W+12,12);rail(EL.west,cz,12,D);rail(EL.east,cz,12,D);
  // columns every 15 m, in the street
  const cols=[];for(let x=EL.west;x<=EL.east;x+=15){cols.push([x,EL.north]);cols.push([x,EL.south]);}for(let z=EL.north+15;z<EL.south;z+=15){cols.push([EL.west,z]);cols.push([EL.east,z]);}
  const cm=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.5,0.6,1,6),steelM,cols.length*2),d=new THREE.Object3D();
  cols.forEach(([x,z],i)=>{for(const s of [-1,1]){const on=Math.abs(z-EL.north)<1||Math.abs(z-EL.south)<1;d.position.set(x+(on?0:s*5),H/2,z+(on?s*5:0));d.scale.set(1,H,1);d.updateMatrix();cm.setMatrixAt(i*2+(s>0?1:0),d.matrix);}});
  cm.castShadow=true;scene.add(cm);
  // trains: EL.trains of EL.cars cars, half each way, on the perimeter
  const P=2*(W+D),carL=15,carG=1.2,N=EL.trains*EL.cars;
  const carM=new THREE.MeshLambertMaterial({color:0xd8dde3,emissive:0x000000}),tm=new THREE.InstancedMesh(new THREE.BoxGeometry(carL,3.4,3.2),carM,N);tm.castShadow=true;tm.userData.life=true;scene.add(tm);
  const trains=[];for(let t=0;t<EL.trains;t++)trains.push({s:t*P/EL.trains,dir:t%2?1:-1,v:11+t*0.7,stop:0});
  const at=(s,side)=>{s=((s%P)+P)%P;const o=side*4;   // a point on the rectangle, offset to the inner or outer track
    if(s<W)return [EL.west+s,EL.north+o,0];s-=W;if(s<D)return [EL.east-o,EL.north+s,Math.PI/2];s-=D;if(s<W)return [EL.east-s,EL.south-o,0];s-=W;return [EL.west+o,EL.south-s,Math.PI/2];};
  let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;let i=0;
    for(const tr of trains){if(tr.stop>0)tr.stop-=dt;else{tr.s+=tr.dir*tr.v*dt;if(Math.floor(tr.s/ (P/8))!==Math.floor((tr.s-tr.dir*tr.v*dt)/(P/8)))tr.stop=3+Math.random()*2;}   // a short stop every eighth of the loop
      for(let c=0;c<EL.cars;c++){const [x,z,a]=at(tr.s-tr.dir*c*(carL+carG),tr.dir);d.position.set(x,H+2.4,z);d.rotation.set(0,a,0);d.scale.set(1,1,1);d.updateMatrix();tm.setMatrixAt(i++,d.matrix);}}
    tm.instanceMatrix.needsUpdate=true;const w=windowF(hourCur);carM.emissive.setRGB(w*0.9,w*0.85,w*0.6);});
  ctx.details=Object.assign(ctx.details||{},{trains:EL.trains});
});
// the Blue Line: up out of the Milwaukee Avenue subway and onto its steel viaduct past Damen, with the station platforms and canopies
section('blue-line',()=>{const BL=EL.blue;if(!BL)return;
  const r=polyLen0({pts:BL.pts}),H=BL.height,blueM=new THREE.MeshLambertMaterial({color:0x2a5aa8});
  const d=new THREE.Object3D(),cols=[];
  for(let i=0;i+1<r.pts.length;i++){const [ax,az]=r.pts[i],[bx,bz]=r.pts[i+1],L=Math.hypot(bx-ax,bz-az),ang=Math.atan2(bz-az,bx-ax);
    const deck=new THREE.Mesh(new THREE.BoxGeometry(L,1.4,10),steelM);deck.position.set((ax+bx)/2,H,(az+bz)/2);deck.rotation.y=-ang;deck.castShadow=true;scene.add(deck);
    for(let s=0;s<L;s+=16)for(const sd of [-1,1]){const x=ax+(bx-ax)*s/L,z=az+(bz-az)*s/L;cols.push([x-Math.sin(ang)*sd*4,z+Math.cos(ang)*sd*4]);}}
  {const cm=new THREE.InstancedMesh(new THREE.BoxGeometry(0.7,1,0.7).translate(0,0.5,0),steelM,cols.length);cols.forEach(([x,z],i)=>{d.position.set(x,0,z);d.rotation.set(0,0,0);d.scale.set(1,H-0.7,1);d.updateMatrix();cm.setMatrixAt(i,d.matrix);});cm.castShadow=true;scene.add(cm);}
  // the portal where the tracks come up from the subway
  {const [x,z]=r.pts[0],[x2,z2]=r.pts[1],ang=Math.atan2(z2-z,x2-x),ramp=new THREE.Mesh(new THREE.BoxGeometry(60,H,11),new THREE.MeshLambertMaterial({color:0x8a847a}));ramp.position.set(x+Math.cos(ang)*30,H/2-0.7,z+Math.sin(ang)*30);ramp.rotation.set(0,-ang,Math.atan2(H,60));scene.add(ramp);}
  // stations: side platforms with canopies, a stair tower down to the street
  for(const [sx,sz,name] of BL.stations){const s=nearestS(r,sx,sz),[x,z,ang]=polyAt0(r,s);const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=-ang;
    if(name==='Division'){const head=new THREE.Mesh(new THREE.BoxGeometry(8,3.2,6),blueM);head.position.set(0,1.6,12);g.add(head);}   // the subway entrance
    else{for(const sd of [-1,1]){const plat=new THREE.Mesh(new THREE.BoxGeometry(130,0.9,4),stoneM);plat.position.set(0,H+0.2,sd*7);const can=new THREE.Mesh(new THREE.BoxGeometry(90,0.3,4.6),blueM);can.position.set(0,H+3.8,sd*7.2);
        const post1=new THREE.Mesh(new THREE.BoxGeometry(0.3,3.4,0.3),steelM);post1.position.set(-40,H+2.1,sd*8.8);const post2=post1.clone();post2.position.x=40;g.add(plat,can,post1,post2);}
      const stair=new THREE.Mesh(new THREE.BoxGeometry(10,H+4,7),blueM);stair.position.set(-58,(H+4)/2,13);const sign=new THREE.Mesh(new THREE.BoxGeometry(3,1,0.2),new THREE.MeshLambertMaterial({color:0xffffff,emissive:0x333333}));sign.position.set(-58,H+5,16.6);g.add(stair,sign);}
    g.userData.info={name:name+' (Blue Line)',info:name==='Damen'?'1558 N Milwaukee Ave · 1895 · an elevated station on the Blue Line to O’Hare, rebuilt in 2019, right at the six corners.':'1200 N Milwaukee Ave · the subway station at Division, Milwaukee and Ashland.'};
    g.traverse(o=>{o.userData.info=g.userData.info;});LANDMARKS.push(g);scene.add(g);}
  // trains: silver cars with a blue stripe, one each way, slowing through the station
  const carL=15,N=BL.trains*BL.cars,carM=new THREE.MeshLambertMaterial({color:0xd0d6dc,emissive:0x000000}),tm=new THREE.InstancedMesh(new THREE.BoxGeometry(carL,3.4,3.2),carM,N);tm.castShadow=true;tm.userData.life=true;tm.frustumCulled=false;scene.add(tm);
  const trains=[];for(let t=0;t<BL.trains;t++)trains.push({s:t*r.len/BL.trains,dir:t%2?1:-1,v:13});
  const stS=BL.stations.map(([sx,sz])=>nearestS(r,sx,sz));let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;let i=0;
    for(const tr of trains){const near=stS.some(s=>Math.abs(s-tr.s)<120);tr.s+=tr.dir*(near?5:tr.v)*dt;if(tr.s>r.len-10){tr.dir=-1;}if(tr.s<10+carL*BL.cars){tr.dir=1;}
      for(let c=0;c<BL.cars;c++){const [x,z,a]=polyAt0(r,tr.s-tr.dir*c*(carL+1.2)),sd=tr.dir;d.position.set(x-Math.sin(a)*sd*2.3,H+2.5,z+Math.cos(a)*sd*2.3);d.rotation.set(0,-a,0);d.scale.set(1,1,1);d.updateMatrix();tm.setMatrixAt(i++,d.matrix);}}
    tm.instanceMatrix.needsUpdate=true;const w=windowF(hourCur);carM.emissive.setRGB(w*0.9,w*0.85,w*0.6);});
  LANDMARKS.push(...TRAIL_INFO);
  ctx.details=Object.assign(ctx.details||{},{blueLineStations:BL.stations.length});
});
function polyLen0(r){let L=0;r.cum=[0];for(let i=0;i+1<r.pts.length;i++){L+=Math.hypot(r.pts[i+1][0]-r.pts[i][0],r.pts[i+1][1]-r.pts[i][1]);r.cum.push(L);}r.len=L;return r;}
function polyAt0(r,s){s=Math.max(0,Math.min(r.len,s));let i=0;while(i<r.cum.length-2&&r.cum[i+1]<s)i++;const a=r.pts[i],b=r.pts[i+1],u=(s-r.cum[i])/((r.cum[i+1]-r.cum[i])||1);return [a[0]+(b[0]-a[0])*u,a[1]+(b[1]-a[1])*u,Math.atan2(b[1]-a[1],b[0]-a[0])];}
function nearestS(r,x,z){let best=0,bd=1e9;for(let s=0;s<=r.len;s+=4){const [px,pz]=polyAt0(r,s),dd=Math.hypot(px-x,pz-z);if(dd<bd){bd=dd;best=s;}}return best;}
// ===== stages/05a-streetscape.js =====
// ---------- streetscape at the focus corners (North & Ashland, the six corners at North/Damen/Milwaukee):
// shopfronts along the diagonal, street lights, traffic signals, CTA bus shelters, parked cars, people on the sidewalks ----------
await stage('streetscape');
section('streetscape',()=>{
  if(!FOCUS.length)return;
  const inFocus=(x,z,pad)=>FOCUS.some(f=>Math.hypot(f.x-x,f.z-z)<f.r+(pad||0));
  const near=STREETS.filter(s=>(s.major||s.axis==='d')&&FOCUS.some(f=>segDist(f.x,f.z,s.a[0],s.a[1],s.b[0],s.b[1])<f.r));
  const R=mkRng(1600);
  // intersections between those streets, inside a focus
  const xings=[];for(let i=0;i<near.length;i++)for(let j=i+1;j<near.length;j++){const h=segHit(near[i].a,near[i].b,near[j].a,near[j].b);if(!h||!inFocus(h.x,h.z,0))continue;if(xings.some(q=>Math.hypot(q.x-h.x,q.z-h.z)<20))continue;xings.push({x:h.x,z:h.z,s:[near[i],near[j]]});}
  const nearXing=(x,z,r)=>xings.some(q=>Math.hypot(q.x-x,q.z-z)<r);
  // walk a street inside the focus, calling fn(x,z,dirx,dirz) every `step` metres
  const along=(s,step,fn)=>{const L=Math.hypot(s.b[0]-s.a[0],s.b[1]-s.a[1]),dx=(s.b[0]-s.a[0])/L,dz=(s.b[1]-s.a[1])/L;for(let u=step/2;u<L;u+=step){const x=s.a[0]+dx*u,z=s.a[1]+dz*u;if(inFocus(x,z,0))fn(x,z,dx,dz);}};
  // 1. shopfronts along the diagonals (Milwaukee), which the block grid leaves ragged
  const occupied=(x,z,r)=>lots.some(l=>Math.abs(l.x-x)<l.w/2+r&&Math.abs(l.z-z)<l.dpt/2+r);
  const BODY_D=[];let dshops=0;
  for(const s of near){if(s.axis!=='d')continue;along(s,11,(x,z,dx,dz)=>{if(nearXing(x,z,22))return;
    for(const sd of [-1,1]){if(R()<0.12)continue;const depth=16+R()*6,off=s.w/2+3.5+depth/2,bx=x-dz*sd*off,bz=z+dx*sd*off,h=10+R()*8;
      if(!inMap(bx,bz,20)||inWater(bx,bz)||parkAt(bx,bz)||occupied(bx,bz,2)||nearLandmark(bx,bz,4))continue;
      const ang=Math.atan2(dz,dx),col=BRICK[Math.floor(R()*BRICK.length)];
      BODY_D.push([bx,bz,11.2,h,depth,ang,col]);lots.push({x:bx,z:bz,w:9,dpt:9,h,ry:ang,kind:'shop',district:districtAt(bx,bz),fixed:false});dshops++;}});}
  // rotated boxes need their own instances: body, cornice, shop glass, awning
  {const n=BODY_D.length,body=new THREE.InstancedMesh(boxG,brickM,n),trim=new THREE.InstancedMesh(boxG,trimM,n),glass=new THREE.InstancedMesh(boxG,shopM,n),awn=new THREE.InstancedMesh(boxG,awningM,n),d=new THREE.Object3D();
   BODY_D.forEach(([x,z,w,h,depth,ang,col],i)=>{const face=[-Math.sin(ang),Math.cos(ang)],fx=(x0,z0)=>[x0,z0];
     const q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),-ang),set=(im,px,py,pz,sx,sy,sz,c)=>{d.position.set(px,py,pz);d.quaternion.copy(q);d.scale.set(sx,sy,sz);d.updateMatrix();im.setMatrixAt(i,d.matrix);if(c)im.setColorAt(i,c);};
     // which side faces the street: the one nearer the diagonal's centre line
     const s0=near.find(s=>s.axis==='d'&&segDist(x,z,s.a[0],s.a[1],s.b[0],s.b[1])<depth/2+s.w/2+8)||near[0],toward=Math.sign((s0.a[0]-x)*face[0]+(s0.a[1]-z)*face[1])||1;
     set(body,x,0,z,w,h,depth,col);set(trim,x,h,z,w+0.6,0.9,depth+0.6,new THREE.Color(col).multiplyScalar(0.7));
     const gx=x+face[0]*toward*(depth/2+0.2),gz=z+face[1]*toward*(depth/2+0.2);set(glass,gx,0.3,gz,w-0.8,3.8,0.5);
     set(awn,x+face[0]*toward*(depth/2+1),4.2,z+face[1]*toward*(depth/2+1),w-1,0.35,2,AWNING[i%AWNING.length]);});
   for(const im of [body,trim,glass,awn]){im.castShadow=im!==glass&&im!==awn;im.receiveShadow=true;scene.add(im);}}
  // 2. street lights: a pole every 30 m on both sidewalks, the head lit at dusk
  const lights=[];for(const s of near)along(s,30,(x,z,dx,dz)=>{if(nearXing(x,z,12))return;for(const sd of [-1,1])lights.push([x-dz*sd*(s.w/2+1.2),z+dx*sd*(s.w/2+1.2),Math.atan2(dz,dx)+(sd>0?Math.PI/2:-Math.PI/2)]);});
  const poleM=new THREE.MeshLambertMaterial({color:0x3a3d40}),headM=new THREE.MeshLambertMaterial({color:0xe8e4d8,emissive:0x000000});
  {const n=lights.length,pole=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.12,0.16,1,6).translate(0,0.5,0),poleM,n),arm=new THREE.InstancedMesh(boxG,poleM,n),head=new THREE.InstancedMesh(boxG,headM,n),d=new THREE.Object3D();
   lights.forEach(([x,z,a],i)=>{d.rotation.set(0,-a,0);d.position.set(x,0,z);d.scale.set(1,9,1);d.updateMatrix();pole.setMatrixAt(i,d.matrix);
     const ex=Math.cos(a)*1.6,ez=Math.sin(a)*1.6;d.position.set(x+ex,8.8,z+ez);d.scale.set(3.2,0.15,0.15);d.updateMatrix();arm.setMatrixAt(i,d.matrix);d.position.set(x+ex*2,8.4,z+ez*2);d.scale.set(1,0.35,0.5);d.updateMatrix();head.setMatrixAt(i,d.matrix);});
   pole.castShadow=true;scene.add(pole,arm,head);animHooks.push(()=>{const w=nightF(hourCur);headM.emissive.setRGB(w,w*0.85,w*0.55);});}
  // 3. traffic signals: a mast arm on two corners of every intersection, heads cycling between the two streets
  const sigHeads=[];const sigM=new THREE.MeshLambertMaterial({color:0x2a2c2e});
  for(const q of xings){const [a,b]=q.s,da=[a.b[0]-a.a[0],a.b[1]-a.a[1]],la=Math.hypot(...da);const ux=da[0]/la,uz=da[1]/la;
    for(const sd of [-1,1]){const cx=q.x+ux*sd*(b.w/2+4)-uz*sd*(a.w/2+2),cz=q.z+uz*sd*(b.w/2+4)+ux*sd*(a.w/2+2);
      const pole=new THREE.Mesh(new THREE.CylinderGeometry(0.2,0.25,7,8),sigM);pole.position.set(cx,3.5,cz);scene.add(pole);
      const armLen=a.w*0.55,mast=new THREE.Mesh(new THREE.BoxGeometry(armLen,0.25,0.25),sigM);mast.position.set(cx+uz*sd*armLen/2,6.8,cz-ux*sd*armLen/2);mast.rotation.y=-Math.atan2(-ux,uz);scene.add(mast);
      for(const k of [0.5,1]){const hx=cx+uz*sd*armLen*k,hz=cz-ux*sd*armLen*k,head=new THREE.Group();head.position.set(hx,5.6,hz);
        const housing=new THREE.Mesh(new THREE.BoxGeometry(0.5,1.5,0.5),sigM);head.add(housing);const lamps=[0xff2a1a,0xffb020,0x30e060].map((c,li)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(0.16,6,4),new THREE.MeshBasicMaterial({color:0x202020}));m.position.set(0,0.45-li*0.45,0.28);m.userData.on=c;head.add(m);return m;});
        head.rotation.y=-Math.atan2(ux*sd,uz*sd);scene.add(head);sigHeads.push({lamps,phase:(sd>0?0:0)+(xings.indexOf(q)%2)*0});}}}
  // one cycle: the diagonal/first street gets 18 s green, 3 s amber, then the cross street
  animHooks.push(now=>{const t=(now/1000)%42;const state=t<18?2:t<21?1:0;for(const h of sigHeads)h.lamps.forEach((m,li)=>m.material.color.setHex(li===state?m.userData.on:0x202020));});
  // 4. CTA bus shelters near the corners
  const glassM=new THREE.MeshLambertMaterial({color:0xa8c8d8,transparent:true,opacity:0.45}),frameM=new THREE.MeshLambertMaterial({color:0x2a3a4a});let shelters=0;
  for(const q of xings){for(const s of q.s){if(s.axis==='d'&&R()<0.5)continue;const L=Math.hypot(s.b[0]-s.a[0],s.b[1]-s.a[1]),dx=(s.b[0]-s.a[0])/L,dz=(s.b[1]-s.a[1])/L,sd=R()<0.5?-1:1,off=34;
    const x=q.x+dx*off*sd-dz*sd*(s.w/2+2.4),z=q.z+dz*off*sd+dx*sd*(s.w/2+2.4);if(!inMap(x,z,10)||inWater(x,z))continue;const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=-Math.atan2(dz,dx);
    const back=new THREE.Mesh(new THREE.BoxGeometry(4.2,2.3,0.08),glassM);back.position.set(0,1.35,-sd*0.8);const roof=new THREE.Mesh(new THREE.BoxGeometry(4.6,0.18,1.9),frameM);roof.position.y=2.6;
    const side=new THREE.Mesh(new THREE.BoxGeometry(0.08,2.3,1.5),glassM);side.position.set(2.1,1.35,0);const bench=new THREE.Mesh(new THREE.BoxGeometry(3,0.1,0.45),frameM);bench.position.set(0,0.5,-sd*0.5);
    const sign=new THREE.Mesh(new THREE.BoxGeometry(0.08,3.2,0.08),frameM);sign.position.set(-2.6,1.6,sd*0.6);g.add(back,roof,side,bench,sign);scene.add(g);shelters++;}}
  // 5. parked cars along both curbs, clear of the corners and the bus stops
  const parked=[];for(const s of near){if(s.w<20)continue;along(s,6.8,(x,z,dx,dz)=>{if(nearXing(x,z,28))return;for(const sd of [-1,1]){if(R()<0.3)continue;const px=x-dz*sd*(s.w/2-1.4),pz=z+dx*sd*(s.w/2-1.4);if(inWater(px,pz)||onBridge(px,pz))continue;parked.push([px,pz,Math.atan2(dz,dx)]);}});}
  {const n=parked.length,body=new THREE.InstancedMesh(new THREE.BoxGeometry(4.5,1.0,1.9).translate(0,0.75,0),new THREE.MeshLambertMaterial({color:0xffffff}),n),cab=new THREE.InstancedMesh(new THREE.BoxGeometry(2.4,0.7,1.7).translate(-0.2,1.6,0),new THREE.MeshLambertMaterial({color:0x2a3440}),n),d=new THREE.Object3D(),c=new THREE.Color();
   parked.forEach(([x,z,a],i)=>{d.position.set(x,0,z);d.rotation.set(0,-a,0);d.scale.set(1,1,1);d.updateMatrix();body.setMatrixAt(i,d.matrix);cab.setMatrixAt(i,d.matrix);body.setColorAt(i,c.setHSL(R(),R()<0.4?0.05:0.5,0.2+R()*0.55));});
   body.castShadow=true;scene.add(body,cab);}
  // 6. people walking the sidewalks
  const walkers=[];for(const s of near){const L=Math.hypot(s.b[0]-s.a[0],s.b[1]-s.a[1]);along(s,9,(x,z,dx,dz)=>{if(R()<0.45)return;const sd=R()<0.5?-1:1;walkers.push({s,L,u:0,x0:x,z0:z,dx,dz,sd,off:s.w/2+2+R()*1.8,v:(R()<0.5?-1:1)*(1.1+R()*0.5),t:R()*100,col:R()});});}
  {const n=walkers.length,body=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.22,0.26,1.35,6).translate(0,0.68,0),new THREE.MeshLambertMaterial({color:0xffffff}),n),head=new THREE.InstancedMesh(new THREE.SphereGeometry(0.13,6,5).translate(0,1.52,0),new THREE.MeshLambertMaterial({color:0xc8a080}),n),d=new THREE.Object3D(),c=new THREE.Color();
   walkers.forEach((w,i)=>body.setColorAt(i,c.setHSL(w.col,0.4,0.25+0.35*((w.col*7)%1))));body.userData.life=true;body.frustumCulled=head.frustumCulled=false;scene.add(body,head);
   let last=performance.now();animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;
     walkers.forEach((w,i)=>{w.t+=w.v*dt;if(Math.abs(w.t)>60){w.v=-w.v;w.t=Math.sign(w.t)*60;}
       const x=w.x0+w.dx*w.t-w.dz*w.sd*w.off,z=w.z0+w.dz*w.t+w.dx*w.sd*w.off,bob=Math.abs(Math.sin(now*0.009+i))*0.05;
       d.position.set(x,bob,z);d.rotation.set(0,-Math.atan2(w.dz*Math.sign(w.v),w.dx*Math.sign(w.v)),0);d.updateMatrix();body.setMatrixAt(i,d.matrix);head.setMatrixAt(i,d.matrix);});
     body.instanceMatrix.needsUpdate=head.instanceMatrix.needsUpdate=true;});}
  ctx.details=Object.assign(ctx.details||{},{focusShops:dshops,streetLights:lights.length,signals:sigHeads.length,shelters,parkedCars:parked.length,people:walkers.length,intersections:xings.length});
});
// ===== stages/06-traffic.js =====
// ---------- traffic: cars on the major streets and Lake Shore Drive, tour boats following the river, and a working lake:
// sailboats that tack, motor yachts and speedboats with wakes, a cruise ship and water taxis from Navy Pier, moored fleets in the harbours, a freighter ----------
await stage('traffic');
const polyLen=r=>{let L=0;r.cum=[0];for(let i=0;i+1<r.pts.length;i++){L+=Math.hypot(r.pts[i+1][0]-r.pts[i][0],r.pts[i+1][1]-r.pts[i][1]);r.cum.push(L);}r.len=L;return r;};
const polyAt=(r,s,wrap)=>{s=wrap?((s%r.len)+r.len)%r.len:Math.max(0,Math.min(r.len,s));let i=0;while(i<r.cum.length-2&&r.cum[i+1]<s)i++;const a=r.pts[i],b=r.pts[i+1],u=(s-r.cum[i])/((r.cum[i+1]-r.cum[i])||1);
  return [a[0]+(b[0]-a[0])*u,a[1]+(b[1]-a[1])*u,Math.atan2(b[1]-a[1],b[0]-a[0])];};
section('traffic',()=>{
  // routes: every major street (and each diagonal) as a polyline; cars run both ways, one lane each side
  const routes=[];
  for(const s of STREETS)if(s.major&&s.axis!=='d')routes.push(polyLen({pts:[s.a,s.b],w:s.w}));
  for(const d of DIAGONALS)routes.push(polyLen({pts:d.pts,w:d.w}));
  // what the road is at every 5 m, worked out once: 0 = none (lake, river with no bridge, off the map), 1 = street, 2 = bridge deck
  for(const r of routes){r.st=new Uint8Array(Math.ceil(r.len/5)+1);for(let k=0;k<r.st.length;k++){const [x,z]=polyAt(r,k*5,true);r.st[k]=inLake(x,z)||!inMap(x,z,20)?0:inRiver(x,z)?(onBridge(x,z)?2:0):1;}}
  const cars=[];for(const r of routes){const n=Math.floor(r.len/70);for(const dir of [-1,1])for(let k=0;k<n;k++)cars.push({r,dir,s:xr()*r.len,v:9+xr()*7,off:dir*r.w/4});}
  const cm=new THREE.InstancedMesh(new THREE.BoxGeometry(4.4,1.5,2),new THREE.MeshLambertMaterial({color:0xffffff}),cars.length),d=new THREE.Object3D(),col=new THREE.Color();
  const cab=new THREE.InstancedMesh(new THREE.BoxGeometry(2.3,0.75,1.8).translate(-0.3,1.1,0),new THREE.MeshLambertMaterial({color:0x26303a}),cars.length);   // the glasshouse on top
  cars.forEach((c,i)=>cm.setColorAt(i,col.setHSL(xr(),0.45,0.3+xr()*0.4)));cm.userData.life=true;cm.frustumCulled=cab.frustumCulled=false;scene.add(cm,cab);
  let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;
    for(let i=0;i<cars.length;i++){const c=cars[i];c.s+=c.dir*c.v*dt;const [x0,z0,a]=polyAt(c.r,c.s,true),x=x0-Math.sin(a)*c.off,z=z0+Math.cos(a)*c.off;
      const st=c.r.st[Math.round((((c.s%c.r.len)+c.r.len)%c.r.len)/5)],y=st===2?6.2:0.8,sc=st?1:0;   // hidden where there is no road
      d.position.set(x,y,z);d.rotation.set(0,-a+(c.dir<0?Math.PI:0),0);d.scale.setScalar(sc);d.updateMatrix();cm.setMatrixAt(i,d.matrix);cab.setMatrixAt(i,d.matrix);}
    cm.instanceMatrix.needsUpdate=cab.instanceMatrix.needsUpdate=true;});
  ctx.details=Object.assign(ctx.details||{},{cars:cars.length});
});
section('boats',()=>{
  const white=new THREE.MeshLambertMaterial({color:0xf2f0ea}),navy=new THREE.MeshLambertMaterial({color:0x223a5a}),teak=new THREE.MeshLambertMaterial({color:0x8a6a48}),glass=new THREE.MeshLambertMaterial({color:0x2a3a48});
  const sailM=new THREE.MeshLambertMaterial({color:0xfbfaf4,side:THREE.DoubleSide}),mastM=new THREE.MeshLambertMaterial({color:0xb0b4b8}),yellow=new THREE.MeshLambertMaterial({color:0xf2c230}),red=new THREE.MeshLambertMaterial({color:0xa02a24});
  const wakeM=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0.5,depthWrite:false});
  const hullG=(L,W,H)=>{const s=new THREE.Shape();s.moveTo(-L/2,-W/2);s.lineTo(L*0.18,-W/2);s.quadraticCurveTo(L*0.45,-W*0.3,L/2,0);s.quadraticCurveTo(L*0.45,W*0.3,L*0.18,W/2);s.lineTo(-L/2,W/2);s.closePath();
    const g=new THREE.ExtrudeGeometry(s,{depth:H,bevelEnabled:false});g.rotateX(-Math.PI/2);return g;};   // a pointed bow at +x, deck at y = H
  const wake=(len,w)=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([0,0.05,0, -len,0.05,-w, -len,0.05,w],3));g.computeVertexNormals();const m=new THREE.Mesh(g,wakeM.clone());m.material.side=THREE.DoubleSide;return m;};
  const lakeOK=(x,z,m)=>inLake(x,z)&&inLake(x-(m||60),z)&&inLake(x,z-(m||60))&&inLake(x,z+(m||60))&&x<B.x1+1300&&z>B.z0+80&&z<B.z1-80&&!onPier(x,z)&&!(x<PIER.x1+60&&Math.abs(z-PIER.z)<PIER.width/2+50);
  const pickLake=(R,xmin,xmax,m)=>{for(let t=0;t<300;t++){const x=xmin+Math.pow(R(),1.6)*(xmax-xmin),z=B.z0+R()*B.d;if(lakeOK(x,z,m))return [x,z];}return [B.x1-300,0];};   // biased towards the shore, where the boats are; the water runs 1.5 km past the map's east edge
  const R=mkRng(2026),movers=[];
  // sailboats: hull, mast, mainsail and jib; they reach across the wind, heel, and tack when the lake runs out
  const WIND=0.35;   // radians: the breeze blows from the east-north-east
  for(let k=0;k<48;k++){const L=8+R()*7,g=new THREE.Group(),hull=new THREE.Mesh(hullG(L,L*0.32,1.1),R()<0.2?navy:white);g.add(hull);
    const rig=new THREE.Group();rig.position.y=1.1;g.add(rig);const mh=L*1.35,mast=new THREE.Mesh(new THREE.CylinderGeometry(0.07,0.09,mh,5),mastM);mast.position.set(L*0.05,mh/2,0);rig.add(mast);
    const tri=(a,b,c)=>{const t=new THREE.BufferGeometry();t.setAttribute('position',new THREE.Float32BufferAttribute([...a,...b,...c],3));t.computeVertexNormals();return new THREE.Mesh(t,sailM);};
    const main=tri([L*0.05,0.8,0],[L*0.05,mh,0],[-L*0.4,0.9,0]),jib=tri([L*0.1,mh*0.85,0],[L*0.46,0.3,0],[L*0.08,0.6,0]);rig.add(main,jib);
    const [x,z]=pickLake(R,SHORE[0][0]+300,B.x1+1200,80);scene.add(g);movers.push({kind:'sail',g,rig,main,jib,x,z,a:WIND+(R()<0.5?1:-1)*(1.0+R()*0.5),v:2.5+R()*2,tack:0,L});}
  // motor yachts and speedboats: straight runs with a wake, turning back at the edges
  for(let k=0;k<22;k++){const fast=k<8,L=fast?7+R()*3:14+R()*10,g=new THREE.Group(),hull=new THREE.Mesh(hullG(L,L*(fast?0.36:0.3),fast?1:1.8),fast&&R()<0.5?red:white);g.add(hull);
    if(fast){const w=new THREE.Mesh(new THREE.BoxGeometry(L*0.25,0.7,L*0.3),glass);w.position.set(-L*0.05,1.35,0);g.add(w);}
    else{const cab=new THREE.Mesh(new THREE.BoxGeometry(L*0.45,2,L*0.22),white);cab.position.set(-L*0.08,2.8,0);const win=new THREE.Mesh(new THREE.BoxGeometry(L*0.46,0.7,L*0.23),glass);win.position.set(-L*0.08,3.2,0);const fly=new THREE.Mesh(new THREE.BoxGeometry(L*0.25,0.2,L*0.2),navy);fly.position.set(-L*0.12,3.9,0);g.add(cab,win,fly);}
    const wk=wake(L*(fast?4:2.5),L*(fast?1.1:0.7));wk.position.x=-L/2;g.add(wk);
    const [x,z]=pickLake(R,SHORE[0][0]+250,B.x1+1200,60);scene.add(g);movers.push({kind:'motor',g,wk,x,z,a:R()*6.28,v:fast?14+R()*8:5+R()*4,L,turn:0});}
  // the cruise ship: a long white three-deck boat on a loop out from Navy Pier and back
  const cruise=new THREE.Group();{const L=60,h=new THREE.Mesh(hullG(L,15,2.6),white);cruise.add(h);for(let k=0;k<3;k++){const deck=new THREE.Mesh(new THREE.BoxGeometry(L*(0.72-k*0.14),2.6,13-k*2),k===1?glass:white);deck.position.set(-L*0.06,2.6+1.3+k*2.6,0);cruise.add(deck);}
    const wk=wake(160,30);wk.position.x=-L/2;cruise.add(wk);scene.add(cruise);}
  const cruiseLoop=polyLen({pts:[[PIER.x0+300,PIER.z-80],[PIER.x1+500,PIER.z-500],[PIER.x1+1500,PIER.z+400],[PIER.x1+900,PIER.z+1800],[PIER.x0+700,PIER.z+1300],[PIER.x0+300,PIER.z+90],[PIER.x0+300,PIER.z-80]]});
  movers.push({kind:'path',g:cruise,r:cruiseLoop,s:0,v:6,wrap:true});
  // water taxis: yellow shuttles between Navy Pier and the Museum Campus
  const [mcx,mcz]=P([41.8676,-87.6120]);
  for(let k=0;k<3;k++){const g=new THREE.Group(),L=16;g.add(new THREE.Mesh(hullG(L,5,1.4),yellow));const top=new THREE.Mesh(new THREE.BoxGeometry(9,2,4),yellow);top.position.set(-1,2.4,0);const roof=new THREE.Mesh(new THREE.BoxGeometry(10,0.3,4.6),white);roof.position.set(-1,3.5,0);g.add(top,roof);
    const wk=wake(40,6);wk.position.x=-L/2;g.add(wk);scene.add(g);
    const route=polyLen({pts:[[PIER.x0+80,PIER.z+PIER.width/2+25],[PIER.x0+260,PIER.z+700],[mcx+220,mcz-900],[mcx+120,mcz-60]]});movers.push({kind:'path',g,r:route,s:k*route.len/3,v:7,dir:k%2?1:-1});}
  // a lake freighter far out, crawling along the horizon
  const freighter=new THREE.Group();{const L=210;freighter.add(new THREE.Mesh(hullG(L,23,9),red));const deck=new THREE.Mesh(new THREE.BoxGeometry(L*0.8,1.2,21),new THREE.MeshLambertMaterial({color:0x3a3a3a}));deck.position.set(0,9.6,0);
    const house=new THREE.Mesh(new THREE.BoxGeometry(18,12,20),white);house.position.set(-L*0.42,15,0);const bow=new THREE.Mesh(new THREE.BoxGeometry(10,8,20),white);bow.position.set(L*0.42,13,0);freighter.add(deck,house,bow);scene.add(freighter);}
  movers.push({kind:'path',g:freighter,r:polyLen({pts:[[B.x1+900,B.z0-600],[B.x1+1100,B.z1+600]]}),s:0,v:4,dir:1});
  // moored boats: rows on the harbour moorings (Monroe Harbor and DuSable Harbor), bobbing
  const harbours=[[[41.8765,-87.6150],[41.8835,-87.6118]],[[41.8850,-87.6128],[41.8878,-87.6106]]];
  const moored=[];for(const [a,b] of harbours){const [x0,z1]=P(a),[x1,z0]=P(b);for(let z=z0+10;z<z1-6;z+=16)for(let x=x0+10;x<x1-6;x+=12)if(inLake(x,z)&&R()<0.75)moored.push([x+R()*3,z+R()*3,R()*6.28,R()<0.7]);}
  {const n=moored.length,hulls=new THREE.InstancedMesh(hullG(9,3,1),white,n),masts=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.06,0.08,11,4).translate(0,6.5,0),mastM,n),dd=new THREE.Object3D();
   moored.forEach(([x,z,a,sail],i)=>{dd.position.set(x,0,z);dd.rotation.set(0,a,0);dd.scale.set(1,1,1);dd.updateMatrix();hulls.setMatrixAt(i,dd.matrix);dd.scale.set(1,sail?1:0.001,1);dd.updateMatrix();masts.setMatrixAt(i,dd.matrix);});
   scene.add(hulls,masts);let t0=0;animHooks.push(now=>{if(now-t0<120)return;t0=now;moored.forEach(([x,z,a,sail],i)=>{const b=Math.sin(now*0.0012+x*0.3)*0.15;dd.position.set(x,b,z);dd.rotation.set(Math.sin(now*0.001+z)*0.03,a,Math.sin(now*0.0013+x)*0.04);dd.scale.set(1,1,1);dd.updateMatrix();hulls.setMatrixAt(i,dd.matrix);dd.scale.set(1,sail?1:0.001,1);dd.updateMatrix();masts.setMatrixAt(i,dd.matrix);});hulls.instanceMatrix.needsUpdate=masts.instanceMatrix.needsUpdate=true;});}
  // river tour boats: up and down the three branches, along the river's own bends
  const tours=[];RIVERS.forEach((rv,ri)=>{const r=polyLen({pts:rv.pts});for(let k=0;k<(ri===0?4:2);k++){const g=new THREE.Group();g.add(new THREE.Mesh(hullG(24,6.5,1.4),white));const top=new THREE.Mesh(new THREE.BoxGeometry(16,1.8,5.2),navy);top.position.set(-2,2.3,0);g.add(top);scene.add(g);
    movers.push({kind:'path',g,r,s:(k+0.5)/4*r.len,v:3.5+R()*2,dir:k%2?1:-1,bounce:true,off:rv.width*0.2});tours.push(g);}});
  let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;const T=now/1000;
    for(const m of movers){
      if(m.kind==='sail'){const nx=m.x+Math.cos(m.a)*m.v*dt,nz=m.z+Math.sin(m.a)*m.v*dt;
        if(m.tack>0){m.tack-=dt;m.a+=(m.ta-m.a)*Math.min(1,dt*0.8);}else if(!lakeOK(nx+Math.cos(m.a)*80,nz+Math.sin(m.a)*80,20)){const rel=m.a-WIND;m.ta=WIND-rel+(Math.sin(rel)>0?0:0);m.ta=WIND+(Math.sin(m.a-WIND)>0?-1:1)*(1.1+((m.x*13)%1)*0.4);m.tack=4;}   // come about onto the other tack
        else{m.x=nx;m.z=nz;}
        const side=Math.sin(m.a-WIND)>0?1:-1;m.g.position.set(m.x,0.2+Math.sin(T*1.3+m.x)*0.12,m.z);m.g.rotation.set(side*0.14*(m.tack>0?0.2:1),-m.a,0);m.rig.rotation.y=side*0.45;}
      else if(m.kind==='motor'){const nx=m.x+Math.cos(m.a)*m.v*dt,nz=m.z+Math.sin(m.a)*m.v*dt;
        if(!lakeOK(nx+Math.cos(m.a)*120,nz+Math.sin(m.a)*120,20)){m.a+=dt*0.9;}else{m.x=nx;m.z=nz;m.a+=Math.sin(T*0.05+m.x)*0.02*dt;}
        m.g.position.set(m.x,0.1+Math.sin(T*2+m.z)*0.08,m.z);m.g.rotation.set(0,-m.a,Math.sin(T*1.7+m.x)*0.02);m.wk.material.opacity=0.35+0.15*Math.sin(T*3+m.x);}
      else{m.dir=m.dir||1;m.s+=m.dir*m.v*dt;if(!m.wrap){if(m.s>m.r.len-30){m.s=m.r.len-30;m.dir=-1;}if(m.s<30){m.s=30;m.dir=1;}}
        const [x,z,a]=polyAt(m.r,m.s,m.wrap),o=(m.off||0)*m.dir;m.g.position.set(x-Math.sin(a)*o,0.2+Math.sin(T+x)*0.08,z+Math.cos(a)*o);m.g.rotation.y=-a+(m.dir>0?0:Math.PI);}}});
  ctx.details=Object.assign(ctx.details||{},{sailboats:48,motorboats:22,moored:moored.length,cruise:1,waterTaxis:3,freighter:1,riverTours:tours.length});
});
// ===== stages/07-ui.js =====
// ---------- camera, views, the clock, the card, the render loop ----------
await stage('ui');
const el=renderer.domElement;
// orbit camera: drag to orbit, right/shift-drag or two fingers to pan, wheel/pinch to zoom, WASD/QE to move the target
const ctl={target:new THREE.Vector3(0,40,0),az:0.6,el:0.5,dist:1400,goal:null};
function applyCam(){const e=Math.max(0.03,Math.min(1.5,ctl.el));camera.position.set(ctl.target.x+Math.cos(ctl.az)*Math.cos(e)*ctl.dist,ctl.target.y+Math.sin(e)*ctl.dist,ctl.target.z+Math.sin(ctl.az)*Math.cos(e)*ctl.dist);camera.lookAt(ctl.target);}
function setView(px,py,pz,tx,ty,tz,fly){const t=new THREE.Vector3(tx,ty,tz),p=new THREE.Vector3(px,py,pz),d=p.clone().sub(t);const goal={target:t,az:Math.atan2(d.z,d.x),el:Math.atan2(d.y,Math.hypot(d.x,d.z)),dist:d.length()};
  if(fly===false||matchMedia('(prefers-reduced-motion: reduce)').matches){Object.assign(ctl,goal);ctl.goal=null;return;}ctl.goal=Object.assign(goal,{t0:performance.now(),from:{target:ctl.target.clone(),az:ctl.az,el:ctl.el,dist:ctl.dist}});}
const ptrs=new Map();let pinch0=0,dist0=0;
el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);ptrs.set(e.pointerId,{x:e.clientX,y:e.clientY,b:e.button,sh:e.shiftKey,moved:0});if(ptrs.size===2){const [a,b]=[...ptrs.values()];pinch0=Math.hypot(a.x-b.x,a.y-b.y);dist0=ctl.dist;}});
el.addEventListener('pointermove',e=>{const p=ptrs.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;p.moved+=Math.abs(dx)+Math.abs(dy);ctl.goal=null;
  if(ptrs.size===2){const [a,b]=[...ptrs.values()];const pd=Math.hypot(a.x-b.x,a.y-b.y);ctl.dist=Math.max(8,Math.min(9000,dist0*pinch0/pd));pan(dx/2,dy/2);return;}
  if(p.b===2||p.sh)pan(dx,dy);else{ctl.az+=dx*0.005;ctl.el=Math.max(0.03,Math.min(1.5,ctl.el+dy*0.005));}});
const endPtr=e=>{const p=ptrs.get(e.pointerId);ptrs.delete(e.pointerId);if(p&&p.moved<6&&e.type==='pointerup'&&p.b===0)clickAt(e.clientX,e.clientY);};
el.addEventListener('pointerup',endPtr);el.addEventListener('pointercancel',endPtr);el.addEventListener('contextmenu',e=>e.preventDefault());
function pan(dx,dy){const k=ctl.dist*0.0016;const fx=Math.cos(ctl.az),fz=Math.sin(ctl.az);ctl.target.x+=(-dx*fz+dy*fx)*k*-1;ctl.target.z+=(dx*fx+dy*fz)*k*-1;}
el.addEventListener('wheel',e=>{e.preventDefault();ctl.goal=null;ctl.dist=Math.max(8,Math.min(9000,ctl.dist*Math.exp(e.deltaY*0.0012)));},{passive:false});
const keys=new Set();addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;keys.add(e.key.toLowerCase());if(e.key==='Escape')closeCard();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function applyKeys(){if(!keys.size)return;const s=ctl.dist*0.012,fx=Math.cos(ctl.az),fz=Math.sin(ctl.az);let mx=0,mz=0;if(keys.has('w'))mx-=1;if(keys.has('s'))mx+=1;if(keys.has('a'))mz+=1;if(keys.has('d'))mz-=1;
  ctl.target.x+=(mx*fx-mz*fz)*s;ctl.target.z+=(mx*fz+mz*fx)*s;if(keys.has('q'))ctl.target.y=Math.max(0,ctl.target.y-s);if(keys.has('e'))ctl.target.y+=s;if(mx||mz||keys.has('q')||keys.has('e'))ctl.goal=null;}
function stepFly(now){const g=ctl.goal;if(!g)return;const u=Math.min(1,(now-g.t0)/1400),k=u*u*(3-2*u);ctl.target.lerpVectors(g.from.target,g.target,k);let da=g.az-g.from.az;da=Math.atan2(Math.sin(da),Math.cos(da));ctl.az=g.from.az+da*k;ctl.el=g.from.el+(g.el-g.from.el)*k;ctl.dist=g.from.dist+(g.dist-g.from.dist)*k;if(u>=1)ctl.goal=null;}
// the panels: viewpoints, the clock, a card for the landmark you click
const ui=document.getElementById('ui'),viewsEl=document.getElementById('views'),card=document.getElementById('card'),side=document.getElementById('side');
const VIEWS={};for(const k in C.views){const [f,t]=C.views[k],[fx,fz]=P(f),[tx,tz]=P(t);VIEWS[k]=[fx,f[2],fz,tx,t[2],tz];}   // [lat,lon,height] from and to
const mkBtn=(label,parent,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;parent.appendChild(b);return b;};
const viewsBtn=mkBtn('Views',ui,()=>{const open=!viewsEl.classList.contains('open');viewsEl.classList.toggle('open',open);viewsBtn.setAttribute('aria-expanded',String(open));});viewsBtn.setAttribute('aria-expanded','false');
{const h=document.createElement('div');h.className='sub';h.textContent='Viewpoints';viewsEl.appendChild(h);for(const k in VIEWS)mkBtn(k,viewsEl,()=>{setView(...VIEWS[k]);viewsEl.classList.remove('open');viewsBtn.setAttribute('aria-expanded','false');});}
const pauseBtn=mkBtn('Pause sun',ui,()=>{if(!clockPaused){clockPaused=true;pausedAt=performance.now()-clockOffset;pauseBtn.textContent='Resume sun';}else{clockPaused=false;clockOffset=performance.now()-pausedAt;pauseBtn.textContent='Pause sun';}});
const tw=document.createElement('div');tw.id='timebar';tw.innerHTML='<label for="tslider" id="tlabel">10:30</label><input id="tslider" type="range" min="0" max="24" step="0.05" value="10.5" aria-label="Time of day"><select id="daylen" aria-label="Length of a day"><option value="120">day 2 min</option><option value="240" selected>day 4 min</option><option value="720">day 12 min</option></select>';side.appendChild(tw);
const tsl=document.getElementById('tslider'),tlab=document.getElementById('tlabel'),dsel=document.getElementById('daylen');let dragging=false;
tsl.addEventListener('pointerdown',()=>{dragging=true;});addEventListener('pointerup',()=>{dragging=false;});tsl.addEventListener('input',()=>setHour(parseFloat(tsl.value)));
dsel.addEventListener('change',()=>{const h=hourCur;DAY=+dsel.value;setHour(h);});
const hud=document.createElement('pre');hud.id='hud';side.appendChild(hud);let hudT=0,tbTxt='';
animHooks.push(now=>{if(now-hudT<200)return;hudT=now;const h=hourCur,t=`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.floor((h%1)*60)).padStart(2,'0')}`;if(!dragging)tsl.value=h.toFixed(2);if(t!==tbTxt){tbTxt=t;tlab.textContent=t;}
  hud.textContent=`${t}\ntarget  x ${ctl.target.x.toFixed(0)}  z ${ctl.target.z.toFixed(0)}\n${districtAt(ctl.target.x,ctl.target.z).name}`+(RES.cur<RES.max-0.01?`\nrender  ×${RES.cur.toFixed(2)}`:'');});
const ray=new THREE.Raycaster(),ndc=new THREE.Vector2();
function clickAt(cx,cy){ndc.set(cx/innerWidth*2-1,-(cy/innerHeight)*2+1);ray.setFromCamera(ndc,camera);const hits=ray.intersectObjects(LANDMARKS,true);if(!hits.length){closeCard();return;}
  let o=hits[0].object,info=null;while(o&&!info){info=o.userData.info;o=o.parent;}if(!info)return;showCard(info);}
function showCard(L){card.innerHTML='';const h=document.createElement('h2');h.textContent=L.name;const p=document.createElement('p');p.textContent=L.info||'';const b=document.createElement('button');b.type='button';b.textContent='Close';b.onclick=closeCard;card.append(h,p,b);card.classList.add('open');card.style.display='block';b.focus();}
function closeCard(){card.classList.remove('open');card.style.display='';}
// the address keeps the view and the hour, like the Iziz page: #v=px,py,pz,tx,ty,tz&t=hour
function stateToHash(){const r1=x=>Math.round(x*10)/10,p=camera.position,t=ctl.target;return '#'+(SEED0!==SEED_DEFAULT?'seed='+SEED0+'&':'')+'v='+[p.x,p.y,p.z,t.x,t.y,t.z].map(r1).join(',')+'&t='+(Math.round(hourCur*20)/20)+(clockPaused?'&paused':'');}
function readHash(){let q;try{q=new URLSearchParams(location.hash.slice(1));}catch(e){return false;}if(!q.has('v'))return false;const v=(q.get('v')||'').split(',').map(Number);if(v.length===6&&v.every(Number.isFinite))setView(...v,false);
  const t=parseFloat(q.get('t'));if(Number.isFinite(t))setHour(((t%24)+24)%24);if(q.has('paused')&&!clockPaused)pauseBtn.click();return true;}
let lastHash='',hashT=0;animHooks.push(now=>{if(now-hashT<1500||ctl.goal||ptrs.size)return;hashT=now;const h=stateToHash();if(h!==lastHash){lastHash=h;try{history.replaceState(null,'',h);}catch(e){}}});
if(!readHash())setView(...VIEWS['Skyline from the lake'],false);
{const hint=document.getElementById('hint');const hide=()=>hint.classList.add('gone');setTimeout(hide,12000);el.addEventListener('pointerdown',hide,{once:true});el.addEventListener('wheel',hide,{once:true,passive:true});}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);updatePx();});
if(SEED0!==SEED_DEFAULT)document.getElementById('seedtag').textContent='seed '+SEED0;
// shadows follow the target; compile everything behind the loading text
await stage('shaders');
section('shaders',()=>{applyCam();sun.target.position.copy(ctl.target);renderer.compile(scene,camera);renderer.render(scene,camera);});
stage('done');ctx.timings=LOAD.times;ctx.loadMs=Math.round(performance.now()-LOAD.t0);if(/debug/.test(location.search))console.table(LOAD.times);
document.getElementById('loading').remove();
renderer.shadowMap.autoUpdate=false;const shadowAt=new THREE.Vector3(1e9,0,0);let shadowTick=0;
function shadowsDue(){if(sun.intensity<=0.02)return false;if(ctl.target.distanceToSquared(shadowAt)>4){shadowAt.copy(ctl.target);sun.target.position.copy(ctl.target);sun.position.copy(ENV.izSunDir.value).multiplyScalar(2500).add(ctl.target);return true;}return (++shadowTick%3)===0;}
// adaptive resolution, as on the Iziz page
const RES={max:Math.min(devicePixelRatio,1.5),cur:Math.min(devicePixelRatio,1.5),min:0.6,acc:0,n:0,good:0,bad:0,prev:performance.now()};
function adaptRes(now){const dt=(now-RES.prev)/1000;RES.prev=now;if(dt>0.5||document.hidden)return;RES.acc+=dt;RES.n++;if(RES.acc<1)return;const fps=RES.n/RES.acc;RES.acc=0;RES.n=0;
  if(fps<45){RES.bad++;RES.good=0;}else if(fps>56){RES.good++;RES.bad=0;}let next=RES.cur;if(RES.bad>=2){next=Math.max(RES.min,RES.cur-0.15);RES.bad=0;}else if(RES.good>=8&&RES.cur<RES.max){next=Math.min(RES.max,RES.cur+0.1);RES.good=0;}
  if(Math.abs(next-RES.cur)>1e-3){RES.cur=+next.toFixed(2);renderer.setPixelRatio(RES.cur);renderer.setSize(innerWidth,innerHeight);updatePx();}}
ctx.res=RES;let fpsN=0,fpsT=performance.now(),renderErr=false;
(function animate(){requestAnimationFrame(animate);try{const now=performance.now();adaptRes(now);fpsN++;if(now-fpsT>1000){ctx.fps=fpsN;fpsN=0;fpsT=now;}
  for(const f of animHooks){try{f(now);}catch(e){if(!f._failed){f._failed=true;report('update',e);}}}stepFly(now);applyKeys();applyCam();if(shadowsDue())renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera);}catch(e){if(!renderErr){renderErr=true;report('render',e);}}})();
}
