// GENERATED by tools/build-page.py from src/chicago/stages/ (8 files, sources 994636ea43372bd0).
// Do not edit: change the stage files and run ./sitectl build.
import {report,section,stage,LOAD} from '../core/diag.js';
import {createLcg,makeNoise,clamp,smooth,hash3,mkRng} from '../core/rng.js';
import {DATA_FN,dataValue,resolveCity} from '../core/data.js';
import {createEnv} from '../core/env.js';
export async function build(ctx){
// ===== stages/00-start.js =====
// ---------- start: three.js check, the city file, randomness, shared helpers ----------
if(!window.THREE){document.getElementById('loading').textContent='three.js did not load (vendor/three/three.min.js). Check the site mounts and reload.';return;}
const THREE=window.THREE;
const CITY_ID=(()=>{const v=new URLSearchParams(location.search).get('city')||'';return /^[a-z0-9-]{1,40}$/.test(v)?v:'chicago';})();
ctx.cityId=CITY_ID;
const DATA=await fetch('data/cities/'+CITY_ID+'.json').then(r=>{if(!r.ok)throw new Error('data/cities/'+CITY_ID+'.json: HTTP '+r.status);return r.json();});
const C=resolveCity(DATA,['name','note','grid','major','shore','river','parks','beach','pier','districts','landmarks','el','views']);
for(const k of ['grid','major','shore','river','parks','beach','pier','districts','landmarks','el','views'])C[k]=DATA[k];
const SEED_DEFAULT=DATA.defaultSeed||1871;
const SEED0=(()=>{try{const v=parseInt(new URLSearchParams(location.search).get('seed')||new URLSearchParams(location.hash.slice(1)).get('seed'),10);return v>0&&v<2147483647?v:SEED_DEFAULT;}catch(e){return SEED_DEFAULT;}})();
const LCG=createLcg(SEED0);const rnd=LCG.rnd,rr=LCG.rr,pick=LCG.pick;
const {vn,fbm}=makeNoise(rnd);
const xr=mkRng(20261017),xrr=(a,b)=>a+(b-a)*xr();
const WORLD=C.WORLD,SHORE=C.shore.x,GRID=C.grid,RIV=C.river,PIER=C.pier,EL=C.el;
const MAJOR=C.major.streets.map(([axis,at,w,name])=>({axis,at,w,name}));
const DIST={};for(const k in C.districts)if(k!=='_'){const [name,col,base,tall]=C.districts[k];DIST[k]={key:k,name,color:parseInt(col.slice(1),16),base,tall};}
const animHooks=[];
// where things are: water, parks, the pier, the major streets
const RM=RIV.main,RN=RIV.north,RS=RIV.south;
function inRiver(x,z){if(x>=RM.xWest-RN.width/2&&x<=RM.xEast&&Math.abs(z-RM.z)<=RM.width/2)return true;
  if(Math.abs(x-RN.x)<=RN.width/2&&z<RM.z&&z>RN.zEnd)return true;if(Math.abs(x-RS.x)<=RS.width/2&&z>RM.z&&z<RS.zEnd)return true;return false;}
function inLake(x,z){if(x>SHORE)return !(x<PIER.x+PIER.length&&Math.abs(z-PIER.z)<=PIER.width/2);return false;}
function inWater(x,z){return inLake(x,z)||inRiver(x,z);}
function parkAt(x,z){for(const p of C.parks)if(x>=p.x0&&x<=p.x1&&z>=p.z0&&z<=p.z1)return p;return null;}
function majorAt(x,z){for(const m of MAJOR){const d=m.axis==='x'?Math.abs(x-m.at):Math.abs(z-m.at);if(d<=m.w/2)return m;}return null;}
function districtAt(x,z){if(x>=-780&&x<=290&&z>=-520&&z<=390)return DIST.loop;if(z<=-720&&z>=-1300){if(x>=-780&&x<=290)return DIST.rivernorth;if(x>290&&x<=SHORE)return DIST.streeterville;}
  if(z<-1300&&x>-400&&x<=SHORE)return DIST.goldcoast;if(x<-780&&z>=-720&&z<=520)return DIST.westloop;if(z>390&&z<=1400&&x<600)return DIST.southloop;return DIST.outer;}
ctx.districtAt=districtAt;ctx.inWater=inWater;
// ===== stages/01-scene.js =====
// ---------- scene: renderer, camera, the sun's day, sky ----------
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,1,12000);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
document.body.appendChild(renderer.domElement);
const {ENV,setEnv}=createEnv();   // the shared uniforms; setEnv gives materials world-unit UV tiling
const updatePx=()=>{ENV.izPx.value=innerHeight*renderer.getPixelRatio()/(2*Math.tan(camera.fov*Math.PI/360));};updatePx();
const ambient=new THREE.AmbientLight(0x9fb4c8,0.35);scene.add(ambient);
const hemi=new THREE.HemisphereLight(0xbfd8f0,0x5a5048,0.55);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xfff2dc,1.1);scene.add(sun);scene.add(sun.target);
sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);{const sc=sun.shadow.camera;sc.left=-700;sc.right=700;sc.top=700;sc.bottom=-700;sc.near=1;sc.far=4000;sc.updateProjectionMatrix();}
sun.shadow.bias=-0.0008;sun.shadow.normalBias=2;
scene.fog=new THREE.FogExp2(0xb9cbe0,0.00022);
// the clock: DAY real seconds per city day
let DAY=240;const HOUR0=10.5;let clockPaused=false,pausedAt=0,clockOffset=0;
function hourNow(now){return ((HOUR0+((now/1000)/(DAY/24)))%24+24)%24;}
function setHour(h){const now=performance.now(),cur=clockPaused?pausedAt:now-clockOffset,tot=HOUR0+(cur/1000)/(DAY/24);let day=Math.floor(tot/24);if(day*24+h<HOUR0)day+=1;const t=(day*24+h-HOUR0)*(DAY/24)*1000;if(clockPaused)pausedAt=t;else clockOffset=now-t;}
window.setHour=setHour;
const nightF=h=>1-smooth(5.6,7.4,h)+smooth(17.6,19.6,h);   // ~1 at night, 0 by day (Chicago, spring)
const windowF=h=>smooth(16.5,18.5,h)*(1-smooth(23,25,h))+0.12*nightF(h);
// the sun: rises in the east over the lake (+x), sets in the west
function sunAt(h){const f=(h-6)/12,E=Math.sin(Math.PI*f)*0.95,az=Math.PI*(1-f);return new THREE.Vector3(Math.cos(az)*Math.cos(E),Math.sin(E),Math.sin(az)*0.35*Math.cos(E)).normalize();}
// sky: a gradient dome, coloured by the hour
const SKY={day:{top:0x2f6fd0,hor:0xbcd3ee},dusk:{top:0x2a3a78,hor:0xf0a060},night:{top:0x050a1c,hor:0x16243c}};
const skyM=new THREE.ShaderMaterial({uniforms:{top:{value:new THREE.Color()},hor:{value:new THREE.Color()},sunDir:{value:new THREE.Vector3(0,1,0)},sunA:{value:1}},side:THREE.BackSide,depthWrite:false,fog:false,
  vertexShader:'varying vec3 vP;void main(){vP=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',
  fragmentShader:'uniform vec3 top;uniform vec3 hor;uniform vec3 sunDir;uniform float sunA;varying vec3 vP;void main(){float t=clamp(vP.y*1.6,0.0,1.0);vec3 c=mix(hor,top,pow(t,0.6));float d=max(dot(vP,sunDir),0.0);c+=vec3(1.0,0.85,0.6)*(pow(d,600.0)*1.2+pow(d,8.0)*0.18)*sunA;gl_FragColor=vec4(c,1.0);}'});
const sky=new THREE.Mesh(new THREE.SphereGeometry(5500,32,16),skyM);sky.userData.noShadow=true;scene.add(sky);
const tmpC=new THREE.Color(),tmpC2=new THREE.Color();
function lerpSky(h){const n=nightF(h),dusk=Math.max(0,1-Math.abs(h-18.6)/1.6,1-Math.abs(h-6.3)/1.4);
  const mixTo=(a,b,k)=>tmpC.set(a).lerp(tmpC2.set(b),k);
  skyM.uniforms.top.value.copy(mixTo(SKY.day.top,SKY.night.top,n)).lerp(tmpC2.set(SKY.dusk.top),dusk*0.7);
  skyM.uniforms.hor.value.copy(mixTo(SKY.day.hor,SKY.night.hor,n)).lerp(tmpC2.set(SKY.dusk.hor),dusk);
  scene.fog.color.copy(skyM.uniforms.hor.value);renderer.setClearColor(skyM.uniforms.hor.value);
  const S=sunAt(h);skyM.uniforms.sunDir.value.copy(S);skyM.uniforms.sunA.value=S.y>-0.05?1:0;
  sun.position.copy(S).multiplyScalar(2500).add(sun.target.position);sun.intensity=1.15*Math.max(0,Math.min(1,S.y*4))*(1-0.85*n);
  sun.color.setHSL(0.09,0.6,0.5+0.45*Math.min(1,S.y*3));hemi.intensity=0.55*(1-0.75*n);ambient.intensity=0.35*(1-0.5*n)+0.12*n;
  ENV.izHour.value=h;ENV.izNight.value=n;ENV.izDay.value=1-n;ENV.izSunDir.value.copy(S);}
let hourCur=HOUR0;
animHooks.push(now=>{hourCur=hourNow(clockPaused?pausedAt:now-clockOffset);ctx.hour=hourCur;ENV.izTime.value=now/1000;lerpSky(hourCur);});
lerpSky(HOUR0);
// ===== stages/02-ground.js =====
// ---------- ground: the painted map (streets, parks, beach), the lake and river, bridges, the pier ----------
await stage('ground');
const GS=2048,PX=GS/WORLD,px=v=>(v+WORLD/2)*PX;
const gcv=document.createElement('canvas');gcv.width=gcv.height=GS;const g2=gcv.getContext('2d');
section('ground',()=>{
  g2.fillStyle='#8d8a82';g2.fillRect(0,0,GS,GS);   // paving and roofs of the low city
  // neighbourhood texture: a faint block grid everywhere
  g2.strokeStyle='rgba(0,0,0,0.10)';g2.lineWidth=2;for(let x=-WORLD/2;x<=WORLD/2;x+=GRID.pitchX){g2.beginPath();g2.moveTo(px(x),0);g2.lineTo(px(x),GS);g2.stroke();}
  for(let z=-WORLD/2;z<=WORLD/2;z+=GRID.pitchZ){g2.beginPath();g2.moveTo(0,px(z));g2.lineTo(GS,px(z));g2.stroke();}
  // parks
  for(const p of C.parks){g2.fillStyle='#5f8a48';g2.fillRect(px(p.x0),px(p.z0),(p.x1-p.x0)*PX,(p.z1-p.z0)*PX);
    const R=mkRng(p.x0*7+p.z0);g2.fillStyle='rgba(30,70,30,0.35)';for(let k=0;k<(p.x1-p.x0)*(p.z1-p.z0)/2500;k++){g2.beginPath();g2.arc(px(p.x0+R()*(p.x1-p.x0)),px(p.z0+R()*(p.z1-p.z0)),2+R()*3,0,7);g2.fill();}
    g2.strokeStyle='#c9bfa8';g2.lineWidth=1.5;for(let k=0;k<3;k++){g2.beginPath();g2.moveTo(px(p.x0),px(p.z0+(k+0.5)*(p.z1-p.z0)/3));g2.lineTo(px(p.x1),px(p.z0+(k+0.5)*(p.z1-p.z0)/3));g2.stroke();}}
  // beach, then the water
  g2.fillStyle='#d9caa2';g2.fillRect(px(C.beach.x0),px(C.beach.z0),(SHORE+40-C.beach.x0)*PX,(C.beach.z1-C.beach.z0)*PX);
  g2.fillStyle='#2b5d88';g2.fillRect(px(SHORE),0,GS-px(SHORE),GS);
  g2.fillStyle='#31678f';g2.fillRect(px(RM.xWest-RN.width/2),px(RM.z-RM.width/2),(RM.xEast-RM.xWest+RN.width/2)*PX,RM.width*PX);
  g2.fillRect(px(RN.x-RN.width/2),px(RN.zEnd),RN.width*PX,(RM.z-RN.zEnd)*PX);g2.fillRect(px(RS.x-RS.width/2),px(RM.z),RS.width*PX,(RS.zEnd-RM.z)*PX);
  // streets: the grid, then the wide ones with a centre line
  const street=(axis,at,w,major)=>{g2.fillStyle=major?'#34363a':'#4a4b4f';if(axis==='x'){if(at>SHORE)return;g2.fillRect(px(at-w/2),0,w*PX,GS);}else g2.fillRect(0,px(at-w/2),Math.min(GS,px(SHORE)),w*PX);
    if(major){g2.strokeStyle='rgba(230,200,90,0.5)';g2.lineWidth=1;g2.setLineDash([6,6]);g2.beginPath();if(axis==='x'){g2.moveTo(px(at),0);g2.lineTo(px(at),GS);}else{g2.moveTo(0,px(at));g2.lineTo(px(SHORE),px(at));}g2.stroke();g2.setLineDash([]);}};
  for(let x=-WORLD/2;x<=SHORE;x+=GRID.pitchX)street('x',x,GRID.street,false);
  for(let z=-WORLD/2;z<=WORLD/2;z+=GRID.pitchZ)street('z',z,GRID.street,false);
  for(const m of MAJOR)street(m.axis,m.at,m.w,true);
  // Lake Shore Drive runs the whole shore; the pier is paved
  g2.fillStyle='#a19b90';g2.fillRect(px(PIER.x),px(PIER.z-PIER.width/2),PIER.length*PX,PIER.width*PX);
  // water takes precedence over streets that were painted across it
  g2.fillStyle='#31678f';g2.fillRect(px(RM.xWest-RN.width/2),px(RM.z-RM.width/2),(RM.xEast-RM.xWest+RN.width/2)*PX,RM.width*PX);
  g2.fillRect(px(RN.x-RN.width/2),px(RN.zEnd),RN.width*PX,(RM.z-RN.zEnd)*PX);g2.fillRect(px(RS.x-RS.width/2),px(RM.z),RS.width*PX,(RS.zEnd-RM.z)*PX);
});
const groundTex=new THREE.CanvasTexture(gcv);groundTex.anisotropy=8;
const ground=new THREE.Mesh(new THREE.PlaneGeometry(WORLD,WORLD),new THREE.MeshLambertMaterial({map:groundTex}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.userData.noShadow=true;scene.add(ground);
// water: one lake plane and three river ribbons, just above the paint
const waterM=new THREE.MeshPhongMaterial({color:0x2c6390,specular:0x9fc4e0,shininess:90,transparent:true,opacity:0.92});
{const lake=new THREE.Mesh(new THREE.PlaneGeometry(WORLD/2-SHORE,WORLD),waterM);lake.rotation.x=-Math.PI/2;lake.position.set((SHORE+WORLD/2)/2,0.12,0);lake.receiveShadow=true;scene.add(lake);
 const rib=(x,z,w,d)=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(w,d),waterM);m.rotation.x=-Math.PI/2;m.position.set(x,0.12,z);scene.add(m);};
 rib((RM.xWest+RM.xEast)/2,RM.z,RM.xEast-RM.xWest+RN.width,RM.width);rib(RN.x,(RM.z+RN.zEnd)/2,RN.width,RM.z-RN.zEnd);rib(RS.x,(RM.z+RS.zEnd)/2,RS.width,RS.zEnd-RM.z);}
animHooks.push(now=>{waterM.shininess=70+25*Math.sin(now*0.0011);});
// a low sea wall along the shore, the pier as a slab with its sheds, and the bridges
const stoneM=new THREE.MeshLambertMaterial({color:0xbdb5a6}),steelM=new THREE.MeshLambertMaterial({color:0x6b6f75});
{const wall=new THREE.Mesh(new THREE.BoxGeometry(6,3,WORLD),stoneM);wall.position.set(SHORE-3,1.2,0);wall.castShadow=true;scene.add(wall);
 const slab=new THREE.Mesh(new THREE.BoxGeometry(PIER.length,4,PIER.width),stoneM);slab.position.set(PIER.x+PIER.length/2,2,PIER.z);slab.castShadow=slab.receiveShadow=true;scene.add(slab);
 for(let k=0;k<4;k++){const shed=new THREE.Mesh(new THREE.BoxGeometry(150,12,50),new THREE.MeshLambertMaterial({color:0xd8d2c4}));shed.position.set(PIER.x+180+k*200,10,PIER.z+(k%2?18:-18));shed.castShadow=true;scene.add(shed);}
 const hall=new THREE.Mesh(new THREE.BoxGeometry(80,26,90),new THREE.MeshLambertMaterial({color:0xc9b8a0}));hall.position.set(PIER.x+PIER.length-60,17,PIER.z);hall.castShadow=true;scene.add(hall);}
const bridges=[];
function bridge(x,z,w,len,along){const b=new THREE.Mesh(new THREE.BoxGeometry(along==='x'?len:w,2.4,along==='x'?w:len),steelM);b.position.set(x,4.2,z);b.castShadow=b.receiveShadow=true;scene.add(b);bridges.push(b);
  for(const s of [-1,1]){const r=new THREE.Mesh(new THREE.BoxGeometry(along==='x'?len:1.2,3.5,along==='x'?1.2:len),steelM);r.position.set(x+(along==='x'?0:s*(w/2-0.6)),7,z+(along==='x'?s*(w/2-0.6):0));scene.add(r);}
  for(const s of [-1,1]){const t=new THREE.Mesh(new THREE.BoxGeometry(6,14,6),stoneM);t.position.set(x+(along==='x'?s*len/2:0),7,z+(along==='x'?0:s*len/2));scene.add(t);}}
for(let x=-WORLD/2;x<=SHORE;x+=GRID.pitchX)if(x>RM.xWest+40&&x<RM.xEast-30){const m=majorAt(x,RM.z-200);bridge(x,RM.z,(m&&m.axis==='x'?m.w:GRID.street)+2,RM.width+16,'z');}
for(let z=-WORLD/2;z<=WORLD/2;z+=GRID.pitchZ)if(Math.abs(z-RM.z)>90){const m=majorAt(RN.x+200,z);bridge(RN.x,z,(m&&m.axis==='z'?m.w:GRID.street)+2,RN.width+16,'x');}
// trees in the parks and along Michigan Avenue
{const trunkM=new THREE.MeshLambertMaterial({color:0x5a4030}),leafM=new THREE.MeshLambertMaterial({color:0x3f7a3a});
 const spots=[];for(const p of C.parks){const R=mkRng(p.x1*3+p.z1);const n=Math.floor((p.x1-p.x0)*(p.z1-p.z0)/2200);for(let k=0;k<n;k++){const x=p.x0+8+R()*(p.x1-p.x0-16),z=p.z0+8+R()*(p.z1-p.z0-16);if(!majorAt(x,z))spots.push([x,z,7+R()*6]);}}
 for(let z=-1500;z<=900;z+=26)for(const s of [-1,1])spots.push([260+s*22,z,7]);
 const tr=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.4,0.6,1,5),trunkM,spots.length),lf=new THREE.InstancedMesh(new THREE.SphereGeometry(1,7,5),leafM,spots.length);
 const d=new THREE.Object3D();spots.forEach(([x,z,h],i)=>{d.position.set(x,h*0.25,z);d.scale.set(1,h*0.5,1);d.updateMatrix();tr.setMatrixAt(i,d.matrix);d.position.set(x,h*0.7,z);d.scale.set(h*0.42,h*0.34,h*0.42);d.updateMatrix();lf.setMatrixAt(i,d.matrix);});
 tr.castShadow=lf.castShadow=true;scene.add(tr,lf);ctx.trees=spots.length;}
// ===== stages/03-blocks.js =====
// ---------- blocks: every grid cell becomes lots; towers rise with the skyline field and light up at night ----------
await stage('blocks');
// window textures: the facade (light ground, dark panes) and what glows at night (only the panes)
function winTex(glow){const cv=document.createElement('canvas');cv.width=cv.height=64;const g=cv.getContext('2d');g.fillStyle=glow?'#000':'#f2f0ec';g.fillRect(0,0,64,64);
  const R=mkRng(glow?5:9);for(let j=0;j<4;j++)for(let i=0;i<4;i++){const lit=R()<0.55;g.fillStyle=glow?(lit?`rgb(${230+R()*25},${200+R()*40},${140+R()*60})`:'#000'):`rgb(${40+R()*30},${52+R()*30},${70+R()*30})`;g.fillRect(i*16+3,j*16+2,9,11);}
  const t=new THREE.CanvasTexture(cv);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t;}
const facadeTex=winTex(false),glowTex=winTex(true);
const bldMats={};   // one material per district: colour × window map, tiled in world units (a window bay every 4 m)
function bldMat(d){if(bldMats[d.key])return bldMats[d.key];const m=new THREE.MeshLambertMaterial({color:d.color,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});m.color.multiplyScalar(1.15);setEnv(m,{K:0.25,id:'bld'+d.key});bldMats[d.key]=m;return m;}
const lots=[];   // {x,z,w,dpt,h,ry,kind,district}
const boxG=new THREE.BoxGeometry(1,1,1);boxG.translate(0,0.5,0);
const LOOP_C={x:0,z:-100};
function skyline(d,x,z){const dist=Math.hypot(x-LOOP_C.x,z-LOOP_C.z),f=Math.pow(Math.max(0,1-dist/1700),1.5),n=0.35+0.65*fbm(x*0.004+3,z*0.004+9);return d.base+(d.tall-d.base)*f*n;}
const lmFoot=C.landmarks.map(l=>({x:l.x,z:l.z,r:Math.max(l.w||40,l.d||40,l.kind==='pier'?0:0)*0.75+20}));
const nearLandmark=(x,z)=>lmFoot.some(f=>Math.hypot(f.x-x,f.z-z)<f.r);
const elBand=(x,z)=>(Math.abs(x-EL.east)<14||Math.abs(x-EL.west)<14)&&z>EL.north-14&&z<EL.south+14||(Math.abs(z-EL.north)<14||Math.abs(z-EL.south)<14)&&x>EL.west-14&&x<EL.east+14;
section('blocks',()=>{
  const half=GRID.street/2;
  for(let bx=-WORLD/2;bx<SHORE-GRID.pitchX;bx+=GRID.pitchX)for(let bz=-WORLD/2;bz<WORLD/2-GRID.pitchZ;bz+=GRID.pitchZ){
    const cx=bx+GRID.pitchX/2,cz=bz+GRID.pitchZ/2;
    if(inWater(cx,cz)||parkAt(cx,cz)||nearLandmark(cx,cz))continue;
    if(cx>C.beach.x0-60&&cz>C.beach.z0&&cz<C.beach.z1)continue;
    // shrink the block away from wide streets and the river
    let x0=bx+half,x1=bx+GRID.pitchX-half,z0=bz+half,z1=bz+GRID.pitchZ-half;
    for(const m of MAJOR){const e=m.w/2+2;if(m.axis==='x'){if(m.at>x0-half&&m.at<x1+half){if(m.at<cx)x0=Math.max(x0,m.at+e);else x1=Math.min(x1,m.at-e);}}else{if(m.at>z0-half&&m.at<z1+half){if(m.at<cz)z0=Math.max(z0,m.at+e);else z1=Math.min(z1,m.at-e);}}}
    if(inRiver(x0,cz)||inRiver(x1,cz)||inRiver(cx,z0)||inRiver(cx,z1)||x1-x0<30||z1-z0<30)continue;
    const d=districtAt(cx,cz),H=skyline(d,cx,cz);
    // lots: one tower on a corner, or two to four buildings filling the block
    const n=H>90?1+(rnd()<0.35?1:0):H>35?2+Math.floor(rnd()*2):4;
    const cols=n>=3?2:n,rows=Math.ceil(n/cols);
    for(let k=0;k<n;k++){const i=k%cols,j=Math.floor(k/cols);const w=(x1-x0)/cols,dd=(z1-z0)/rows;const gx=x0+i*w,gz=z0+j*dd;
      const inset=H>90?w*0.12:2+rnd()*3,w2=w-2*inset,d2=dd-2*inset;if(w2<8||d2<8)continue;
      let h=H*(0.55+0.9*rnd());if(k>0&&H>90)h*=0.35;h=Math.max(6,Math.min(h,d.tall*1.1));
      if(elBand(gx+w/2,gz+dd/2))h=Math.min(h,d.base*0.8);
      lots.push({x:gx+w/2,z:gz+dd/2,w:w2,dpt:d2,h,ry:0,kind:h>120?'tower':h>35?'midrise':'low',district:d,fixed:false});}}
  ctx.lots=lots.length;ctx.lotList=lots;
  // geometry: towers get setbacks, everything gets a roof box now and then
  const byD={};for(const l of lots){(byD[l.district.key]=byD[l.district.key]||[]).push(l);}
  const dm=new THREE.Object3D();let total=0;
  for(const key in byD){const L=byD[key],parts=[];
    for(const l of L){if(l.kind==='tower'){const tiers=2+Math.floor(rnd()*2);let y=0,w=l.w,d=l.dpt;for(let t=0;t<tiers;t++){const hh=l.h*(t===tiers-1?0.35:0.65/(tiers-1));parts.push([l.x,y,l.z,w,hh,d]);y+=hh;w*=0.78;d*=0.78;}}
      else parts.push([l.x,0,l.z,l.w,l.h,l.dpt]);
      if(rnd()<0.5)parts.push([l.x+(rnd()-0.5)*l.w*0.3,l.h,l.z+(rnd()-0.5)*l.dpt*0.3,Math.max(3,l.w*0.25),2+rnd()*3,Math.max(3,l.dpt*0.25)]);}
    const im=new THREE.InstancedMesh(boxG,bldMat(DIST[key]),parts.length),tint=new THREE.Color();
    parts.forEach((p,i)=>{dm.position.set(p[0],p[1],p[2]);dm.scale.set(p[3],p[4],p[5]);dm.updateMatrix();im.setMatrixAt(i,dm.matrix);
      const k=hash3(p[0],p[2],5);tint.setHSL(0.55+0.5*hash3(p[0],p[2],6),k<0.5?0.05:0.25,0.62+0.5*hash3(p[0],p[2],7));im.setColorAt(i,tint);});   // every building its own shade: glass, stone, brick
    im.castShadow=im.receiveShadow=true;im.userData.district=key;scene.add(im);total+=parts.length;}
  ctx.details={buildings:total,lots:lots.length};
});
// windows come on at dusk
animHooks.push(()=>{const w=windowF(hourCur);for(const k in bldMats)bldMats[k].emissive.setRGB(w,w*0.92,w*0.8);});
// ===== stages/04-landmarks.js =====
// ---------- landmarks: parametric massing for the buildings everyone knows ----------
await stage('landmarks');
const LANDMARKS=[];   // meshes with userData.info, for the click card
const glassM=new THREE.MeshLambertMaterial({color:0x4a6a8a,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(glassM,{K:0.25,id:'lmglass'});
const darkM=new THREE.MeshLambertMaterial({color:0x2c3038,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(darkM,{K:0.25,id:'lmdark'});
const lmMats=[glassM,darkM];
function lmMat(hex){if(!hex)return glassM;const m=new THREE.MeshLambertMaterial({color:parseInt(hex.slice(1),16),map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(m,{K:0.25,id:'lm'+hex});lmMats.push(m);return m;}
const chromeM=new THREE.MeshPhongMaterial({color:0xdde4ea,specular:0xffffff,shininess:120});
function reg(mesh,L){mesh.userData.info=L;mesh.castShadow=mesh.receiveShadow=true;LANDMARKS.push(mesh);scene.add(mesh);return mesh;}
function box(x,y,z,w,h,d,m){const b=new THREE.Mesh(boxG,m);b.position.set(x,y,z);b.scale.set(w,h,d);return b;}
function group(L,parts){const g=new THREE.Group();for(const p of parts){p.castShadow=p.receiveShadow=true;p.userData.info=L;g.add(p);}g.userData.info=L;LANDMARKS.push(g);scene.add(g);return g;}
const KINDS={
  bundle(L){const m=darkM,t=L.w/3,H=L.h,levels=[[0,0,1],[1,0,.92],[2,0,.62],[0,1,.62],[1,1,1],[2,1,.83],[0,2,.46],[1,2,.62],[2,2,.46]];   // nine tubes, the taller ones at the core
    return group(L,levels.map(([i,j,f])=>box(L.x-L.w/2+t*(i+.5),0,L.z-L.w/2+t*(j+.5),t-0.6,H*f,t-0.6,m)).concat([box(L.x-8,H,L.z-8,2,80,2,steelM),box(L.x+8,H,L.z+8,2,70,2,steelM)]));},
  taper(L){const g=new THREE.Mesh(new THREE.CylinderGeometry(1,1.6,1,4,1),darkM);g.geometry.translate(0,0.5,0);g.rotation.y=Math.PI/4;g.position.set(L.x,0,L.z);g.scale.set(L.w*0.72,L.h,L.d*0.72);
    const g2=group(L,[g,box(L.x-9,L.h,L.z,1.6,110,1.6,steelM),box(L.x+9,L.h,L.z,1.6,110,1.6,steelM)]);   // X-braces: four thin diagonals a side
    for(const s of [-1,1])for(let k=0;k<5;k++){const br=box(L.x+s*(L.w*0.36-k*L.w*0.03),k*L.h/5,L.z,1.2,L.h/5*1.06,L.d*0.7,steelM);br.rotation.z=s*0.22;br.userData.info=L;g2.add(br);}return g2;},
  setbacks(L){const H=L.h,steps=[[1,1,0.3],[0.8,0.85,0.35],[0.62,0.7,0.35]];let y=0;const parts=[];for(const [fw,fd,fh] of steps){parts.push(box(L.x+(1-fw)*L.w/2*0.5,y,L.z,L.w*fw,H*fh,L.d*fd,glassM));y+=H*fh;}
    if(L.spire)parts.push(box(L.x,H,L.z,2,L.spire,2,chromeM));return group(L,parts);},
  box(L){return reg(box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),L);},
  stacked(L){const parts=[];const stems=[[0,-L.d/3,0.62],[0,0,1],[0,L.d/3,0.8]];for(const [dx,dz,f] of stems){let y=0;for(let k=0;k<7;k++){const hh=L.h*f/7;const fr=new THREE.Mesh(new THREE.CylinderGeometry(0.5*(k%2?0.8:1.1),0.5*(k%2?1.1:0.8),1,4,1),glassM);fr.geometry.translate(0,0.5,0);fr.rotation.y=Math.PI/4;fr.position.set(L.x+dx,y,L.z+dz);fr.scale.set(L.w*0.85,hh,L.d/3*1.05);parts.push(fr);y+=hh;}}return group(L,parts);},
  crown(L){const parts=[box(L.x,0,L.z,L.w,L.h*0.7,L.d,glassM),box(L.x,L.h*0.7,L.z,L.w*0.8,L.h*0.16,L.d*0.8,glassM),box(L.x,L.h*0.86,L.z,L.w*0.55,L.h*0.14,L.d*0.55,glassM),box(L.x,L.h,L.z,1.5,L.h*0.2,1.5,chromeM)];return group(L,parts);},
  twin(L){const parts=[];for(const s of [-1,1]){const c=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,24,1),lmMat('#c9c2b4'));c.geometry.translate(0,0.5,0);c.position.set(L.x+s*L.gap/2,0,L.z);c.scale.set(L.w/2,L.h,L.w/2);parts.push(c);
      for(let k=0;k<12;k++){const r=new THREE.Mesh(new THREE.TorusGeometry(1,0.04,4,24),darkM);r.rotation.x=Math.PI/2;r.position.set(L.x+s*L.gap/2,L.h*(0.3+k*0.058),L.z);r.scale.setScalar(L.w/2*1.04);parts.push(r);}}return group(L,parts);},
  slab(L){return group(L,[box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),box(L.x,L.h,L.z,L.w*0.25,L.tower||20,L.d*0.4,lmMat(L.color))]);},
  deco(L){const m=lmMat(L.color),parts=[];const steps=[[1,1,0.5],[0.7,0.8,0.25],[0.45,0.55,0.18]];let y=0;for(const [fw,fd,fh] of steps){parts.push(box(L.x,y,L.z,L.w*fw,L.h*fh,L.d*fd,m));y+=L.h*fh;}parts.push(box(L.x,y,L.z,4,L.h*0.09,4,chromeM));return group(L,parts);},
  crowncyl(L){const c=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,20,1),new THREE.MeshLambertMaterial({color:0xe8f0ff,emissive:0x8fb4e0,emissiveIntensity:0.5,transparent:true,opacity:0.8}));c.geometry.translate(0,0.5,0);c.position.set(L.x,L.h*0.89,L.z);c.scale.set(L.w*0.36,L.h*0.11,L.w*0.36);
    return group(L,[box(L.x,0,L.z,L.w,L.h*0.89,L.d,lmMat(L.color)),c]);},
  gothic(L){const m=lmMat(L.color),parts=[box(L.x,0,L.z,L.w,L.h*0.72,L.d,m),box(L.x,L.h*0.72,L.z,L.w*0.7,L.h*0.28,L.d*0.7,m)];for(let k=0;k<8;k++){const a=k/8*Math.PI*2;parts.push(box(L.x+Math.cos(a)*L.w*0.34,L.h*0.72,L.z+Math.sin(a)*L.d*0.34,2.4,L.h*0.36,2.4,m));}return group(L,parts);},
  clocktower(L){const m=lmMat(L.color);return group(L,[box(L.x,0,L.z,L.w,L.h*0.6,L.d,m),box(L.x,L.h*0.6,L.z+L.d*0.2,L.w*0.5,L.h*0.3,L.w*0.5,m),box(L.x,L.h*0.9,L.z+L.d*0.2,L.w*0.3,L.h*0.1,L.w*0.3,m)]);},
  diamond(L){const top=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),glassM);top.geometry.translate(0,0.5,0);top.position.set(L.x,L.h*0.78,L.z);top.rotation.z=0;top.scale.set(L.w,L.h*0.22,L.d*0.5);
    const wedge=new THREE.Mesh(new THREE.CylinderGeometry(0,1,1,4,1),glassM);wedge.geometry.translate(0,0.5,0);wedge.rotation.y=Math.PI/4;wedge.position.set(L.x,L.h*0.78,L.z);wedge.scale.set(L.w*0.75,L.h*0.22,L.d*0.75);
    return group(L,[box(L.x,0,L.z,L.w,L.h*0.78,L.d,glassM),wedge]);},
  ypoint(L){const parts=[];for(let k=0;k<3;k++){const a=k/3*Math.PI*2+0.5;const wing=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,16,1,false,0,Math.PI*0.55),darkM);wing.geometry.translate(0,0.5,0);wing.rotation.y=a;wing.position.set(L.x,0,L.z);wing.scale.set(L.w*0.55,L.h,L.w*0.55);parts.push(wing);}
    const core=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,12,1),darkM);core.geometry.translate(0,0.5,0);core.position.set(L.x,0,L.z);core.scale.set(L.w*0.22,L.h,L.w*0.22);parts.push(core);return group(L,parts);},
  watertower(L){const m=lmMat(L.color);const parts=[box(L.x,0,L.z,L.w*2.2,L.h*0.3,L.w*2.2,m),box(L.x,L.h*0.3,L.z,L.w,L.h*0.6,L.w,m)];const cap=new THREE.Mesh(new THREE.ConeGeometry(0.7,1,4),m);cap.geometry.translate(0,0.5,0);cap.position.set(L.x,L.h*0.9,L.z);cap.scale.set(L.w,L.h*0.1,L.w);parts.push(cap);return group(L,parts);},
  bean(L){const b=new THREE.Mesh(new THREE.SphereGeometry(1,32,20),chromeM);b.position.set(L.x,L.h*0.55,L.z);b.scale.set(L.w/2,L.h*0.45,L.d/2);const base=box(L.x,0,L.z,L.w*1.6,0.4,L.d*1.8,stoneM);return group(L,[b,base]);},
  fountain(L){const parts=[];for(let k=0;k<3;k++){const r=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,28,1),stoneM);r.geometry.translate(0,0.5,0);r.position.set(L.x,k*2.2,L.z);r.scale.set(L.w/2*(1-k*0.3),2.2,L.w/2*(1-k*0.3));parts.push(r);}
    const jet=new THREE.Mesh(new THREE.CylinderGeometry(0.6,2.5,1,10,1),waterM);jet.geometry.translate(0,0.5,0);jet.position.set(L.x,6,L.z);jet.scale.set(1,30,1);parts.push(jet);const g=group(L,parts);animHooks.push(now=>{jet.scale.y=18+14*Math.max(0,Math.sin(now*0.0007));});return g;},
  lowrise(L){return reg(box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),L);},
  stadium(L){const parts=[];const ring=new THREE.Mesh(new THREE.CylinderGeometry(1,1.1,1,32,1,true),stoneM);ring.geometry.translate(0,0.5,0);ring.position.set(L.x,0,L.z);ring.scale.set(L.w/2,L.h,L.d/2);ring.material=stoneM.clone();ring.material.side=THREE.DoubleSide;parts.push(ring);
    for(const s of [-1,1])for(let k=0;k<12;k++){parts.push(box(L.x+s*(L.w/2+8),0,L.z-L.d*0.4+k*L.d*0.8/11,3,L.h*0.55,3,stoneM));}return group(L,parts);},
  pier(L){const parts=[];const wheel=new THREE.Group();const rim=new THREE.Mesh(new THREE.TorusGeometry(PIER.wheelR,1.2,6,48),steelM);wheel.add(rim);
    for(let k=0;k<12;k++){const a=k/12*Math.PI*2;const sp=box(0,0,0,1,PIER.wheelR*2,1,steelM);sp.position.set(0,0,0);sp.rotation.z=a;sp.geometry=new THREE.BoxGeometry(1,1,1);sp.scale.set(0.8,PIER.wheelR*2,0.8);wheel.add(sp);
      const car=new THREE.Mesh(new THREE.SphereGeometry(2.4,8,6),new THREE.MeshLambertMaterial({color:0xe8f0ff}));car.position.set(Math.cos(a)*PIER.wheelR,Math.sin(a)*PIER.wheelR,0);wheel.add(car);}
    wheel.position.set(PIER.wheelX,PIER.wheelR+6,PIER.z);wheel.rotation.y=Math.PI/2;wheel.userData.info=L;parts.push(wheel);
    for(const s of [-1,1]){const leg=box(PIER.wheelX,4,PIER.z+s*10,3,PIER.wheelR+2,3,steelM);leg.rotation.x=s*0.16;parts.push(leg);}
    const g=group(L,parts);animHooks.push(now=>{wheel.rotation.x=now*0.00012;});return g;},
};
section('landmarks',()=>{for(const L of C.landmarks){const f=KINDS[L.kind];if(!f){report('landmark '+L.name,new Error('unknown kind '+L.kind));continue;}try{f(L);}catch(e){report('landmark '+L.name,e);}}
  // warning beacons on the tallest roofs
  const beacons=[];for(const L of C.landmarks)if(L.h>250){const b=new THREE.Mesh(new THREE.SphereGeometry(2,8,6),new THREE.MeshBasicMaterial({color:0xff2020}));b.position.set(L.x,L.h+(L.kind==='bundle'?80:L.kind==='taper'?110:L.spire||8),L.z);scene.add(b);beacons.push(b);}
  animHooks.push(now=>{const on=(now%1600)<800;for(const b of beacons)b.visible=on||hourCur<6||hourCur>18;});
  ctx.details.landmarks=LANDMARKS.length;});
animHooks.push(()=>{const w=windowF(hourCur);for(const m of lmMats)m.emissive.setRGB(w,w*0.92,w*0.8);});
// ===== stages/05-el.js =====
// ---------- the L: the Loop's elevated tracks on their columns, and the trains that circle them ----------
await stage('el');
section('el',()=>{
  const H=EL.height,W=EL.east-EL.west,D=EL.south-EL.north,cx=(EL.east+EL.west)/2,cz=(EL.north+EL.south)/2;
  const rail=(x,z,w,d)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(w,1.2,d),steelM);b.position.set(x,H,z);b.castShadow=true;scene.add(b);};
  rail(cx,EL.north,W+12,12);rail(cx,EL.south,W+12,12);rail(EL.west,cz,12,D);rail(EL.east,cz,12,D);
  // columns every 15 m, in the street
  const cols=[];for(let x=EL.west;x<=EL.east;x+=15){cols.push([x,EL.north]);cols.push([x,EL.south]);}for(let z=EL.north+15;z<EL.south;z+=15){cols.push([EL.west,z]);cols.push([EL.east,z]);}
  const cm=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.5,0.6,1,6),steelM,cols.length*2),d=new THREE.Object3D();
  cols.forEach(([x,z],i)=>{for(const s of [-1,1]){const on=Math.abs(z-EL.north)<1||Math.abs(z-EL.south)<1;d.position.set(x+(on?0:s*5),H/2,z+(on?s*5:0));d.scale.set(1,H,1);d.updateMatrix();cm.setMatrixAt(i*2+(s>0?1:0),d.matrix);}});
  cm.castShadow=true;scene.add(cm);
  // trains: EL.trains of EL.cars cars, half each way, on the perimeter
  const P=2*(W+D),carL=15,carG=1.2,N=EL.trains*EL.cars;
  const carM=new THREE.MeshLambertMaterial({color:0xd8dde3,emissive:0x000000}),tm=new THREE.InstancedMesh(new THREE.BoxGeometry(carL,3.4,3.2),carM,N);tm.castShadow=true;tm.userData.life=true;scene.add(tm);
  const trains=[];for(let t=0;t<EL.trains;t++)trains.push({s:t*P/EL.trains,dir:t%2?1:-1,v:11+t*0.7,stop:0});
  const at=(s,side)=>{s=((s%P)+P)%P;const o=side*4;   // a point on the rectangle, offset to the inner or outer track
    if(s<W)return [EL.west+s,EL.north+o,0];s-=W;if(s<D)return [EL.east-o,EL.north+s,Math.PI/2];s-=D;if(s<W)return [EL.east-s,EL.south-o,0];s-=W;return [EL.west+o,EL.south-s,Math.PI/2];};
  let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;let i=0;
    for(const tr of trains){if(tr.stop>0)tr.stop-=dt;else{tr.s+=tr.dir*tr.v*dt;if(Math.floor(tr.s/ (P/8))!==Math.floor((tr.s-tr.dir*tr.v*dt)/(P/8)))tr.stop=3+Math.random()*2;}   // a short stop every eighth of the loop
      for(let c=0;c<EL.cars;c++){const [x,z,a]=at(tr.s-tr.dir*c*(carL+carG),tr.dir);d.position.set(x,H+2.4,z);d.rotation.set(0,a,0);d.scale.set(1,1,1);d.updateMatrix();tm.setMatrixAt(i++,d.matrix);}}
    tm.instanceMatrix.needsUpdate=true;const w=windowF(hourCur);carM.emissive.setRGB(w*0.9,w*0.85,w*0.6);});
  ctx.details.trains=EL.trains;
});
// ===== stages/06-traffic.js =====
// ---------- traffic: cars on the wide streets, tour boats on the river, sails on the lake ----------
await stage('traffic');
section('traffic',()=>{
  const lanes=[];for(const m of MAJOR){const len=m.axis==='x'?WORLD:SHORE+WORLD/2;const n=Math.floor(len/38);for(const dir of [-1,1])lanes.push({m,dir,n,len,off:dir*(m.w/4)});}
  const cars=[];for(const ln of lanes)for(let k=0;k<ln.n;k++)cars.push({ln,s:xr()*ln.len,v:9+xr()*7,col:new THREE.Color().setHSL(xr(),0.5,0.35+xr()*0.35)});
  const cm=new THREE.InstancedMesh(new THREE.BoxGeometry(4.4,1.5,2),new THREE.MeshLambertMaterial({color:0xffffff}),cars.length),d=new THREE.Object3D();
  cars.forEach((c,i)=>cm.setColorAt(i,c.col));cm.userData.life=true;cm.userData.noShadow=true;scene.add(cm);
  const carPos=c=>{const m=c.ln.m,s=((c.s%c.ln.len)+c.ln.len)%c.ln.len;if(m.axis==='x')return [m.at+c.ln.off,s-WORLD/2,Math.PI/2];return [s-WORLD/2,m.at+c.ln.off,0];};
  let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;
    for(let i=0;i<cars.length;i++){const c=cars[i];c.s+=c.ln.dir*c.v*dt;const [x,z,a]=carPos(c);const y=inRiver(x,z)?5.5:0.8;d.position.set(x,y,z);d.rotation.set(0,a,0);d.updateMatrix();cm.setMatrixAt(i,d.matrix);}
    cm.instanceMatrix.needsUpdate=true;});
  // boats: tour boats along the main stem, sailboats out on the lake
  const boatM=new THREE.MeshLambertMaterial({color:0xf0ede6}),sailM=new THREE.MeshLambertMaterial({color:0xffffff,side:THREE.DoubleSide});
  const boats=[];for(let k=0;k<5;k++){const b=new THREE.Mesh(new THREE.BoxGeometry(24,3,6),boatM);b.position.y=1.2;const top=new THREE.Mesh(new THREE.BoxGeometry(16,2,4),new THREE.MeshLambertMaterial({color:0x3a5f8a}));top.position.set(-2,2.5,0);b.add(top);b.castShadow=true;scene.add(b);boats.push({m:b,s:k*300+xr()*200,dir:k%2?1:-1,v:4+xr()*2});}
  const sails=[];for(let k=0;k<14;k++){const g=new THREE.Group();const hull=new THREE.Mesh(new THREE.BoxGeometry(8,1.6,2.6),boatM);hull.position.y=0.6;const sail=new THREE.Mesh(new THREE.ConeGeometry(2.5,11,3),sailM);sail.position.set(0.5,7,0);g.add(hull,sail);scene.add(g);
    sails.push({g,x:SHORE+120+xr()*800,z:-1700+xr()*3000,a:xr()*6.28,v:1.5+xr()*2});}
  let lastB=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-lastB)/1000);lastB=now;
    for(const b of boats){b.s+=b.dir*b.v*dt;const span=RM.xEast-RM.xWest-120;if(b.s>span){b.s=span;b.dir=-1;}if(b.s<0){b.s=0;b.dir=1;}b.m.position.set(RM.xWest+60+b.s,1.2,RM.z+(b.dir>0?-12:12));b.m.rotation.y=b.dir>0?0:Math.PI;}
    for(const s of sails){s.a+=(xr()-0.5)*0.4*dt;s.x+=Math.cos(s.a)*s.v*dt;s.z+=Math.sin(s.a)*s.v*dt;if(s.x<SHORE+80)s.a=0;if(s.x>WORLD/2-80)s.a=Math.PI;if(s.z<-WORLD/2+80)s.a=Math.PI/2;if(s.z>WORLD/2-80)s.a=-Math.PI/2;
      if(s.x<PIER.x+PIER.length+30&&Math.abs(s.z-PIER.z)<PIER.width/2+30)s.z+=(s.z<PIER.z?-1:1)*20*dt;s.g.position.set(s.x,0.3+Math.sin(now*0.002+s.x)*0.15,s.z);s.g.rotation.y=-s.a;s.g.rotation.z=0.12*Math.sin(now*0.0015+s.z);}});
  ctx.details.cars=cars.length;ctx.details.boats=boats.length+sails.length;
});
// ===== stages/07-ui.js =====
// ---------- camera, views, the clock, the card, the render loop ----------
await stage('ui');
const el=renderer.domElement;
// orbit camera: drag to orbit, right/shift-drag or two fingers to pan, wheel/pinch to zoom, WASD/QE to move the target
const ctl={target:new THREE.Vector3(0,40,0),az:0.6,el:0.5,dist:1400,goal:null};
function applyCam(){const e=Math.max(0.03,Math.min(1.5,ctl.el));camera.position.set(ctl.target.x+Math.cos(ctl.az)*Math.cos(e)*ctl.dist,ctl.target.y+Math.sin(e)*ctl.dist,ctl.target.z+Math.sin(ctl.az)*Math.cos(e)*ctl.dist);camera.lookAt(ctl.target);}
function setView(px,py,pz,tx,ty,tz,fly){const t=new THREE.Vector3(tx,ty,tz),p=new THREE.Vector3(px,py,pz),d=p.clone().sub(t);const goal={target:t,az:Math.atan2(d.z,d.x),el:Math.atan2(d.y,Math.hypot(d.x,d.z)),dist:d.length()};
  if(fly===false||matchMedia('(prefers-reduced-motion: reduce)').matches){Object.assign(ctl,goal);ctl.goal=null;return;}ctl.goal=Object.assign(goal,{t0:performance.now(),from:{target:ctl.target.clone(),az:ctl.az,el:ctl.el,dist:ctl.dist}});}
const ptrs=new Map();let pinch0=0,dist0=0;
el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);ptrs.set(e.pointerId,{x:e.clientX,y:e.clientY,b:e.button,sh:e.shiftKey,moved:0});if(ptrs.size===2){const [a,b]=[...ptrs.values()];pinch0=Math.hypot(a.x-b.x,a.y-b.y);dist0=ctl.dist;}});
el.addEventListener('pointermove',e=>{const p=ptrs.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;p.moved+=Math.abs(dx)+Math.abs(dy);ctl.goal=null;
  if(ptrs.size===2){const [a,b]=[...ptrs.values()];const pd=Math.hypot(a.x-b.x,a.y-b.y);ctl.dist=Math.max(30,Math.min(6000,dist0*pinch0/pd));pan(dx/2,dy/2);return;}
  if(p.b===2||p.sh)pan(dx,dy);else{ctl.az+=dx*0.005;ctl.el=Math.max(0.03,Math.min(1.5,ctl.el+dy*0.005));}});
const endPtr=e=>{const p=ptrs.get(e.pointerId);ptrs.delete(e.pointerId);if(p&&p.moved<6&&e.type==='pointerup'&&p.b===0)clickAt(e.clientX,e.clientY);};
el.addEventListener('pointerup',endPtr);el.addEventListener('pointercancel',endPtr);el.addEventListener('contextmenu',e=>e.preventDefault());
function pan(dx,dy){const k=ctl.dist*0.0016;const fx=Math.cos(ctl.az),fz=Math.sin(ctl.az);ctl.target.x+=(-dx*fz+dy*fx)*k*-1;ctl.target.z+=(dx*fx+dy*fz)*k*-1;}
el.addEventListener('wheel',e=>{e.preventDefault();ctl.goal=null;ctl.dist=Math.max(30,Math.min(6000,ctl.dist*Math.exp(e.deltaY*0.0012)));},{passive:false});
const keys=new Set();addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;keys.add(e.key.toLowerCase());if(e.key==='Escape')closeCard();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function applyKeys(){if(!keys.size)return;const s=ctl.dist*0.012,fx=Math.cos(ctl.az),fz=Math.sin(ctl.az);let mx=0,mz=0;if(keys.has('w'))mx-=1;if(keys.has('s'))mx+=1;if(keys.has('a'))mz+=1;if(keys.has('d'))mz-=1;
  ctl.target.x+=(mx*fx-mz*fz)*s;ctl.target.z+=(mx*fz+mz*fx)*s;if(keys.has('q'))ctl.target.y=Math.max(0,ctl.target.y-s);if(keys.has('e'))ctl.target.y+=s;if(mx||mz||keys.has('q')||keys.has('e'))ctl.goal=null;}
function stepFly(now){const g=ctl.goal;if(!g)return;const u=Math.min(1,(now-g.t0)/1400),k=u*u*(3-2*u);ctl.target.lerpVectors(g.from.target,g.target,k);let da=g.az-g.from.az;da=Math.atan2(Math.sin(da),Math.cos(da));ctl.az=g.from.az+da*k;ctl.el=g.from.el+(g.el-g.from.el)*k;ctl.dist=g.from.dist+(g.dist-g.from.dist)*k;if(u>=1)ctl.goal=null;}
// the panels: viewpoints, the clock, a card for the landmark you click
const ui=document.getElementById('ui'),viewsEl=document.getElementById('views'),card=document.getElementById('card'),side=document.getElementById('side');
const VIEWS={};for(const k in C.views)VIEWS[k]=dataValue(C.views[k],{...C,...DATA_FN});
const mkBtn=(label,parent,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;parent.appendChild(b);return b;};
const viewsBtn=mkBtn('Views',ui,()=>{const open=!viewsEl.classList.contains('open');viewsEl.classList.toggle('open',open);viewsBtn.setAttribute('aria-expanded',String(open));});viewsBtn.setAttribute('aria-expanded','false');
{const h=document.createElement('div');h.className='sub';h.textContent='Viewpoints';viewsEl.appendChild(h);for(const k in VIEWS)mkBtn(k,viewsEl,()=>{setView(...VIEWS[k]);viewsEl.classList.remove('open');viewsBtn.setAttribute('aria-expanded','false');});}
const pauseBtn=mkBtn('Pause sun',ui,()=>{if(!clockPaused){clockPaused=true;pausedAt=performance.now()-clockOffset;pauseBtn.textContent='Resume sun';}else{clockPaused=false;clockOffset=performance.now()-pausedAt;pauseBtn.textContent='Pause sun';}});
const tw=document.createElement('div');tw.id='timebar';tw.innerHTML='<label for="tslider" id="tlabel">10:30</label><input id="tslider" type="range" min="0" max="24" step="0.05" value="10.5" aria-label="Time of day"><select id="daylen" aria-label="Length of a day"><option value="120">day 2 min</option><option value="240" selected>day 4 min</option><option value="720">day 12 min</option></select>';side.appendChild(tw);
const tsl=document.getElementById('tslider'),tlab=document.getElementById('tlabel'),dsel=document.getElementById('daylen');let dragging=false;
tsl.addEventListener('pointerdown',()=>{dragging=true;});addEventListener('pointerup',()=>{dragging=false;});tsl.addEventListener('input',()=>setHour(parseFloat(tsl.value)));
dsel.addEventListener('change',()=>{const h=hourCur;DAY=+dsel.value;setHour(h);});
const hud=document.createElement('pre');hud.id='hud';side.appendChild(hud);let hudT=0,tbTxt='';
animHooks.push(now=>{if(now-hudT<200)return;hudT=now;const h=hourCur,t=`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.floor((h%1)*60)).padStart(2,'0')}`;if(!dragging)tsl.value=h.toFixed(2);if(t!==tbTxt){tbTxt=t;tlab.textContent=t;}
  hud.textContent=`${t}\ntarget  x ${ctl.target.x.toFixed(0)}  z ${ctl.target.z.toFixed(0)}\n${districtAt(ctl.target.x,ctl.target.z).name}`+(RES.cur<RES.max-0.01?`\nrender  ×${RES.cur.toFixed(2)}`:'');});
const ray=new THREE.Raycaster(),ndc=new THREE.Vector2();
function clickAt(cx,cy){ndc.set(cx/innerWidth*2-1,-(cy/innerHeight)*2+1);ray.setFromCamera(ndc,camera);const hits=ray.intersectObjects(LANDMARKS,true);if(!hits.length){closeCard();return;}
  let o=hits[0].object,info=null;while(o&&!info){info=o.userData.info;o=o.parent;}if(!info)return;showCard(info);}
function showCard(L){card.innerHTML='';const h=document.createElement('h2');h.textContent=L.name;const p=document.createElement('p');p.textContent=L.info||'';const b=document.createElement('button');b.type='button';b.textContent='Close';b.onclick=closeCard;card.append(h,p,b);card.classList.add('open');card.style.display='block';b.focus();}
function closeCard(){card.classList.remove('open');card.style.display='';}
// the address keeps the view and the hour, like the Iziz page: #v=px,py,pz,tx,ty,tz&t=hour
function stateToHash(){const r1=x=>Math.round(x*10)/10,p=camera.position,t=ctl.target;return '#'+(SEED0!==SEED_DEFAULT?'seed='+SEED0+'&':'')+'v='+[p.x,p.y,p.z,t.x,t.y,t.z].map(r1).join(',')+'&t='+(Math.round(hourCur*20)/20)+(clockPaused?'&paused':'');}
function readHash(){let q;try{q=new URLSearchParams(location.hash.slice(1));}catch(e){return false;}if(!q.has('v'))return false;const v=(q.get('v')||'').split(',').map(Number);if(v.length===6&&v.every(Number.isFinite))setView(...v,false);
  const t=parseFloat(q.get('t'));if(Number.isFinite(t))setHour(((t%24)+24)%24);if(q.has('paused')&&!clockPaused)pauseBtn.click();return true;}
let lastHash='',hashT=0;animHooks.push(now=>{if(now-hashT<1500||ctl.goal||ptrs.size)return;hashT=now;const h=stateToHash();if(h!==lastHash){lastHash=h;try{history.replaceState(null,'',h);}catch(e){}}});
if(!readHash())setView(...VIEWS['Skyline from the lake'],false);
{const hint=document.getElementById('hint');const hide=()=>hint.classList.add('gone');setTimeout(hide,12000);el.addEventListener('pointerdown',hide,{once:true});el.addEventListener('wheel',hide,{once:true,passive:true});}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);updatePx();});
if(SEED0!==SEED_DEFAULT)document.getElementById('seedtag').textContent='seed '+SEED0;
// shadows follow the target; compile everything behind the loading text
await stage('shaders');
section('shaders',()=>{applyCam();sun.target.position.copy(ctl.target);renderer.compile(scene,camera);renderer.render(scene,camera);});
stage('done');ctx.timings=LOAD.times;ctx.loadMs=Math.round(performance.now()-LOAD.t0);if(/debug/.test(location.search))console.table(LOAD.times);
document.getElementById('loading').remove();
renderer.shadowMap.autoUpdate=false;const shadowAt=new THREE.Vector3(1e9,0,0);let shadowTick=0;
function shadowsDue(){if(sun.intensity<=0.02)return false;if(ctl.target.distanceToSquared(shadowAt)>4){shadowAt.copy(ctl.target);sun.target.position.copy(ctl.target);sun.position.copy(ENV.izSunDir.value).multiplyScalar(2500).add(ctl.target);return true;}return (++shadowTick%3)===0;}
// adaptive resolution, as on the Iziz page
const RES={max:Math.min(devicePixelRatio,1.5),cur:Math.min(devicePixelRatio,1.5),min:0.6,acc:0,n:0,good:0,bad:0,prev:performance.now()};
function adaptRes(now){const dt=(now-RES.prev)/1000;RES.prev=now;if(dt>0.5||document.hidden)return;RES.acc+=dt;RES.n++;if(RES.acc<1)return;const fps=RES.n/RES.acc;RES.acc=0;RES.n=0;
  if(fps<45){RES.bad++;RES.good=0;}else if(fps>56){RES.good++;RES.bad=0;}let next=RES.cur;if(RES.bad>=2){next=Math.max(RES.min,RES.cur-0.15);RES.bad=0;}else if(RES.good>=8&&RES.cur<RES.max){next=Math.min(RES.max,RES.cur+0.1);RES.good=0;}
  if(Math.abs(next-RES.cur)>1e-3){RES.cur=+next.toFixed(2);renderer.setPixelRatio(RES.cur);renderer.setSize(innerWidth,innerHeight);updatePx();}}
ctx.res=RES;let fpsN=0,fpsT=performance.now(),renderErr=false;
(function animate(){requestAnimationFrame(animate);try{const now=performance.now();adaptRes(now);fpsN++;if(now-fpsT>1000){ctx.fps=fpsN;fpsN=0;fpsT=now;}
  for(const f of animHooks){try{f(now);}catch(e){if(!f._failed){f._failed=true;report('update',e);}}}stepFly(now);applyKeys();applyCam();if(shadowsDue())renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera);}catch(e){if(!renderErr){renderErr=true;report('render',e);}}})();
}
