// GENERATED by tools/build-page.py from src/chicago/stages/ (8 files, sources 31d3fd25ffc4047c).
// Do not edit: change the stage files and run ./sitectl build.
import {report,section,stage,LOAD} from '../core/diag.js';
import {createLcg,makeNoise,clamp,smooth,hash3,mkRng} from '../core/rng.js';
import {DATA_FN,dataValue,resolveCity} from '../core/data.js';
import {createEnv} from '../core/env.js';
export async function build(ctx){
// ===== stages/00-start.js =====
// ---------- start: three.js check, the city file, projection, randomness, where things are ----------
if(!window.THREE){document.getElementById('loading').textContent='three.js did not load (vendor/three/three.min.js). Check the site mounts and reload.';return;}
const THREE=window.THREE;
const CITY_ID=(()=>{const v=new URLSearchParams(location.search).get('city')||'';return /^[a-z0-9-]{1,40}$/.test(v)?v:'chicago';})();
ctx.cityId=CITY_ID;
const C=await fetch('data/cities/'+CITY_ID+'.json').then(r=>{if(!r.ok)throw new Error('data/cities/'+CITY_ID+'.json: HTTP '+r.status);return r.json();});
const SEED_DEFAULT=C.defaultSeed||1871;
const SEED0=(()=>{try{const v=parseInt(new URLSearchParams(location.search).get('seed')||new URLSearchParams(location.hash.slice(1)).get('seed'),10);return v>0&&v<2147483647?v:SEED_DEFAULT;}catch(e){return SEED_DEFAULT;}})();
const LCG=createLcg(SEED0);const rnd=LCG.rnd,rr=LCG.rr,pick=LCG.pick;
const {vn,fbm}=makeNoise(rnd);
const xr=mkRng(20261017),xrr=(a,b)=>a+(b-a)*xr();
const WORLD=C.WORLD,HALF=WORLD/2,animHooks=[];
// projection: metres east (x) and south (z) of the origin; good to a few metres across downtown
const [LAT0,LON0]=C.origin,M_LAT=111132,M_LON=111320*Math.cos(LAT0*Math.PI/180);
const lonX=lon=>(lon-LON0)*M_LON,latZ=lat=>-(lat-LAT0)*M_LAT;
const P=([lat,lon])=>[lonX(lon),latZ(lat)];
const toLatLon=(x,z)=>[LAT0-z/M_LAT,LON0+x/M_LON];
ctx.project=P;ctx.toLatLon=toLatLon;
// geometry helpers
function segDist(px,pz,ax,az,bx,bz){const dx=bx-ax,dz=bz-az,L=dx*dx+dz*dz;let t=L?((px-ax)*dx+(pz-az)*dz)/L:0;t=Math.max(0,Math.min(1,t));return Math.hypot(px-ax-t*dx,pz-az-t*dz);}
function pathDist(x,z,pts){let d=Infinity;for(let i=0;i+1<pts.length;i++)d=Math.min(d,segDist(x,z,pts[i][0],pts[i][1],pts[i+1][0],pts[i+1][1]));return d;}
function inPoly(x,z,poly){let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const [xi,zi]=poly[i],[xj,zj]=poly[j];if((zi>z)!==(zj>z)&&x<(xj-xi)*(z-zi)/(zj-zi)+xi)c=!c;}return c;}
function segHit(a,b,c,d){const r=[b[0]-a[0],b[1]-a[1]],s=[d[0]-c[0],d[1]-c[1]],den=r[0]*s[1]-r[1]*s[0];if(Math.abs(den)<1e-9)return null;
  const t=((c[0]-a[0])*s[1]-(c[1]-a[1])*s[0])/den,u=((c[0]-a[0])*r[1]-(c[1]-a[1])*r[0])/den;if(t<0||t>1||u<0||u>1)return null;return {x:a[0]+t*r[0],z:a[1]+t*r[1],r,s};}
// water: the lake is everything east of the shore line; rivers are thick polylines
const SHORE=C.shore.map(P);
const FAR=HALF+2000,LAKE_POLY=[[SHORE[0][0],-FAR],...SHORE,[SHORE[SHORE.length-1][0],FAR],[FAR,FAR],[FAR,-FAR]];   // shore north to south, then round the east side
const RIVERS=C.rivers.map(r=>({name:r.name,width:r.width,pts:r.path.map(P)}));
const PIER=(()=>{const b=P(C.pier.base),e=P(C.pier.end),w=P(C.pier.wheel);return {x0:b[0],x1:e[0],z:b[1],width:C.pier.width,wheelX:w[0],wheelR:C.pier.wheelR,length:e[0]-b[0]};})();
function onPier(x,z){return x>=PIER.x0-40&&x<=PIER.x1&&Math.abs(z-PIER.z)<=PIER.width/2;}
function inLake(x,z){return inPoly(x,z,LAKE_POLY)&&!onPier(x,z);}
function riverAt(x,z,pad){for(const r of RIVERS)if(pathDist(x,z,r.pts)<=r.width/2+(pad||0))return r;return null;}
const inRiver=(x,z)=>!!riverAt(x,z,0);
const inWater=(x,z)=>inLake(x,z)||inRiver(x,z);
// streets: named lists plus the regular Chicago grid filled in around them
const range=(r,a,b)=>r.length>4?[r[4],r[5]]:[a,b];
const STREETS=[];   // {name,w,major,a:[x,z],b:[x,z]} straight segments; diagonals are split into segments
for(const s of C.streetsNS){const [lat0,lat1]=range(s,-90,90);const x=lonX(s[1]);STREETS.push({name:s[0],w:s[2],major:!!s[3],a:[x,Math.max(-HALF,latZ(lat1))],b:[x,Math.min(HALF,latZ(lat0))],axis:'x',at:x});}
for(const s of C.streetsEW){const [lon0,lon1]=range(s,-180,180);const z=latZ(s[1]);STREETS.push({name:s[0],w:s[2],major:!!s[3],a:[Math.max(-HALF,lonX(lon0)),z],b:[Math.min(HALF,lonX(lon1)),z],axis:'z',at:z});}
{const F=C.fill,nsX=STREETS.filter(s=>s.axis==='x').map(s=>s.at),ewZ=STREETS.filter(s=>s.axis==='z').map(s=>s.at);
 for(let x=Math.round(-HALF/F.ns)*F.ns;x<=HALF;x+=F.ns)if(!nsX.some(v=>Math.abs(v-x)<F.ns*0.6))STREETS.push({name:'',w:F.street,major:false,a:[x,-HALF],b:[x,HALF],axis:'x',at:x,fill:true});
 for(let z=Math.round(-HALF/F.ew)*F.ew;z<=HALF;z+=F.ew)if(!ewZ.some(v=>Math.abs(v-z)<F.ew*0.45))STREETS.push({name:'',w:F.street,major:false,a:[-HALF,z],b:[HALF,z],axis:'z',at:z,fill:true});}
const DIAGONALS=C.diagonals.map(([name,w,path])=>({name,w,major:true,pts:path.map(P)}));
for(const d of DIAGONALS)for(let i=0;i+1<d.pts.length;i++)STREETS.push({name:d.name,w:d.w,major:true,a:d.pts[i],b:d.pts[i+1],axis:'d'});
function streetAt(x,z){for(const s of STREETS)if(segDist(x,z,s.a[0],s.a[1],s.b[0],s.b[1])<=s.w/2)return s;return null;}
// parks, beaches, districts
const PARKS=C.parks.map(p=>{const [la0,lo0,la1,lo1]=p.rect;return {name:p.name,x0:lonX(lo0),x1:lonX(lo1),z0:latZ(la1),z1:latZ(la0)};});
function parkAt(x,z){for(const p of PARKS)if(x>=p.x0&&x<=p.x1&&z>=p.z0&&z<=p.z1)return p;return null;}
const BEACHES=C.beaches.map(b=>({name:b.name,w:b.width,pts:b.path.map(P)}));
const DIST={},DIST_BOX=[];
for(const k in C.districts){if(k==='_')continue;const [name,col,base,tall,box]=C.districts[k];DIST[k]={key:k,name,color:parseInt(col.slice(1),16),base,tall};
  if(box)DIST_BOX.push([DIST[k],lonX(box[1]),lonX(box[3]),latZ(box[2]),latZ(box[0])]);}
function districtAt(x,z){for(const [d,x0,x1,z0,z1] of DIST_BOX)if(x>=x0&&x<=x1&&z>=z0&&z<=z1)return d;return DIST.outer;}
const SKY_C=P(C.skylineCentre);
const EL=(()=>{const e=C.el;return {north:latZ(e.north),south:latZ(e.south),east:lonX(e.east),west:lonX(e.west),height:e.height,trains:e.trains,cars:e.cars};})();
ctx.districtAt=districtAt;ctx.inWater=inWater;ctx.streets=STREETS.length;
// ===== stages/01-scene.js =====
// ---------- scene: renderer, camera, the sun's day, sky ----------
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(50,innerWidth/innerHeight,1,24000);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
document.body.appendChild(renderer.domElement);
const {ENV,setEnv}=createEnv();   // the shared uniforms; setEnv gives materials world-unit UV tiling
const updatePx=()=>{ENV.izPx.value=innerHeight*renderer.getPixelRatio()/(2*Math.tan(camera.fov*Math.PI/360));};updatePx();
const ambient=new THREE.AmbientLight(0x9fb4c8,0.35);scene.add(ambient);
const hemi=new THREE.HemisphereLight(0xbfd8f0,0x5a5048,0.55);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xfff2dc,1.1);scene.add(sun);scene.add(sun.target);
sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);{const sc=sun.shadow.camera;sc.left=-700;sc.right=700;sc.top=700;sc.bottom=-700;sc.near=1;sc.far=6000;sc.updateProjectionMatrix();}
sun.shadow.bias=-0.0008;sun.shadow.normalBias=2;
scene.fog=new THREE.FogExp2(0xb9cbe0,0.00013);
// the clock: DAY real seconds per city day
let DAY=240;const HOUR0=10.5;let clockPaused=false,pausedAt=0,clockOffset=0;
function hourNow(now){return ((HOUR0+((now/1000)/(DAY/24)))%24+24)%24;}
function setHour(h){const now=performance.now(),cur=clockPaused?pausedAt:now-clockOffset,tot=HOUR0+(cur/1000)/(DAY/24);let day=Math.floor(tot/24);if(day*24+h<HOUR0)day+=1;const t=(day*24+h-HOUR0)*(DAY/24)*1000;if(clockPaused)pausedAt=t;else clockOffset=now-t;}
window.setHour=setHour;
const nightF=h=>1-smooth(5.6,7.4,h)+smooth(17.6,19.6,h);   // ~1 at night, 0 by day (Chicago, spring)
const windowF=h=>smooth(16.5,18.5,h)*(1-smooth(23,25,h))+0.12*nightF(h);
// the sun: rises in the east over the lake (+x), sets in the west
function sunAt(h){const f=(h-6)/12,E=Math.sin(Math.PI*f)*0.95,az=Math.PI*(1-f);return new THREE.Vector3(Math.cos(az)*Math.cos(E),Math.sin(E),Math.sin(az)*0.35*Math.cos(E)).normalize();}
// sky: a gradient dome, coloured by the hour
const SKY={day:{top:0x2f6fd0,hor:0xbcd3ee},dusk:{top:0x2a3a78,hor:0xf0a060},night:{top:0x050a1c,hor:0x16243c}};
const skyM=new THREE.ShaderMaterial({uniforms:{top:{value:new THREE.Color()},hor:{value:new THREE.Color()},sunDir:{value:new THREE.Vector3(0,1,0)},sunA:{value:1}},side:THREE.BackSide,depthWrite:false,fog:false,
  vertexShader:'varying vec3 vP;void main(){vP=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',
  fragmentShader:'uniform vec3 top;uniform vec3 hor;uniform vec3 sunDir;uniform float sunA;varying vec3 vP;void main(){float t=clamp(vP.y*1.6,0.0,1.0);vec3 c=mix(hor,top,pow(t,0.6));float d=max(dot(vP,sunDir),0.0);c+=vec3(1.0,0.85,0.6)*(pow(d,600.0)*1.2+pow(d,8.0)*0.18)*sunA;gl_FragColor=vec4(c,1.0);}'});
const sky=new THREE.Mesh(new THREE.SphereGeometry(11000,32,16),skyM);sky.userData.noShadow=true;scene.add(sky);
const tmpC=new THREE.Color(),tmpC2=new THREE.Color();
function lerpSky(h){const n=nightF(h),dusk=Math.max(0,1-Math.abs(h-18.6)/1.6,1-Math.abs(h-6.3)/1.4);
  const mixTo=(a,b,k)=>tmpC.set(a).lerp(tmpC2.set(b),k);
  skyM.uniforms.top.value.copy(mixTo(SKY.day.top,SKY.night.top,n)).lerp(tmpC2.set(SKY.dusk.top),dusk*0.7);
  skyM.uniforms.hor.value.copy(mixTo(SKY.day.hor,SKY.night.hor,n)).lerp(tmpC2.set(SKY.dusk.hor),dusk);
  scene.fog.color.copy(skyM.uniforms.hor.value);renderer.setClearColor(skyM.uniforms.hor.value);
  const S=sunAt(h);skyM.uniforms.sunDir.value.copy(S);skyM.uniforms.sunA.value=S.y>-0.05?1:0;
  sun.position.copy(S).multiplyScalar(2500).add(sun.target.position);sun.intensity=1.15*Math.max(0,Math.min(1,S.y*4))*(1-0.85*n);
  sun.color.setHSL(0.09,0.6,0.5+0.45*Math.min(1,S.y*3));hemi.intensity=0.55*(1-0.75*n);ambient.intensity=0.35*(1-0.5*n)+0.12*n;
  ENV.izHour.value=h;ENV.izNight.value=n;ENV.izDay.value=1-n;ENV.izSunDir.value.copy(S);}
let hourCur=HOUR0;
animHooks.push(now=>{hourCur=hourNow(clockPaused?pausedAt:now-clockOffset);ctx.hour=hourCur;ENV.izTime.value=now/1000;lerpSky(hourCur);});
lerpSky(HOUR0);
// ===== stages/02-ground.js =====
// ---------- ground: the painted map (streets, parks, beaches), the lake shore, the river's real course, bridges, the pier ----------
await stage('ground');
const GS=4096,PX=GS/WORLD,px=v=>(v+HALF)*PX;
const gcv=document.createElement('canvas');gcv.width=gcv.height=GS;const g2=gcv.getContext('2d');
const polyPath=(pts,close)=>{g2.beginPath();pts.forEach(([x,z],i)=>i?g2.lineTo(px(x),px(z)):g2.moveTo(px(x),px(z)));if(close)g2.closePath();};
const strokePath=(pts,w,col)=>{g2.strokeStyle=col;g2.lineWidth=w*PX;g2.lineCap='round';g2.lineJoin='round';polyPath(pts,false);g2.stroke();};
const WATER='#2f6690';
function paintWater(){g2.fillStyle=WATER;polyPath(LAKE_POLY,true);g2.fill();for(const r of RIVERS)strokePath(r.pts,r.width,WATER);}
section('ground',()=>{
  g2.fillStyle='#7a776f';g2.fillRect(0,0,GS,GS);   // paving and roofs of the low city
  const street=(s,col)=>{strokePath([s.a,s.b],s.w,col);};
  for(const s of STREETS)if(!s.major)street(s,'#4d4e52');
  for(const p of PARKS){g2.fillStyle='#5f8a48';g2.fillRect(px(p.x0),px(p.z0),(p.x1-p.x0)*PX,(p.z1-p.z0)*PX);
    const R=mkRng(Math.round(p.x0*7+p.z0));g2.fillStyle='rgba(30,70,30,0.35)';for(let k=0;k<(p.x1-p.x0)*(p.z1-p.z0)/900;k++){g2.beginPath();g2.arc(px(p.x0+R()*(p.x1-p.x0)),px(p.z0+R()*(p.z1-p.z0)),1.5+R()*3,0,7);g2.fill();}}
  for(const b of BEACHES)strokePath(b.pts,b.w*2,'#dccda4');
  for(const s of STREETS)if(s.major)street(s,'#35373b');
  // centre lines on the majors
  g2.setLineDash([10,10]);for(const s of STREETS)if(s.major)strokePath([s.a,s.b],1.2/PX*1.2,'rgba(230,200,90,0.55)');g2.setLineDash([]);
  g2.fillStyle='#a19b90';g2.fillRect(px(PIER.x0-40),px(PIER.z-PIER.width/2),(PIER.length+40)*PX,PIER.width*PX);
  for(const r of RIVERS)strokePath(r.pts,r.width+12,'#c9c2b4');   // the river walls: a pale edge along both banks
  paintWater();   // the lake and the river win over anything painted across them
  g2.fillStyle='#a19b90';g2.fillRect(px(PIER.x0),px(PIER.z-PIER.width/2),PIER.length*PX,PIER.width*PX);
});
const groundTex=new THREE.CanvasTexture(gcv);groundTex.anisotropy=8;
const ground=new THREE.Mesh(new THREE.PlaneGeometry(WORLD,WORLD),new THREE.MeshLambertMaterial({map:groundTex}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.userData.noShadow=true;scene.add(ground);
// water surfaces: the lake as its real outline, each river as a ribbon that follows its bends
const waterM=new THREE.MeshPhongMaterial({color:0x2c6390,specular:0x9fc4e0,shininess:90,transparent:true,opacity:0.92});
{const shape=new THREE.Shape();LAKE_POLY.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));   // shape is in x,y; rotated flat, y becomes -z
 const lake=new THREE.Mesh(new THREE.ShapeGeometry(shape),waterM);lake.rotation.x=-Math.PI/2;lake.position.y=0.15;lake.receiveShadow=true;scene.add(lake);
 for(const r of RIVERS){const pos=[],idx=[],L=r.pts;for(let i=0;i<L.length;i++){const a=L[Math.max(0,i-1)],b=L[Math.min(L.length-1,i+1)];let dx=b[0]-a[0],dz=b[1]-a[1];const n=Math.hypot(dx,dz)||1;dx/=n;dz/=n;const h=r.width/2+2;
     pos.push(L[i][0]-dz*h,0.2,L[i][1]+dx*h,L[i][0]+dz*h,0.2,L[i][1]-dx*h);if(i)idx.push((i-1)*2,(i-1)*2+1,i*2,(i-1)*2+1,i*2+1,i*2);}
   const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();
   const m=new THREE.Mesh(g,waterM.clone());m.material.side=THREE.DoubleSide;scene.add(m);}}
animHooks.push(now=>{waterM.shininess=70+25*Math.sin(now*0.0011);});
const stoneM=new THREE.MeshLambertMaterial({color:0xbdb5a6}),steelM=new THREE.MeshLambertMaterial({color:0x6b6f75});
// the pier: a slab with its sheds and the Festival Hall at the end
{const slab=new THREE.Mesh(new THREE.BoxGeometry(PIER.length,4,PIER.width),stoneM);slab.position.set(PIER.x0+PIER.length/2,2,PIER.z);slab.castShadow=slab.receiveShadow=true;scene.add(slab);
 const shedM=new THREE.MeshLambertMaterial({color:0xd8d2c4});for(let k=0;k<5;k++){const shed=new THREE.Mesh(new THREE.BoxGeometry(140,12,34),shedM);shed.position.set(PIER.x0+140+k*160,10,PIER.z+(k%2?20:-20));shed.castShadow=true;scene.add(shed);}
 const hall=new THREE.Mesh(new THREE.BoxGeometry(80,26,86),new THREE.MeshLambertMaterial({color:0xc9b8a0}));hall.position.set(PIER.x1-45,17,PIER.z);hall.castShadow=true;scene.add(hall);}
// bridges: wherever a street crosses a river, a deck along the street, as long as the crossing is wide
const bridges=[];
function bridge(x,z,ang,w,len){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=-ang;
  const deck=new THREE.Mesh(new THREE.BoxGeometry(len,2.4,w),steelM);deck.position.y=4.2;deck.castShadow=deck.receiveShadow=true;g.add(deck);
  for(const s of [-1,1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(len,3.2,1.2),steelM);rail.position.set(0,7,s*(w/2-0.6));g.add(rail);
    const tower=new THREE.Mesh(new THREE.BoxGeometry(7,13,7),stoneM);tower.position.set(s*(len/2-3),6.5,w/2+3);g.add(tower);}
  scene.add(g);bridges.push({x,z,ang,w,len});}
section('bridges',()=>{
  for(const s of STREETS)for(const r of RIVERS)for(let i=0;i+1<r.pts.length;i++){const h=segHit(s.a,s.b,r.pts[i],r.pts[i+1]);if(!h)continue;
    const rl=Math.hypot(...h.r),sl=Math.hypot(...h.s),sin=Math.abs(h.r[0]*h.s[1]-h.r[1]*h.s[0])/(rl*sl);if(sin<0.45)continue;   // a street running along the bank is not a crossing
    if(bridges.some(b=>Math.hypot(b.x-h.x,b.z-h.z)<25))continue;
    bridge(h.x,h.z,Math.atan2(h.r[1],h.r[0]),s.w+2,r.width/sin+18);}
  ctx.details=Object.assign(ctx.details||{},{bridges:bridges.length});});
function onBridge(x,z){for(const b of bridges){const dx=x-b.x,dz=z-b.z,c=Math.cos(b.ang),s=Math.sin(b.ang),u=dx*c+dz*s,v=-dx*s+dz*c;if(Math.abs(u)<=b.len/2&&Math.abs(v)<=b.w/2)return true;}return false;}
// trees: in the parks and along Michigan Avenue and the river
const PARK_FEATURES=C.landmarks.map(l=>{const [x,z]=P(l.at);return [x,z,Math.max(l.w||20,l.d||0)*0.6+(l.gap||0)*0.6+(l.kind==='pavilion'?110:25)];});   // plazas, lawns and fountains stay open
{const trunkM=new THREE.MeshLambertMaterial({color:0x5a4030}),leafM=new THREE.MeshLambertMaterial({color:0x3f7a3a});
 const spots=[];for(const p of PARKS){const R=mkRng(Math.round(p.x1*3+p.z1));const n=Math.floor((p.x1-p.x0)*(p.z1-p.z0)/1500);
   for(let k=0;k<n;k++){const x=p.x0+8+R()*(p.x1-p.x0-16),z=p.z0+8+R()*(p.z1-p.z0-16);if(!streetAt(x,z)&&!inWater(x,z)&&!PARK_FEATURES.some(f=>Math.hypot(f[0]-x,f[1]-z)<f[2]))spots.push([x,z,7+R()*6]);}}
 const mich=lonX(-87.6245);for(let z=latZ(41.9008);z<=latZ(41.8674);z+=24)for(const s of [-1,1]){const x=mich+s*22;if(!inWater(x,z)&&!parkAt(x,z))spots.push([x,z,7]);}
 const tr=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.4,0.6,1,5),trunkM,spots.length),lf=new THREE.InstancedMesh(new THREE.SphereGeometry(1,7,5),leafM,spots.length);
 const d=new THREE.Object3D();spots.forEach(([x,z,h],i)=>{d.position.set(x,h*0.25,z);d.scale.set(1,h*0.5,1);d.updateMatrix();tr.setMatrixAt(i,d.matrix);d.position.set(x,h*0.7,z);d.scale.set(h*0.42,h*0.34,h*0.42);d.updateMatrix();lf.setMatrixAt(i,d.matrix);});
 tr.castShadow=lf.castShadow=true;scene.add(tr,lf);ctx.trees=spots.length;}
// ===== stages/03-blocks.js =====
// ---------- blocks: every grid cell becomes lots; towers rise with the skyline field and light up at night ----------
await stage('blocks');
// window textures: the facade (light ground, dark panes) and what glows at night (only the panes)
function winTex(glow){const cv=document.createElement('canvas');cv.width=cv.height=64;const g=cv.getContext('2d');g.fillStyle=glow?'#000':'#f2f0ec';g.fillRect(0,0,64,64);
  const R=mkRng(glow?5:9);for(let j=0;j<4;j++)for(let i=0;i<4;i++){const lit=R()<0.55;g.fillStyle=glow?(lit?`rgb(${230+R()*25},${200+R()*40},${140+R()*60})`:'#000'):`rgb(${40+R()*30},${52+R()*30},${70+R()*30})`;g.fillRect(i*16+3,j*16+2,9,11);}
  const t=new THREE.CanvasTexture(cv);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t;}
const facadeTex=winTex(false),glowTex=winTex(true);
const bldMats={};   // one material per district: colour × window map, tiled in world units (a window bay every 4 m)
function bldMat(d){if(bldMats[d.key])return bldMats[d.key];const m=new THREE.MeshLambertMaterial({color:d.color,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});m.color.multiplyScalar(1.15);setEnv(m,{K:0.25,id:'bld'+d.key});bldMats[d.key]=m;return m;}
const lots=[];   // {x,z,w,dpt,h,ry,kind,district}
const boxG=new THREE.BoxGeometry(1,1,1);boxG.translate(0,0.5,0);
function skyline(d,x,z){const dist=Math.hypot(x-SKY_C[0],z-SKY_C[1]),f=Math.pow(Math.max(0,1-dist/1900),1.4),n=0.35+0.65*fbm(x*0.004+3,z*0.004+9);return d.base+(d.tall-d.base)*f*n;}
const lmFoot=C.landmarks.filter(l=>l.kind!=='pier').map(l=>{const [x,z]=P(l.at);return {x,z,r:Math.max(l.w||40,(l.d||0)+(l.gap||0))*0.6+14};});
const nearLandmark=(x,z,r)=>lmFoot.some(f=>Math.hypot(f.x-x,f.z-z)<f.r+r);
const DIAG_SEGS=STREETS.filter(s=>s.axis==='d');
const dry=(x,z)=>!inWater(x,z)&&!parkAt(x,z)&&!onPier(x,z)&&!DIAG_SEGS.some(s=>segDist(x,z,s.a[0],s.a[1],s.b[0],s.b[1])<=s.w/2+3);   // diagonals (Milwaukee, Lake Shore Drive) cut through the grid
section('blocks',()=>{
  // block edges: the centre lines of every axis-aligned street, with the half-width to stay clear of
  const xs=[...new Map(STREETS.filter(s=>s.axis==='x').map(s=>[Math.round(s.at),s])).values()].sort((a,b)=>a.at-b.at);
  const zs=[...new Map(STREETS.filter(s=>s.axis==='z').map(s=>[Math.round(s.at),s])).values()].sort((a,b)=>a.at-b.at);
  const covers=(s,v)=>v>=Math.min(s.a[s.axis==='x'?1:0],s.b[s.axis==='x'?1:0])-1&&v<=Math.max(s.a[s.axis==='x'?1:0],s.b[s.axis==='x'?1:0])+1;   // a street with a range only bounds blocks inside it
  for(let i=0;i+1<xs.length;i++)for(let j=0;j+1<zs.length;j++){
    const cx0=(xs[i].at+xs[i+1].at)/2,cz0=(zs[j].at+zs[j+1].at)/2;
    // a ranged street that does not reach this block does not split it: skip the narrow half-cell, the neighbour covers it
    let W=xs[i],E=xs[i+1],N=zs[j],S=zs[j+1];
    if(!covers(W,cz0)||!covers(N,cx0))continue;
    let ii=i+1;while(ii<xs.length-1&&!covers(xs[ii],cz0))ii++;E=xs[ii];
    let jj=j+1;while(jj<zs.length-1&&!covers(zs[jj],cx0))jj++;S=zs[jj];
    let x0=W.at+W.w/2+1,x1=E.at-E.w/2-1,z0=N.at+N.w/2+1,z1=S.at-S.w/2-1;
    if(x1-x0<24||z1-z0<24)continue;
    const cx=(x0+x1)/2,cz=(z0+z1)/2;if(Math.abs(cx)>HALF-60||Math.abs(cz)>HALF-60)continue;
    const d=districtAt(cx,cz),H=skyline(d,cx,cz);
    // lots: towers alone or in pairs, midrises two to four, low buildings in a row of narrow frontages
    const n=H>90?1+(rnd()<0.35?1:0):H>35?2+Math.floor(rnd()*3):Math.max(2,Math.round((z1-z0)/28));
    const long=(z1-z0)>(x1-x0),cols=H>35?(n>=3?2:n):(long?2:n),rows=H>35?Math.ceil(n/cols):(long?Math.ceil(n/2):1);
    for(let k=0;k<cols*rows&&k<n+ (H<=35?n:0);k++){const ci=k%cols,rj=Math.floor(k/cols);if(rj>=rows)break;const w=(x1-x0)/cols,dd=(z1-z0)/rows,gx=x0+ci*w,gz=z0+rj*dd;
      const inset=H>90?Math.min(w,dd)*0.1:1+rnd()*2,w2=w-2*inset,d2=dd-2*inset;if(w2<7||d2<7)continue;
      const lx=gx+w/2,lz=gz+dd/2,rad=Math.max(w2,d2)/2;
      // every corner and the middle must be dry land, and clear of the river walls, the parks and the landmarks
      const pts=[[lx,lz],[gx+inset,gz+inset],[gx+w-inset,gz+inset],[gx+inset,gz+dd-inset],[gx+w-inset,gz+dd-inset]];
      if(!pts.every(([x,z])=>dry(x,z)&&!riverAt(x,z,8)))continue;
      if(nearLandmark(lx,lz,rad*0.7))continue;
      let h=H*(0.55+0.9*rnd());if(k>0&&H>90)h*=0.35;h=Math.max(5,Math.min(h,d.tall*1.1));
      lots.push({x:lx,z:lz,w:w2,dpt:d2,h,ry:0,kind:h>120?'tower':h>35?'midrise':'low',district:d,fixed:false});}}
  ctx.lots=lots.length;ctx.lotList=lots;
  // geometry: towers get setbacks, everything gets a roof box now and then
  const byD={};for(const l of lots){(byD[l.district.key]=byD[l.district.key]||[]).push(l);}
  const dm=new THREE.Object3D();let total=0;
  for(const key in byD){const L=byD[key],parts=[];
    for(const l of L){if(l.kind==='tower'){const tiers=2+Math.floor(rnd()*2);let y=0,w=l.w,d=l.dpt;for(let t=0;t<tiers;t++){const hh=l.h*(t===tiers-1?0.35:0.65/(tiers-1));parts.push([l.x,y,l.z,w,hh,d]);y+=hh;w*=0.78;d*=0.78;}}
      else parts.push([l.x,0,l.z,l.w,l.h,l.dpt]);
      if(rnd()<0.5)parts.push([l.x+(rnd()-0.5)*l.w*0.3,l.h,l.z+(rnd()-0.5)*l.dpt*0.3,Math.max(3,l.w*0.25),2+rnd()*3,Math.max(3,l.dpt*0.25)]);}
    const im=new THREE.InstancedMesh(boxG,bldMat(DIST[key]),parts.length),tint=new THREE.Color();
    parts.forEach((p,i)=>{dm.position.set(p[0],p[1],p[2]);dm.scale.set(p[3],p[4],p[5]);dm.updateMatrix();im.setMatrixAt(i,dm.matrix);
      const k=hash3(p[0],p[2],5);tint.setHSL(0.55+0.5*hash3(p[0],p[2],6),k<0.5?0.05:0.25,0.62+0.5*hash3(p[0],p[2],7));im.setColorAt(i,tint);});   // every building its own shade: glass, stone, brick
    im.castShadow=im.receiveShadow=true;im.userData.district=key;scene.add(im);total+=parts.length;}
  ctx.details={buildings:total,lots:lots.length};
});
// windows come on at dusk
animHooks.push(()=>{const w=windowF(hourCur);for(const k in bldMats)bldMats[k].emissive.setRGB(w,w*0.92,w*0.8);});
// ===== stages/04-landmarks.js =====
// ---------- landmarks: parametric massing for the buildings everyone knows ----------
await stage('landmarks');
const LANDMARKS=[];   // meshes with userData.info, for the click card
const glassM=new THREE.MeshLambertMaterial({color:0x4a6a8a,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(glassM,{K:0.25,id:'lmglass'});
const darkM=new THREE.MeshLambertMaterial({color:0x2c3038,map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(darkM,{K:0.25,id:'lmdark'});
const lmMats=[glassM,darkM];
function lmMat(hex){if(!hex)return glassM;const m=new THREE.MeshLambertMaterial({color:parseInt(hex.slice(1),16),map:facadeTex,emissiveMap:glowTex,emissive:0x000000});setEnv(m,{K:0.25,id:'lm'+hex});lmMats.push(m);return m;}
const chromeM=new THREE.MeshPhongMaterial({color:0xdde4ea,specular:0xffffff,shininess:120});
function reg(mesh,L){mesh.userData.info=L;mesh.castShadow=mesh.receiveShadow=true;LANDMARKS.push(mesh);scene.add(mesh);return mesh;}
function box(x,y,z,w,h,d,m){const b=new THREE.Mesh(boxG,m);b.position.set(x,y,z);b.scale.set(w,h,d);return b;}
function group(L,parts){const g=new THREE.Group();for(const p of parts){p.castShadow=p.receiveShadow=true;p.userData.info=L;g.add(p);}g.userData.info=L;LANDMARKS.push(g);scene.add(g);return g;}
const KINDS={
  bundle(L){const m=darkM,t=L.w/3,H=L.h,levels=[[0,0,1],[1,0,.92],[2,0,.62],[0,1,.62],[1,1,1],[2,1,.83],[0,2,.46],[1,2,.62],[2,2,.46]];   // nine tubes, the taller ones at the core
    return group(L,levels.map(([i,j,f])=>box(L.x-L.w/2+t*(i+.5),0,L.z-L.w/2+t*(j+.5),t-0.6,H*f,t-0.6,m)).concat([box(L.x-8,H,L.z-8,2,80,2,steelM),box(L.x+8,H,L.z+8,2,70,2,steelM)]));},
  taper(L){const g=new THREE.Mesh(new THREE.CylinderGeometry(1,1.6,1,4,1),darkM);g.geometry.translate(0,0.5,0);g.rotation.y=Math.PI/4;g.position.set(L.x,0,L.z);g.scale.set(L.w*0.72,L.h,L.d*0.72);
    const g2=group(L,[g,box(L.x-9,L.h,L.z,1.6,110,1.6,steelM),box(L.x+9,L.h,L.z,1.6,110,1.6,steelM)]);   // X-braces: four thin diagonals a side
    for(const s of [-1,1])for(let k=0;k<5;k++){const br=box(L.x+s*(L.w*0.36-k*L.w*0.03),k*L.h/5,L.z,1.2,L.h/5*1.06,L.d*0.7,steelM);br.rotation.z=s*0.22;br.userData.info=L;g2.add(br);}return g2;},
  setbacks(L){const H=L.h,steps=[[1,1,0.3],[0.8,0.85,0.35],[0.62,0.7,0.35]];let y=0;const parts=[];for(const [fw,fd,fh] of steps){parts.push(box(L.x+(1-fw)*L.w/2*0.5,y,L.z,L.w*fw,H*fh,L.d*fd,glassM));y+=H*fh;}
    if(L.spire)parts.push(box(L.x,H,L.z,2,L.spire,2,chromeM));return group(L,parts);},
  box(L){return reg(box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),L);},
  stacked(L){const parts=[];const stems=[[0,-L.d/3,0.62],[0,0,1],[0,L.d/3,0.8]];for(const [dx,dz,f] of stems){let y=0;for(let k=0;k<7;k++){const hh=L.h*f/7;const fr=new THREE.Mesh(new THREE.CylinderGeometry(0.5*(k%2?0.8:1.1),0.5*(k%2?1.1:0.8),1,4,1),glassM);fr.geometry.translate(0,0.5,0);fr.rotation.y=Math.PI/4;fr.position.set(L.x+dx,y,L.z+dz);fr.scale.set(L.w*0.85,hh,L.d/3*1.05);parts.push(fr);y+=hh;}}return group(L,parts);},
  crown(L){const parts=[box(L.x,0,L.z,L.w,L.h*0.7,L.d,glassM),box(L.x,L.h*0.7,L.z,L.w*0.8,L.h*0.16,L.d*0.8,glassM),box(L.x,L.h*0.86,L.z,L.w*0.55,L.h*0.14,L.d*0.55,glassM),box(L.x,L.h,L.z,1.5,L.h*0.2,1.5,chromeM)];return group(L,parts);},
  twin(L){const parts=[];for(const s of [-1,1]){const c=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,24,1),lmMat('#c9c2b4'));c.geometry.translate(0,0.5,0);c.position.set(L.x+s*L.gap/2,0,L.z);c.scale.set(L.w/2,L.h,L.w/2);parts.push(c);
      for(let k=0;k<12;k++){const r=new THREE.Mesh(new THREE.TorusGeometry(1,0.04,4,24),darkM);r.rotation.x=Math.PI/2;r.position.set(L.x+s*L.gap/2,L.h*(0.3+k*0.058),L.z);r.scale.setScalar(L.w/2*1.04);parts.push(r);}}return group(L,parts);},
  slab(L){return group(L,[box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),box(L.x,L.h,L.z,L.w*0.25,L.tower||20,L.d*0.4,lmMat(L.color))]);},
  deco(L){const m=lmMat(L.color),parts=[];const steps=[[1,1,0.5],[0.7,0.8,0.25],[0.45,0.55,0.18]];let y=0;for(const [fw,fd,fh] of steps){parts.push(box(L.x,y,L.z,L.w*fw,L.h*fh,L.d*fd,m));y+=L.h*fh;}parts.push(box(L.x,y,L.z,4,L.h*0.09,4,chromeM));return group(L,parts);},
  crowncyl(L){const c=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,20,1),new THREE.MeshLambertMaterial({color:0xe8f0ff,emissive:0x8fb4e0,emissiveIntensity:0.5,transparent:true,opacity:0.8}));c.geometry.translate(0,0.5,0);c.position.set(L.x,L.h*0.89,L.z);c.scale.set(L.w*0.36,L.h*0.11,L.w*0.36);
    return group(L,[box(L.x,0,L.z,L.w,L.h*0.89,L.d,lmMat(L.color)),c]);},
  gothic(L){const m=lmMat(L.color),parts=[box(L.x,0,L.z,L.w,L.h*0.72,L.d,m),box(L.x,L.h*0.72,L.z,L.w*0.7,L.h*0.28,L.d*0.7,m)];for(let k=0;k<8;k++){const a=k/8*Math.PI*2;parts.push(box(L.x+Math.cos(a)*L.w*0.34,L.h*0.72,L.z+Math.sin(a)*L.d*0.34,2.4,L.h*0.36,2.4,m));}return group(L,parts);},
  clocktower(L){const m=lmMat(L.color);return group(L,[box(L.x,0,L.z,L.w,L.h*0.6,L.d,m),box(L.x,L.h*0.6,L.z+L.d*0.2,L.w*0.5,L.h*0.3,L.w*0.5,m),box(L.x,L.h*0.9,L.z+L.d*0.2,L.w*0.3,L.h*0.1,L.w*0.3,m)]);},
  diamond(L){const top=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),glassM);top.geometry.translate(0,0.5,0);top.position.set(L.x,L.h*0.78,L.z);top.rotation.z=0;top.scale.set(L.w,L.h*0.22,L.d*0.5);
    const wedge=new THREE.Mesh(new THREE.CylinderGeometry(0,1,1,4,1),glassM);wedge.geometry.translate(0,0.5,0);wedge.rotation.y=Math.PI/4;wedge.position.set(L.x,L.h*0.78,L.z);wedge.scale.set(L.w*0.75,L.h*0.22,L.d*0.75);
    return group(L,[box(L.x,0,L.z,L.w,L.h*0.78,L.d,glassM),wedge]);},
  ypoint(L){const parts=[];for(let k=0;k<3;k++){const a=k/3*Math.PI*2+0.5;const wing=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,16,1,false,0,Math.PI*0.55),darkM);wing.geometry.translate(0,0.5,0);wing.rotation.y=a;wing.position.set(L.x,0,L.z);wing.scale.set(L.w*0.55,L.h,L.w*0.55);parts.push(wing);}
    const core=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,12,1),darkM);core.geometry.translate(0,0.5,0);core.position.set(L.x,0,L.z);core.scale.set(L.w*0.22,L.h,L.w*0.22);parts.push(core);return group(L,parts);},
  watertower(L){const m=lmMat(L.color);const parts=[box(L.x,0,L.z,L.w*2.2,L.h*0.3,L.w*2.2,m),box(L.x,L.h*0.3,L.z,L.w,L.h*0.6,L.w,m)];const cap=new THREE.Mesh(new THREE.ConeGeometry(0.7,1,4),m);cap.geometry.translate(0,0.5,0);cap.position.set(L.x,L.h*0.9,L.z);cap.scale.set(L.w,L.h*0.1,L.w);parts.push(cap);return group(L,parts);},
  bean(L){   // Cloud Gate: a polished bean that mirrors the park and the skyline, raised on its two ends over the omphalos arch
    const g=new THREE.SphereGeometry(1,64,36),v=g.attributes.position;
    for(let k=0;k<v.count;k++){let x=v.getX(k),y=v.getY(k),z=v.getZ(k);
      if(y<0)y*=0.55;                                            // a flatter underside
      x*=1+0.12*Math.max(0,y);                                  // the top swells a little past the ends
      const arch=Math.max(0,1-Math.abs(x)/0.55);if(y<0)y+=arch*arch*0.62*(-y+0.2)*1.2;   // the arch under the middle
      v.setXYZ(k,x,y,z);}
    g.computeVertexNormals();
    const rt=new THREE.WebGLCubeRenderTarget(256,{format:THREE.RGBFormat,generateMipmaps:true,minFilter:THREE.LinearMipmapLinearFilter});
    const cube=new THREE.CubeCamera(1,4000,rt);cube.position.set(L.x,6,L.z);scene.add(cube);
    const beanM=new THREE.MeshPhongMaterial({color:0xdfe4ea,specular:0xffffff,shininess:220,envMap:rt.texture,combine:THREE.MixOperation,reflectivity:0.9});
    const b=new THREE.Mesh(g,beanM);b.position.set(L.x,L.h*0.5,L.z);b.scale.set(L.w/2,L.h*0.5,L.d/2);
    const plaza=box(L.x,0,L.z,L.w*3,0.3,L.d*4,new THREE.MeshLambertMaterial({color:0x9e988c}));
    const grp=group(L,[plaza,b]);b.castShadow=true;
    let lastR=-1e9;animHooks.push(now=>{if(now-lastR<2500||camera.position.distanceTo(b.position)>900)return;lastR=now;b.visible=false;cube.update(renderer,scene);b.visible=true;});   // the reflection refreshes every few seconds while you are near
    return grp;},
  fountain(L){const parts=[];for(let k=0;k<3;k++){const r=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,28,1),stoneM);r.geometry.translate(0,0.5,0);r.position.set(L.x,k*2.2,L.z);r.scale.set(L.w/2*(1-k*0.3),2.2,L.w/2*(1-k*0.3));parts.push(r);}
    const jet=new THREE.Mesh(new THREE.CylinderGeometry(0.6,2.5,1,10,1),waterM);jet.geometry.translate(0,0.5,0);jet.position.set(L.x,6,L.z);jet.scale.set(1,30,1);parts.push(jet);const g=group(L,parts);animHooks.push(now=>{jet.scale.y=18+14*Math.max(0,Math.sin(now*0.0007));});return g;},
  lowrise(L){return reg(box(L.x,0,L.z,L.w,L.h,L.d,lmMat(L.color)),L);},
  stadium(L){const parts=[];const ring=new THREE.Mesh(new THREE.CylinderGeometry(1,1.1,1,32,1,true),stoneM);ring.geometry.translate(0,0.5,0);ring.position.set(L.x,0,L.z);ring.scale.set(L.w/2,L.h,L.d/2);ring.material=stoneM.clone();ring.material.side=THREE.DoubleSide;parts.push(ring);
    for(const s of [-1,1])for(let k=0;k<12;k++){parts.push(box(L.x+s*(L.w/2+8),0,L.z-L.d*0.4+k*L.d*0.8/11,3,L.h*0.55,3,stoneM));}return group(L,parts);},
  wavy(L){const parts=[box(L.x,0,L.z,L.w,L.h,L.d,glassM)],slabM=lmMat('#e8ecee');   // Aqua: floor plates whose balconies swell and recede
    for(let k=0,y=12;y<L.h;k++,y+=7.5){const t=y*0.045;const e=[2+2*Math.sin(t+L.x*0.01),2+2*Math.sin(t*1.3+1.7),2+2*Math.sin(t*0.8+3.1),2+2*Math.sin(t*1.1+4.6)];
      parts.push(box(L.x+(e[1]-e[3])/2,y,L.z+(e[2]-e[0])/2,L.w+e[1]+e[3],0.5,L.d+e[0]+e[2],slabM));}return group(L,parts);},
  pavilion(L){const parts=[box(L.x,0,L.z,26,14,30,stoneM)];   // Pritzker: the stage, steel ribbons over it, and the trellis over the lawn to the east
    for(let k=0;k<9;k++){const r=new THREE.Mesh(new THREE.TorusGeometry(10+k*1.6,0.35,3,18,Math.PI*(0.7+0.05*k)),chromeM);r.position.set(L.x+2-k*0.8,18+k*1.8,L.z+(k-4)*3.2);r.rotation.set(0.3*(k%3-1),Math.PI/2+0.25*(k-4),0.6+0.1*k);r.scale.set(1,1.4,3);parts.push(r);}
    for(let k=1;k<=6;k++){const arc=new THREE.Mesh(new THREE.TorusGeometry(46,0.4,3,24,Math.PI),steelM);arc.position.set(L.x+10+k*16,0,L.z);arc.rotation.y=Math.PI/2;arc.scale.set(1,0.5,1);parts.push(arc);}
    for(let k=-2;k<=2;k++){const rib=box(L.x+56,22.5-Math.abs(k)*2,L.z+k*18,96,0.6,0.6,steelM);parts.push(rib);}
    return group(L,parts);},
  crownfountain(L){const faceM=new THREE.MeshLambertMaterial({color:0xdfe8ee,emissive:0x8fb0c8,emissiveIntensity:0.35,transparent:true,opacity:0.9});const parts=[];
    for(const s of [-1,1])parts.push(box(L.x,0,L.z+s*L.gap/2,15,L.h,L.w,faceM));
    const pool=box(L.x,0,L.z,22,0.3,L.gap-L.w,new THREE.MeshPhongMaterial({color:0x1c2a38,specular:0xb0c8e0,shininess:120}));parts.push(pool);
    const g=group(L,parts);animHooks.push(now=>{const k=0.25+0.2*Math.sin(now*0.0004);faceM.emissiveIntensity=k+0.4*windowF(hourCur);});return g;},
  dome(L){const m=lmMat(L.color),parts=[];const hall=new THREE.Mesh(new THREE.CylinderGeometry(L.w/2,L.w/2,L.h*0.6,12,1),m);hall.geometry.translate(0,L.h*0.3,0);hall.position.set(L.x,0,L.z);parts.push(hall);
    const dm=new THREE.Mesh(new THREE.SphereGeometry(L.w*0.34,20,10,0,Math.PI*2,0,Math.PI/2),new THREE.MeshLambertMaterial({color:0xb87a4a}));dm.position.set(L.x,L.h*0.6,L.z);parts.push(dm);return group(L,parts);},
  pier(L){const parts=[];const wheel=new THREE.Group();const rim=new THREE.Mesh(new THREE.TorusGeometry(PIER.wheelR,1.2,6,48),steelM);wheel.add(rim);
    for(let k=0;k<12;k++){const a=k/12*Math.PI*2;const sp=box(0,0,0,1,PIER.wheelR*2,1,steelM);sp.position.set(0,0,0);sp.rotation.z=a;sp.geometry=new THREE.BoxGeometry(1,1,1);sp.scale.set(0.8,PIER.wheelR*2,0.8);wheel.add(sp);
      const car=new THREE.Mesh(new THREE.SphereGeometry(2.4,8,6),new THREE.MeshLambertMaterial({color:0xe8f0ff}));car.position.set(Math.cos(a)*PIER.wheelR,Math.sin(a)*PIER.wheelR,0);wheel.add(car);}
    wheel.position.set(PIER.wheelX,PIER.wheelR+6,PIER.z);wheel.rotation.y=Math.PI/2;wheel.userData.info=L;parts.push(wheel);
    for(const s of [-1,1]){const leg=box(PIER.wheelX,4,PIER.z+s*10,3,PIER.wheelR+2,3,steelM);leg.rotation.x=s*0.16;parts.push(leg);}
    const g=group(L,parts);animHooks.push(now=>{wheel.rotation.x=now*0.00012;});return g;},
};
section('landmarks',()=>{for(const L of C.landmarks){[L.x,L.z]=P(L.at);const f=KINDS[L.kind];if(!f){report('landmark '+L.name,new Error('unknown kind '+L.kind));continue;}try{f(L);}catch(e){report('landmark '+L.name,e);}}
  // warning beacons on the tallest roofs
  const beacons=[];for(const L of C.landmarks)if(L.h>250){const b=new THREE.Mesh(new THREE.SphereGeometry(2,8,6),new THREE.MeshBasicMaterial({color:0xff2020}));b.position.set(L.x,L.h+(L.kind==='bundle'?80:L.kind==='taper'?110:L.spire||8),L.z);scene.add(b);beacons.push(b);}
  animHooks.push(now=>{const on=(now%1600)<800;for(const b of beacons)b.visible=on||hourCur<6||hourCur>18;});
  ctx.details.landmarks=LANDMARKS.length;});
animHooks.push(()=>{const w=windowF(hourCur);for(const m of lmMats)m.emissive.setRGB(w,w*0.92,w*0.8);});
// ===== stages/05-el.js =====
// ---------- the L: the Loop's elevated tracks on their columns, and the trains that circle them ----------
await stage('el');
section('el',()=>{
  const H=EL.height,W=EL.east-EL.west,D=EL.south-EL.north,cx=(EL.east+EL.west)/2,cz=(EL.north+EL.south)/2;
  const rail=(x,z,w,d)=>{const b=new THREE.Mesh(new THREE.BoxGeometry(w,1.2,d),steelM);b.position.set(x,H,z);b.castShadow=true;scene.add(b);};
  rail(cx,EL.north,W+12,12);rail(cx,EL.south,W+12,12);rail(EL.west,cz,12,D);rail(EL.east,cz,12,D);
  // columns every 15 m, in the street
  const cols=[];for(let x=EL.west;x<=EL.east;x+=15){cols.push([x,EL.north]);cols.push([x,EL.south]);}for(let z=EL.north+15;z<EL.south;z+=15){cols.push([EL.west,z]);cols.push([EL.east,z]);}
  const cm=new THREE.InstancedMesh(new THREE.CylinderGeometry(0.5,0.6,1,6),steelM,cols.length*2),d=new THREE.Object3D();
  cols.forEach(([x,z],i)=>{for(const s of [-1,1]){const on=Math.abs(z-EL.north)<1||Math.abs(z-EL.south)<1;d.position.set(x+(on?0:s*5),H/2,z+(on?s*5:0));d.scale.set(1,H,1);d.updateMatrix();cm.setMatrixAt(i*2+(s>0?1:0),d.matrix);}});
  cm.castShadow=true;scene.add(cm);
  // trains: EL.trains of EL.cars cars, half each way, on the perimeter
  const P=2*(W+D),carL=15,carG=1.2,N=EL.trains*EL.cars;
  const carM=new THREE.MeshLambertMaterial({color:0xd8dde3,emissive:0x000000}),tm=new THREE.InstancedMesh(new THREE.BoxGeometry(carL,3.4,3.2),carM,N);tm.castShadow=true;tm.userData.life=true;scene.add(tm);
  const trains=[];for(let t=0;t<EL.trains;t++)trains.push({s:t*P/EL.trains,dir:t%2?1:-1,v:11+t*0.7,stop:0});
  const at=(s,side)=>{s=((s%P)+P)%P;const o=side*4;   // a point on the rectangle, offset to the inner or outer track
    if(s<W)return [EL.west+s,EL.north+o,0];s-=W;if(s<D)return [EL.east-o,EL.north+s,Math.PI/2];s-=D;if(s<W)return [EL.east-s,EL.south-o,0];s-=W;return [EL.west+o,EL.south-s,Math.PI/2];};
  let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;let i=0;
    for(const tr of trains){if(tr.stop>0)tr.stop-=dt;else{tr.s+=tr.dir*tr.v*dt;if(Math.floor(tr.s/ (P/8))!==Math.floor((tr.s-tr.dir*tr.v*dt)/(P/8)))tr.stop=3+Math.random()*2;}   // a short stop every eighth of the loop
      for(let c=0;c<EL.cars;c++){const [x,z,a]=at(tr.s-tr.dir*c*(carL+carG),tr.dir);d.position.set(x,H+2.4,z);d.rotation.set(0,a,0);d.scale.set(1,1,1);d.updateMatrix();tm.setMatrixAt(i++,d.matrix);}}
    tm.instanceMatrix.needsUpdate=true;const w=windowF(hourCur);carM.emissive.setRGB(w*0.9,w*0.85,w*0.6);});
  ctx.details.trains=EL.trains;
});
// ===== stages/06-traffic.js =====
// ---------- traffic: cars on the major streets and Lake Shore Drive, tour boats following the river, sails on the lake ----------
await stage('traffic');
section('traffic',()=>{
  // routes: every major street (and each diagonal) as a polyline; cars run both ways, one lane each side
  const routes=[];
  for(const s of STREETS)if(s.major&&s.axis!=='d')routes.push({pts:[s.a,s.b],w:s.w});
  for(const d of DIAGONALS)routes.push({pts:d.pts,w:d.w});
  for(const r of routes){let L=0;r.cum=[0];for(let i=0;i+1<r.pts.length;i++){L+=Math.hypot(r.pts[i+1][0]-r.pts[i][0],r.pts[i+1][1]-r.pts[i][1]);r.cum.push(L);}r.len=L;}
  const at=(r,s)=>{s=((s%r.len)+r.len)%r.len;let i=0;while(i<r.cum.length-2&&r.cum[i+1]<s)i++;const a=r.pts[i],b=r.pts[i+1],u=(s-r.cum[i])/((r.cum[i+1]-r.cum[i])||1);
    return [a[0]+(b[0]-a[0])*u,a[1]+(b[1]-a[1])*u,Math.atan2(b[1]-a[1],b[0]-a[0])];};
  // what the road is at every 5 m, worked out once: 0 = none (lake, river with no bridge, off the map), 1 = street, 2 = bridge deck
  for(const r of routes){r.st=new Uint8Array(Math.ceil(r.len/5)+1);for(let k=0;k<r.st.length;k++){const [x,z]=at(r,k*5);r.st[k]=inLake(x,z)||Math.abs(x)>HALF-20||Math.abs(z)>HALF-20?0:inRiver(x,z)?(onBridge(x,z)?2:0):1;}}
  const cars=[];for(const r of routes){const n=Math.floor(r.len/70);for(const dir of [-1,1])for(let k=0;k<n;k++)cars.push({r,dir,s:xr()*r.len,v:9+xr()*7,off:dir*r.w/4});}
  const cm=new THREE.InstancedMesh(new THREE.BoxGeometry(4.4,1.5,2),new THREE.MeshLambertMaterial({color:0xffffff}),cars.length),d=new THREE.Object3D(),col=new THREE.Color();
  cars.forEach((c,i)=>cm.setColorAt(i,col.setHSL(xr(),0.45,0.3+xr()*0.4)));cm.userData.life=true;cm.frustumCulled=false;scene.add(cm);
  let last=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-last)/1000);last=now;
    for(let i=0;i<cars.length;i++){const c=cars[i];c.s+=c.dir*c.v*dt;const [x0,z0,a]=at(c.r,c.s),x=x0-Math.sin(a)*c.off,z=z0+Math.cos(a)*c.off;
      const st=c.r.st[Math.round((((c.s%c.r.len)+c.r.len)%c.r.len)/5)],y=st===2?6.2:0.8,sc=st?1:0;   // hidden where there is no road
      d.position.set(x,y,z);d.rotation.set(0,-a,0);d.scale.setScalar(sc);d.updateMatrix();cm.setMatrixAt(i,d.matrix);}
    cm.instanceMatrix.needsUpdate=true;});
  // tour boats: up and down the three branches, along the river's own bends
  const boatM=new THREE.MeshLambertMaterial({color:0xf0ede6}),roofM=new THREE.MeshLambertMaterial({color:0x3a5f8a}),sailM=new THREE.MeshLambertMaterial({color:0xffffff,side:THREE.DoubleSide});
  const boats=[];RIVERS.forEach((rv,ri)=>{const r={pts:rv.pts};let L=0;r.cum=[0];for(let i=0;i+1<r.pts.length;i++){L+=Math.hypot(r.pts[i+1][0]-r.pts[i][0],r.pts[i+1][1]-r.pts[i][1]);r.cum.push(L);}r.len=L;
    for(let k=0;k<(ri===0?4:2);k++){const b=new THREE.Mesh(new THREE.BoxGeometry(24,3,6),boatM);const top=new THREE.Mesh(new THREE.BoxGeometry(16,2,4),roofM);top.position.set(-2,2.5,0);b.add(top);b.castShadow=true;scene.add(b);
      boats.push({m:b,r,s:(k+0.5)/4*L,dir:k%2?1:-1,v:3.5+xr()*2,off:rv.width*0.2});}});
  const sails=[];for(let k=0;k<18;k++){const g=new THREE.Group();const hull=new THREE.Mesh(new THREE.BoxGeometry(8,1.6,2.6),boatM);hull.position.y=0.6;const sail=new THREE.Mesh(new THREE.ConeGeometry(2.5,11,3),sailM);sail.position.set(0.5,7,0);g.add(hull,sail);scene.add(g);
    let x=0,z=0;for(let t=0;t<40;t++){x=xrr(PIER.x0,HALF-150);z=xrr(-HALF+200,HALF-200);if(inLake(x,z)&&!inLake(x-120,z)===false)break;}sails.push({g,x,z,a:xr()*6.28,v:1.5+xr()*2});}
  let lastB=performance.now();
  animHooks.push(now=>{const dt=Math.min(0.05,(now-lastB)/1000);lastB=now;
    for(const b of boats){b.s+=b.dir*b.v*dt;if(b.s>b.r.len-40){b.s=b.r.len-40;b.dir=-1;}if(b.s<40){b.s=40;b.dir=1;}const [x,z,a]=at(b.r,b.s);b.m.position.set(x-Math.sin(a)*b.off*b.dir,1.2,z+Math.cos(a)*b.off*b.dir);b.m.rotation.y=-a+(b.dir>0?0:Math.PI);}
    for(const s of sails){s.a+=(xr()-0.5)*0.4*dt;const nx=s.x+Math.cos(s.a)*s.v*dt,nz=s.z+Math.sin(s.a)*s.v*dt;if(inLake(nx,nz)&&inLake(nx-60,nz)&&Math.abs(nz)<HALF-100&&nx<HALF-80){s.x=nx;s.z=nz;}else s.a+=Math.PI*0.6;
      s.g.position.set(s.x,0.3+Math.sin(now*0.002+s.x)*0.15,s.z);s.g.rotation.y=-s.a;s.g.rotation.z=0.12*Math.sin(now*0.0015+s.z);}});
  ctx.details.cars=cars.length;ctx.details.boats=boats.length+sails.length;
});
// ===== stages/07-ui.js =====
// ---------- camera, views, the clock, the card, the render loop ----------
await stage('ui');
const el=renderer.domElement;
// orbit camera: drag to orbit, right/shift-drag or two fingers to pan, wheel/pinch to zoom, WASD/QE to move the target
const ctl={target:new THREE.Vector3(0,40,0),az:0.6,el:0.5,dist:1400,goal:null};
function applyCam(){const e=Math.max(0.03,Math.min(1.5,ctl.el));camera.position.set(ctl.target.x+Math.cos(ctl.az)*Math.cos(e)*ctl.dist,ctl.target.y+Math.sin(e)*ctl.dist,ctl.target.z+Math.sin(ctl.az)*Math.cos(e)*ctl.dist);camera.lookAt(ctl.target);}
function setView(px,py,pz,tx,ty,tz,fly){const t=new THREE.Vector3(tx,ty,tz),p=new THREE.Vector3(px,py,pz),d=p.clone().sub(t);const goal={target:t,az:Math.atan2(d.z,d.x),el:Math.atan2(d.y,Math.hypot(d.x,d.z)),dist:d.length()};
  if(fly===false||matchMedia('(prefers-reduced-motion: reduce)').matches){Object.assign(ctl,goal);ctl.goal=null;return;}ctl.goal=Object.assign(goal,{t0:performance.now(),from:{target:ctl.target.clone(),az:ctl.az,el:ctl.el,dist:ctl.dist}});}
const ptrs=new Map();let pinch0=0,dist0=0;
el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);ptrs.set(e.pointerId,{x:e.clientX,y:e.clientY,b:e.button,sh:e.shiftKey,moved:0});if(ptrs.size===2){const [a,b]=[...ptrs.values()];pinch0=Math.hypot(a.x-b.x,a.y-b.y);dist0=ctl.dist;}});
el.addEventListener('pointermove',e=>{const p=ptrs.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;p.moved+=Math.abs(dx)+Math.abs(dy);ctl.goal=null;
  if(ptrs.size===2){const [a,b]=[...ptrs.values()];const pd=Math.hypot(a.x-b.x,a.y-b.y);ctl.dist=Math.max(8,Math.min(9000,dist0*pinch0/pd));pan(dx/2,dy/2);return;}
  if(p.b===2||p.sh)pan(dx,dy);else{ctl.az+=dx*0.005;ctl.el=Math.max(0.03,Math.min(1.5,ctl.el+dy*0.005));}});
const endPtr=e=>{const p=ptrs.get(e.pointerId);ptrs.delete(e.pointerId);if(p&&p.moved<6&&e.type==='pointerup'&&p.b===0)clickAt(e.clientX,e.clientY);};
el.addEventListener('pointerup',endPtr);el.addEventListener('pointercancel',endPtr);el.addEventListener('contextmenu',e=>e.preventDefault());
function pan(dx,dy){const k=ctl.dist*0.0016;const fx=Math.cos(ctl.az),fz=Math.sin(ctl.az);ctl.target.x+=(-dx*fz+dy*fx)*k*-1;ctl.target.z+=(dx*fx+dy*fz)*k*-1;}
el.addEventListener('wheel',e=>{e.preventDefault();ctl.goal=null;ctl.dist=Math.max(8,Math.min(9000,ctl.dist*Math.exp(e.deltaY*0.0012)));},{passive:false});
const keys=new Set();addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;keys.add(e.key.toLowerCase());if(e.key==='Escape')closeCard();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function applyKeys(){if(!keys.size)return;const s=ctl.dist*0.012,fx=Math.cos(ctl.az),fz=Math.sin(ctl.az);let mx=0,mz=0;if(keys.has('w'))mx-=1;if(keys.has('s'))mx+=1;if(keys.has('a'))mz+=1;if(keys.has('d'))mz-=1;
  ctl.target.x+=(mx*fx-mz*fz)*s;ctl.target.z+=(mx*fz+mz*fx)*s;if(keys.has('q'))ctl.target.y=Math.max(0,ctl.target.y-s);if(keys.has('e'))ctl.target.y+=s;if(mx||mz||keys.has('q')||keys.has('e'))ctl.goal=null;}
function stepFly(now){const g=ctl.goal;if(!g)return;const u=Math.min(1,(now-g.t0)/1400),k=u*u*(3-2*u);ctl.target.lerpVectors(g.from.target,g.target,k);let da=g.az-g.from.az;da=Math.atan2(Math.sin(da),Math.cos(da));ctl.az=g.from.az+da*k;ctl.el=g.from.el+(g.el-g.from.el)*k;ctl.dist=g.from.dist+(g.dist-g.from.dist)*k;if(u>=1)ctl.goal=null;}
// the panels: viewpoints, the clock, a card for the landmark you click
const ui=document.getElementById('ui'),viewsEl=document.getElementById('views'),card=document.getElementById('card'),side=document.getElementById('side');
const VIEWS={};for(const k in C.views){const [f,t]=C.views[k],[fx,fz]=P(f),[tx,tz]=P(t);VIEWS[k]=[fx,f[2],fz,tx,t[2],tz];}   // [lat,lon,height] from and to
const mkBtn=(label,parent,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;parent.appendChild(b);return b;};
const viewsBtn=mkBtn('Views',ui,()=>{const open=!viewsEl.classList.contains('open');viewsEl.classList.toggle('open',open);viewsBtn.setAttribute('aria-expanded',String(open));});viewsBtn.setAttribute('aria-expanded','false');
{const h=document.createElement('div');h.className='sub';h.textContent='Viewpoints';viewsEl.appendChild(h);for(const k in VIEWS)mkBtn(k,viewsEl,()=>{setView(...VIEWS[k]);viewsEl.classList.remove('open');viewsBtn.setAttribute('aria-expanded','false');});}
const pauseBtn=mkBtn('Pause sun',ui,()=>{if(!clockPaused){clockPaused=true;pausedAt=performance.now()-clockOffset;pauseBtn.textContent='Resume sun';}else{clockPaused=false;clockOffset=performance.now()-pausedAt;pauseBtn.textContent='Pause sun';}});
const tw=document.createElement('div');tw.id='timebar';tw.innerHTML='<label for="tslider" id="tlabel">10:30</label><input id="tslider" type="range" min="0" max="24" step="0.05" value="10.5" aria-label="Time of day"><select id="daylen" aria-label="Length of a day"><option value="120">day 2 min</option><option value="240" selected>day 4 min</option><option value="720">day 12 min</option></select>';side.appendChild(tw);
const tsl=document.getElementById('tslider'),tlab=document.getElementById('tlabel'),dsel=document.getElementById('daylen');let dragging=false;
tsl.addEventListener('pointerdown',()=>{dragging=true;});addEventListener('pointerup',()=>{dragging=false;});tsl.addEventListener('input',()=>setHour(parseFloat(tsl.value)));
dsel.addEventListener('change',()=>{const h=hourCur;DAY=+dsel.value;setHour(h);});
const hud=document.createElement('pre');hud.id='hud';side.appendChild(hud);let hudT=0,tbTxt='';
animHooks.push(now=>{if(now-hudT<200)return;hudT=now;const h=hourCur,t=`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.floor((h%1)*60)).padStart(2,'0')}`;if(!dragging)tsl.value=h.toFixed(2);if(t!==tbTxt){tbTxt=t;tlab.textContent=t;}
  hud.textContent=`${t}\ntarget  x ${ctl.target.x.toFixed(0)}  z ${ctl.target.z.toFixed(0)}\n${districtAt(ctl.target.x,ctl.target.z).name}`+(RES.cur<RES.max-0.01?`\nrender  ×${RES.cur.toFixed(2)}`:'');});
const ray=new THREE.Raycaster(),ndc=new THREE.Vector2();
function clickAt(cx,cy){ndc.set(cx/innerWidth*2-1,-(cy/innerHeight)*2+1);ray.setFromCamera(ndc,camera);const hits=ray.intersectObjects(LANDMARKS,true);if(!hits.length){closeCard();return;}
  let o=hits[0].object,info=null;while(o&&!info){info=o.userData.info;o=o.parent;}if(!info)return;showCard(info);}
function showCard(L){card.innerHTML='';const h=document.createElement('h2');h.textContent=L.name;const p=document.createElement('p');p.textContent=L.info||'';const b=document.createElement('button');b.type='button';b.textContent='Close';b.onclick=closeCard;card.append(h,p,b);card.classList.add('open');card.style.display='block';b.focus();}
function closeCard(){card.classList.remove('open');card.style.display='';}
// the address keeps the view and the hour, like the Iziz page: #v=px,py,pz,tx,ty,tz&t=hour
function stateToHash(){const r1=x=>Math.round(x*10)/10,p=camera.position,t=ctl.target;return '#'+(SEED0!==SEED_DEFAULT?'seed='+SEED0+'&':'')+'v='+[p.x,p.y,p.z,t.x,t.y,t.z].map(r1).join(',')+'&t='+(Math.round(hourCur*20)/20)+(clockPaused?'&paused':'');}
function readHash(){let q;try{q=new URLSearchParams(location.hash.slice(1));}catch(e){return false;}if(!q.has('v'))return false;const v=(q.get('v')||'').split(',').map(Number);if(v.length===6&&v.every(Number.isFinite))setView(...v,false);
  const t=parseFloat(q.get('t'));if(Number.isFinite(t))setHour(((t%24)+24)%24);if(q.has('paused')&&!clockPaused)pauseBtn.click();return true;}
let lastHash='',hashT=0;animHooks.push(now=>{if(now-hashT<1500||ctl.goal||ptrs.size)return;hashT=now;const h=stateToHash();if(h!==lastHash){lastHash=h;try{history.replaceState(null,'',h);}catch(e){}}});
if(!readHash())setView(...VIEWS['Skyline from the lake'],false);
{const hint=document.getElementById('hint');const hide=()=>hint.classList.add('gone');setTimeout(hide,12000);el.addEventListener('pointerdown',hide,{once:true});el.addEventListener('wheel',hide,{once:true,passive:true});}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);updatePx();});
if(SEED0!==SEED_DEFAULT)document.getElementById('seedtag').textContent='seed '+SEED0;
// shadows follow the target; compile everything behind the loading text
await stage('shaders');
section('shaders',()=>{applyCam();sun.target.position.copy(ctl.target);renderer.compile(scene,camera);renderer.render(scene,camera);});
stage('done');ctx.timings=LOAD.times;ctx.loadMs=Math.round(performance.now()-LOAD.t0);if(/debug/.test(location.search))console.table(LOAD.times);
document.getElementById('loading').remove();
renderer.shadowMap.autoUpdate=false;const shadowAt=new THREE.Vector3(1e9,0,0);let shadowTick=0;
function shadowsDue(){if(sun.intensity<=0.02)return false;if(ctl.target.distanceToSquared(shadowAt)>4){shadowAt.copy(ctl.target);sun.target.position.copy(ctl.target);sun.position.copy(ENV.izSunDir.value).multiplyScalar(2500).add(ctl.target);return true;}return (++shadowTick%3)===0;}
// adaptive resolution, as on the Iziz page
const RES={max:Math.min(devicePixelRatio,1.5),cur:Math.min(devicePixelRatio,1.5),min:0.6,acc:0,n:0,good:0,bad:0,prev:performance.now()};
function adaptRes(now){const dt=(now-RES.prev)/1000;RES.prev=now;if(dt>0.5||document.hidden)return;RES.acc+=dt;RES.n++;if(RES.acc<1)return;const fps=RES.n/RES.acc;RES.acc=0;RES.n=0;
  if(fps<45){RES.bad++;RES.good=0;}else if(fps>56){RES.good++;RES.bad=0;}let next=RES.cur;if(RES.bad>=2){next=Math.max(RES.min,RES.cur-0.15);RES.bad=0;}else if(RES.good>=8&&RES.cur<RES.max){next=Math.min(RES.max,RES.cur+0.1);RES.good=0;}
  if(Math.abs(next-RES.cur)>1e-3){RES.cur=+next.toFixed(2);renderer.setPixelRatio(RES.cur);renderer.setSize(innerWidth,innerHeight);updatePx();}}
ctx.res=RES;let fpsN=0,fpsT=performance.now(),renderErr=false;
(function animate(){requestAnimationFrame(animate);try{const now=performance.now();adaptRes(now);fpsN++;if(now-fpsT>1000){ctx.fps=fpsN;fpsN=0;fpsT=now;}
  for(const f of animHooks){try{f(now);}catch(e){if(!f._failed){f._failed=true;report('update',e);}}}stepFly(now);applyKeys();applyCam();if(shadowsDue())renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera);}catch(e){if(!renderErr){renderErr=true;report('render',e);}}})();
}
