// The wave field's Godot include, from core/atmos itself: ATMOS.waveGLSL() (89-atmos-a-waves.js, written from
// PRESETS.waves) translated to Godot shading language. The uniforms atmWaveT and atmWaveAmp become the global shader
// parameters atm_wave_t and atm_wave_amp (project.godot, set by the Atmos autoload); the functions keep their bodies
// and take snake_case names: atm_wave_height(xz, chopW), atm_wave_slope(xz, camDist), atm_wave_normal(xz, camDist, k).
//   node godot/tools/atmos_waves.js            (writes godot/shaders/atmos_waves.gdshaderinc; rerun after changing
//                                               PRESETS.waves or the chunk; atmos_golden.js keeps a copy to catch drift)
//   node godot/tools/atmos_waves.js --print    (prints it instead)
const fs = require('fs'), path = require('path');
const DIR = path.join(__dirname, '..', '..', 'core', 'atmos');
const OUT = path.join(__dirname, '..', 'shaders', 'atmos_waves.gdshaderinc');

function load() {
  if (global.ATMOS && global.ATMOS.waveGLSL) return global.ATMOS;
  const FRAGS = fs.readdirSync(DIR).filter(f => /^89-atmos-.*\.js$/.test(f)).sort();
  global.window = global;
  eval(FRAGS.map(f => fs.readFileSync(path.join(DIR, f), 'utf8')).join('\n') + ';global.ATMOS=ATMOS;');
  return global.ATMOS;
}

// atmWaveSlope -> atm_wave_slope, atmWaveT -> atm_wave_t
const snake = s => s.replace(/\batmWave([A-Z]\w*)\b/g, (m, r) => 'atm_wave_' + r.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase());

function gdshaderinc() {
  const A = load(), glsl = A.waveGLSL();
  const UNI = 'uniform float atmWaveT;uniform float atmWaveAmp;';
  if (!glsl.startsWith(UNI + '\n')) throw new Error('waveGLSL() no longer starts with its two uniforms: update the translation');
  const body = snake(glsl.slice(UNI.length + 1));
  for (const bad of [/\bTIME\b/, /\buniform\b/, /\batmWave/, /\bgl_/, /\bprecision\b/, /#/])
    if (bad.test(body)) throw new Error('untranslated GLSL in the wave chunk: ' + bad);
  return ['// GENERATED by godot/tools/atmos_waves.js from core/atmos/89-atmos-a-waves.js (ATMOS.waveGLSL(), PRESETS.waves).',
    '// Do not edit: rerun   node godot/tools/atmos_waves.js   after changing either. core/atmos/GODOT.md, "The wave field".',
    '// The open-water wave field: atm_wave_height(xz, chopW) metres to add to VERTEX.y (world xz; the swell, plus the chop',
    '// where chopW > 0, a fine mesh only); atm_wave_slope(xz, camDist) (dh/dx, dh/dz, crest 0..1, 0.5 still) for shading;',
    '// atm_wave_normal(xz, camDist, k) the shading normal, tilt scaled by k. The CPU twin is krator/atmos.gd',
    '// (Atmos.wave_height, wave_slope). The clock is atm_wave_t (the module clock wrapped at presets.waves.period), never TIME.',
    '#ifndef ATMOS_WAVES_INC',
    '#define ATMOS_WAVES_INC',
    'global uniform float atm_wave_t;',
    'global uniform float atm_wave_amp;',
    body,
    '#endif',
    ''].join('\n');
}

module.exports = { gdshaderinc, load };

if (require.main === module) {
  const s = gdshaderinc();
  if (process.argv.includes('--print')) process.stdout.write(s);
  else { fs.writeFileSync(OUT, s); console.log('wrote godot/shaders/atmos_waves.gdshaderinc:', s.length, 'bytes'); }
}
