// The cloud deck's Godot include, from core/atmos itself: ATMOS.deckGLSL() (89-atmos-d-clouddeck.js, written from
// PRESETS.clouddeck) translated to Godot shading language. The uniform atmDeckT becomes the global shader parameter
// atm_deck_t (project.godot, set by the Atmos autoload); the functions keep their bodies and take snake_case names:
// atm_deck_height(xz, y), atm_deck_slope(xz, camDist), atm_deck_normal(slope).
//   node godot/tools/atmos_clouddeck.js            (writes godot/shaders/atmos_clouddeck.gdshaderinc; rerun after changing
//                                                   PRESETS.clouddeck or the chunk; atmos_golden.js keeps a copy to catch drift)
//   node godot/tools/atmos_clouddeck.js --print    (prints it instead)
const fs = require('fs'), path = require('path');
const OUT = path.join(__dirname, '..', 'shaders', 'atmos_clouddeck.gdshaderinc');
const { load } = require('./atmos_waves.js');

// atmDeckSlope -> atm_deck_slope, atmDeckT -> atm_deck_t
const snake = s => s.replace(/\batmDeck([A-Z]\w*)\b/g, (m, r) => 'atm_deck_' + r.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase());

function gdshaderinc() {
  const A = load();
  if (!A.deckGLSL) throw new Error('core/atmos has no deckGLSL(): is 89-atmos-d-clouddeck.js there?');
  const glsl = A.deckGLSL(), UNI = 'uniform float atmDeckT;';
  if (!glsl.startsWith(UNI + '\n')) throw new Error('deckGLSL() no longer starts with its uniform: update the translation');
  const body = snake(glsl.slice(UNI.length + 1));
  for (const bad of [/\bTIME\b/, /\buniform\b/, /\batmDeck/, /\bgl_/, /\bprecision\b/, /#/])
    if (bad.test(body)) throw new Error('untranslated GLSL in the cloud deck chunk: ' + bad);
  return ['// GENERATED by godot/tools/atmos_clouddeck.js from core/atmos/89-atmos-d-clouddeck.js (ATMOS.deckGLSL(), PRESETS.clouddeck).',
    '// Do not edit: rerun   node godot/tools/atmos_clouddeck.js   after changing either. core/atmos/GODOT.md, "The cloud deck".',
    '// The cloud deck: atm_deck_height(xz, y) the deck\'s top in metres at world xz for a deck at level y;',
    '// atm_deck_slope(xz, camDist) (dh/dx, dh/dz, the crest 0..1, the detail\'s crest 0..1) for shading, the detail faded by',
    '// camera distance; atm_deck_normal(slope) the shading normal. The CPU twin is krator/atmos.gd (Atmos.deck_height,',
    '// deck_slope). The clock is atm_deck_t (the module clock wrapped at presets.clouddeck.period), never TIME.',
    '#ifndef ATMOS_CLOUDDECK_INC',
    '#define ATMOS_CLOUDDECK_INC',
    'global uniform float atm_deck_t;',
    body,
    '#endif',
    ''].join('\n');
}

module.exports = { gdshaderinc };

if (require.main === module) {
  const s = gdshaderinc();
  if (process.argv.includes('--print')) process.stdout.write(s);
  else { fs.writeFileSync(OUT, s); console.log('wrote godot/shaders/atmos_clouddeck.gdshaderinc:', s.length, 'bytes'); }
}
