// ================================================================= FURNITURE: placed from the catalog (core/furnish), not drawn by the kit
// Everything in or round a tent that is not the tent itself (cushions, rugs, toshaks, tray tables, lanterns, stoves, chests,
// saddle racks, the forge and anvil, the tethering post) is a master-catalog piece (kits/catalog, the Zeijani culture file
// krator-master-furniture-zeijani.js and its fallbacks), placed as data and built by the catalog's own code through
// KratorFurniture (38-furniture-bundle.js, generated by build.py), merged into one mesh per render family for the page.
// A builder calls, in its CURRENT frame:
//   FURNISH(key, lx, ly, lz, lry, {v, seed, setting})     a piece standing at (lx, ly, lz), its front turned lry
//   FURNISH_HANG(key, lx, topY, lz, lry, o)               a ceiling piece whose top is at topY (its declared height subtracted)
// Each record is on its building's REG record (rec.furniture) and in core/tags as class furniture with the building as parent.
// A key the catalog lacks is counted, not thrown (ZJF.missing, _api.furniture().missing). ?furniture=0 places nothing drawn.
KratorFurniture.setDetail(.6);
const ZJF=KFURN.create(Object.assign(KFURN.flags(false),{
 catalog:KFURN.catalogOf(KratorFurniture),interiors:null,
 seed:(o,ctx)=>ctx.seed*100+ctx.list.length+1,
 draw:(rec,ctx)=>{const r=KFURN.drawRec(ZJF,rec,ctx.wealth);if(r.error)reportErr('furniture '+rec.key+': '+r.error);
  /* the piece's lights become halos (91n-night.js): fires big and warm, lamps small */
  const fire=/fire|brazier|stove|forge|cauldron|smoke|kiln/.test(rec.key);
  for(const L of (r.lights||[])){const k=Math.round(L.x/.6)+','+Math.round(L.y/.6)+','+Math.round(L.z/.6);if(HALOKEY.has(k))continue;HALOKEY.add(k);
   const c=hc(fire?0xff8a30:0xffc878);HALOS.push({x:L.x,y:L.y,z:L.z,r:c.r,g:c.g,b:c.b,big:fire});}}}));
ZJF.WEALTH={};   // a def's 0..1 wealth for its furniture (its tags.wealth name, or .5)
function svfNewBatch(){KFURN.useBatch(ZJF,KratorFurniture,null);ZJF.placed=[];ZJF.missing={};ZJF.cfg.tags=ZJTAGS;}
function svfWealth(rec){const w=rec&&rec.tags&&rec.tags.wealth;return w==='rich'?.9:w==='poor'?.25:w==='middle'?.55:.55;}
function FURNISH(key,lx,ly,lz,lry,o){o=o||{};if(!CURREC){reportErr('FURNISH '+key+' outside a builder');return null;}
 if(PLACE_DRY)return null;lry=lry||0;
 if(!KratorFurniture.has(key)){ZJF.missing[key]=(ZJF.missing[key]||0)+1;return null;}
 const w=new THREE.Vector3(lx,ly||0,lz).applyMatrix4(CM),e=CM.elements,wry=Math.atan2(e[8],e[10])+lry;
 const c=CURREC;const seed=(DEFS[c.key].seed*7+(c.v|0)*131+(((Math.round(c.x*10)*73856093)^(Math.round(c.z*10)*19349663))>>>0)%9973)>>>0;
 return ZJF.place(key,w.x,w.y,w.z,wry,Object.assign({setting:'indoor'},o),[lx,ly||0,lz,lry],{building:c.tid,list:c.furniture,seed:seed,wealth:svfWealth(c)});}
function FURNISH_HANG(key,lx,topY,lz,lry,o){const A=KratorFurniture.FURN_BY_KEY[key];if(!A){if(!PLACE_DRY)ZJF.missing[key]=(ZJF.missing[key]||0)+1;return null;}
 const dm=KratorFurniture.entryDims(A,(o&&o.v)|0);return FURNISH(key,lx,topY-dm.h,lz,lry,o);}
/* the height of a catalog piece (a table top for a tea set): its declared h, or the fallback */
function svfH(key,v,dflt){const A=KratorFurniture.FURN_BY_KEY[key];return A?KratorFurniture.entryDims(A,v|0).h:dflt;}
/* ---- DETAIL MAPS on the furniture (after settlements/girder/src/48-detail.js). The catalog's merged meshes are vertex-coloured and
   carry no UVs, so a library set reaches them as a detail map sampled by TRIPLANAR projection of the world position (three planar
   maps blended by the normal): no UVs, no shear. materials.json f_<family> names the set per render family; its brightness is
   normalised to `mean` by the packer and divided back out here, so the vertex colour keeps the piece's colour and the set adds its
   weave, grain, tooling or patina. ?mat=proc attaches nothing. Godot: StandardMaterial3D's triplanar does the same. */
function svfDetail(mt){const tf=mt.userData.texFamily,Lt=KMAT.mode==='lib'&&tf?KMAT.packed('zeijani','f_'+tf):null,fam=Lt&&Lt.map?tf:mt.userData.family,L=Lt&&Lt.map?Lt:KMAT.mode==='lib'&&fam?KMAT.packed('zeijani','f_'+fam):null;if(!L||!L.map||mt.isMeshBasicMaterial)return false;
 const T=KMAT.textures(L,{aniso:TEXANISO}),gain=1/Math.max(.05,Math.pow(L.mean==null?.5:L.mean,2.2)),tile=1/((L.scale&&L.scale[0])||1);
 mt.map=T.map;if(T.normalMap&&!mt.transparent){mt.normalMap=null;}
 matHook(mt,'fdet|'+fam,sh=>{sh.uniforms.uDetTile={value:tile};sh.uniforms.uDetGain={value:gain};
  sh.vertexShader=sh.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vDetP;varying vec3 vDetN;').replace('#include <uv_vertex>','#include <uv_vertex>\nvDetP=position;vDetN=normal;');
  sh.fragmentShader=sh.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vDetP;varying vec3 vDetN;uniform float uDetTile;uniform float uDetGain;')
   .replace('#include <map_fragment>',['#ifdef USE_MAP','vec3 dW=pow(abs(normalize(vDetN))+1e-4,vec3(4.0));dW/=(dW.x+dW.y+dW.z);vec3 dP=vDetP*uDetTile;',
    'vec4 texelColor=texture2D(map,dP.zy)*dW.x+texture2D(map,dP.xz)*dW.y+texture2D(map,dP.xy)*dW.z;texelColor=mapTexelToLinear(texelColor);',
    'diffuseColor.rgb*=texelColor.rgb*uDetGain;','#endif'].join('\n'));});
 return true;}
// ---- the batch becomes meshes once per world build, after every def is placed
const svfBuildWorld=buildWorld;
buildWorld=function(){zjTagsReset();svfNewBatch();const t0=performance.now();const W0=svfBuildWorld();
 const g=ZJF.group=ZJF.batch.flush(WORLD);g.userData.furniture=true;
 ZJF.detailed=[];g.traverse(m=>{if(m.isMesh){const f=m.material.userData.family;m.castShadow=f!=='glow'&&f!=='glass';m.receiveShadow=true;KFURN.linearColours(m.geometry);if(!m.material.map&&svfDetail(m.material))ZJF.detailed.push(f);}});
 if(window._build)window._build.furniture={placed:ZJF.placed.length,tris:Math.round(ZJF.batch.tris),missing:Object.assign({},ZJF.missing),ms:Math.round(performance.now()-t0)};
 if(typeof nightRebuild==='function')nightRebuild();
 return W0;};
