// ================================================================= FURNITURE: placed from the catalog (core/furnish), not drawn by the kit
// Everything in or round a tent that is not the tent itself (cushions, rugs, toshaks, tray tables, lanterns, stoves, chests,
// saddle racks, the forge and anvil, the tethering post) is a master-catalog piece (kits/catalog, the Zeijani culture file
// krator-master-furniture-zeijani.js and its fallbacks), placed as data and built by the catalog's own code through
// KratorFurniture (38-furniture-bundle.js, generated by build.py), merged into one mesh per render family for the page.
// A builder calls, in its CURRENT frame:
//   FURNISH(key, lx, ly, lz, lry, {v, seed, setting})     a piece standing at (lx, ly, lz), its front turned lry
//   FURNISH_HANG(key, lx, topY, lz, lry, o)               a ceiling piece whose top is at topY (its declared height subtracted)
// Each record is on its building's REG record (rec.furniture) and in core/tags as class furniture with the building as parent.
// A key the catalog lacks is counted, not thrown (ZJF.missing, _api.furniture().missing). ?furniture=0 places nothing drawn.
KratorFurniture.setDetail(.6);
const ZJF=KFURN.create(Object.assign(KFURN.flags(true),{
 catalog:KFURN.catalogOf(KratorFurniture),interiors:KratorInteriors,
 seed:(o,ctx)=>ctx.seed*100+ctx.list.length+1,
 draw:(rec,ctx)=>{const r=KFURN.drawRec(ZJF,rec,ctx.wealth);if(r.error)reportErr('furniture '+rec.key+': '+r.error);
  /* the piece's lights become halos (91n-night.js): fires big and warm, lamps small */
  const fire=/fire|brazier|stove|forge|cauldron|smoke|kiln/.test(rec.key);
  for(const L of (r.lights||[])){const k=Math.round(L.x/.6)+','+Math.round(L.y/.6)+','+Math.round(L.z/.6);if(HALOKEY.has(k))continue;HALOKEY.add(k);
   const c=hc(fire?0xff8a30:0xffc878);HALOS.push({x:L.x,y:L.y,z:L.z,r:c.r,g:c.g,b:c.b,big:fire});}}}));
ZJF.WEALTH={};   // a def's 0..1 wealth for its furniture (its tags.wealth name, or .5)
function svfNewBatch(){KFURN.useBatch(ZJF,KratorFurniture,KratorInteriors);ZJF.placed=[];ZJF.missing={};ZJF.cfg.tags=ZJTAGS;ZJF.rooms=[];ZJF.interiorPieces=0;}
/* ---- INTERIORS: every def whose key has an item in kits/interiors/sets/zeijani.js gets its rooms planned and furnished at
   its placement (core/furnish's R.interior over the interiors kit). The runtime adapter draws into the batch without a
   record, so this wrapper registers what the interiors place, before it is drawn (GODOT-PLAN.md rule 4): each room as a
   `part` of its building (kind room, tags.room its kind), each piece as `furniture` with its room as parent. */
function zjItem(key){const S=KratorInteriors.sets.byName.zeijani;const it=S&&S.byKey[key];return it&&!it.skip?it:null;}
function zjTagAdapter(base,rec){const roomTid={};
 return Object.assign({},base,{build:(p,room)=>{let parent=rec.tid;
   if(room&&ZJTAGS){if(!roomTid[room.id]){const t=ZJTAGS.child(rec.tid,{'class':'part',kind:'room',key:room.id,name:(room.kind||'room')+' of '+rec.name,
      at:[room.centroid[0],room.y,room.centroid[1]],ry:rec.ry,tags:{room:room.kind,culture:'zeijani',setting:'room'},note:Math.round(room.area)+' m2',frag:'kits/interiors/sets/zeijani.js'});
     roomTid[room.id]=t.id;ZJF.rooms.push({id:room.id,kind:room.kind,building:rec.key,tid:t.id,area:room.area});}parent=roomTid[room.id];}
   const A=KratorFurniture.FURN_BY_KEY[p.key];
   if(ZJTAGS)ZJTAGS.child(parent,{'class':'furniture',kind:A?A.type:'piece',key:p.key,name:A?A.name:p.key,at:[p.x,p.y,p.z],ry:p.ry,
     tags:{culture:A&&A.culture||'zeijani',setting:'room',room:room?room.kind:null,job:A&&A.job||undefined},frag:'kits/catalog'});
   ZJF.interiorPieces++;return base.build(p,room);}});}
/* a carved room is furnished in its outline drawn in 0.25 m: the cavern's walls round its corners and bulge at the floor (the fillet,
   a cell's wander), so a piece set against the straight outline would stand in the rock */
const ZJ_FURNITEM={};
function zjFurnishItem(it){if(ZJ_FURNITEM[it.key])return ZJ_FURNITEM[it.key];const cv=r=>r.carved===true||(it.carved&&r.carved!==false);
 if(!(it.rooms||[]).some(cv))return ZJ_FURNITEM[it.key]=it;
 /* each door moves to the nearest point of the inset outline (a door must lie within 0.6 m of a wall) */
 const near=(P,q)=>{let b=null,bd=1e9;for(let i=0;i<P.length;i++){const a=P[i],c=P[(i+1)%P.length],dx=c[0]-a[0],dz=c[1]-a[1],L2=dx*dx+dz*dz||1,t=Math.max(0,Math.min(1,((q[0]-a[0])*dx+(q[1]-a[1])*dz)/L2)),x=a[0]+dx*t,z=a[1]+dz*t,d=(x-q[0])**2+(z-q[1])**2;if(d<bd){bd=d;b=[x,z];}}return b;};
 return ZJ_FURNITEM[it.key]=Object.assign({},it,{rooms:it.rooms.map(r=>{if(!cv(r))return r;const P=KCAVERN.insetPoly(r.poly,.25);
  return Object.assign({},r,{poly:P,doors:(r.doors||[]).map(d=>Object.assign({},d,{at:near(P,d.at)}))});})});}
function zjInteriors(){if(!ZJF.on||!ZJF.cfg.interiorsOn)return;for(const rec of REG){if(rec.parent)continue;const it0=zjItem(rec.key);if(!it0)continue;const it=zjFurnishItem(it0);
  try{const fi=ZJF.interior(it,rec.x,rec.z,rec.ry,zjTagAdapter(ZJF.adapter,rec),{baseY:rec.y,prefix:zwPrefix(rec)});rec.interior=fi.summary;
   fi.result.inst.rooms.forEach(R=>{const P=fi.result.plans[R.id];(P&&P.lights||[]).forEach(l=>{const k=Math.round(l.x/.6)+','+Math.round(l.y/.6)+','+Math.round(l.z/.6);
    if(!HALOKEY.has(k)){HALOKEY.add(k);const c=hc(0xffc878);HALOS.push({x:l.x,y:l.y,z:l.z,r:c.r,g:c.g,b:c.b,big:false});}});});}
  catch(e){reportErr('interior '+rec.key+': '+(e&&e.stack||e));}}}
function svfWealth(rec){const w=rec&&rec.tags&&rec.tags.wealth;return w==='rich'?.9:w==='poor'?.25:w==='middle'?.55:.55;}
function FURNISH(key,lx,ly,lz,lry,o){o=o||{};if(!CURREC){reportErr('FURNISH '+key+' outside a builder');return null;}
 if(PLACE_DRY)return null;lry=lry||0;
 if(!KratorFurniture.has(key)){ZJF.missing[key]=(ZJF.missing[key]||0)+1;return null;}
 const w=new THREE.Vector3(lx,ly||0,lz).applyMatrix4(CM),e=CM.elements,wry=Math.atan2(e[8],e[10])+lry;
 const c=CURREC;const seed=(DEFS[c.key].seed*7+(c.v|0)*131+(((Math.round(c.x*10)*73856093)^(Math.round(c.z*10)*19349663))>>>0)%9973)>>>0;
 return ZJF.place(key,w.x,w.y,w.z,wry,Object.assign({setting:'indoor'},o),[lx,ly||0,lz,lry],{building:c.tid,list:c.furniture,seed:seed,wealth:svfWealth(c)});}
function FURNISH_HANG(key,lx,topY,lz,lry,o){const A=KratorFurniture.FURN_BY_KEY[key];if(!A){if(!PLACE_DRY)ZJF.missing[key]=(ZJF.missing[key]||0)+1;return null;}
 const dm=KratorFurniture.entryDims(A,(o&&o.v)|0);return FURNISH(key,lx,topY-dm.h,lz,lry,o);}
/* the height of a catalog piece (a table top for a tea set): its declared h, or the fallback */
function svfH(key,v,dflt){const A=KratorFurniture.FURN_BY_KEY[key];return A?KratorFurniture.entryDims(A,v|0).h:dflt;}
/* ---- DETAIL MAPS on the furniture (after settlements/girder/src/48-detail.js). The catalog's merged meshes are vertex-coloured and
   carry no UVs, so a library set reaches them as a detail map sampled by TRIPLANAR projection of the world position (three planar
   maps blended by the normal): no UVs, no shear. materials.json f_<family> names the set per render family; its brightness is
   normalised to `mean` by the packer and divided back out here, so the vertex colour keeps the piece's colour and the set adds its
   weave, grain, tooling or patina. ?mat=proc attaches nothing. Godot: StandardMaterial3D's triplanar does the same. */
function svfDetail(mt){const tf=mt.userData.texFamily,Lt=KMAT.mode==='lib'&&tf?KMAT.packed('zeijani','f_'+tf):null,fam=Lt&&Lt.map?tf:mt.userData.family,L=Lt&&Lt.map?Lt:KMAT.mode==='lib'&&fam?KMAT.packed('zeijani','f_'+fam):null;if(!L||!L.map||mt.isMeshBasicMaterial)return false;
 const T=KMAT.textures(L,{aniso:TEXANISO}),gain=1/Math.max(.05,Math.pow(L.mean==null?.5:L.mean,2.2)),tile=1/((L.scale&&L.scale[0])||1);
 mt.map=T.map;if(T.normalMap&&!mt.transparent){mt.normalMap=null;}
 matHook(mt,'fdet|'+fam,sh=>{sh.uniforms.uDetTile={value:tile};sh.uniforms.uDetGain={value:gain};
  sh.vertexShader=sh.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vDetP;varying vec3 vDetN;').replace('#include <uv_vertex>','#include <uv_vertex>\nvDetP=position;vDetN=normal;');
  sh.fragmentShader=sh.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vDetP;varying vec3 vDetN;uniform float uDetTile;uniform float uDetGain;')
   .replace('#include <map_fragment>',['#ifdef USE_MAP','vec3 dW=pow(abs(normalize(vDetN))+1e-4,vec3(4.0));dW/=(dW.x+dW.y+dW.z);vec3 dP=vDetP*uDetTile;',
    'vec4 texelColor=texture2D(map,dP.zy)*dW.x+texture2D(map,dP.xz)*dW.y+texture2D(map,dP.xy)*dW.z;texelColor=mapTexelToLinear(texelColor);',
    'diffuseColor.rgb*=texelColor.rgb*uDetGain;','#endif'].join('\n'));});
 return true;}
/* a painted hanging (F.decal: its own canvas map) gets the cloth's weave from the library (f_cloth), projected in world space as
   the detail maps are, so a banner reads as cloth and not paint on glass */
function svfWeave(mt){const L=KMAT.mode==='lib'?KMAT.packed('zeijani','f_cloth'):null;if(!L||!L.map||mt.userData.weave)return;mt.userData.weave=true;
 const T=KMAT.textures(L,{aniso:TEXANISO}),gain=1/Math.max(.05,Math.pow(L.mean==null?.5:L.mean,2.2)),tile=1/((L.scale&&L.scale[0])||1);
 matHook(mt,'weave',sh=>{sh.uniforms.uWv={value:T.map};sh.uniforms.uWvT={value:tile};sh.uniforms.uWvG={value:gain};
  sh.vertexShader=sh.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vWvP;varying vec3 vWvN;').replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nvWvP=(modelMatrix*vec4(transformed,1.)).xyz;vWvN=normalize(mat3(modelMatrix)*objectNormal);');
  sh.fragmentShader=sh.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vWvP;varying vec3 vWvN;uniform sampler2D uWv;uniform float uWvT;uniform float uWvG;')
   .replace('#include <map_fragment>','#include <map_fragment>\n{vec3 w=pow(abs(normalize(vWvN))+1e-4,vec3(4.));w/=(w.x+w.y+w.z);vec3 p=vWvP*uWvT;vec3 t=texture2D(uWv,p.zy).rgb*w.x+texture2D(uWv,p.xz).rgb*w.y+texture2D(uWv,p.xy).rgb*w.z;diffuseColor.rgb*=mix(vec3(1.),mapTexelToLinear(vec4(t,1.)).rgb*uWvG,.8);}');});}
/* contact shadows: underground the sun casts none, so a piece on a carved floor reads as floating. A soft dark patch under every
   piece that stands on a floor (not on a surface, a wall or the ceiling; not a rug or a hanging), one merged mesh */
let ZJ_SHTEX=null;
function zjContactShadows(parent){if(!ZJ_SHTEX){ZJ_SHTEX=canvasTex(64,64,(g,w,h)=>{const r=g.createRadialGradient(w/2,h/2,0,w/2,h/2,w/2);r.addColorStop(0,'rgba(0,0,0,.62)');r.addColorStop(.55,'rgba(0,0,0,.4)');r.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=r;g.fillRect(0,0,w,h);});ZJ_SHTEX.wrapS=ZJ_SHTEX.wrapT=THREE.ClampToEdgeWrapping;}
 let q=ZJTAGS.query({});q=Array.isArray(q)?q:Object.values(q);const pos=[],uv=[],F=KratorFurniture.FURN_BY_KEY;
 for(const r of q){if(r.class!=='furniture'||!r.at)continue;const A=F[r.key];if(!A)continue;const an=A.anchor||'floor',t=A.type;
  if(an==='surface'||an==='ceiling'||t==='rug'||t==='banner'||t==='art'||t==='lamp'&&an==='wall')continue;
  const dm=KratorFurniture.entryDims(A,0),hw=dm.w/2+.16,hd=dm.d/2+.16,c=Math.cos(r.ry||0),s=Math.sin(r.ry||0),y=r.at[1]+.012;
  const P=[[-hw,-hd],[hw,-hd],[hw,hd],[-hw,hd]].map(([x,z])=>[r.at[0]+x*c+z*s,y,r.at[2]-x*s+z*c]);
  for(const k of [0,1,2,0,2,3]){pos.push(...P[k]);uv.push(k===0||k===3?0:1,k<2?0:1);}}
 if(!pos.length)return;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));
 const m=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({map:ZJ_SHTEX,transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2,side:THREE.DoubleSide}));
 m.userData.probeSkip=true;m.raycast=()=>{};m.renderOrder=1;parent.add(m);ZJF.shadowPatches=pos.length/18;}
// ---- the batch becomes meshes once per world build, after every def is placed
const svfBuildWorld=buildWorld;
buildWorld=function(){zjTagsReset();svfNewBatch();const t0=performance.now();const W0=svfBuildWorld();zjInteriors();
 const g=ZJF.group=ZJF.batch.flush(WORLD);g.userData.furniture=true;
 ZJF.detailed=[];g.traverse(m=>{if(m.isMesh){const f=m.material.userData.family;m.castShadow=f!=='glow'&&f!=='glass';m.receiveShadow=true;KFURN.linearColours(m.geometry);if(!m.material.map&&svfDetail(m.material))ZJF.detailed.push(f);else if(m.material.map&&m.name==='furniture:decal')svfWeave(m.material);}});
 zjContactShadows(g);
 if(window._build)window._build.furniture={placed:ZJF.placed.length,interiorPieces:ZJF.interiorPieces,rooms:ZJF.rooms.length,tris:Math.round(ZJF.batch.tris),missing:Object.assign({},ZJF.missing),ms:Math.round(performance.now()-t0)};
 if(typeof nightRebuild==='function')nightRebuild();
 return W0;};
