/* ============================== 13a. FURNITURE: PLACED from the catalog, not drawn ==============================
   Everything a builder puts in or around a building that is not the building itself (walls, floors, roofs,
   stairs, decks, galleries, rails, fences, built-in masonry, facade signs and banners, outbuildings) is
   FURNITURE: a master-catalog piece (kits/catalog), placed as DATA and built by the catalog's own code through
   KratorFurniture (52, generated by build.py: kits/catalog/furniture_bundle.py), merged into one mesh per render
   family for the whole world and added to the scene when the kit is emitted (75-terrain.js). A builder calls
     brfUse(f, y);  FURNISH(key, lx, ly, lz, lry, {v, seed, setting, lamp})    in a FRM frame (55-arch): +z = f's
                                                                              front (fx,fz), +x = its right (-fz,fx)
     FURNISH_AT(key, x, y, z, ry, {...})                                       in world space; ry is three.js
                                                                              rotation.y, the piece's front is +z
   o.v is the catalog variant; o.lamp = [amp, rad, cool, maxLights] registers the piece's own lights (the catalog
   keeps them as data) in the night light volume, as LANTERN() did. Each call returns the placement record
   (core/furnish) {id, key, variant, seed, lx, ly, lz, lry, x, y, z, ry, building, setting, room, job}; kept in BRF.placed and on
   the open building (brfIn(name) ... brfDone(site): site.furniture). A key the catalog lacks is counted in
   BRF.missing, never thrown. ?furniture=0 places nothing (the records are still kept).
   Interiors: the rooms inside the buildings and the levels are 57a-interiors.js (each builder's own shell, planned
   by the interiors kit and kept as records) and 57c (drawn near the camera); ?interiors=0 turns them off. */
KratorFurniture.setDetail(.5);   /* settlement-scale: half the segments on round furniture parts */
/* the catalog recentred some harvested pieces on their footprint (F.shift(dx,dz) in the piece's build): the
   placement undoes it, so the piece stands where the builder drew it */
var BRF_SHIFT = { br_h_viewing_stand:[0,-0.1], br_h_reviewing_dais:[0,-0.36], br_h_speaker_rostrum:[0,-0.325],
  br_h_smithy_forge:function(v){ return v?null:[0.497,0]; }, br_h_banner_pole:[-0.5,0], br_market_stall:[0.04,-0.14],
  br_h_barrel_cluster:function(v){ return [-0.443, v?0.304:-0.069]; }, br_h_hitching_rail:function(v){ return v?null:[0.43,-0.43]; } };
/* the placement pass is core/furnish (50-core-furnish.js: the record, the recentring above, the missing count, the
   id); this is Mav's Refuge's adapter onto it: its seed rule (a hash of the spot), the open building, and the lamps */
var BRF = KFURN.create(Object.assign(KFURN.flags(true), {
  catalog: KFURN.catalogOf(KratorFurniture), interiors: KratorInteriors, shift: BRF_SHIFT,
  tags: (KTAGS.page = KTAGS.create({ build:'mavs-refuge' })),   /* every piece registered in core/tags (core/tags/README.md) */
  seed: function(o, ctx, R, x, y, z){ return 1 + Math.floor(phash(x, y, z, 7.7)*999983); },
  draw: function(rec, ctx, o){
    var w = o.wealth==null ? 0.5 : o.wealth;
    KFURN.drawRec(BRF, rec, w);
    if(o.lamp){
      var c = Math.cos(rec.ry), s = Math.sin(rec.ry), ls = KratorFurniture.lightsOf(rec.key, rec.variant, rec.seed, w), L = o.lamp, n = Math.min(ls.length, L[3]==null ? 99 : L[3]);
      for(var i=0;i<n;i++){ var l = ls[i]; nlLampAdd(rec.x + l.x*c + l.z*s, rec.y + l.y, rec.z - l.x*s + l.z*c, L[0], L[1], L[2]); BRF.lights++; }
    }
  }
}));
Object.assign(BRF, { cur: null, stack: [], frame: null });
KFURN.useBatch(BRF, KratorFurniture, KratorInteriors);
window._brf = BRF;                                                     /* read-only, for probes and the console */
/* the pieces the many small benches, tables and spear racks use (one place to trade look for triangles) */
var BRF_BENCH = 'br_bench', BRF_TABLE = 'br_table', BRF_SPEARS = 'br_weapon_rack';
function brfSkip(n){ for(var i=0;i<n;i++) rnd(); }                    /* draw what a removed drawing drew, so the stream after it does not move */
/* the building a builder is furnishing: brfIn(name) opens it (nested: the outer one comes back after), brfDone(site)
   hands its records to the REGISTER()ed site and closes it, brfIn(null) closes it without a site */
function brfIn(name){ if(name==null){ BRF.cur = BRF.stack.pop()||null; return null; } BRF.stack.push(BRF.cur); BRF.cur = { name:name, furniture:[] }; return BRF.cur; }
function brfDone(site){ if(BRF.cur && site) site.furniture = BRF.cur.furniture; BRF.cur = BRF.stack.pop()||null; return site; }
function brfUse(f, y){ BRF.frame = { x:f.x, z:f.z, y:y, fx:f.fx, fz:f.fz }; }
function brfHead(fx, fz){ return Math.atan2(fx, fz); }                 /* the ry that turns a piece's front (+z) to (fx,fz) */
function brfAlong(dx, dz){ return Math.atan2(-dz, dx); }               /* the ry that lays a piece's width (+x) along (dx,dz) */
function FURNISH(key, lx, ly, lz, lry, o){
  var f = BRF.frame;
  if(!f){ ERR('FURNISH '+key+' with no frame (brfUse)'); return null; }
  lx = lx||0; ly = ly||0; lz = lz||0; lry = lry||0;
  return brfPlace(key, f.x - f.fz*lx + f.fx*lz, f.y + ly, f.z + f.fx*lx + f.fz*lz, brfHead(f.fx, f.fz) + lry, o, [lx, ly, lz, lry]);
}
function FURNISH_AT(key, x, y, z, ry, o){ return brfPlace(key, x, y, z, ry||0, o, null); }
function brfPlace(key, x, y, z, ry, o, loc){
  o = o || {};
  return BRF.place(key, x, y, z, ry, o, loc, { building: BRF.cur ? BRF.cur.name : (o.building||'street'), list: BRF.cur ? BRF.cur.furniture : null });
}
/* the batch becomes meshes once, when the kit is emitted (75-terrain.js). Shaded like the kit: the kit's surfaces
   are vertex colour x a grayscale sRGB texture, the catalog's are bare vertex colour, so each furniture family is
   a Lambert material tinted by the mean (linear) brightness of the kit family it reads as, and takes the night
   light volume. brfMaterial(fam) is that material, one per family (the interiors, 57c, draw with the same ones) */
var BRF_FAM = { wood:'timber', plank:'plank', cloth:'cloth', hide:'cloth', stone:'rock', thatch:'thatch', leafy:'leafy', rope:'rope',
                ixwall:'wall', ixwood:'plank' };
var BRF_MAT = {};
function brfMaterial(fam){
  if(BRF_MAT[fam]) return BRF_MAT[fam];
  var kf = BRF_FAM[fam] || 'timber', tint = BRF.tint || (BRF.tint = {});
  var k = tint[kf] || (tint[kf] = brfTexMean(kf)), mt = new THREE.MeshLambertMaterial({ vertexColors:true, color:new THREE.Color(k, k, k) });
  mt.userData.family = fam;
  return (BRF_MAT[fam] = nlMaterial(mt, 'furn-'+fam));
}
function brfTexMean(fam){
  var t = FAMMAT[fam] && FAMMAT[fam].tex, c = t && t.image;
  if(!c || !c.getContext) return 0.5;
  var d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data, sum = 0, n = 0;
  for(var i=0;i<d.length;i+=32){ var v = d[i]/255; sum += v <= 0.04045 ? v/12.92 : Math.pow((v+0.055)/1.055, 2.4); n++; }
  return n ? sum/n : 0.5;
}
var brfEmit0 = emitBuckets;
emitBuckets = function(){
  var g = BRF.batch.flush(scene); BRF.group = g;
  g.children.forEach(function(m){
    var fam = m.material.userData.family;
    if(fam !== 'glow'){ m.material.dispose(); m.material = brfMaterial(fam); }
    else BRF_MAT.glow = m.material;
    m.castShadow = m.receiveShadow = !FAST; m.frustumCulled = false; m.userData.fam = 'Furniture';
  });
  var tris = 0; g.children.forEach(function(m){ var q = m.geometry; tris += (q.index ? q.index.count : q.attributes.position.count)/3; });
  window._furniture = { placed:BRF.placed.length, tris:tris|0, meshes:g.children.length, lights:BRF.lights, missing:BRF.missing,
                        interiors:BRF.buildings.length, interiorPieces:BRF.buildings.reduce(function(a,b){ return a+b.interior.pieces; }, 0),
                        byKey:BRF.placed.reduce(function(a,r){ a[r.key]=(a[r.key]||0)+1; return a; }, {}) };
  return brfEmit0();
};
