// ---------------------------------------------------------------- furniture: PLACED from the catalog, not drawn
// Everything a Post-Apoc builder puts in or around a building that is not the building itself (its reclaimed core, the additions
// lashed to it, its yard walls, fences, stairs and outbuildings) is FURNITURE: a master-catalog piece (kits/catalog, the harvested
// pa_* pieces in krator-master-furniture-scrap.js and -post-apoc.js), placed as data and built by the catalog's own code through
// KratorFurniture (38-furniture-bundle.js, generated by build.py), merged into one mesh per render family for the whole page.
// A builder (or a 34-adds helper: barrel, crate, sacks, lamp, fire, tireStack ...) calls, in its CURRENT frame (W() frames included):
//   FURNISH(key, lx, ly, lz, lry, {v, seed, setting, ax, az})   -> the placement record, also on the building's REG record (rec.furniture)
// (ax, az): the point of the PIECE (its own frame, metres) that lands on (lx, lz); a piece is centred on its footprint, so a lamp
// post whose pole is 0.23 m off its centre passes ax:-.23. Indoors, the rooms of every top-level building are the interiors kit's:
// its set (kits/interiors/sets/post-apoc.js) is planned and furnished through the same catalog with ?interiors=1 (off by default:
// the roofs hide it). ?furniture=0 places nothing (the records are still kept). A key the catalog lacks is counted, not thrown
// (PAF.missing, _api.furniture().missing).
KratorFurniture.setDetail(.5);   // settlement-scale: half the segments on round furniture parts
const PAF={on:!/[?&]furniture=0\b/.test(location.search),interiors:/[?&]interiors=1\b/.test(location.search),
 batch:null,adapter:null,group:null,placed:[],missing:{},buildings:[],cur:null,dry:0,
 FIRE:{pa_camp_fire:1,pa_forge:1,pa_brick_grill:1,pa_box_stove:1},   // their lights are fires (big halos), the rest lamps
 NOCOLL:{pa_lamp_post:1,pa_hanging_lamp:1,pa_goods_rail:1,pa_gibbet:1}};   // thin or hung: no collider
function pafNewBatch(){PAF.batch=KratorFurniture.batch();PAF.adapter=KratorInteriors.runtimeAdapter(KratorFurniture,PAF.batch);PAF.placed=[];PAF.missing={};PAF.buildings=[];}
pafNewBatch();
function pafWealth(key){const it=KratorInteriors.sets.find(key);return it&&it.wealth!=null?it.wealth:.3;}
function FURNISH(key,lx,ly,lz,lry,o){o=o||{};const c=PAF.cur;if(!c||!CURKEY){reportErr('FURNISH '+key+' outside a builder');return null;}
 lry=lry||0;if(!KratorFurniture.has(key)){if(!PAF.dry)PAF.missing[key]=(PAF.missing[key]||0)+1;return null;}
 if(o.ax||o.az){const ax=o.ax||0,az=o.az||0,cs=Math.cos(lry),sn=Math.sin(lry);lx-=ax*cs+az*sn;lz-=-ax*sn+az*cs;}
 const w=new THREE.Vector3(lx,ly,lz).applyMatrix4(CM),e=CM.elements,wry=Math.atan2(e[8],e[10])+lry;
 const b=w.clone().applyMatrix4(c.M0inv);   // the building's own frame (origin = plot centre on the ground, +z the front)
 const v=o.v|0,seed=o.seed||(c.seed*100+c.list.length+1);
 const rec={key,variant:v,seed,lx:+b.x.toFixed(3),ly:+b.y.toFixed(3),lz:+b.z.toFixed(3),lry:+(wry-c.ry).toFixed(4),x:w.x,y:w.y,z:w.z,ry:wry,building:CURKEY,setting:o.setting||'outdoor'};
 c.list.push(rec);
 if(!PAF.NOCOLL[key]){const A=KratorFurniture.FURN_BY_KEY[key],d=KratorFurniture.entryDims(A,v);if(d.h>=.3)collSolid(lx,ly,lz,d.w,d.h,d.d,lry,'furniture');}
 if(PAF.dry)return rec;
 PAF.placed.push(rec);
 if(PAF.on){const r=PAF.batch.place(key,w.x,w.y,w.z,wry,{variant:v,seed:seed,wealth:c.wealth,building:CURKEY,setting:rec.setting});
  if(r.error)reportErr('furniture '+key+': '+r.error);
  /* the piece's lights become HALO records (glow sprites, the night light pool, the lamp cones: 91n-night.js, 93-anim.js) as the kit's own glow did */
  const fireK=!!PAF.FIRE[key];for(const L of r.lights){const k=Math.round(L.x/.6)+','+Math.round(L.y/.6)+','+Math.round(L.z/.6);if(HALOKEY.has(k))continue;HALOKEY.add(k);
   const cc=hc(fireK?0xff9a3a:0xffd890);HALOS.push({x:L.x,y:L.y+(fireK?0:.06),z:L.z,r:cc.r,g:cc.g,b:cc.b,big:fireK,kind:fireK?'ConeGeometry':'SphereGeometry'});}}
 return rec;}
// ---- the registry hook: every place() gets its own record list (nested placements, the compound's slots, keep theirs) and the
// interiors hook runs after a TOP-LEVEL placement (not a sub-building a compound places); frontOf()'s throwaway builds batch nothing
const pafPlace=place,pafFrontOf=frontOf;
place=function(key,x,z,ry,o){const d=DEFS[key];if(!d)return pafPlace.apply(this,arguments);o=o||{};const top=!CURKEY,keep=PAF.cur;
 const y=o.y!==undefined?o.y:terrainH(x,z);const M0=CM.clone().multiply(TF(x,y,z,ry||0)),e=M0.elements;
 const c=PAF.cur={key,seed:d.seed+(o.v|0)*7+(((Math.round(x*10)*73856093)^(Math.round(z*10)*19349663))>>>0)%9973,M0inv:M0.clone().invert(),ry:Math.atan2(e[8],e[10]),wealth:pafWealth(key),list:[]};
 let rec;try{rec=pafPlace.apply(this,arguments);}finally{PAF.cur=keep;}
 if(!rec)return rec;rec.furniture=c.list;
 if(top&&!PAF.dry&&PAF.interiors&&PAF.on){const it=KratorInteriors.sets.find(key);
  if(it&&!it.skip){try{const r=KratorInteriors.sets.furnish(it,x,z,ry||0,PAF.adapter,{baseY:y,prefix:'pa.'+PAF.buildings.length+'.'});
    rec.interior={rooms:r.inst.rooms.length,pieces:Object.keys(r.plans).reduce((a,k)=>a+r.plans[k].placements.length,0),residence:r.residence};
    PAF.buildings.push({key,x,z,ry:ry||0,interior:rec.interior});}catch(err){reportErr('interiors '+key+': '+(err.stack||err));}}}
 return rec;};
frontOf=function(key){PAF.dry++;try{return pafFrontOf(key);}finally{PAF.dry--;}};
// the catalog's colours are sRGB values; this renderer works in linear light (outputEncoding sRGB, every kit colour through SRGB2LIN), so the
// batch's vertex colours are converted once (to floats: linear uint8 would band the darks)
const PAF_LIN=new Float32Array(256).map((_,i)=>{const c=i/255;return c<=.04045?c/12.92:Math.pow((c+.055)/1.055,2.4);});
function pafLinear(geo){const a=geo.getAttribute('color');if(!a||a.array instanceof Float32Array)return;const src=a.array,out=new Float32Array(src.length);
 for(let i=0;i<src.length;i++)out[i]=PAF_LIN[src[i]];geo.setAttribute('color',new THREE.BufferAttribute(out,3));}
// ---- the batch becomes meshes ONCE per world build, after every building is placed
const pafBuildWorld=buildWorld;
buildWorld=function(cultureKey){pafNewBatch();const t0=performance.now();const W0=pafBuildWorld(cultureKey);
 const g=PAF.group=PAF.batch.flush(WORLD);g.traverse(m=>{if(m.isMesh){const f=m.material.userData.family;m.castShadow=f!=='glow'&&f!=='glass';m.receiveShadow=true;pafLinear(m.geometry);}});
 if(window._build)window._build.furniture={placed:PAF.placed.length,tris:Math.round(PAF.batch.tris),missing:Object.assign({},PAF.missing),interiors:PAF.buildings.length,ms:Math.round(performance.now()-t0)};
 return W0;};
// probe: _api.furniture() = counts, missing keys, triangles; _api.furniture(true) adds every record; the interiors summary with ?interiors=1
window._api.furniture=function(all){const by={};for(const r of PAF.placed)by[r.key]=(by[r.key]||0)+1;
 const ib=PAF.buildings;const out={on:PAF.on,interiors:PAF.interiors,placed:PAF.placed.length,keys:by,missing:Object.assign({},PAF.missing),tris:Math.round(PAF.batch.tris),
  buildings:REG.filter(r=>r.furniture&&r.furniture.length).length,
  interiorBuildings:ib.length,rooms:ib.reduce((a,b)=>a+b.interior.rooms,0),pieces:ib.reduce((a,b)=>a+b.interior.pieces,0),
  residenceFails:ib.reduce((a,b)=>a.concat((b.interior.residence&&b.interior.residence.fails)||[]),[])};
 if(all)out.records=PAF.placed;return out;};
