// ---------------------------------------------------------------- furniture: PLACED from the catalog, not drawn
// Everything a Post-Apoc builder puts in or around a building that is not the building itself (its reclaimed core, the additions
// lashed to it, its yard walls, fences, stairs and outbuildings) is FURNITURE: a master-catalog piece (kits/catalog, the harvested
// pa_* pieces in krator-master-furniture-scrap.js and -post-apoc.js), placed as data and built by the catalog's own code through
// KratorFurniture (38-furniture-bundle.js, generated by build.py), merged into one mesh per render family for the whole page.
// A builder (or a 34-adds helper: barrel, crate, sacks, lamp, fire, tireStack ...) calls, in its CURRENT frame (W() frames included):
//   FURNISH(key, lx, ly, lz, lry, {v, seed, setting, ax, az})   -> the placement record, also on the building's REG record (rec.furniture)
// (ax, az): the point of the PIECE (its own frame, metres) that lands on (lx, lz); a piece is centred on its footprint, so a lamp
// post whose pole is 0.23 m off its centre passes ax:-.23. Indoors, the rooms of every top-level building are the interiors kit's:
// its set (kits/interiors/sets/post-apoc.js) is planned and furnished through the same catalog with ?interiors=1 (off by default:
// the roofs hide it). ?furniture=0 places nothing (the records are still kept). A key the catalog lacks is counted, not thrown
// (PAF.missing, _api.furniture().missing).
KratorFurniture.setDetail(.5);   // settlement-scale: half the segments on round furniture parts
// the placement pass is core/furnish (50-core-furnish.js: the record, the missing count, the id); this is Post-Apoc's adapter
// onto it: its seed rule (the building's seed and the record's place in its list), the colliders, and the lights as halos
const PAF=KFURN.create(Object.assign(KFURN.flags(false),{
 catalog:KFURN.catalogOf(KratorFurniture),interiors:KratorInteriors,
 seed:(o,ctx)=>ctx.pa.seed*100+ctx.pa.list.length+1,
 onRecord:(rec,ctx,o,A,d)=>{if(!PAF.NOCOLL[rec.key]&&d.h>=.3){const L=ctx.local;collSolid(L[0],L[1],L[2],d.w,d.h,d.d,L[3],'furniture');}},
 draw:(rec,ctx)=>{const r=KFURN.drawRec(PAF,rec,ctx.pa.wealth);
  if(r.error)reportErr('furniture '+rec.key+': '+r.error);
  /* the piece's lights become HALO records (glow sprites, the night light pool, the lamp cones: 91n-night.js, 93-anim.js) as the kit's own glow did */
  const fireK=!!PAF.FIRE[rec.key];for(const L of r.lights){const k=Math.round(L.x/.6)+','+Math.round(L.y/.6)+','+Math.round(L.z/.6);if(HALOKEY.has(k))continue;HALOKEY.add(k);
   const cc=hc(fireK?0xff9a3a:0xffd890);HALOS.push({x:L.x,y:L.y+(fireK?0:.06),z:L.z,r:cc.r,g:cc.g,b:cc.b,big:fireK,kind:fireK?'ConeGeometry':'SphereGeometry'});}}}));
Object.assign(PAF,{cur:null,dry:0,
 FIRE:{pa_camp_fire:1,pa_forge:1,pa_brick_grill:1,pa_box_stove:1},   // their lights are fires (big halos), the rest lamps
 NOCOLL:{pa_lamp_post:1,pa_hanging_lamp:1,pa_goods_rail:1,pa_gibbet:1}});   // thin or hung: no collider
// a fresh world starts its ids again, so it gets a fresh core/tags registry too (core/tags/README.md)
function pafNewBatch(){KFURN.useBatch(PAF,KratorFurniture,KratorInteriors);PAF.placed=[];PAF.missing={};PAF.buildings=[];PAF.cfg.tags=KTAGS.page=KTAGS.create({build:'post-apoc'});}
pafNewBatch();
function pafWealth(key){const it=KratorInteriors.sets.find(key);return it&&it.wealth!=null?it.wealth:.3;}
function FURNISH(key,lx,ly,lz,lry,o){o=o||{};const c=PAF.cur;if(!c||!CURKEY){reportErr('FURNISH '+key+' outside a builder');return null;}
 lry=lry||0;if(!KratorFurniture.has(key)){if(!PAF.dry)PAF.missing[key]=(PAF.missing[key]||0)+1;return null;}
 if(o.ax||o.az){const ax=o.ax||0,az=o.az||0,cs=Math.cos(lry),sn=Math.sin(lry);lx-=ax*cs+az*sn;lz-=-ax*sn+az*cs;}
 const w=new THREE.Vector3(lx,ly,lz).applyMatrix4(CM),e=CM.elements,wry=Math.atan2(e[8],e[10])+lry;
 const b=w.clone().applyMatrix4(c.M0inv);   // the building's own frame (origin = plot centre on the ground, +z the front)
 return PAF.place(key,w.x,w.y,w.z,wry,o,[+b.x.toFixed(3),+b.y.toFixed(3),+b.z.toFixed(3),+(wry-c.ry).toFixed(4)],
  {building:CURKEY,list:c.list,pa:c,local:[lx,ly,lz,lry],dry:!!PAF.dry});}
// ---- the registry hook: every place() gets its own record list (nested placements, the compound's slots, keep theirs) and the
// interiors hook runs after a TOP-LEVEL placement (not a sub-building a compound places); frontOf()'s throwaway builds batch nothing
const pafPlace=place,pafFrontOf=frontOf;
place=function(key,x,z,ry,o){const d=DEFS[key];if(!d)return pafPlace.apply(this,arguments);o=o||{};const top=!CURKEY,keep=PAF.cur;
 const y=o.y!==undefined?o.y:terrainH(x,z);const M0=CM.clone().multiply(TF(x,y,z,ry||0)),e=M0.elements;
 const c=PAF.cur={key,seed:d.seed+(o.v|0)*7+(((Math.round(x*10)*73856093)^(Math.round(z*10)*19349663))>>>0)%9973,M0inv:M0.clone().invert(),ry:Math.atan2(e[8],e[10]),wealth:pafWealth(key),list:[]};
 let rec;try{rec=pafPlace.apply(this,arguments);}finally{PAF.cur=keep;}
 if(!rec)return rec;rec.furniture=c.list;
 if(top&&!PAF.dry&&PAF.interiors&&PAF.on){const it=KratorInteriors.sets.find(key);
  if(it&&!it.skip){try{const r=PAF.interior(it,x,z,ry||0,PAF.adapter,{baseY:y,prefix:'pa.'+PAF.buildings.length+'.'}).summary;
    rec.interior={rooms:r.rooms,pieces:r.pieces,residence:r.residence};
    Object.assign(PAF.buildings[PAF.buildings.length-1],{key,interior:rec.interior});}catch(err){reportErr('interiors '+key+': '+(err.stack||err));}}}
 return rec;};
frontOf=function(key){PAF.dry++;try{return pafFrontOf(key);}finally{PAF.dry--;}};
// the catalog's colours are sRGB values; this renderer works in linear light (outputEncoding sRGB, every kit colour through SRGB2LIN), so the
// batch's vertex colours are converted once (to floats: linear uint8 would band the darks)
const pafLinear=KFURN.linearColours;
// ---- the batch becomes meshes ONCE per world build, after every building is placed
const pafBuildWorld=buildWorld;
buildWorld=function(cultureKey){pafNewBatch();const t0=performance.now();const W0=pafBuildWorld(cultureKey);
 const g=PAF.group=PAF.batch.flush(WORLD);g.traverse(m=>{if(m.isMesh){const f=m.material.userData.family;m.castShadow=f!=='glow'&&f!=='glass';m.receiveShadow=true;pafLinear(m.geometry);}});
 if(window._build)window._build.furniture={placed:PAF.placed.length,tris:Math.round(PAF.batch.tris),missing:Object.assign({},PAF.missing),interiors:PAF.buildings.length,ms:Math.round(performance.now()-t0)};
 return W0;};
// probe: _api.furniture() = counts, missing keys, triangles; _api.furniture(true) adds every record; the interiors summary with ?interiors=1
window._api.furniture=function(all){const by={};for(const r of PAF.placed)by[r.key]=(by[r.key]||0)+1;
 const ib=PAF.buildings;const out={on:PAF.on,interiors:PAF.interiors,placed:PAF.placed.length,keys:by,missing:Object.assign({},PAF.missing),tris:Math.round(PAF.batch.tris),
  buildings:REG.filter(r=>r.furniture&&r.furniture.length).length,
  interiorBuildings:ib.length,rooms:ib.reduce((a,b)=>a+b.interior.rooms,0),pieces:ib.reduce((a,b)=>a+b.interior.pieces,0),
  residenceFails:ib.reduce((a,b)=>a.concat((b.interior.residence&&b.interior.residence.fails)||[]),[])};
 if(all)out.records=PAF.placed;return out;};
