// Water 7: entry point for water7.html. Fan work after Eiichiro Oda's One Piece: the City of Water, generated by
// tools/make-water7.py, on the shared engine; its fountain, docks and ships are modelled in landmarks.js, its canals
// and boats and sea train in life.js.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {boot} from '../core/shell.js';
import {build} from '../engine/build.js';
import {landmarks} from './landmarks.js';
import {life} from './life.js';
import {events} from './events.js';
import {ocean} from './ocean.js';
import {seawall} from './seawall.js';
import {dress} from '../core/dress.js';
import {work} from './work.js';
import {folk} from './folk.js';
import {backstreet} from './backstreet.js';
import {lights} from './lights.js';
import {sound} from './sound.js';
import {crowds} from '../core/crowds.js';
import {streetlife} from '../core/streetlife.js';
import {navmap} from '../core/navmap.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({
  lines:[
    'Water 7 is built like a fountain: the water from the top runs down through every tier of the city to the sea.',
    'The canals are the streets. Water 7 gets about by yagara bull, a fish-horse that tows a boat.',
    'Galley-La\'s shipwrights are the best in the world, and their president is the mayor.',
    'Every year Aqua Laguna comes over Back Street. Everyone goes up to Up Town to wait for it to pass.',
    'The Puffing Tom runs on rails laid on the sea, to St. Poplar, San Faldo, Pucci and Enies Lobby.',
  ],
  prefix:'raising Water 7… ',labels:{'map-data':'filling the canals',ground:'raising the tiers',buildings:'building the houses',details:'mooring the yagara',landmarks:'turning on the fountain',el:'',ui:'opening the docks'}});
const ctx=window._iz={defaultCity:'water7',models:[landmarks],extras:[{name:'ocean',fn:ocean},{name:'seawall',fn:seawall},{name:'dress',fn:dress},{name:'work',fn:work},{name:'folk',fn:folk},{name:'backstreet',fn:backstreet},{name:'lights',fn:lights},{name:'sound',fn:sound},{name:'life',fn:life},{name:'streetlife',fn:streetlife},{name:'crowds',fn:crowds},{name:'navmap',fn:navmap},{name:'events',fn:events}]};
ctx.extras=ctx.extras.map(e=>({name:e.name,fn:api=>{const t0=performance.now();try{return e.fn(api);}finally{api.ctx.details=api.ctx.details||{};(api.ctx.details.extraMs=api.ctx.details.extraMs||{})[e.name]=Math.round(performance.now()-t0);}}}));
boot(()=>build(ctx));
