// Conamara Station: entry point for europa.html. Original work — the geology is Europa's, reconstructed
// from what is known of it, and the engineering is this project's own. The ice is generated by
// tools/make-europa.py; the engine is the one Chicago and New York share.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {build} from '../engine/build.js';
import {landmarks} from './landmarks.js';
import {sky} from './sky.js';
import {life} from './life.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({prefix:'making orbit… ',labels:{'map-data':'reading the ice',ground:'laying the plains',buildings:'breaking the chaos',details:'',landmarks:'raising the derrick',el:'',traffic:'',ui:'lighting the site'}});
const ctx=window._iz={defaultCity:'europa',models:[landmarks],
  extras:[{name:'sky',fn:sky},{name:'life',fn:life}]};
requestAnimationFrame(()=>setTimeout(()=>{build(ctx).catch(e=>{report('build',e);const l=document.getElementById('loading');if(l)l.remove();});},30));
