#!/usr/bin/env python3
"""Extract one Mixamo clip from a glTF binary (e.g. three.js's examples/models/gltf/Xbot.glb)
into a JS data fragment: per-bone quaternions (and the hips translation) resampled at 30 fps.

    python3 extract_mixamo.py Xbot.glb walk src/20-mixamo-walk.js

Only the bones the Krator rig has are kept (no fingers, eyes, toes). Names drop the
'mixamorig:' colon the way three.js's FBXLoader does ('mixamorigHips'), because ':' is a
reserved character in AnimationClip track names.
"""
import json, struct, sys

KEEP = ['Hips', 'Spine', 'Spine1', 'Spine2', 'Neck', 'Head',
        'LeftShoulder', 'LeftArm', 'LeftForeArm', 'LeftHand', 'LeftUpLeg', 'LeftLeg', 'LeftFoot',
        'RightShoulder', 'RightArm', 'RightForeArm', 'RightHand', 'RightUpLeg', 'RightLeg', 'RightFoot']
CT = {5126: ('f', 4), 5123: ('H', 2), 5121: ('B', 1), 5125: ('I', 4)}
NC = {'SCALAR': 1, 'VEC3': 3, 'VEC4': 4}


def main(glb, clip, out, fps=30):
    d = open(glb, 'rb').read()
    ln = struct.unpack('<I', d[12:16])[0]
    j = json.loads(d[20:20 + ln])
    off = 20 + ln
    cl = struct.unpack('<I', d[off:off + 4])[0]
    binc = d[off + 8:off + 8 + cl]

    def accessor(i):
        a = j['accessors'][i]; bv = j['bufferViews'][a['bufferView']]
        fmt, sz = CT[a['componentType']]; n = NC[a['type']]
        start = bv.get('byteOffset', 0) + a.get('byteOffset', 0)
        stride = bv.get('byteStride', sz * n)
        rows = []
        for k in range(a['count']):
            p = start + k * stride
            rows.append(struct.unpack('<' + fmt * n, binc[p:p + sz * n]))
        return rows

    nodes = j['nodes']
    anim = next(a for a in j['animations'] if a['name'] == clip)
    tracks = {}
    for ch in anim['channels']:
        node = nodes[ch['target']['node']]; name = node.get('name', '')
        short = name.replace('mixamorig:', '')
        if short not in KEEP: continue
        s = anim['samplers'][ch['sampler']]
        times = [t[0] for t in accessor(s['input'])]; vals = accessor(s['output'])
        tracks.setdefault(short, {})[ch['target']['path']] = (times, vals)
    duration = max(t[-1] for tr in tracks.values() for (t, v) in tr.values())
    frames = int(round(duration * fps))
    rest = {}
    for n in nodes:
        short = (n.get('name') or '').replace('mixamorig:', '')
        if short in KEEP: rest[short] = n.get('translation', [0, 0, 0])

    def sample(times, vals, t, quat):
        if t <= times[0]: return vals[0]
        if t >= times[-1]: return vals[-1]
        hi = next(i for i, x in enumerate(times) if x >= t); lo = hi - 1
        f = (t - times[lo]) / (times[hi] - times[lo]) if times[hi] > times[lo] else 0
        a, b = vals[lo], vals[hi]
        if quat and sum(x * y for x, y in zip(a, b)) < 0: b = [-x for x in b]
        r = [x + (y - x) * f for x, y in zip(a, b)]
        if quat:
            L = sum(x * x for x in r) ** 0.5; r = [x / L for x in r]
        return r

    bones = {}
    for name, tr in tracks.items():
        rec = {}
        if 'rotation' in tr:
            T, V = tr['rotation']; rec['q'] = [round(x, 4) for k in range(frames) for x in sample(T, V, k / fps, True)]
        if 'translation' in tr and name == 'Hips':
            T, V = tr['translation']; rec['p'] = [round(x, 3) for k in range(frames) for x in sample(T, V, k / fps, False)]
        bones['mixamorig' + name] = rec
    hips_rest = rest['Hips']
    data = {'name': clip, 'source': glb.split('/')[-1], 'fps': fps, 'frames': frames,
            'duration': round(frames / fps, 4), 'unitScale': 0.01, 'hipsRest': hips_rest,
            'hipHeight': round(hips_rest[1] * 0.01, 4), 'bones': bones}
    with open(out, 'w') as fh:
        fh.write('/* ============================== Mixamo clip: %s ==============================\n' % clip)
        fh.write('   Generated by extract_mixamo.py from %s (the Mixamo X Bot shipped with three.js\n' % glb.split('/')[-1])
        fh.write('   examples). Local quaternions per bone at %d fps, hips translation in cm.\n' % fps)
        fh.write('   The X Bot rest pose has identity rotations on every bone (a T-pose with +X = the\n')
        fh.write('   character\'s left), the same convention as the Krator rig, so these apply directly. */\n')
        fh.write('var MIXAMO_%s = %s;\n' % (clip.upper(), json.dumps(data, separators=(',', ':'))))
    hp = bones['mixamorigHips'].get('p', [])
    xs, ys, zs = hp[0::3], hp[1::3], hp[2::3]
    print('%s: %d frames, %.2fs, hips x %.1f..%.1f y %.1f..%.1f z %.1f..%.1f cm' % (clip, frames, data['duration'], min(xs), max(xs), min(ys), max(ys), min(zs), max(zs)))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3])
