/* ============================== 13b. FURNITURE (CATALOG PIECES AS DATA) ==============================
   Everything Girder's builders put in or round a building that is not the building itself (its structure
   and its outbuildings) is FURNITURE: a master-catalog piece (kits/catalog), placed as DATA and built by the
   catalog's own code through KratorFurniture (51-furniture-bundle.js, GENERATED by build.py from
   kits/catalog/furniture_bundle.py), merged into one mesh per render family for the whole village.

   A builder names the building it is dressing, then places pieces in that building's LOCAL frame:
     gfAt(owner, id, f, y, wealth)        owner: the layout record (SLOTS[i], HOUSES[i], a roost, a stall...);
                                          f: a 55-arch FRM frame {x,z,fx,fz} (local x = right, z = front) or
                                          null for world-aligned offsets from (owner.x, owner.z); y: its floor
     FURNISH(key, lx, ly, lz, lry, {v, seed, setting, noLight})
                                          -> the placement record, also pushed on owner.furniture and GFURN.placed
     FURNISHW(key, x, y, z, ry, o)        the same at a WORLD point and heading (helpers that work in world space)
   Headings are the catalog's: ry turns the piece's front (+z) to (sin ry, cos ry); in an FRM frame lry 0 faces
   the frame's front and lry +PI/2 its LEFT (the catalog's x is the mirror of FRM's "right").
   A record: { key, variant, seed, lx, ly, lz, lry, x, y, z, ry, building, setting }. A key the bundle lacks is
   COUNTED in GFURN.missing, never thrown. ?furniture=0 builds nothing (the records are still kept).
   The batch becomes meshes ONCE, when the kit emits its buckets (75-terrain.js calls emitBuckets()).
   The interiors (56-interiors.js) furnish the rooms through the same batch: ?interiors=0 turns them off.
   A catalog piece's lights stay data: the glue hands them to the night light volume (nlLampAdd); pieces that
   replace one of Girder's own lamps keep Girder's lamp (noLight: true) so the night is lit as before.     */
KratorFurniture.setDetail(.5);   /* settlement scale: half the segments on round furniture parts */
var GFURN = { on: !/[?&]furniture=0\b/.test(location.search), interiors: !/[?&]interiors=0\b/.test(location.search),
           batch: KratorFurniture.batch(), placed: [], missing: {}, cur: null, group: null, lights: 0,
           buildings: [], ixPlaced: [], residenceFails: [], ms: 0 };
GFURN.adapter = KratorInteriors.runtimeAdapter(KratorFurniture, GFURN.batch);
if(!GFURN.on) GFURN.adapter.build = function(p, room){   /* ?furniture=0: plan the rooms, keep the data, build nothing */
  return { key:p.key, variant:p.variant, seed:p.seed, x:p.x, y:p.y, z:p.z, ry:p.ry, building:room?room.building:null, room:room?room.id:null, setting:'indoor', lights:[] }; };
function gfAt(owner, id, f, y, wealth){ GFURN.cur = { owner:owner, id:id, f:f||null, y:y||0, wealth:wealth==null?0.45:wealth }; return GFURN.cur; }
function gfLights(rec, k){            /* a built piece's lights into the night light volume */
  (rec.lights||[]).forEach(function(l){ nlLampAdd(l.x, l.y, l.z, (l.intensity||1)*(k||0.7), Math.min(18, l.distance||12), false); GFURN.lights++; });
}
function gfPlace(key, x, y, z, ry, o, loc){
  var c=GFURN.cur; o=o||{};
  if(!c){ ERR('FURNISH '+key+' outside a building (call gfAt first)'); return null; }
  if(!KratorFurniture.has(key)){ GFURN.missing[key]=(GFURN.missing[key]||0)+1; return null; }
  var rec={ key:key, variant:o.v|0, seed:o.seed||(GFURN.placed.length+1), lx:loc[0], ly:loc[1], lz:loc[2], lry:loc[3],
            x:+x.toFixed(3), y:+y.toFixed(3), z:+z.toFixed(3), ry:+wrapPi(ry).toFixed(4), building:c.id, setting:o.setting||'outdoor' };
  (c.owner.furniture||(c.owner.furniture=[])).push(rec); GFURN.placed.push(rec);
  var A=KratorFurniture.FURN_BY_KEY[key], dm=KratorFurniture.entryDims(A, rec.variant);   /* the walk mode bumps into it */
  if(A.anchor!=='ceiling' && A.anchor!=='surface' && A.type!=='lamp' && A.type!=='rug' && dm.h>=0.3) gwBox(rec.x, rec.y, rec.z, dm.w, dm.h, dm.d, rec.ry, 'furniture');
  if(GFURN.on){ var b=GFURN.batch.place(key, rec.x, rec.y, rec.z, rec.ry, { variant:rec.variant, seed:rec.seed, wealth:c.wealth, building:c.id, setting:rec.setting });
    if(b.error) ERR('furniture '+key+': '+b.error);
    if(!o.noLight) gfLights(b, 0.7); }
  return rec;
}
function FURNISH(key, lx, ly, lz, lry, o){
  var c=GFURN.cur, f=c&&c.f, x, z, ry;
  if(!c) return gfPlace(key,0,0,0,0,o,[lx,ly,lz,lry||0]);
  if(f){ x=f.x - f.fz*lx + f.fx*lz; z=f.z + f.fx*lx + f.fz*lz; ry=Math.atan2(f.fx,f.fz)+(lry||0); }
  else { x=c.owner.x + lx; z=c.owner.z + lz; ry=lry||0; }
  return gfPlace(key, x, c.y+ly, z, ry, o, [lx,ly,lz,lry||0]);
}
function FURNISHW(key, x, y, z, ry, o){ var c=GFURN.cur; return gfPlace(key, x, y, z, ry||0, o, [x-(c?c.owner.x||0:0), y-(c?c.y:0), z-(c?c.owner.z||0:0), ry||0]); }

/* the batch becomes meshes once, when the kit emits its instanced buckets (75-terrain.js) */
var gfEmitKit = emitBuckets;
emitBuckets = function(){ gfFlush(); return gfEmitKit(); };
/* the catalog's colours are sRGB values; Girder's fabric is linear (45-kit converts every colour): the
   furniture meshes keep their 8-bit vertex colours and linearise them in the vertex shader */
function gfSRGBHook(sh){
  sh.vertexShader = sh.vertexShader.replace('#include <color_vertex>',
    '#include <color_vertex>\n#ifdef USE_COLOR\n  vColor.rgb = pow(max(vColor.rgb, vec3(0.0)), vec3(2.2));\n#endif');
}
/* painted panels (the catalog's F.decal: a canvas map) leave a batch as one mesh each; they are merged per
   material, so each painted pattern is one draw call. gfDecal(m) -> its geometry in world space, non-indexed */
function gfDecal(m){ m.updateMatrix(); var g = m.geometry.index ? m.geometry.toNonIndexed() : m.geometry.clone(); g.applyMatrix4(m.matrix); m.geometry.dispose(); return g; }
function gfDecalMaterial(mt){
  if(!mt.userData.gfDone){ if(mt.map){ mt.map.encoding = THREE.sRGBEncoding; mt.map.needsUpdate = true; } nlMaterial(mt, 'decal|'+(mt.userData.family||'')); mt.userData.gfDone = true; }
  return mt;
}
function gfMergeGeos(geos){
  var n=0; geos.forEach(function(g){ n += g.attributes.position.count; });
  var out = new THREE.BufferGeometry(), at = {};
  [['position',3],['normal',3],['uv',2]].forEach(function(s){ var a=new Float32Array(n*s[1]), o=0;
    geos.forEach(function(g){ var b=g.attributes[s[0]]; if(b) a.set(b.array, o); o += g.attributes.position.count*s[1]; });
    out.setAttribute(s[0], new THREE.BufferAttribute(a, s[1])); });
  geos.forEach(function(g){ g.dispose(); });
  out.computeBoundingSphere();
  return out;
}
function gfFlush(){
  if(GFURN.group) return GFURN.group;
  GFURN.tris = GFURN.batch.tris|0;
  var g = GFURN.batch.flush(scene), decals = {}; GFURN.group = g; g.userData.inspectLabel = 'Furniture (catalog)';
  g.children.slice().forEach(function(m){
    if(m.material.map){ var k=m.material.uuid; (decals[k]||(decals[k]={ mt:m.material, geos:[] })).geos.push(gfDecal(m)); g.remove(m); return; }
    m.geometry.computeBoundingSphere();
    if(m.material.isMeshBasicMaterial) m.material.onBeforeCompile = gfSRGBHook;
    else nlMaterial(m.material, 'furn|'+m.material.userData.family, gfSRGBHook);   /* + the lamp pools at night */
    m.castShadow = !FAST; m.receiveShadow = !FAST; m.frustumCulled = false;
  });
  Object.keys(decals).forEach(function(k){ var D=decals[k], m=new THREE.Mesh(gfMergeGeos(D.geos), gfDecalMaterial(D.mt));
    m.name='furniture:decals'; m.userData.furniture=true; m.castShadow=!FAST; m.receiveShadow=!FAST; m.frustumCulled=false; g.add(m); });
  GFURN.meshes = g.children.length;
  gfReport();
  return g;
}
/* a small summary for the verifier (window._* is printed whole), the full state for the console */
function gfReport(){
  var keys={}, kv={}; GFURN.placed.forEach(function(r){ keys[r.key]=(keys[r.key]||0)+1; kv[r.key+'|'+r.variant]=(kv[r.key+'|'+r.variant]||0)+1; });
  window._furniture = { on:GFURN.on, placed:GFURN.placed.length, keys:Object.keys(keys).length, missing:GFURN.missing,
    tris:GFURN.tris||0, meshes:GFURN.meshes||0, lights:GFURN.lights };
  window.girderFurniture = { GFURN:GFURN, byKey:keys, byKeyVariant:kv, GWALK:GWALK, GIX:typeof GIX!=='undefined'?GIX:null };
}

/* ---------------------------------------------------------------- walk-mode solids (83-walk.js)
   What the builders draw that a walker stands on or bumps into, registered as they draw it: an oriented
   box (BOX's convention: base y, centre x z, yaw ry turns local x to (cos ry, -sin ry)), a wall segment, a
   disc. A solid supports a walker on its top and blocks one whose body overlaps its height (bot..top).
   83-walk.js adds the ruin, the decks, the stairs and the bridges from the layout. */
var GWALK = { solids:[], onAdd:null };
function gwAdd(s){ GWALK.solids.push(s); if(GWALK.onAdd) GWALK.onAdd(s); return s; }
function gwBox(x,y,z,w,h,d,ry,tag){ var c=Math.cos(ry||0), s=Math.sin(ry||0);
  return gwAdd({ x:x, z:z, ux:c, uz:-s, hw:w/2, hd:d/2, top:y+h, bot:y, tag:tag||'' }); }
function gwSeg(ax,az,bx,bz,th,y0,y1,tag){ var dx=bx-ax, dz=bz-az, L=Math.hypot(dx,dz); if(L<1e-3) return null;
  return gwAdd({ x:(ax+bx)/2, z:(az+bz)/2, ux:dx/L, uz:dz/L, hw:L/2, hd:th/2, top:y1, bot:y0, tag:tag||'' }); }
function gwDisc(x,z,r,top,bot,tag){ return gwAdd({ x:x, z:z, r:r, top:top, bot:bot, tag:tag||'' }); }
