#!/usr/bin/env python3
"""Assemble src/<page>/build.js from the stage files in src/<page>/stages/.

    python3 tools/build-page.py            # every page that has a stages/ folder
    python3 tools/build-page.py iziz       # one page
    python3 tools/build-page.py --check    # exit 1 if any build.js is stale (nothing written)

The stage files are fragments of one function body, run in file order inside build(ctx); they share
one scope, so a stage may use anything an earlier stage defined. build.js is generated: edit the
stages, not build.js. ./sitectl check/reload/restart run this first.
"""
import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")

IMPORTS = """import {report,section,stage,LOAD} from '../core/diag.js';
import {createLcg,makeNoise,clamp,smooth,hash3,mkRng} from '../core/rng.js';
import {createEnv} from '../core/env.js';
import {createIzani} from '../izani/atlas.js';
import {DATA_FN,dataValue,resolveCity} from '../core/data.js';
"""


def assemble(page):
    d = os.path.join(SRC, page, "stages")
    files = sorted(f for f in os.listdir(d) if f.endswith(".js"))
    parts = []
    h = hashlib.sha256()
    for f in files:
        text = open(os.path.join(d, f), encoding="utf-8").read()
        h.update(f.encode()); h.update(text.encode())
        parts.append(f"// ===== stages/{f} =====\n{text.rstrip()}\n")
    digest = h.hexdigest()[:16]
    out = (f"// GENERATED by tools/build-page.py from src/{page}/stages/ ({len(files)} files, sources {digest}).\n"
           f"// Do not edit: change the stage files and run ./sitectl build.\n"
           + IMPORTS + "export async function build(ctx){\n" + "".join(parts) + "}\n")
    return out, digest


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    pages = args or [p for p in sorted(os.listdir(SRC)) if os.path.isdir(os.path.join(SRC, p, "stages"))]
    stale = 0
    for page in pages:
        out, digest = assemble(page)
        target = os.path.join(SRC, page, "build.js")
        cur = open(target, encoding="utf-8").read() if os.path.exists(target) else ""
        if cur == out:
            print(f"{page}: build.js up to date ({digest})")
            continue
        if check:
            print(f"{page}: build.js is STALE, run ./sitectl build")
            stale += 1
            continue
        open(target, "w", encoding="utf-8").write(out)
        print(f"{page}: wrote build.js ({len(out)} bytes, sources {digest})")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
