#!/usr/bin/env python3
"""Generate City 17 as a city data file the OSM engine can read.

    python3 tools/make-city17.py

Writes data/cities/city17-osm.json in the same shape tools/build-osm-city.py produces for a real city
(terrain grid, water, land areas, streets, rail, buildings), so city17.html renders it with the same
stages as Chicago and Portland.

This is fan work: an Eastern-European city under occupation, laid out from the game's geography as we
remember it - the Citadel in a cleared exclusion zone at the centre, the trainstation plaza south-west of
it, the canals running south out of the city, the Combine wall cutting the districts apart. Every shape
here is modelled from scratch in this project's own low-poly style; no assets from the game are used,
copied or redistributed. Half-Life 2 and City 17 belong to Valve.
"""
import json
import math
import os
import random
from lib.geo import q, flat, rect, smoothstep, simplify

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "cities", "city17-osm.json")
R = random.Random(1748)

HALF = 2200.0           # the map runs from -HALF to +HALF in both directions
CITADEL = (0.0, -260.0)  # the Citadel stands a little north of the middle
CORDON_R = 540.0        # the cleared exclusion zone the Citadel tore out of the city
WALL_R = 1780.0         # the outer Combine wall
BLOCK = 108.0
STREET = 16.0
AVENUE = 30.0
RIVER_W = 88.0
CANAL_W = 52.0
PLAZA_LEVEL = 28.0
GATES = [0.45, 1.95, 3.55, 5.05]   # gaps in the outer wall
STATION = (-620.0, 430.0)          # trainstation plaza


def dist_to_polyline(x, z, pts):
    best = 1e9
    for i in range(len(pts) - 1):
        ax, az = pts[i]
        bx, bz = pts[i + 1]
        dx, dz = bx - ax, bz - az
        L = dx * dx + dz * dz
        t = 0 if L == 0 else max(0, min(1, ((x - ax) * dx + (z - az) * dz) / L))
        best = min(best, math.hypot(x - ax - t * dx, z - az - t * dz))
    return best


# ---------- water: the river across the south, and the canals running out of it ----------
def river_centre(x):
    """The river crosses the city west to east, bending south as it goes."""
    return 880 + 150 * math.sin(x / 1400.0 + 0.4) + 55 * math.sin(x / 520.0)


CANALS = [
    [(-1180, 900), (-1210, 1400), (-1330, 1900), (-1360, HALF + 200)],   # Route Kanal, heading south
    [(640, 930), (760, 1380), (735, 1900), (690, HALF + 200)],
    [(250, 905), (250, 380), (170, 90), (150, -120)],                    # the spur reaching north into the city
]


def in_river(x, z):
    return abs(z - river_centre(x)) < RIVER_W / 2


def in_canal(x, z):
    for line in CANALS:
        if dist_to_polyline(x, z, line) < CANAL_W / 2:
            return True
    return False


def in_water(x, z):
    return in_river(x, z) or in_canal(x, z)


def terrain_height(x, z):
    """A river plain: the water at zero, the ground rising gently north to the Citadel's terrace."""
    dr = abs(z - river_centre(x))
    bank = min(17.0, 2.0 + dr * 0.055)
    north = 22 * smoothstep(400, -1600, z)                       # rises towards the north of the map
    roll = 6 * math.sin(x / 760.0 + 0.7) * math.cos(z / 920.0)
    h = bank + north + roll
    # the exclusion zone is a cut terrace: dead level out to the cordon, fading over 300 m beyond it
    cx, cz = CITADEL
    d = math.hypot(x - cx, z - cz)
    cut = 1 - smoothstep(CORDON_R, CORDON_R + 300, d)
    h = h * (1 - cut) + PLAZA_LEVEL * cut
    # the ground eases down to the water datum at the edge of the map, so the map has no cliff at its rim
    h *= smoothstep(HALF, HALF - 280, max(abs(x), abs(z)))
    if in_water(x, z):
        return -2.0
    return max(0.0, h)


def main():
    out = {"attribution": "City 17: fan geometry generated by tools/make-city17.py; no game assets used",
           "units": "decimetres east (x) and south (z) of origin", "origin": [48.0, 20.0],
           "bounds": [47.9802, 19.9705, 48.0198, 20.0295]}

    # ---------- terrain ----------
    step = 20
    nx = int(2 * HALF) // step + 2
    nz = nx
    hs = []
    for j in range(nz):
        for i in range(nx):
            hs.append(terrain_height(-HALF + i * step, -HALF + j * step))
    out["terrain"] = {"step": step, "nx": nx, "nz": nz, "x0": q(-HALF), "z0": q(-HALF), "datum": 96.0,
                      "h": [int(round(h * 10)) for h in hs]}

    # ---------- water ----------
    north, south = [], []
    for x in range(int(-HALF) - 200, int(HALF) + 201, 40):
        c = river_centre(x)
        north.append((x, c - RIVER_W / 2))
        south.append((x, c + RIVER_W / 2))
    out["lake"] = []
    out["islands"] = []
    out["water"] = [{"o": flat(north + south[::-1]), "i": [], "n": "The river"}]
    names = ["Route Kanal", "East Canal", "North Spur"]
    for k, line in enumerate(CANALS):
        left, right = [], []
        for i in range(len(line) - 1):
            ax, az = line[i]
            bx, bz = line[i + 1]
            dx, dz = bx - ax, bz - az
            L = math.hypot(dx, dz) or 1
            nxv, nzv = -dz / L * CANAL_W / 2, dx / L * CANAL_W / 2
            left += [(ax + nxv, az + nzv), (bx + nxv, bz + nzv)]
            right += [(ax - nxv, az - nzv), (bx - nxv, bz - nzv)]
        out["water"].append({"o": flat(left + right[::-1]), "i": [], "n": names[k]})
    out["marina"], out["beach"], out["pier"] = [], [], []
    out["waterways"] = [{"n": "The river", "p": flat([(x, river_centre(x)) for x in range(int(-HALF), int(HALF) + 1, 60)])}]
    for k, line in enumerate(CANALS):
        out["waterways"].append({"n": names[k], "p": flat(line)})

    # ---------- streets ----------
    roads = []

    def road(pts, cls, w, name="", bridge=0):
        pts = simplify(pts)
        r = {"c": cls, "w": round(w, 1), "p": flat(pts)}
        if name:
            r["n"] = name
        if bridge:
            r["b"] = bridge
        roads.append(r)

    def emit_line(pts, cls, w, name="", bridged=False):
        """Walk a line, laying street over dry ground and a bridge deck over every water crossing."""
        dense = []
        for i in range(len(pts) - 1):
            ax, az = pts[i]
            bx, bz = pts[i + 1]
            L = math.hypot(bx - ax, bz - az)
            steps = max(1, int(L // 12))
            for k in range(steps):
                u = k / steps
                dense.append((ax + (bx - ax) * u, az + (bz - az) * u))
        dense.append(pts[-1])
        cx, cz = CITADEL
        run, wet_run = [], []
        for x, z in dense:
            inside = math.hypot(x, z) < WALL_R * 1.12
            cleared = math.hypot(x - cx, z - cz) < CORDON_R * 0.93   # nothing runs through the exclusion zone
            if not inside or cleared:
                if len(run) > 1:
                    road(run, cls, w, name)
                run = []
                continue
            if in_water(x, z):
                wet_run.append((x, z))
                if len(run) > 1:
                    road(run, cls, w, name)
                run = []
            else:
                if wet_run:
                    if bridged and len(wet_run) > 1:
                        a, b = wet_run[0], wet_run[-1]
                        dx, dz = b[0] - a[0], b[1] - a[1]
                        L = math.hypot(dx, dz) or 1
                        road([(a[0] - dx / L * 45, a[1] - dz / L * 45), (b[0] + dx / L * 45, b[1] + dz / L * 45)],
                             cls, w, name, bridge=1)
                    wet_run = []
                run.append((x, z))
        if len(run) > 1:
            road(run, cls, w, name)

    AVENUE_NAMES = ["Kanal", "Vostok", "Tarnov", "Reznik", "Brezina", "Ostrov", "Dubrava", "Slavin",
                    "Marek", "Petrov", "Zilina", "Krona", "Vrana", "Hrad", "Lomna", "Sever"]
    n = int(HALF // BLOCK)
    for i in range(-n, n + 1):
        v = i * BLOCK
        major = i % 5 == 0
        cls, w = ("secondary", AVENUE) if major else ("residential", STREET)
        k = i + n
        ns = AVENUE_NAMES[k % len(AVENUE_NAMES)] + " Street" if major else f"{k + 1} Street"
        ew = AVENUE_NAMES[(k + 7) % len(AVENUE_NAMES)] + " Prospect" if major else f"{k + 1} Row"
        emit_line([(v, -HALF), (v, HALF)], cls, w, ns, bridged=major)
        emit_line([(-HALF, v), (HALF, v)], cls, w, ew, bridged=major)
    # the ring road just inside the outer wall, and the roads out to each gate
    ring = [(WALL_R * 0.93 * math.cos(a), WALL_R * 0.93 * math.sin(a)) for a in
            [i / 144 * math.tau for i in range(145)]]
    emit_line(ring, "primary", 22, "Perimeter Road", bridged=True)
    for k, a in enumerate(GATES):
        pts = [(math.cos(a) * r, math.sin(a) * r) for r in range(int(CORDON_R), int(WALL_R * 1.03), 25)]
        emit_line(pts, "primary", 26, f"Gate Road {k + 1}", bridged=True)
    # the approach from the trainstation plaza to the cordon: the walk everyone takes
    sx, sz = STATION
    cx, cz = CITADEL
    d = math.hypot(cx - sx, cz - sz)
    emit_line([(sx, sz), (sx + (cx - sx) / d * (d - CORDON_R), sz + (cz - sz) / d * (d - CORDON_R))],
              "primary", 30, "Station Approach")
    out["roads"] = roads

    # ---------- land ----------
    areas = [{"k": "plaza", "n": "Trainstation Plaza", "o": flat(rect(sx, sz, 230, 175)), "i": []},
             {"k": "plaza", "n": "Exclusion Zone", "o": flat([(cx + math.cos(a) * CORDON_R * 0.97,
                                                               cz + math.sin(a) * CORDON_R * 0.97)
                                                              for a in [i / 48 * math.tau for i in range(48)]]), "i": []}]
    for ax, az, w, dd, kind, name in [(-1250, 1320, 620, 420, "industrial", "Canal Works"),
                                      (880, 1280, 520, 360, "industrial", "East Yards"),
                                      (-1480, -680, 420, 320, "railyard", "Rail Yard"),
                                      (960, -980, 300, 240, "park", "Overgrown Park"),
                                      (-820, -1180, 280, 220, "park", "Old Square"),
                                      (420, 640, 240, 180, "parking", "Muster Ground")]:
        areas.append({"k": kind, "n": name, "o": flat(rect(ax, az, w, dd)), "i": []})
    out["areas"] = areas

    def razor_z(x):
        """Where the razor train's alignment crosses this easting."""
        return 430 + 120 * math.sin((x + 600) / 900.0)

    RAIL_CLEAR = 26.0        # metres either side of the alignment that stay open

    def on_rail(rx, rz, half):
        """Would a footprint this deep, centred here, foul the corridor?"""
        return abs(rz - razor_z(rx)) < RAIL_CLEAR + half

    # ---------- rail: the razor train line in, and the yard spur ----------
    # The razor train comes in on a viaduct that was driven through the city rather than fitted into it, so the
    # blocks it crosses are not there any more: nothing is built within RAIL_CLEAR of the alignment, which leaves
    # an open corridor with the deck running down the middle of it. Without that the line is laid straight through
    # the housing and a viaduct thirty metres up is invisible from anywhere in the streets.
    rail = [{"t": "L", "e": 1, "n": "Razor Train", "p": flat(
                [(x, razor_z(x)) for x in range(int(-HALF) + 80, int(HALF) - 79, 50)])},
            {"t": "rail", "e": 0, "n": "Yard Spur", "p": flat([(-1480 + i * 28, -680 + i * 3) for i in range(42)])},
            {"t": "tram", "e": 0, "n": "Tram", "p": flat([(-HALF + 220, 208), (HALF - 220, 208)])},
            {"t": "tram", "e": 0, "n": "Tram", "p": flat([(-216, -HALF + 220), (-216, 780)])}]
    out["rail"] = rail
    out["stations"] = [{"n": "City 17 Trainstation", "x": q(sx + 40), "z": q(sz - 90)},
                       {"n": "East Platform", "x": q(1180), "z": q(560)}]

    # ---------- buildings ----------
    buildings = []
    # the human palette: weathered brick, cracked concrete, peeling plaster, rusted iron, pre-war stone
    BRICK = ["#7a4a3a", "#8a5545", "#6e4234", "#96604a", "#83503e", "#6a3f33"]
    PLASTER = ["#a89c86", "#b8ac95", "#94897a", "#c2b8a2", "#9e9280"]
    CONCRETE = ["#8a8880", "#79776f", "#6c6a64", "#96938a", "#827c6f", "#6a6f6b"]
    RUST = ["#7a5a44", "#6a4f3c", "#8a6a4e", "#6f5140"]
    STONE = ["#c0b49a", "#b0a48c", "#cabfa6", "#a99d86"]       # the grand pre-war blocks around the terminal
    ARMOUR = ["#4a4f55", "#41464c", "#53585e", "#3a3f45"]      # the blocks the Combine has plated over

    def palette_at(bx, bz):
        """Which district a block belongs to decides what it is built of."""
        if math.hypot(bx - sx, bz - sz) < 520:
            return STONE + PLASTER                     # District 1: the urban core around the terminal
        for a in areas:
            if a["k"] in ("industrial", "railyard"):
                x0, x1, z0, z1 = area_bbox(a)
                if x0 - 220 < bx < x1 + 220 and z0 - 220 < bz < z1 + 220:
                    return RUST + CONCRETE             # District 3: the works along the canals
        if min(dist_to_polyline(bx, bz, line) for line in CANALS) < 300:
            return RUST + CONCRETE + BRICK
        return BRICK + BRICK + PLASTER + CONCRETE      # District 2: the residential blocks

    def put(ring, h, kind=None, colour=None, name=None, roof=None, minh=None):
        b = {"p": flat(ring), "h": round(h, 1)}
        if kind:
            b["t"] = kind
        if colour:
            b["c"] = colour
        if name:
            b["n"] = name
        if roof:
            b["r"] = roof
        if minh:
            b["m"] = round(minh, 1)
        buildings.append(b)

    def area_bbox(a):
        xs = [a["o"][i] / 10 for i in range(0, len(a["o"]), 2)]
        zs = [a["o"][i] / 10 for i in range(1, len(a["o"]), 2)]
        return min(xs), max(xs), min(zs), max(zs)

    def block_free(bx, bz):
        if math.hypot(bx, bz) > WALL_R * 1.02:
            return False   # the outer wall is driven straight through whatever stood on its line
        if math.hypot(bx - cx, bz - cz) < CORDON_R - 10:
            return False   # inside the cordon there is nothing left; right at the wall the blocks are cut through
        if in_water(bx, bz):
            return False
        for a in areas:
            if a["n"] == "Exclusion Zone":
                continue   # a circle, already tested above; its square bbox would clear the corners too
            x0, x1, z0, z1 = area_bbox(a)
            if x0 - 8 < bx < x1 + 8 and z0 - 8 < bz < z1 + 8:
                return False
        return True

    def line_w(i):
        return AVENUE if i % 5 == 0 else STREET

    def span(i):
        """The ground a block actually gets between the two street lines either side of it."""
        lo = i * BLOCK + line_w(i) / 2 + 2
        hi = (i + 1) * BLOCK - line_w(i + 1) / 2 - 2
        return (lo + hi) / 2, hi - lo

    for i in range(-n, n + 1):
        for j in range(-n, n + 1):
            bx, wx = span(i)
            bz, wz = span(j)
            if not block_free(bx, bz):
                continue
            d = math.hypot(bx - cx, bz - cz)
            # the closer to the Citadel, the more the Combine has built over the city
            plated = R.random() < max(0.0, 0.7 - d / 1800.0)
            core = max(0.0, 1 - d / (WALL_R * 0.9))
            base = 15 + core * 20 + R.random() * 9
            depth = 12 + R.random() * 3
            for side in range(4):
                if R.random() < 0.13:
                    continue
                h = base * (0.85 + R.random() * 0.4)
                if R.random() < 0.07:
                    h += 16 + R.random() * 28
                ang = side * math.pi / 2
                across, along = (wx, wz) if side % 2 == 0 else (wz, wx)
                ox = math.cos(ang) * (across / 2 - depth / 2)
                oz = math.sin(ang) * (across / 2 - depth / 2)
                length = along * (0.74 + R.random() * 0.26)
                rd = length if side % 2 == 0 else depth
                if on_rail(bx + ox, bz + oz, rd / 2):
                    continue                           # the razor train came through here
                ring = rect(bx + ox, bz + oz, depth if side % 2 == 0 else length, rd)
                pal = palette_at(bx, bz)
                if plated and R.random() < 0.55:
                    put(ring, h, "apartments", ARMOUR[R.randrange(len(ARMOUR))], roof="f")
                    if R.random() < 0.5:   # armour grafted over the roof
                        put(rect(bx + ox, bz + oz, (depth if side % 2 == 0 else length) * 0.7,
                                 (length if side % 2 == 0 else depth) * 0.7),
                            h + 4 + R.random() * 7, "armour", "#333940", roof="f", minh=h)
                else:
                    put(ring, h, "apartments", pal[R.randrange(len(pal))], roof="f")
            if R.random() < 0.22 and not on_rail(bx, bz, 20):
                put(rect(bx + R.uniform(-12, 12), bz + R.uniform(-12, 12), 14 + R.random() * 10, 12 + R.random() * 8),
                    5 + R.random() * 4, "shed", "#6c685f", roof="f")
    # the works: long sheds and silos along the canals
    for a in areas:
        if a["k"] not in ("industrial", "railyard"):
            continue
        x0, x1, z0, z1 = area_bbox(a)
        for _ in range(11):
            ax = R.uniform(x0 + 40, x1 - 40)
            az = R.uniform(z0 + 30, z1 - 30)
            put(rect(ax, az, R.uniform(50, 120), R.uniform(30, 64)), R.uniform(9, 18), "industrial", RUST[R.randrange(len(RUST))], roof="f")
    # the trainstation: a long hall on the plaza, with the concourse beside it
    put(rect(sx + 40, sz - 120, 190, 54), 26, "station", "#8d8878", name="City 17 Trainstation", roof="f")
    put(rect(sx + 40, sz - 165, 190, 30), 15, "station", "#807b6c", roof="f")
    # the Nexus: a civic block the Combine has taken over and armoured, south-east of the cordon
    NEXUS = (520, 260)
    put(rect(NEXUS[0], NEXUS[1], 116, 92), 54, "nexus", "#464c52", name="Overwatch Nexus", roof="f")
    put(rect(NEXUS[0], NEXUS[1], 86, 66), 72, "nexus", "#3c424a", roof="f", minh=54)
    # the outer Combine wall: tall, dark, with towers, and gaps at the gates
    seg = math.tau / 150
    for k in range(150):
        a0 = k * seg
        if any(abs(((a0 - g + math.pi) % math.tau) - math.pi) < 0.055 for g in GATES):
            continue
        a1 = a0 + seg * 0.97
        p0 = (math.cos(a0) * WALL_R, math.sin(a0) * WALL_R)
        p1 = (math.cos(a1) * WALL_R, math.sin(a1) * WALL_R)
        dx, dz = p1[0] - p0[0], p1[1] - p0[1]
        L = math.hypot(dx, dz)
        nxv, nzv = -dz / L * 5.0, dx / L * 5.0
        put([(p0[0] + nxv, p0[1] + nzv), (p1[0] + nxv, p1[1] + nzv), (p1[0] - nxv, p1[1] - nzv), (p0[0] - nxv, p0[1] - nzv)],
            26, "wall", "#454a50", roof="f")
        if k % 9 == 0:
            put(rect(math.cos(a0) * WALL_R, math.sin(a0) * WALL_R, 20, 20, a0), 38, "tower", "#3c4148", roof="f")
    # the cordon wall around the exclusion zone: lower, unbroken except where the approach road meets it
    ap = math.atan2(sz - cz, sx - cx)
    seg2 = math.tau / 96
    for k in range(96):
        a0 = k * seg2
        if abs(((a0 - ap + math.pi) % math.tau) - math.pi) < 0.07:
            continue
        a1 = a0 + seg2 * 0.96
        p0 = (cx + math.cos(a0) * CORDON_R, cz + math.sin(a0) * CORDON_R)
        p1 = (cx + math.cos(a1) * CORDON_R, cz + math.sin(a1) * CORDON_R)
        dx, dz = p1[0] - p0[0], p1[1] - p0[1]
        L = math.hypot(dx, dz)
        nxv, nzv = -dz / L * 3.5, dx / L * 3.5
        put([(p0[0] + nxv, p0[1] + nzv), (p1[0] + nxv, p1[1] + nzv), (p1[0] - nxv, p1[1] - nzv), (p0[0] - nxv, p0[1] - nzv)],
            17, "wall", "#4a4f55", roof="f")
    # the exclusion zone is not empty: it is what is left of the blocks that stood here
    for _ in range(260):
        a = R.uniform(0, math.tau)
        d = R.uniform(300, CORDON_R - 25)
        px, pz = cx + math.cos(a) * d, cz + math.sin(a) * d
        put(rect(px, pz, R.uniform(6, 20), R.uniform(6, 16), R.uniform(0, math.pi)),
            R.uniform(1.5, 6), "rubble", "#5a5750", roof="f")
    # the torn edge: the blocks at the rim came down but did not come away
    for _ in range(110):
        a = R.uniform(0, math.tau)
        d = R.uniform(CORDON_R + 60, CORDON_R + 230)
        px, pz = cx + math.cos(a) * d, cz + math.sin(a) * d
        if in_water(px, pz):
            continue
        put(rect(px, pz, R.uniform(10, 26), R.uniform(10, 22), R.uniform(0, math.pi)),
            R.uniform(3, 13), "ruin", "#6b675e", roof="f")
    # outside the wall: wasteland, and what the city used to reach
    for _ in range(190):
        a = R.uniform(0, math.tau)
        d = R.uniform(WALL_R + 70, HALF * 0.97)
        px, pz = math.cos(a) * d, math.sin(a) * d
        if in_water(px, pz):
            continue
        put(rect(px, pz, R.uniform(10, 34), R.uniform(8, 26), R.uniform(0, math.pi)),
            R.uniform(2.5, 11), "ruin", "#6e6a61", roof="f")
    out["buildings"] = buildings

    # ---------- trees: the parks only; the streets were stripped long ago ----------
    trees = []
    for a in areas:
        if a["k"] != "park":
            continue
        x0, x1, z0, z1 = area_bbox(a)
        for _ in range(110):
            trees += [q(R.uniform(x0 + 8, x1 - 8)), q(R.uniform(z0 + 8, z1 - 8))]
    out["trees"] = trees
    out["pois"] = []

    json.dump(out, open(OUT, "w"), separators=(",", ":"))
    print(f"wrote {OUT}: {os.path.getsize(OUT)/1e6:.1f} MB; buildings {len(buildings)}; roads {len(roads)}; "
          f"areas {len(areas)}; terrain {nx}x{nz} at {step} m; trees {len(trees)//2}")


if __name__ == "__main__":
    main()
