#!/usr/bin/env python3
"""Generate Night City as a city data file the OSM engine can read.

    python3 tools/make-nightcity.py

Fan work: a coastal cyberpunk megacity drawing on Blade Runner's Los Angeles and on Cyberpunk's Night City.
Nothing here is surveyed and no assets from either are used - the layout is generated from a seed and every
shape is modelled from scratch in this project's own low-poly style. Blade Runner belongs to its rights
holders and Night City to CD Projekt Red.

Writes data/cities/nightcity-osm.json in the same shape tools/build-osm-city.py produces for a real city, so
nightcity.html renders it with the same stages as Chicago and New York:

  the Pacific to the west, a shoreline of docks and sea walls
  a supertall core on a tight grid, towers stacked to 500 m
  megablock housing: single slabs a quarter of a kilometre long, tens of thousands of people each
  an elevated ring highway on piers, with radials into the core
  an industrial plain to the south-east where the flare stacks burn
"""
import json
import math
import os
import random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "cities", "nightcity-osm.json")
R = random.Random(2049)

HALF = 2600.0
CORE = (260.0, -180.0)      # the corporate core
CORE_R = 760.0
BLOCK = 92.0                # a tight grid: the city was built up, not out
STREET = 15.0
AVENUE = 32.0
HIWAY_R = 1320.0            # the elevated ring
HIWAY_W = 34.0
PLAZA_LEVEL = 12.0


def q(v):
    return int(round(v * 10))


def flat(pts):
    out = []
    for x, z in pts:
        out += [q(x), q(z)]
    return out


def rect(cx, cz, w, d, rot=0.0):
    c, s = math.cos(rot), math.sin(rot)
    return [(cx + x * c - z * s, cz + x * s + z * c) for x, z in
            ((-w / 2, -d / 2), (w / 2, -d / 2), (w / 2, d / 2), (-w / 2, d / 2))]


def smoothstep(a, b, v):
    t = max(0.0, min(1.0, (v - a) / (b - a)))
    return t * t * (3 - 2 * t)


def simplify(pts, eps=1.0):
    if len(pts) < 3:
        return pts
    ax, az = pts[0]
    bx, bz = pts[-1]
    dx, dz = bx - ax, bz - az
    L = math.hypot(dx, dz)
    worst, wi = 0.0, 0
    for i in range(1, len(pts) - 1):
        px, pz = pts[i]
        d = abs(dx * (az - pz) - dz * (ax - px)) / L if L else math.hypot(px - ax, pz - az)
        if d > worst:
            worst, wi = d, i
    if worst <= eps:
        return [pts[0], pts[-1]]
    return simplify(pts[:wi + 1], eps)[:-1] + simplify(pts[wi:], eps)


# ---------- the coast ----------
def shore_x(z):
    """The waterline: the Pacific is west, and the shore bends around a bay in the north."""
    return -1520 + 250 * math.sin(z / 1500.0 + 0.6) + 90 * math.sin(z / 520.0)


def in_water(x, z):
    return x < shore_x(z)


def terrain_height(x, z):
    """A coastal plain that lifts inland, and the seabed falling away west of the shore."""
    d = x - shore_x(z)
    if d < 0:
        return max(-9.0, -1.5 + d * 0.02)
    rise = 34 * smoothstep(0, 2600, d) + 16 * smoothstep(1800, 3400, d)
    roll = 5 * math.sin(x / 640.0 + 1.3) * math.cos(z / 880.0)
    h = 2.5 + rise + roll
    cx, cz = CORE
    cut = 1 - smoothstep(CORE_R * 0.5, CORE_R * 1.3, math.hypot(x - cx, z - cz))
    h = h * (1 - cut) + PLAZA_LEVEL * cut          # the core sits on a levelled deck
    h *= smoothstep(HALF, HALF - 300, max(abs(x), abs(z)))
    return max(0.4, h)


def main():
    out = {"attribution": "Night City: fan geometry generated by tools/make-nightcity.py; no game or film assets used",
           "units": "decimetres east (x) and south (z) of origin", "origin": [34.05, -118.24],
           "bounds": [34.0266, -118.2682, 34.0734, -118.2118]}

    # ---------- terrain ----------
    step = 20
    nx = int(2 * HALF) // step + 2
    hs = []
    for j in range(nx):
        for i in range(nx):
            hs.append(terrain_height(-HALF + i * step, -HALF + j * step))
    out["terrain"] = {"step": step, "nx": nx, "nz": nx, "x0": q(-HALF), "z0": q(-HALF), "datum": 0.0,
                      "h": [int(round(h * 10)) for h in hs]}

    # ---------- the sea ----------
    edge = [(shore_x(z), z) for z in range(int(-HALF) - 300, int(HALF) + 301, 40)]
    out["lake"] = []
    out["islands"] = []
    out["water"] = [{"o": flat(edge + [(-HALF - 60000, HALF + 300), (-HALF - 60000, -HALF - 300)]), "i": [], "n": "The Pacific"}]
    out["marina"], out["beach"], out["pier"] = [], [], []
    out["waterways"] = []

    # ---------- streets ----------
    roads = []

    def road(pts, cls, w, name="", bridge=0):
        pts = simplify(pts)
        if len(pts) < 2:
            return
        r = {"c": cls, "w": round(w, 1), "p": flat(pts)}
        if name:
            r["n"] = name
        if bridge:
            r["b"] = bridge
        roads.append(r)

    def walk(pts, cls, w, name="", bridged=False):
        dense = []
        for i in range(len(pts) - 1):
            ax, az = pts[i]
            bx, bz = pts[i + 1]
            L = math.hypot(bx - ax, bz - az)
            n = max(1, int(L // 12))
            for k in range(n):
                u = k / n
                dense.append((ax + (bx - ax) * u, az + (bz - az) * u))
        dense.append(pts[-1])
        run = []
        for x, z in dense:
            if in_water(x, z) or max(abs(x), abs(z)) > HALF - 40:
                if len(run) > 1:
                    road(run, cls, w, name)
                run = []
                continue
            run.append((x, z))
        if len(run) > 1:
            road(run, cls, w, name)

    NAMES = ["Kanaka", "Sunset", "Ono", "Vasquez", "Tyrell", "Kowloon", "Delamain", "Santo", "Bradbury",
             "Sebastian", "Holden", "Rachael", "Arasaka", "Leon", "Zhirafa", "Mesa"]
    n = int(HALF // BLOCK)
    for i in range(-n, n + 1):
        v = i * BLOCK
        major = i % 5 == 0
        cls, w = ("secondary", AVENUE) if major else ("residential", STREET)
        k = i + n
        walk([(v, -HALF), (v, HALF)], cls, w, (NAMES[k % len(NAMES)] + " Street") if major else f"{k+1} Street")
        walk([(-HALF, v), (HALF, v)], cls, w, (NAMES[(k + 6) % len(NAMES)] + " Boulevard") if major else f"{k+1} Lane")

    # the elevated ring on its piers, and four radials dropping into the core
    ring = [(CORE[0] + math.cos(a) * HIWAY_R, CORE[1] + math.sin(a) * HIWAY_R)
            for a in [i / 96 * math.tau for i in range(97)]]
    ring = [p for p in ring if not in_water(*p) and max(abs(p[0]), abs(p[1])) < HALF - 60]
    if len(ring) > 2:
        road(ring, "trunk", HIWAY_W, "Ring Freeway", bridge=1)
    for k, a in enumerate([0.5, 2.0, 3.6, 5.1]):
        pts = [(CORE[0] + math.cos(a) * r, CORE[1] + math.sin(a) * r) for r in range(int(CORE_R * 0.6), int(HIWAY_R * 1.6), 30)]
        pts = [p for p in pts if not in_water(*p) and max(abs(p[0]), abs(p[1])) < HALF - 60]
        if len(pts) > 2:
            road(pts, "trunk", 26, f"Radial {k+1}", bridge=1)
    out["roads"] = roads

    # ---------- land ----------
    areas = [{"k": "plaza", "n": "Corporate Plaza", "o": flat(rect(CORE[0], CORE[1], 300, 260)), "i": []},
             {"k": "industrial", "n": "The Flats", "o": flat(rect(1500, 1500, 1500, 1000)), "i": []},
             {"k": "industrial", "n": "Dock Yards", "o": flat(rect(-1150, -900, 620, 760)), "i": []},
             {"k": "park", "n": "Reclamation Park", "o": flat(rect(-500, 1250, 420, 320)), "i": []},
             {"k": "parking", "n": "Lower Stacks", "o": flat(rect(950, -1150, 380, 300)), "i": []}]
    out["areas"] = areas

    def area_bbox(a):
        xs = [a["o"][i] / 10 for i in range(0, len(a["o"]), 2)]
        zs = [a["o"][i] / 10 for i in range(1, len(a["o"]), 2)]
        return min(xs), max(xs), min(zs), max(zs)

    # ---------- rail: the transit line along the shore and a spur to the flats ----------
    out["rail"] = [{"t": "L", "e": 1, "n": "Coast Line",
                    "p": flat([(shore_x(z) + 210, z) for z in range(int(-HALF) + 120, int(HALF) - 119, 60)])},
                   {"t": "rail", "e": 0, "n": "Flats Spur", "p": flat([(700 + i * 34, 900 + i * 12) for i in range(36)])},
                   {"t": "tram", "e": 0, "n": "Tram", "p": flat([(-HALF + 300, 184), (HALF - 300, 184)])}]
    out["stations"] = [{"n": "Coast Terminal", "x": q(-980), "z": q(-120)},
                       {"n": "Core Station", "x": q(180), "z": q(340)}]

    # ---------- buildings ----------
    buildings = []
    # the human city underneath: grimed concrete, stained render, corrugated iron, and a lot of dark glass
    CONCRETE = ["#55565a", "#4c4d52", "#606167", "#47484d", "#6a6a70"]
    GRIME = ["#5a5148", "#4e463f", "#655a4f", "#453f3a"]
    GLASS = ["#2c3a48", "#243140", "#35455a", "#1e2833", "#3d4f66"]
    IRON = ["#5d4f45", "#6a5a4c", "#4f453e"]

    def put(ring, h, kind=None, colour=None, name=None, roof="f", minh=None):
        b = {"p": flat(ring), "h": round(h, 1), "r": roof}
        if kind:
            b["t"] = kind
        if colour:
            b["c"] = colour
        if name:
            b["n"] = name
        if minh:
            b["m"] = round(minh, 1)
        buildings.append(b)

    def line_w(i):
        return AVENUE if i % 5 == 0 else STREET

    def span(i):
        lo = i * BLOCK + line_w(i) / 2 + 1.5
        hi = (i + 1) * BLOCK - line_w(i + 1) / 2 - 1.5
        return (lo + hi) / 2, hi - lo

    cx, cz = CORE
    for i in range(-n, n + 1):
        for j in range(-n, n + 1):
            bx, wx = span(i)
            bz, wz = span(j)
            if in_water(bx, bz) or max(abs(bx), abs(bz)) > HALF - 90:
                continue
            skip = False
            for a in areas:
                x0, x1, z0, z1 = area_bbox(a)
                if x0 - 10 < bx < x1 + 10 and z0 - 10 < bz < z1 + 10:
                    skip = True
            if skip:
                continue
            d = math.hypot(bx - cx, bz - cz)
            core = max(0.0, 1 - d / CORE_R)
            if d < CORE_R * 0.42 and R.random() < 0.62:
                # the core: one tower to a block, and they are stacked as high as they will go
                h = 170 + core * 190 + R.random() * 150
                if R.random() < 0.10:
                    h += 150 + R.random() * 190
                w = min(wx, wz) * (0.62 + R.random() * 0.26)
                put(rect(bx, bz, w, w * (0.8 + R.random() * 0.35), R.random() * 0.25), h,
                    "tower", GLASS[R.randrange(len(GLASS))])
                if R.random() < 0.5:      # a setback shaft carrying the mast
                    put(rect(bx, bz, w * 0.5, w * 0.5, 0.2), h + 30 + R.random() * 70, "tower",
                        GLASS[R.randrange(len(GLASS))], minh=h)
                continue
            if 0.30 < core < 0.82 and R.random() < 0.13:
                # megablocks: a single slab filling the plot, with the whole population of a district in it
                h = 110 + R.random() * 110
                put(rect(bx, bz, wx * 0.94, wz * 0.94), h, "megablock", CONCRETE[R.randrange(len(CONCRETE))])
                for k in range(3):        # the service towers that stand off its roof
                    put(rect(bx + (R.random() - 0.5) * wx * 0.6, bz + (R.random() - 0.5) * wz * 0.6, 9, 9),
                        h + 12 + R.random() * 26, "plant", "#3f4046", minh=h)
                continue
            # everything else: the retrofitted low city, built up in pieces and never cleared
            base = 22 + core * 60 + R.random() * 26
            depth = 13 + R.random() * 5
            for side in range(4):
                if R.random() < 0.10:
                    continue
                h = base * (0.8 + R.random() * 0.5)
                ang = side * math.pi / 2
                across, along = (wx, wz) if side % 2 == 0 else (wz, wx)
                ox = math.cos(ang) * (across / 2 - depth / 2)
                oz = math.sin(ang) * (across / 2 - depth / 2)
                length = along * (0.76 + R.random() * 0.24)
                ring = rect(bx + ox, bz + oz, depth if side % 2 == 0 else length, length if side % 2 == 0 else depth)
                pal = GRIME if R.random() < 0.45 else CONCRETE
                put(ring, h, "apartments", pal[R.randrange(len(pal))])
                if R.random() < 0.35:     # the accretions: plant, shacks and ducting bolted on top
                    put(rect(bx + ox, bz + oz, (depth if side % 2 == 0 else length) * 0.5,
                             (length if side % 2 == 0 else depth) * 0.5),
                        h + 4 + R.random() * 12, "plant", IRON[R.randrange(len(IRON))], minh=h)
            if R.random() < 0.3:
                put(rect(bx + (R.random() - 0.5) * 14, bz + (R.random() - 0.5) * 14, 12 + R.random() * 10, 10 + R.random() * 8),
                    6 + R.random() * 7, "shed", IRON[R.randrange(len(IRON))])

    # the works out on the flats, and the sheds along the dock
    for a in areas:
        if a["k"] != "industrial":
            continue
        x0, x1, z0, z1 = area_bbox(a)
        for _ in range(26):
            ax = R.uniform(x0 + 50, x1 - 50)
            az = R.uniform(z0 + 40, z1 - 40)
            if in_water(ax, az):
                continue
            if R.random() < 0.3:
                put(rect(ax, az, R.uniform(22, 44), R.uniform(22, 44)), R.uniform(20, 54), "tank", "#4a4741")
            else:
                put(rect(ax, az, R.uniform(60, 150), R.uniform(36, 78)), R.uniform(11, 26), "industrial",
                    IRON[R.randrange(len(IRON))])
    # ---------- the sea wall ----------
    # The Pacific stands ninety-five metres above the city and this is what is between them. It is battered
    # seaward, so it goes up as four stepped courses each set a little further inland than the one below, with
    # buttresses every third bay taking the load out into the water, sluice towers along it, and a road on top.
    WALL_H = 208.0
    COURSES = 4
    BAY = 42
    b = 0
    for z in range(int(-HALF) - 200, int(HALF) + 200, BAY):
        sx = shore_x(z)
        sx2 = shore_x(z + BAY)
        for c in range(COURSES):
            t0 = c / COURSES
            t1 = (c + 1) / COURSES
            inset = 26 * t0                       # each course steps back: the face leans into the sea
            thick = 34 - 6 * t0
            put([(sx + inset, z), (sx + inset + thick, z),
                 (sx2 + inset + thick, z + BAY), (sx2 + inset, z + BAY)],
                WALL_H * t1, "wall", "#4f5055" if c % 2 else "#565760", minh=WALL_H * t0)
        # the landward face: pilasters the full height of it every bay, and a string course at each step.
        # Without them 208 m of plain concrete reads as background rather than as a wall.
        shade = ["#53545a", "#4b4c51", "#5a5b62", "#494a50"][(z // BAY) % 4]
        put([(sx + 30, z + 5), (sx + 42, z + 5), (sx + 42, z + 17), (sx + 30, z + 17)],
            WALL_H * 0.96, "pilaster", shade)
        put([(sx + 30, z + 26), (sx + 42, z + 26), (sx + 42, z + 38), (sx + 30, z + 38)],
            WALL_H * 0.72, "pilaster", shade)
        for c in range(1, COURSES):
            y = WALL_H * c / COURSES
            put([(sx + 26 * (c / COURSES) - 3, z), (sx + 40, z), (sx2 + 40, z + BAY), (sx2 + 26 * (c / COURSES) - 3, z + BAY)],
                y + 5, "course", "#404146", minh=y - 4)
        # the parapet along the top
        put([(sx + 24, z), (sx + 34, z), (sx2 + 34, z + BAY), (sx2 + 24, z + BAY)],
            WALL_H + 7, "parapet", "#3c3d42", minh=WALL_H)
        # the buttresses, out into the water
        if (z // BAY) % 3 == 0:
            put([(sx - 58, z + 12), (sx + 6, z + 12), (sx + 6, z + 30), (sx - 58, z + 30)],
                WALL_H * 0.62, "buttress", "#494a4f")
            put([(sx - 34, z + 12), (sx + 6, z + 12), (sx + 6, z + 30), (sx - 34, z + 30)],
                WALL_H * 0.82, "buttress", "#4e4f55")
        # sluice towers, and the lamp masts along the parapet
        if (z // BAY) % 11 == 0:
            put(rect(sx + 14, z + 21, 30, 30), WALL_H * 1.14, "tower", "#3f4045")
        b += 1
    # the road along the top of it
    top = [(shore_x(z) + 22, z) for z in range(int(-HALF) + 40, int(HALF) - 39, 80)]
    road(top, "trunk", 22, "Sea Wall Road")
    out["buildings"] = buildings

    trees = []
    for a in areas:
        if a["k"] != "park":
            continue
        x0, x1, z0, z1 = area_bbox(a)
        for _ in range(160):
            trees += [q(R.uniform(x0 + 8, x1 - 8)), q(R.uniform(z0 + 8, z1 - 8))]
    out["trees"] = trees
    out["pois"] = []

    json.dump(out, open(OUT, "w"), separators=(",", ":"))
    t = out["terrain"]
    print(f"wrote {OUT}: {os.path.getsize(OUT)/1e6:.1f} MB; buildings {len(buildings)}; roads {len(roads)}; "
          f"areas {len(areas)}; terrain {t['nx']}x{t['nz']} at {t['step']} m; trees {len(trees)//2}")


if __name__ == "__main__":
    main()
