#!/usr/bin/env python3
"""Write INDEX.md at the repo root and in every build folder.

A build's INDEX.md lists each src/ fragment with its size and section
headings, so an agent can find the part it needs without opening large
files. The root INDEX.md lists every build.

Usage:  python3 tools/make_index.py      (from anywhere; rewrites every INDEX.md)
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIG = 30 * 1024          # CLAUDE.md: never read a fragment this size whole

ABOUT = {
    'settlements/voth': 'Voth: a Venice/Vivec-like Dunmer city on an enclosed brackish bay, with the most complete life layer and collision system.',
    'settlements/yuni': 'Yuni: the city, plus its building-kit and plant sheets (its furniture is in kits/catalog).',
    'settlements/dalab': 'Dalab: the mound settlement of the southwestern lowlands, and its building set.',
    'settlements/highlands': 'Highlands: Republican, Rustic and Tribal building kits for the temperate highlands of the Inner Wall, and the town of Roketstad.',
    'settlements/iziz': 'Iziz: the city rebuilt on the Iziz Vernacular style and the Ancients kit.',
    'settlements/reedlake': 'Reed Lake: a floating reed-lake village and its kit.',
    'settlements/screamers': 'Hexahedron: the Screamers\' tribal village in and under a ruined arcology, forked from the Ancients kit.',
    'settlements/locus': 'Locus: a fork of the Yuni engine in the eastern abyss, with its own kit sheet and plant catalogue.',
    'settlements/girder': 'Girder: an outlying Beast Rider village in the central-crater hyperjungle.',
    'settlements/mavs-refuge': "Mav's Refuge: a refuge in the hypertropic jungle on the lee shore of the Ring Sea.",
    'settlements/ys': 'Ys: the half-drowned Hykkousoi capital on the ruins of an Ancient city at the head of the north-west bay of the Ring Sea (phase 0: harness and empty world).',
    'settlements/xanadu': 'Xanadu: the building kit of the southern Sultanate (Tibetan massing, Indian, Turkish and Persian detail) and the city of Erewhon.',
    'kits/ringsea': 'Ring Sea watercraft: 21 procedural vessels (warships, cargo ships, barges, canoes, outriggers, rafts) of the cultures round the Ring Sea.',
    'kits/post-apoc': 'The Post-Apoc set: reclaimed and recycled buildings (containers, silos, tanks, buses, bulkheads, tyre and bottle walls) with sockets for any culture\'s marks.',
    'kits/ancients': 'The Ancients kit: ruined megastructures of the ancient civilisation, 33 structure types, one target per site.',
}
# Files that are generated or duplicated elsewhere: never edit or read them whole.
GENERATED = {
    'settlements/yuni/src/61a-ancients-kit.js': 'generated by tools/gen_ancients.py: a patched copy of the Ancients kit',
}
RE_SECTION = [re.compile(r'^/\*\s*={3,}\s*(.+?)\s*=*\s*(?:\*/)?\s*$'),
              re.compile(r'^//\s*-{8,}\s*(\S.*?)\s*$')]


def sections(path):
    out = []
    with open(path, encoding='utf-8', errors='replace') as fh:
        for n, line in enumerate(fh, 1):
            for rx in RE_SECTION:
                m = rx.match(line)
                if m:
                    t = re.sub(r'\s*={2,}.*$', '', m.group(1)).strip(' *')
                    if t:
                        out.append('%s (%d)' % (t[:48], n))
                    break
    return out


def kb(n):
    return '%d' % round(n / 1024) if n >= 1024 else '<1'


def core_files(build):
    """Files a build pulls from core/materials/ (see srcpath() in its build.py)."""
    bp = os.path.join(ROOT, build, 'build.py')
    if 'CORE_FILES' not in open(bp).read():
        return []
    d = os.path.join(ROOT, 'core', 'materials')
    return sorted(f for f in os.listdir(d) if f[0].isdigit())


def frag_table(build, folder, rel):
    rows = []
    for f in sorted(os.listdir(folder)):
        p = os.path.join(folder, f)
        if not os.path.isfile(p) or not f[0].isdigit():
            continue
        size = os.path.getsize(p)
        note = GENERATED.get('%s/%s/%s' % (build, rel, f))
        secs = '; '.join(sections(p)[:10]) if f.endswith('.js') else ''
        flag = ' **big**' if size >= BIG else ''
        rows.append('| `%s` | %s%s | %s |' % (f, kb(size), flag,
                                          ('*%s.* ' % note if note else '') + secs))
    return rows


def outputs(build):
    d = os.path.join(ROOT, build)
    out = [f for f in sorted(os.listdir(d)) if f.endswith('.html') and not f.startswith('.')]
    if os.path.isdir(os.path.join(d, 'dist')):
        out += ['dist/' + f for f in sorted(os.listdir(os.path.join(d, 'dist'))) if f.endswith('.html')]
    return out


def build_index(build):
    d = os.path.join(ROOT, build)
    src = os.path.join(d, 'src')
    lines = ['# %s: index' % build, '',
             '*Generated by `tools/make_index.py`. Do not edit; rerun it after adding or splitting fragments.*', '']
    if build in ABOUT:
        lines += [ABOUT[build], '']
    docs = [f for f in sorted(os.listdir(d)) if f.endswith('.md') and f != 'INDEX.md']
    if docs:
        lines += ['Docs: ' + ', '.join('`%s`' % f for f in docs), '']
    outs = outputs(build)
    if outs:
        lines += ['Built output (never open it; edit `src/` and rebuild): ' + ', '.join('`%s`' % f for f in outs), '']
    lines += ['Build: `cd %s && python3 build.py`. Fragments are concatenated in filename order.' % build]
    if 'def units(' in open(os.path.join(d, 'build.py')).read():
        lines += ['Files that share a numeric prefix (`78a-`, `78b-`) are one fragment split into parts: '
                  'one `reseed(N)` stream, one unit for the build rules.']
    lines += ['Fragments marked **big** are over 30 KB: find the section below and read only that range.', '']
    cf = core_files(build)
    if cf:
        lines += ['From `core/materials/` (shared; see `core/README.md`): ' + ', '.join('`%s`' % f for f in cf), '']
    lines += ['## src/', '', '| Fragment | KB | Sections (line) |', '|---|---|---|']
    lines += frag_table(build, src, 'src')
    tdir = os.path.join(d, 'targets')
    if os.path.isdir(tdir):
        lines += ['', '## targets/', '',
                  'Each target adds its own fragments to `src/` and builds one output.', '',
                  '| Target | Fragments | KB |', '|---|---|---|']
        for t in sorted(os.listdir(tdir)):
            td = os.path.join(tdir, t)
            if os.path.isdir(td):
                fs = [f for f in os.listdir(td) if f[0].isdigit()]
                lines.append('| `%s` | %s | %s |' % (t, ', '.join('`%s`' % f for f in sorted(fs)),
                                                    kb(sum(os.path.getsize(os.path.join(td, f)) for f in fs))))
    with open(os.path.join(d, 'INDEX.md'), 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')
    sizes = [os.path.getsize(os.path.join(src, f)) for f in os.listdir(src) if f[0].isdigit()]
    return len(sizes), sum(sizes), max(sizes), outs


def main():
    builds = []
    for top in ('settlements', 'kits', 'biomes'):
        for name in sorted(os.listdir(os.path.join(ROOT, top))):
            b = '%s/%s' % (top, name)
            if os.path.isfile(os.path.join(ROOT, b, 'build.py')) and os.path.isdir(os.path.join(ROOT, b, 'src')):
                builds.append(b)
    rows = []
    for b in builds:
        n, total, biggest, outs = build_index(b)
        about = ABOUT.get(b, 'Biome kit: see `biomes/README.md`.' if b.startswith('biomes/') else '')
        rows.append('| [`%s`](%s/INDEX.md) | %d | %s | %s | %s |' % (b, b, n, kb(total), kb(biggest), about))
    lines = ['# Krator: index', '',
             '*Generated by `tools/make_index.py`. Do not edit; rerun it after adding a build or fragments.*', '',
             'Every build is a folder with `src/` fragments and a `build.py`. Open a build\'s `INDEX.md` '
             'before its source. Design rules for all builds are in `README.md`; working rules for agents '
             'are in `CLAUDE.md`.', '',
             '| Build | Fragments | src KB | Largest KB | What |', '|---|---|---|---|---|'] + rows + [
             '', '## Not builds', '',
             '| Path | What |', '|---|---|',
             '| `core/` | shared code: `core/materials/` (see `core/README.md`) and `core/sockets/` (cultural sockets, banners and awnings, with a runnable example) |',
             '| `kits/catalog/` | harvested master catalog of furniture, plants and buildings (unverified) |',
             '| `kits/furniture/`, `kits/interiors/` | specs only |',
             '| `gallery/` | the shareable gallery of every built world |',
             '| `host/` | the LAN site server: Krator Worlds plus the World Menagerie pages (`host/README.md`) |',
             '| `tools/` | repo-wide scripts: this index |',
             '| `archive/` | old scratch and screenshots; do not build from it |']
    with open(os.path.join(ROOT, 'INDEX.md'), 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')
    print('wrote INDEX.md and %d build indexes' % len(builds))


if __name__ == '__main__':
    main()
