#!/usr/bin/env python3
"""Generate the Kowloon Walled City as a city data file the OSM engine can read.

    python3 tools/make-kowloon.py

The Walled City was demolished in 1993-94 and this is a model of what stood there, generated from the
published surveys and photographs; no plan, drawing or photograph is used or redistributed, and every shape
here is this project's own.

It is the smallest place in the menagerie and the densest thing in it by a long way. The site is 210 m by
120 m - two and a half hectares, about a third of the Iziz temple platform - and at the end there were some
three hundred and fifty buildings on it, grown into each other over forty years, holding around thirty-three
thousand people. Nothing was designed. Every building leant on the ones beside it, the lanes between them
were roofed over by the floors above, and the whole block ran to fourteen storeys and stopped, because Kai
Tak's approach path was overhead and anything taller was in the way of the aeroplanes.

So the interesting numbers are the other way up from every other place here. Chicago is 81,000 buildings over
eighty square kilometres; this is 350 over a quarter of one, and the model is built at metre scale rather than
ten-metre scale:

  the block itself, as a grid of plots six to nine metres across, each one run up to between eight and
  fourteen storeys, with the light wells and the two lanes left as gaps in it
  the roof, which is the only open ground the place had: water tanks, aerials, huts and the school
  the Yamen in the middle, which was there first and outlived it
  the streets round it, and the ordinary Kowloon City tenements across them
  Kai Tak, off to the south-east, and the approach that held the height down
"""
import json
import math
import os
import random
from lib.geo import q, flat, rect, smoothstep

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "cities", "kowloon-osm.json")
R = random.Random(1993)

HX, HZ = 620.0, 620.0            # half-extents: 1.24 km square
STEP = 10                        # the height grid: the ground here is flat, and what matters is above it

GROUND = 6.0                     # the site is a few metres above the harbour
BLOCK_W, BLOCK_D = 210.0, 120.0  # the Walled City itself
BLOCK_A = 0.14                   # and the angle it sits at
STOREY = 2.9


def terrain_height(x, z):
    h = GROUND
    h += 5.0 * smoothstep(-200, -620, z)          # the ground rises a little towards the hills, north
    h -= 3.0 * smoothstep(200, 620, x)            # and falls away towards the old airport, east
    h += 0.8 * math.sin(x / 90.0) * math.cos(z / 110.0)
    return h * smoothstep(HX, HX - 120, abs(x)) * smoothstep(HZ, HZ - 120, abs(z))


# the block's own frame: u along its length, v across it
def BP(u, v):
    c, s = math.cos(BLOCK_A), math.sin(BLOCK_A)
    return (u * c - v * s, u * s + v * c)


def main():
    out = {"attribution": "Kowloon Walled City: massing model generated by tools/make-kowloon.py from published "
                          "descriptions; no survey, drawing or photograph is used",
           "units": "decimetres east (x) and south (z) of origin", "origin": [22.3325, 114.1904],
           "bounds": [22.32692, 114.18437, 22.33808, 114.19643]}

    nx = int(2 * HX) // STEP + 2
    nz = int(2 * HZ) // STEP + 2
    hs = []
    for j in range(nz):
        zz = -HZ + j * STEP
        for i in range(nx):
            hs.append(terrain_height(-HX + i * STEP, zz))
    out["terrain"] = {"step": STEP, "nx": nx, "nz": nz, "x0": q(-HX), "z0": q(-HZ), "datum": 0.0,
                      "h": [int(round(h * 10)) for h in hs]}

    out["water"], out["lake"], out["islands"] = [], [], []
    out["marina"], out["beach"], out["pier"], out["waterways"] = [], [], [], []

    # ---------- the streets ----------
    roads = []

    def road(pts, cls, w, name=""):
        r = {"c": cls, "w": round(w, 1), "p": flat(pts)}
        if name:
            r["n"] = name
        roads.append(r)

    HW, HD = BLOCK_W / 2 + 16, BLOCK_D / 2 + 14        # the four roads that boxed it in
    ring = [BP(-HW, -HD), BP(HW, -HD), BP(HW, HD), BP(-HW, HD), BP(-HW, -HD)]
    road([ring[0], ring[1]], "secondary", 12, "Tung Tau Tsuen Road")
    road([ring[1], ring[2]], "secondary", 11, "Lung Shing Road")
    road([ring[2], ring[3]], "secondary", 12, "Tung Tsing Road")
    road([ring[3], ring[0]], "secondary", 11, "Carpenter Road")
    # the district outside: a grid of ordinary streets at the same angle
    for k in range(-3, 4):
        if k == 0:
            continue
        road([BP(-600, k * 95), BP(600, k * 95)], "residential", 9)
        road([BP(k * 130, -600), BP(k * 130, 600)], "residential", 9)
    # the two lanes through the block, which are the only ones that had names
    road([BP(-BLOCK_W / 2, -10), BP(BLOCK_W / 2, -10)], "footway", 2.2, "Lung Chun Front Road")
    road([BP(-20, -BLOCK_D / 2), BP(-20, BLOCK_D / 2)], "footway", 1.8, "Tai Cheng Street")
    out["roads"] = roads

    # ---------- areas ----------
    areas = [{"k": "plaza", "n": "The Yamen", "o": flat(rect(*BP(0, 0), 44, 26, BLOCK_A)), "i": []}]
    for k in range(9):                                   # the playgrounds and drying grounds outside
        a = R.uniform(0, math.tau)
        d = R.uniform(240, 520)
        areas.append({"k": "park" if k % 3 else "grass", "n": "",
                      "o": flat(rect(math.cos(a) * d, math.sin(a) * d,
                                     R.uniform(40, 90), R.uniform(30, 70), BLOCK_A)), "i": []})
    out["areas"] = areas
    out["rail"] = []
    out["stations"] = []

    # ---------- the block ----------
    buildings = []

    def put(ring, h, kind=None, colour=None, name=None, roof=None, minh=None):
        b = {"p": flat(ring), "h": round(h, 1)}
        if kind:
            b["t"] = kind
        if colour:
            b["c"] = colour
        if name:
            b["n"] = name
        if roof:
            b["r"] = roof
        if minh:
            b["m"] = round(minh, 1)
        buildings.append(b)

    # The palette is what forty years of unpainted concrete, cement render and rust looks like: no two
    # buildings the same age, and nothing that was ever chosen.
    CONC = ["#8e8a80", "#7f7b72", "#9a958a", "#6f6c66", "#878378", "#928c7e", "#6a6760"]
    STAIN = ["#5f5a50", "#6a6256", "#55514a"]
    # the plots the block is divided into, and the light wells and lanes that are left out of it
    PW, PD = 7.5, 8.5
    VOIDS = [(-64, 8, 11), (-18, -26, 9), (26, 18, 10), (68, -14, 12), (44, -36, 8), (-40, 34, 9)]

    def is_void(u, v):
        # The test is against the plot's centre, so the clearance has to allow for half a plot either side:
        # at 2.6 m the lane fell between two rows of centres and was never cleared at all, and the two named
        # lanes of the Walled City ran straight through the middle of somebody's building.
        if abs(v + 10) < 2.6 + PD / 2 or abs(u + 20) < 2.3 + PW / 2:
            return True
        for (vu, vv, vr) in VOIDS:
            if math.hypot(u - vu, v - vv) < vr:
                return True
        return False

    # the plots: a grid across the site, each one a building run up on its own
    n = [0]
    nu = int(BLOCK_W / PW)
    nv = int(BLOCK_D / PD)
    for i in range(nu):
        for j in range(nv):
            u = -BLOCK_W / 2 + (i + 0.5) * PW
            v = -BLOCK_D / 2 + (j + 0.5) * PD
            if is_void(u, v):
                continue
            # The height: fourteen storeys at the middle, falling off towards the edges, because the outside
            # of the block is where the older and lower buildings were. Nothing goes over 14: Kai Tak.
            core = 1 - max(abs(u) / (BLOCK_W / 2), abs(v) / (BLOCK_D / 2))
            st = 6 + round(core * 7 + R.uniform(-1.6, 1.6))
            st = max(3, min(14, st))
            h = GROUND + st * STOREY
            w = PW * R.uniform(0.86, 1.0)
            d = PD * R.uniform(0.86, 1.0)
            cx, cz = BP(u + R.uniform(-0.5, 0.5), v + R.uniform(-0.5, 0.5))
            put(rect(cx, cz, w, d, BLOCK_A + R.uniform(-0.05, 0.05)), h, "residential",
                CONC[R.randrange(len(CONC))], roof="f")
            n[0] += 1
            # the additions: a floor or two bolted on top, set back and a different colour, which is how
            # the block grew after the buildings under them were finished
            if R.random() < 0.42:
                add = R.randint(1, 3)
                put(rect(cx + R.uniform(-1, 1), cz + R.uniform(-1, 1), w * R.uniform(0.6, 0.9),
                         d * R.uniform(0.6, 0.9), BLOCK_A), h + add * STOREY, "addition",
                    STAIN[R.randrange(len(STAIN))], roof="f", minh=h)
                n[0] += 1
            # the cage balconies hanging off the street faces
            if R.random() < 0.3 and (i == 0 or i == nu - 1 or j == 0 or j == nv - 1):
                bx, bz = BP(u + (1.4 if i > nu / 2 else -1.4) * PW * 0.5, v)
                put(rect(bx, bz, 2.2, d * 0.7, BLOCK_A), h - R.uniform(3, 12), "balcony", "#5a5f5a",
                    roof="f", minh=GROUND + 3 * STOREY)

    # The lanes were not open to the sky for long. Once a building had a floor to spare it was built out over
    # the lane, so the two lanes ran as tunnels under everybody else's flats, lit by strip lights, and what
    # daylight got in got in at the ends. These are those overbuilds: a floor bridging the lane, starting
    # three storeys up so the lane itself stays open at head height.
    for u in range(int(-BLOCK_W / 2) + 12, int(BLOCK_W / 2) - 12, 9):
        if R.random() < 0.34:
            continue
        base = GROUND + R.randint(3, 6) * STOREY
        top = base + R.randint(2, 6) * STOREY
        cx, cz = BP(u + R.uniform(-1, 1), -10)
        put(rect(cx, cz, 8, 7.4, BLOCK_A), top, "overbuild", CONC[R.randrange(len(CONC))],
            roof="f", minh=base)
    for v in range(int(-BLOCK_D / 2) + 10, int(BLOCK_D / 2) - 10, 9):
        if R.random() < 0.4:
            continue
        base = GROUND + R.randint(3, 6) * STOREY
        top = base + R.randint(2, 5) * STOREY
        cx, cz = BP(-20, v + R.uniform(-1, 1))
        put(rect(cx, cz, 6.6, 8, BLOCK_A), top, "overbuild", CONC[R.randrange(len(CONC))],
            roof="f", minh=base)

    # ---------- the roof: the only open ground the place had ----------
    # Water tanks, aerials by the thousand, huts, pigeon lofts and the rooftop school. The engine puts its own
    # units on flat roofs; these are the things that were particular to here.
    for k in range(240):
        u = R.uniform(-BLOCK_W / 2 + 4, BLOCK_W / 2 - 4)
        v = R.uniform(-BLOCK_D / 2 + 4, BLOCK_D / 2 - 4)
        if is_void(u, v):
            continue
        core = 1 - max(abs(u) / (BLOCK_W / 2), abs(v) / (BLOCK_D / 2))
        top = GROUND + max(3, min(14, 6 + round(core * 7))) * STOREY
        cx, cz = BP(u, v)
        kind = R.random()
        if kind < 0.42:                                   # an aerial: a mast and a rake of elements
            put(rect(cx, cz, 0.5, 0.5, BLOCK_A), top + R.uniform(3, 9), "mast", "#4a4a48", roof="f", minh=top)
            for e in range(R.randint(2, 5)):
                put(rect(cx, cz, R.uniform(1.6, 3.4), 0.2, BLOCK_A + R.uniform(0, 1.2)),
                    top + 3 + e * 1.2, "aerial", "#5a5a56", roof="f", minh=top + 2.6 + e * 1.2)
        elif kind < 0.72:                                 # a water tank
            put(rect(cx, cz, R.uniform(1.8, 3.2), R.uniform(1.6, 2.6), BLOCK_A), top + R.uniform(1.4, 2.4),
                "tank", "#7a6f5e", roof="f", minh=top)
        elif kind < 0.92:                                 # a hut, of which there were hundreds
            put(rect(cx, cz, R.uniform(3, 6), R.uniform(2.6, 5), BLOCK_A), top + R.uniform(2.2, 3.2),
                "shed", "#6c675e", roof="f", minh=top)
        else:                                             # a pigeon loft
            put(rect(cx, cz, R.uniform(2, 3.4), R.uniform(1.8, 2.6), BLOCK_A), top + 2.4, "loft", "#82705a",
                roof="f", minh=top)
    # the rooftop school, which was a real thing and stood on the highest roofs at the middle
    sx, sz = BP(6, 14)
    put(rect(sx, sz, 16, 9, BLOCK_A), GROUND + 14 * STOREY + 3.2, "school", "#9a9384",
        name="The rooftop school", roof="f", minh=GROUND + 14 * STOREY)

    # ---------- the Yamen ----------
    # The Qing magistrate's office: three halls round two courtyards, put up in 1847, and the only thing on
    # the site that was built on purpose. It outlived everything round it and is still there.
    for k, (du, dd) in enumerate(((-14, 0), (0, 0), (14, 0))):
        yx, yz = BP(du, dd)
        put(rect(yx, yz, 10, 20, BLOCK_A), GROUND + 6.5, "civic", "#7d6a55",
            name="The Yamen" if k == 1 else None, roof="g")

    # ---------- the district outside ----------
    for k in range(150):
        a = R.uniform(0, math.tau)
        d = R.uniform(150, 560)
        cx, cz = math.cos(a) * d, math.sin(a) * d
        if abs(cx) < BLOCK_W / 2 + 26 and abs(cz) < BLOCK_D / 2 + 24:
            continue
        w, dd = R.uniform(14, 30), R.uniform(12, 24)
        put(rect(cx, cz, w, dd, BLOCK_A + R.uniform(-0.1, 0.1)), GROUND + R.uniform(5, 9) * STOREY,
            "residential", CONC[R.randrange(len(CONC))], roof="f")

    out["buildings"] = buildings

    # ---------- trees and points of interest ----------
    trees = []
    for k in range(120):
        a = R.uniform(0, math.tau)
        d = R.uniform(190, 600)
        trees.append({"x": q(math.cos(a) * d), "z": q(math.sin(a) * d), "r": q(R.uniform(2.5, 5))})
    out["trees"] = trees
    out["pois"] = [{"n": "The Yamen", "x": q(BP(0, 0)[0]), "z": q(BP(0, 0)[1]), "k": "civic", "ang": BLOCK_A}]

    t = out["terrain"]
    with open(OUT, "w") as f:
        json.dump(out, f, separators=(",", ":"))
    print(f"wrote {OUT}: {os.path.getsize(OUT)/1e6:.2f} MB; buildings {len(buildings)} "
          f"({n[0]} in the block); roads {len(roads)}; terrain {t['nx']}x{t['nz']} at {t['step']} m")


if __name__ == "__main__":
    main()
