#!/usr/bin/env python3
"""Generate the fictional occupied city of Vashrin as a city data file the OSM engine can read.

    python3 tools/make-vashrin.py

Writes data/cities/vashrin-osm.json in the same shape tools/build-osm-city.py produces for a real city
(terrain grid, water, land areas, streets, rail, buildings), so vashrin.html renders it with the same
stages as Chicago and Portland. Everything here is invented: a river valley, a grid of courtyard blocks,
a ring wall with checkpoints, rail yards, and the plaza the tower stands on.

This is an original design in the spirit of Eastern-bloc-styled dystopian cities; it is not a copy of any
particular published city.
"""
import json
import math
import os
import random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "cities", "vashrin-osm.json")
R = random.Random(1704)

HALF = 1900.0          # the map runs from -HALF to +HALF in both directions
WALL_R = 1500.0        # the perimeter wall
PLAZA = 220.0          # half-width of the central plaza
BLOCK = 104.0          # block pitch
STREET = 16.0
AVENUE = 30.0
RIVER_W = 95.0
CANAL_W = 26.0
PLAZA_LEVEL = 44.0     # the plaza is a cut terrace, and the whole city is laid out around it
GATES = [0.6, 2.1, 3.7, 5.2]   # the four gaps in the wall, and the avenues that run to them


def q(v):
    return int(round(v * 10))


def flat(pts):
    out = []
    for x, z in pts:
        out += [q(x), q(z)]
    return out


def rect(cx, cz, w, d, rot=0.0):
    c, s = math.cos(rot), math.sin(rot)
    return [(cx + x * c - z * s, cz + x * s + z * c) for x, z in
            ((-w / 2, -d / 2), (w / 2, -d / 2), (w / 2, d / 2), (-w / 2, d / 2))]


# ---------- the valley ----------
def river_centre(z):
    """The river runs north to south with a slow bend, passing east of the plaza."""
    return 560 + 210 * math.sin(z / 1250.0) + 90 * math.sin(z / 430.0 + 1.2)


def canal_lines():
    return [[(-HALF + 120, -820), (HALF - 700, -820)], [(-980, -HALF + 200), (-980, 1080)]]


def simplify(pts, eps=1.0):
    """Douglas-Peucker: drop the points the walk added along a straight run."""
    if len(pts) < 3:
        return pts
    ax, az = pts[0]
    bx, bz = pts[-1]
    dx, dz = bx - ax, bz - az
    L = math.hypot(dx, dz)
    worst, wi = 0.0, 0
    for i in range(1, len(pts) - 1):
        px, pz = pts[i]
        d = abs(dx * (az - pz) - dz * (ax - px)) / L if L else math.hypot(px - ax, pz - az)
        if d > worst:
            worst, wi = d, i
    if worst <= eps:
        return [pts[0], pts[-1]]
    return simplify(pts[:wi + 1], eps)[:-1] + simplify(pts[wi:], eps)


def dist_to_polyline(x, z, pts):
    best = 1e9
    for i in range(len(pts) - 1):
        ax, az = pts[i]
        bx, bz = pts[i + 1]
        dx, dz = bx - ax, bz - az
        L = dx * dx + dz * dz
        t = 0 if L == 0 else max(0, min(1, ((x - ax) * dx + (z - az) * dz) / L))
        best = min(best, math.hypot(x - ax - t * dx, z - az - t * dz))
    return best


def in_water(x, z):
    if abs(x - river_centre(z)) < RIVER_W / 2:
        return True
    for line in canal_lines():
        if dist_to_polyline(x, z, line) < CANAL_W / 2:
            return True
    return False


def terrain_height(x, z):
    """A river valley: the water at zero, a low west bank, and a bluff climbing away to the east."""
    d = x - river_centre(z)
    bank = min(22.0, 2.5 + abs(d) * 0.05)
    # the east bank climbs a terraced bluff; the west bank stays low and rolls gently
    if d > 0:
        rise = 78 * smoothstep(60, 1250, d) + 34 * smoothstep(1250, 1850, d)
        ripple = 7 * math.sin(z / 520.0) * smoothstep(200, 900, d)
    else:
        rise = 20 * smoothstep(80, 1500, -d)
        ripple = 9 * math.sin(x / 700.0 + 1.1) * math.cos(z / 830.0) * smoothstep(120, 800, -d)
    h = bank + rise + ripple
    # the plaza is cut level: the tower stands on flat ground, and the cut fades out over 400 m
    plaza = 1 - smoothstep(PLAZA, PLAZA + 400, max(abs(x), abs(z)))
    h = h * (1 - plaza) + PLAZA_LEVEL * plaza
    if in_water(x, z):
        return -1.5
    return max(0.6, h)


def smoothstep(a, b, v):
    t = max(0.0, min(1.0, (v - a) / (b - a)))
    return t * t * (3 - 2 * t)


def main():
    out = {"attribution": "Vashrin is an invented city: generated by tools/make-vashrin.py, no map data",
           "units": "decimetres east (x) and south (z) of origin", "origin": [50.0, 14.0],
           "bounds": [49.9829, 13.9735, 50.0171, 14.0265]}

    # ---------- terrain ----------
    step = 20
    nx = int(2 * HALF) // step + 2
    nz = nx
    hs = []
    for j in range(nz):
        for i in range(nx):
            hs.append(terrain_height(-HALF + i * step, -HALF + j * step))
    out["terrain"] = {"step": step, "nx": nx, "nz": nz, "x0": q(-HALF), "z0": q(-HALF), "datum": 118.0,
                      "h": [int(round(h * 10)) for h in hs]}

    # ---------- water ----------
    left, right = [], []
    for z in range(int(-HALF) - 200, int(HALF) + 201, 40):
        c = river_centre(z)
        left.append((c - RIVER_W / 2, z))
        right.append((c + RIVER_W / 2, z))
    out["lake"] = []
    out["islands"] = []
    out["water"] = [{"o": flat(left + right[::-1]), "i": [], "n": "Vash River"}]
    for k, line in enumerate(canal_lines()):
        (ax, az), (bx, bz) = line[0], line[-1]
        dx, dz = bx - ax, bz - az
        L = math.hypot(dx, dz)
        nxv, nzv = -dz / L * CANAL_W / 2, dx / L * CANAL_W / 2
        out["water"].append({"o": flat([(ax + nxv, az + nzv), (bx + nxv, bz + nzv), (bx - nxv, bz - nzv), (ax - nxv, az - nzv)]),
                             "i": [], "n": f"North Canal" if k == 0 else "West Canal"})
    out["marina"], out["beach"], out["pier"] = [], [], []
    out["waterways"] = [{"n": "Vash River", "p": flat([(river_centre(z), z) for z in range(int(-HALF), int(HALF) + 1, 60)])}]

    # ---------- streets ----------
    roads = []

    def road(pts, cls, w, name="", bridge=0):
        r = {"c": cls, "w": round(w, 1), "p": flat(simplify(pts))}
        if name:
            r["n"] = name
        if bridge:
            r["b"] = bridge
        roads.append(r)

    def emit_line(pts, cls, w, name="", bridged=False):
        """Walk a line, laying street over dry ground and a bridge deck over every water crossing."""
        dense = []
        for i in range(len(pts) - 1):
            ax, az = pts[i]
            bx, bz = pts[i + 1]
            L = math.hypot(bx - ax, bz - az)
            for k in range(max(1, int(L // 12))):
                u = k / max(1, int(L // 12))
                dense.append((ax + (bx - ax) * u, az + (bz - az) * u))
        dense.append(pts[-1])
        run, wet_run = [], []
        for x, z in dense:
            inside = math.hypot(x, z) < WALL_R * 1.16
            plaza_in = abs(x) < PLAZA and abs(z) < PLAZA
            if not inside or plaza_in:
                if len(run) > 1:
                    road(run, cls, w, name)
                run = []
                continue
            if in_water(x, z):
                wet_run.append((x, z))
                if len(run) > 1:
                    road(run, cls, w, name)
                run = []
            else:
                if wet_run:
                    if bridged and len(wet_run) > 1:
                        # the deck reaches one span either side of the water so its ramps land on the banks
                        a, b = wet_run[0], wet_run[-1]
                        dx, dz = b[0] - a[0], b[1] - a[1]
                        L = math.hypot(dx, dz) or 1
                        road([(a[0] - dx / L * 45, a[1] - dz / L * 45), (b[0] + dx / L * 45, b[1] + dz / L * 45)],
                             cls, w, name, bridge=1)
                    wet_run = []
                run.append((x, z))
        if len(run) > 1:
            road(run, cls, w, name)

    # street names: the avenues carry names, the rest are numbered, so the engine can find corners and post signals
    AVENUE_NAMES = ["Brelka", "Novost", "Tamnik", "Vrelo", "Zaluze", "Kamenna", "Dravin", "Selice", "Morvec", "Ulka",
                    "Zborna", "Petrik", "Rusna", "Halka", "Ostrec", "Velin"]

    ring_pts = [(WALL_R * 0.92 * math.cos(a), WALL_R * 0.92 * math.sin(a)) for a in
                [i / 144 * math.tau for i in range(145)]]
    emit_line(ring_pts, "primary", 22, "Ring Road", bridged=True)
    # the grid: every block pitch in both directions, the fifth one an avenue that bridges the water
    n = int(HALF // BLOCK)
    for i in range(-n, n + 1):
        v = i * BLOCK
        major = i % 5 == 0
        cls, w = ("secondary", AVENUE) if major else ("residential", STREET)
        k = i + n
        ns = AVENUE_NAMES[k % len(AVENUE_NAMES)] + " Avenue" if major else f"{k + 1} Street"
        ew = AVENUE_NAMES[(k + 7) % len(AVENUE_NAMES)] + " Row" if major else f"{k + 1} Row"
        emit_line([(v, -HALF), (v, HALF)], cls, w, ns, bridged=major)
        emit_line([(-HALF, v), (HALF, v)], cls, w, ew, bridged=major)
    # four avenues radiating from the plaza to the wall gates
    for k, a in enumerate(GATES):
        pts = [(math.cos(a) * r, math.sin(a) * r) for r in range(int(PLAZA), int(WALL_R * 1.02), 25)]
        emit_line(pts, "primary", 26, f"Gate Road {k + 1}", bridged=True)
    out["roads"] = roads

    # ---------- land ----------
    areas = [{"k": "plaza", "n": "Assembly Plaza", "o": flat(rect(0, 0, PLAZA * 2, PLAZA * 2)), "i": []}]
    for cx, cz, w, d, kind, name in [(-1180, 420, 520, 380, "industrial", "West Yards"),
                                     (1080, -980, 460, 320, "industrial", "River Works"),
                                     (-620, -1180, 300, 220, "park", "Old Park"),
                                     (760, 900, 340, 260, "park", "East Green"),
                                     (-1320, -520, 300, 240, "railyard", "Freight Yard"),
                                     (420, -1320, 260, 200, "parking", "Muster Ground")]:
        areas.append({"k": kind, "n": name, "o": flat(rect(cx, cz, w, d)), "i": []})
    out["areas"] = areas

    # ---------- rail ----------
    rail = [{"t": "L", "e": 1, "n": "Transit Line", "p": flat([(x, -240 + 60 * math.sin(x / 700)) for x in range(int(-HALF) + 100, int(HALF) - 99, 50)])},
            {"t": "rail", "e": 0, "n": "Freight Spur", "p": flat([(-1320 + i * 30, -520 + i * 2) for i in range(40)])},
            {"t": "tram", "e": 0, "n": "Tram", "p": flat([(-HALF + 200, 208), (HALF - 200, 208)])},
            {"t": "tram", "e": 0, "n": "Tram", "p": flat([(-208, -HALF + 200), (-208, HALF - 200)])}]
    out["rail"] = rail
    out["stations"] = [{"n": "Central Transit", "x": q(-60), "z": q(-250)}, {"n": "East Gate", "x": q(1040), "z": q(-320)}]

    # ---------- buildings ----------
    buildings = []
    GREY = ["#8d8b84", "#7c7a72", "#9a978c", "#6e6c66", "#a39e90", "#857f72", "#6a6f6b", "#94907f"]

    def put(ring, h, kind=None, colour=None, name=None, roof=None):
        b = {"p": flat(ring), "h": round(h, 1)}
        if kind:
            b["t"] = kind
        if colour:
            b["c"] = colour
        if name:
            b["n"] = name
        if roof:
            b["r"] = roof
        buildings.append(b)

    def block_free(cx, cz):
        if math.hypot(cx, cz) > WALL_R * 0.94 or (abs(cx) < PLAZA + 40 and abs(cz) < PLAZA + 40):
            return False
        if in_water(cx, cz):
            return False
        for a in areas[1:]:
            xs = [a["o"][i] / 10 for i in range(0, len(a["o"]), 2)]
            zs = [a["o"][i] / 10 for i in range(1, len(a["o"]), 2)]
            if min(xs) - 30 < cx < max(xs) + 30 and min(zs) - 30 < cz < max(zs) + 30:
                return False
        return True

    inner = BLOCK - AVENUE
    for i in range(-n, n + 1):
        for j in range(-n, n + 1):
            cx, cz = (i + 0.5) * BLOCK, (j + 0.5) * BLOCK
            if not block_free(cx, cz):
                continue
            d = math.hypot(cx, cz)
            core = max(0.0, 1 - d / (WALL_R * 0.9))
            base = 14 + core * 22 + R.random() * 8
            depth = 13 + R.random() * 3
            w = inner - 6
            # a courtyard block: a bar along each side, with gaps and stepped heights
            for side in range(4):
                if R.random() < 0.12:
                    continue
                h = base * (0.85 + R.random() * 0.4)
                if R.random() < 0.06:
                    h += 18 + R.random() * 26      # an occasional slab tower
                ang = side * math.pi / 2
                ox = math.cos(ang) * (w / 2 - depth / 2)
                oz = math.sin(ang) * (w / 2 - depth / 2)
                length = w * (0.72 + R.random() * 0.28)
                ring = rect(cx + ox, cz + oz, depth if side % 2 == 0 else length, length if side % 2 == 0 else depth)
                put(ring, h, "apartments", GREY[R.randrange(len(GREY))], roof="f")
            if R.random() < 0.25:   # something small in the courtyard
                put(rect(cx + R.uniform(-12, 12), cz + R.uniform(-12, 12), 14 + R.random() * 10, 12 + R.random() * 8),
                    5 + R.random() * 4, "shed", "#6f6b62", roof="f")
    # industrial sheds and yard buildings
    for a in areas[1:]:
        if a["k"] not in ("industrial", "railyard"):
            continue
        xs = [a["o"][i] / 10 for i in range(0, len(a["o"]), 2)]
        zs = [a["o"][i] / 10 for i in range(1, len(a["o"]), 2)]
        for _ in range(9):
            cx = R.uniform(min(xs) + 40, max(xs) - 40)
            cz = R.uniform(min(zs) + 30, max(zs) - 30)
            put(rect(cx, cz, R.uniform(50, 110), R.uniform(30, 60)), R.uniform(9, 16), "industrial", "#7a7368", roof="f")
    # the wall: segments with a guard tower every 240 m, and gaps at the four checkpoints
    gates = GATES
    seg = math.tau / 120
    for k in range(120):
        a0 = k * seg
        if any(abs(((a0 - g + math.pi) % math.tau) - math.pi) < 0.06 for g in gates):
            continue
        a1 = a0 + seg * 0.96
        p0 = (math.cos(a0) * WALL_R, math.sin(a0) * WALL_R)
        p1 = (math.cos(a1) * WALL_R, math.sin(a1) * WALL_R)
        dx, dz = p1[0] - p0[0], p1[1] - p0[1]
        L = math.hypot(dx, dz)
        nxv, nzv = -dz / L * 4.5, dx / L * 4.5
        wide = [(p0[0] + nxv, p0[1] + nzv), (p1[0] + nxv, p1[1] + nzv), (p1[0] - nxv, p1[1] - nzv), (p0[0] - nxv, p0[1] - nzv)]
        put(wide, 17, "wall", "#6d6a63", roof="f")
        if k % 8 == 0:
            put(rect(math.cos(a0) * WALL_R, math.sin(a0) * WALL_R, 18, 18, a0), 26, "tower", "#5f5d58", roof="f")
        elif k % 4 == 0:   # a buttress on the inside face
            put(rect(math.cos(a0) * (WALL_R - 6), math.sin(a0) * (WALL_R - 6), 9, 9, a0), 11, "wall", "#63605a", roof="f")
    out["buildings"] = buildings

    # ---------- trees: a few in the parks, none on the streets ----------
    trees = []
    for a in areas[1:]:
        if a["k"] != "park":
            continue
        xs = [a["o"][i] / 10 for i in range(0, len(a["o"]), 2)]
        zs = [a["o"][i] / 10 for i in range(1, len(a["o"]), 2)]
        for _ in range(90):
            trees += [q(R.uniform(min(xs) + 8, max(xs) - 8)), q(R.uniform(min(zs) + 8, max(zs) - 8))]
    out["trees"] = trees
    out["pois"] = []

    json.dump(out, open(OUT, "w"), separators=(",", ":"))
    print(f"wrote {OUT}: {os.path.getsize(OUT)/1e6:.1f} MB; buildings {len(buildings)}; roads {len(roads)}; "
          f"areas {len(areas)}; terrain {nx}x{nz} at {step} m; trees {len(trees)//2}")


if __name__ == "__main__":
    main()
