#!/usr/bin/env python3
"""Generate Mega-City One as a city data file the OSM engine can read.

    python3 tools/make-megacity.py

Fan work in the spirit of Judge Dredd's Mega-City One, which belongs to Rebellion. Nothing here is surveyed
and no assets from the comics, films or games are used: the layout is generated from a seed and every shape
is modelled from scratch in this project's own low-poly style.

What the place is, and what that means for the geometry:

  a city block is one building. It holds fifty thousand people, it is three hundred metres across and the
  better part of a kilometre tall, and it has a name. They stand well apart, so the city reads as a field
  of enormous separate objects rather than a grid of streets.
  megways weave between them on pillars at four or five levels, curving, never touching the ground.
  the ground itself is a long way down and mostly in shadow.
  the Black Atlantic is east; the city wall is west, and past it the Cursed Earth, where nothing is built.
"""
import json
import math
import os
import random
from lib.geo import q, flat, rect, smoothstep, simplify

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "cities", "megacity-osm.json")
R = random.Random(2099)

HALF = 3200.0
PITCH = 470.0            # city blocks stand this far apart
WALL_X = -2560.0         # the city wall; the Cursed Earth is west of it
SEA_X = 2280.0           # the Black Atlantic
JUSTICE = (120.0, -160.0)

# Blocks are named after people nobody now remembers. These are invented.
NAMES = ["Ashgrove", "Bellamy", "Carrow", "Denning", "Ellery", "Fenwick", "Garrick", "Halloran", "Ivers",
         "Jessop", "Kesterling", "Lomax", "Merrit", "Nystrom", "Okonjo", "Prentice", "Quillan", "Rushmore",
         "Selwyn", "Tarrant", "Underhill", "Vance", "Wexford", "Yarrow", "Zeller", "Abernathy", "Blackwood",
         "Coltrane", "Drummond", "Easterbrook", "Faraday", "Gallagher", "Hargreaves", "Inglewood", "Jarrow",
         "Kilbride", "Langtry", "Mortlake", "Northcote", "Ormsby", "Pemberton", "Radcliffe", "Sandoval",
         "Thorncroft", "Ulverston", "Vayne", "Wisteria", "Xanthe", "Yardley", "Zamora"]


def ngon(cx, cz, r, n=8, rot=0.0, squash=1.0):
    return [(cx + math.cos(rot + i / n * math.tau) * r,
             cz + math.sin(rot + i / n * math.tau) * r * squash) for i in range(n)]


def in_water(x, z):
    return x > SEA_X + 90 * math.sin(z / 700.0)


def in_cursed(x, z):
    return x < WALL_X


def terrain_height(x, z):
    if in_water(x, z):
        return max(-8.0, -1.0 - (x - SEA_X) * 0.03)
    if in_cursed(x, z):
        # the Cursed Earth: broken ground that the city turned its back on
        h = 6 + 14 * math.sin(x / 260.0) * math.cos(z / 310.0) + 9 * math.sin(z / 140.0)
        return max(1.0, h) * smoothstep(HALF, HALF - 300, max(abs(x), abs(z)))
    h = 8 + 5 * math.sin(x / 900.0 + 0.4) * math.cos(z / 1100.0)
    return max(1.0, h) * smoothstep(HALF, HALF - 300, max(abs(x), abs(z)))


def main():
    out = {"attribution": "Mega-City One: fan geometry generated by tools/make-megacity.py; no assets used",
           "units": "decimetres east (x) and south (z) of origin", "origin": [40.0, -74.5],
           "bounds": [39.9712, -74.5375, 40.0288, -74.4625]}

    step = 25
    nx = int(2 * HALF) // step + 2
    hs = []
    for j in range(nx):
        for i in range(nx):
            hs.append(terrain_height(-HALF + i * step, -HALF + j * step))
    out["terrain"] = {"step": step, "nx": nx, "nz": nx, "x0": q(-HALF), "z0": q(-HALF), "datum": 0.0,
                      "h": [int(round(h * 10)) for h in hs]}

    # ---------- the Black Atlantic ----------
    edge = [(SEA_X + 90 * math.sin(z / 700.0), z) for z in range(int(-HALF) - 300, int(HALF) + 301, 50)]
    out["lake"] = []
    out["islands"] = []
    out["water"] = [{"o": flat(edge + [(HALF + 2600, HALF + 300), (HALF + 2600, -HALF - 300)]), "i": [],
                     "n": "The Black Atlantic"}]
    out["marina"], out["beach"], out["pier"] = [], [], []
    out["waterways"] = []

    roads = []

    def road(pts, cls, w, name="", bridge=0):
        pts = simplify(pts)
        if len(pts) < 2:
            return
        r = {"c": cls, "w": round(w, 1), "p": flat(pts)}
        if name:
            r["n"] = name
        if bridge:
            r["b"] = bridge
        roads.append(r)

    def walk(pts, cls, w, name="", bridge=0):
        dense = []
        for i in range(len(pts) - 1):
            ax, az = pts[i]
            bx, bz = pts[i + 1]
            L = math.hypot(bx - ax, bz - az)
            n = max(1, int(L // 14))
            for k in range(n):
                u = k / n
                dense.append((ax + (bx - ax) * u, az + (bz - az) * u))
        dense.append(pts[-1])
        run = []
        for x, z in dense:
            if in_water(x, z) or in_cursed(x, z) or max(abs(x), abs(z)) > HALF - 60:
                if len(run) > 1:
                    road(run, cls, w, name, bridge)
                run = []
                continue
            run.append((x, z))
        if len(run) > 1:
            road(run, cls, w, name, bridge)

    # ---------- the ground: a sparse grid a long way below everything ----------
    n = int(HALF // PITCH)
    for i in range(-n, n + 1):
        v = i * PITCH
        walk([(v, -HALF), (v, HALF)], "secondary", 26, f"Sector {i + n + 1} Street")
        walk([(-HALF, v), (HALF, v)], "secondary", 26, f"Sector {i + n + 1} Row")
        walk([(v + PITCH / 2, -HALF), (v + PITCH / 2, HALF)], "residential", 15)
        walk([(-HALF, v + PITCH / 2), (HALF, v + PITCH / 2)], "residential", 15)

    # ---------- the megways: they curve between the blocks and never come down ----------
    MEGWAYS = []
    for k in range(9):
        a0 = R.uniform(0, math.tau)
        amp = 420 + R.random() * 620
        wob = 0.7 + R.random() * 1.7
        horiz = k % 2 == 0
        off = (k - 4) * 620 + R.uniform(-90, 90)
        pts = []
        for t in range(-int(HALF), int(HALF) + 1, 40):
            s = amp * math.sin(t / 900.0 * wob + a0)
            pts.append((t, off + s) if horiz else (off + s, t))
        pts = [p for p in pts if not in_water(*p) and not in_cursed(*p) and max(abs(p[0]), abs(p[1])) < HALF - 80]
        if len(pts) > 3:
            nm = f"Megway {k + 1}"
            road(pts, "trunk", 30, nm, bridge=1)
            MEGWAYS.append(nm)
    out["roads"] = roads

    areas = [{"k": "plaza", "n": "Hall of Justice Plaza", "o": flat(rect(JUSTICE[0], JUSTICE[1], 520, 420)), "i": []},
             {"k": "industrial", "n": "Port of Mega-City One", "o": flat(rect(1850, 900, 700, 900)), "i": []},
             {"k": "park", "n": "Sector 7 Green", "o": flat(rect(-900, 1400, 360, 300)), "i": []}]
    out["areas"] = areas

    def area_bbox(a):
        xs = [a["o"][i] / 10 for i in range(0, len(a["o"]), 2)]
        zs = [a["o"][i] / 10 for i in range(1, len(a["o"]), 2)]
        return min(xs), max(xs), min(zs), max(zs)

    out["rail"] = [{"t": "L", "e": 1, "n": "Zoom Line",
                    "p": flat([(x, 1180 + 140 * math.sin(x / 1100.0)) for x in range(int(-2400), int(2200), 60)])}]
    out["stations"] = [{"n": "Justice Central", "x": q(JUSTICE[0] - 320), "z": q(JUSTICE[1] + 240)}]

    # ---------- the blocks ----------
    buildings = []
    HULL = ["#6f6a63", "#5f5b55", "#7b756c", "#565249", "#6a6459", "#7f786c"]
    ACCENT = ["#6a5044", "#4d5a66", "#5d5563", "#66604a"]   # balcony decks, weathered rather than painted

    def put(ring, h, kind=None, colour=None, name=None, minh=None):
        b = {"p": flat(ring), "h": round(h, 1), "r": "f"}
        if kind:
            b["t"] = kind
        if colour:
            b["c"] = colour
        if name:
            b["n"] = name
        if minh:
            b["m"] = round(minh, 1)
        buildings.append(b)

    def city_block(cx, cz, name):
        """One building, fifty thousand people: a body, its setbacks, balcony bands and whatever is on the roof."""
        w = 190 + R.random() * 150
        d = w * (0.55 + R.random() * 0.5)
        H = 380 + R.random() * 520
        rot = R.uniform(0, math.pi)
        col = HULL[R.randrange(len(HULL))]
        shape = R.random()
        if shape < 0.3:
            body = ngon(cx, cz, w / 2, 8, rot, d / w)      # the rounded ones
        elif shape < 0.45:
            body = ngon(cx, cz, w / 2, 6, rot, d / w)
        else:
            body = rect(cx, cz, w, d, rot)
        put(body, H, "megablock", col, name=name + " Block")
        # setbacks: the block steps in two or three times on its way up
        steps = R.randint(1, 3)
        for k in range(steps):
            f = 1 - (k + 1) * (0.14 + R.random() * 0.1)
            hh = H * (1 + (k + 1) * (0.10 + R.random() * 0.09))
            sb = (ngon(cx, cz, w / 2 * f, 8, rot, d / w) if shape < 0.45 else rect(cx, cz, w * f, d * f, rot))
            put(sb, hh, "megablock", col, minh=H * (1 + k * 0.10))
        top = H * (1 + steps * 0.11)
        # the balcony bands, which is what you actually see of a block from a distance
        bands = int(H / (52 + R.random() * 34))
        for k in range(1, bands):
            y = H * k / bands
            bw = 1.055
            ring = (ngon(cx, cz, w / 2 * bw, 8, rot, d / w) if shape < 0.45 else rect(cx, cz, w * bw, d * bw, rot))
            put(ring, y + 5.5, "balcony", ACCENT[(k + len(name)) % len(ACCENT)], minh=y)
        # the roof: plant, masts, and a landing deck
        for k in range(R.randint(2, 5)):
            ox, oz = (R.random() - 0.5) * w * 0.5, (R.random() - 0.5) * d * 0.5
            put(rect(cx + ox, cz + oz, 16 + R.random() * 26, 14 + R.random() * 22, rot),
                top + 14 + R.random() * 46, "plant", "#4a4740", minh=top)
        put(rect(cx, cz, 10, 10, rot), top + 60 + R.random() * 70, "mast", "#3f3d3a", minh=top)

    placed = []
    idx = 0
    for i in range(-n - 1, n + 2):
        for j in range(-n - 1, n + 2):
            cx = (i + 0.5) * PITCH + R.uniform(-60, 60)
            cz = (j + 0.5) * PITCH + R.uniform(-60, 60)
            if in_water(cx, cz) or in_cursed(cx + 220, cz) or max(abs(cx), abs(cz)) > HALF - 260:
                continue
            skip = False
            for a in areas:
                x0, x1, z0, z1 = area_bbox(a)
                if x0 - 150 < cx < x1 + 150 and z0 - 150 < cz < z1 + 150:
                    skip = True
            if skip:
                continue
            city_block(cx, cz, NAMES[idx % len(NAMES)] + ("" if idx < len(NAMES) else f" {idx//len(NAMES)+1}"))
            placed.append((cx, cz))
            idx += 1

    # sky bridges between blocks that ended up close together
    for a in range(len(placed)):
        for b in range(a + 1, len(placed)):
            ax, az = placed[a]
            bx, bz = placed[b]
            dd = math.hypot(bx - ax, bz - az)
            if dd > PITCH * 1.15 or R.random() < 0.55:
                continue
            ux, uz = (bx - ax) / dd, (bz - az) / dd
            for k in range(R.randint(1, 2)):
                y = 150 + R.random() * 280
                px, pz = (ax + bx) / 2, (az + bz) / 2
                ang = math.atan2(uz, ux)
                put(rect(px, pz, dd, 9 + R.random() * 7, ang), y + 7, "skybridge", "#5a5f66", minh=y)

    # the city wall, and the port sheds
    for z in range(int(-HALF), int(HALF), 50):
        put([(WALL_X, z), (WALL_X + 26, z), (WALL_X + 26, z + 50), (WALL_X, z + 50)], 120, "wall", "#55514a")
        if (z // 50) % 6 == 0:
            put(rect(WALL_X + 13, z + 25, 46, 46), 165, "tower", "#4b4741")
    for a in areas:
        if a["k"] != "industrial":
            continue
        x0, x1, z0, z1 = area_bbox(a)
        for _ in range(18):
            ax = R.uniform(x0 + 50, x1 - 50)
            az = R.uniform(z0 + 40, z1 - 40)
            if in_water(ax, az):
                continue
            put(rect(ax, az, R.uniform(60, 140), R.uniform(40, 90)), R.uniform(16, 40), "industrial", "#5f584e")
    out["buildings"] = buildings

    trees = []
    for a in areas:
        if a["k"] != "park":
            continue
        x0, x1, z0, z1 = area_bbox(a)
        for _ in range(140):
            trees += [q(R.uniform(x0 + 8, x1 - 8)), q(R.uniform(z0 + 8, z1 - 8))]
    out["trees"] = trees
    out["pois"] = []

    json.dump(out, open(OUT, "w"), separators=(",", ":"))
    t = out["terrain"]
    print(f"wrote {OUT}: {os.path.getsize(OUT)/1e6:.1f} MB; buildings {len(buildings)}; city blocks {len(placed)}; "
          f"roads {len(roads)}; megways {len(MEGWAYS)}; terrain {t['nx']}x{t['nz']} at {t['step']} m")


if __name__ == "__main__":
    main()
