#!/usr/bin/env python3
"""Generate Mega-City One as the 2012 film has it.

    python3 tools/make-dredd2012.py

Fan work. Judge Dredd belongs to Rebellion and the film to its rights holders; nothing from either is used,
and every shape is modelled from scratch here.

This is a different city from the comics one in tools/make-megacity.py, and deliberately so. The film shot
its city in Johannesburg and Cape Town and kept them: a flat, dusty, low-rise sprawl that goes on past the
horizon, ordinary streets, ordinary traffic, and standing out of it at intervals a small number of enormous
plain concrete slabs - the Mega-Blocks - each holding seventy-five thousand people behind one wall.

  the sprawl is the city: two to six storeys, packed tight, accreted rather than planned
  the blocks are monoliths: no curves, no ornament, two hundred storeys of poured concrete on a bare apron
  Peach Trees is one of them, and from the outside there is nothing to say which
  the wall runs the eastern edge, and past it the Cursed Earth is just desert
"""
import json
import math
import os
import random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "data", "cities", "dredd2012-osm.json")
R = random.Random(2012)

HALF = 4200.0
PITCH = 78.0              # the sprawl's street grid
STREET = 13.0
AVENUE = 26.0
WALL_X = 3560.0           # the city wall; the Cursed Earth is east of it
BLOCK_PITCH = 1250.0      # how far apart the Mega-Blocks stand
PEACH = (-620.0, 340.0)   # Peach Trees

BLOCK_NAMES = ["Peach Trees", "Hollow Ridge", "Sunset Fields", "Cedar Heights", "Blackwater", "Rosebank",
               "Silverton", "Kestrel Point", "Marlow", "Verwey", "Ashcroft", "Dunsmore", "Riverlea",
               "Ferndale", "Northcliff", "Brixton Gate", "Kew Park", "Orchards", "Saxonwold", "Troyeville",
               "Yeoville", "Bezuiden", "Crown Mines", "Turffontein"]


def q(v):
    return int(round(v * 10))


def flat(pts):
    out = []
    for x, z in pts:
        out += [q(x), q(z)]
    return out


def rect(cx, cz, w, d, rot=0.0):
    c, s = math.cos(rot), math.sin(rot)
    return [(cx + x * c - z * s, cz + x * s + z * c) for x, z in
            ((-w / 2, -d / 2), (w / 2, -d / 2), (w / 2, d / 2), (-w / 2, d / 2))]


def smoothstep(a, b, v):
    t = max(0.0, min(1.0, (v - a) / (b - a)))
    return t * t * (3 - 2 * t)


def simplify(pts, eps=1.0):
    if len(pts) < 3:
        return pts
    ax, az = pts[0]
    bx, bz = pts[-1]
    dx, dz = bx - ax, bz - az
    L = math.hypot(dx, dz)
    worst, wi = 0.0, 0
    for i in range(1, len(pts) - 1):
        px, pz = pts[i]
        d = abs(dx * (az - pz) - dz * (ax - px)) / L if L else math.hypot(px - ax, pz - az)
        if d > worst:
            worst, wi = d, i
    if worst <= eps:
        return [pts[0], pts[-1]]
    return simplify(pts[:wi + 1], eps)[:-1] + simplify(pts[wi:], eps)


def in_cursed(x, z):
    return x > WALL_X


def terrain_height(x, z):
    """A dusty plateau with a long shallow rise through it; the desert beyond the wall is flatter and paler."""
    h = 26 + 16 * math.sin(x / 1700.0 + 0.5) * math.cos(z / 2100.0) + 7 * math.sin(z / 760.0)
    if in_cursed(x, z):
        h = 20 + 9 * math.sin(x / 520.0) * math.cos(z / 610.0) + 5 * math.sin(z / 260.0)
    h *= smoothstep(HALF, HALF - 340, max(abs(x), abs(z)))
    return max(1.0, h)


# the Mega-Blocks: where they stand, worked out once so the sprawl can be cleared around them
def block_sites():
    sites = []
    n = int(HALF // BLOCK_PITCH)
    for i in range(-n, n + 1):
        for j in range(-n, n + 1):
            cx = i * BLOCK_PITCH + R.uniform(-240, 240)
            cz = j * BLOCK_PITCH + R.uniform(-240, 240)
            if in_cursed(cx + 300, cz) or max(abs(cx), abs(cz)) > HALF - 700:
                continue
            if R.random() < 0.18:
                continue
            sites.append([cx, cz])
    # Peach Trees is one of them, and it sits where the story needs it
    if sites:
        best = min(range(len(sites)), key=lambda k: math.hypot(sites[k][0] - PEACH[0], sites[k][1] - PEACH[1]))
        sites[best] = [PEACH[0], PEACH[1]]
        sites.insert(0, sites.pop(best))
    return sites


def main():
    out = {"attribution": "Mega-City One (2012): fan geometry generated by tools/make-dredd2012.py; no assets used",
           "units": "decimetres east (x) and south (z) of origin", "origin": [-26.2041, 28.0473],
           "bounds": [-26.2419, 28.0055, -26.1663, 28.0891]}

    step = 20
    nx = int(2 * HALF) // step + 2
    hs = []
    for j in range(nx):
        for i in range(nx):
            hs.append(terrain_height(-HALF + i * step, -HALF + j * step))
    out["terrain"] = {"step": step, "nx": nx, "nz": nx, "x0": q(-HALF), "z0": q(-HALF), "datum": 1580.0,
                      "h": [int(round(h * 10)) for h in hs]}

    out["lake"] = []
    out["islands"] = []
    out["water"] = []
    out["marina"], out["beach"], out["pier"] = [], [], []
    out["waterways"] = []

    SITES = block_sites()
    APRON = 330.0          # the bare ground each block stands on

    def on_apron(x, z):
        for cx, cz in SITES:
            if abs(x - cx) < APRON and abs(z - cz) < APRON:
                return True
        return False

    # ---------- streets ----------
    roads = []

    def road(pts, cls, w, name=""):
        pts = simplify(pts)
        if len(pts) < 2:
            return
        r = {"c": cls, "w": round(w, 1), "p": flat(pts)}
        if name:
            r["n"] = name
        roads.append(r)

    def walk(pts, cls, w, name=""):
        dense = []
        for i in range(len(pts) - 1):
            ax, az = pts[i]
            bx, bz = pts[i + 1]
            L = math.hypot(bx - ax, bz - az)
            n = max(1, int(L // 12))
            for k in range(n):
                u = k / n
                dense.append((ax + (bx - ax) * u, az + (bz - az) * u))
        dense.append(pts[-1])
        run = []
        for x, z in dense:
            if in_cursed(x, z) or max(abs(x), abs(z)) > HALF - 60:
                if len(run) > 1:
                    road(run, cls, w, name)
                run = []
                continue
            run.append((x, z))
        if len(run) > 1:
            road(run, cls, w, name)

    NAMES = ["Marlow", "Verwey", "Anderson", "Hershey", "Kaplan", "Lorenzo", "Duval", "Chan", "Mbeki",
             "Delacroix", "Pretorius", "Sector 13", "Ndlovu", "Volt", "Cassidy", "Roth"]
    n = int(HALF // PITCH)
    for i in range(-n, n + 1):
        v = i * PITCH
        major = i % 6 == 0
        cls, w = ("secondary", AVENUE) if major else ("residential", STREET)
        k = i + n
        walk([(v, -HALF), (v, HALF)], cls, w, (NAMES[k % len(NAMES)] + " Street") if major else f"{k+1} Street")
        walk([(-HALF, v), (HALF, v)], cls, w, (NAMES[(k + 5) % len(NAMES)] + " Avenue") if major else f"{k+1} Row")
    # the through-routes: at ground level in this city, not weaving between towers
    for k, off in enumerate([-2600, -700, 900, 2500]):
        walk([(-HALF, off + 200 * math.sin(-HALF / 2200)), (HALF, off + 200 * math.sin(HALF / 2200))],
             "trunk", 42, f"Route {k + 1}")
    for k, off in enumerate([-2100, 300, 2200]):
        walk([(off, -HALF), (off, HALF)], "trunk", 38, f"Interstate {k + 1}")
    out["roads"] = roads

    areas = [{"k": "industrial", "n": "The Yards", "o": flat(rect(2500, -2600, 900, 700)), "i": []},
             {"k": "parking", "n": "Sector House 13", "o": flat(rect(-1900, -1500, 320, 260)), "i": []},
             {"k": "residential", "n": "The Sprawl", "o": flat(rect(0, 0, 7400, 7400)), "i": []}]
    out["areas"] = areas
    out["rail"] = []
    out["stations"] = []

    # ---------- what is built ----------
    buildings = []
    # sun-bleached render, dust-stained concrete, rusted iron, painted brick gone chalky
    SPRAWL = ["#b0a28a", "#9c8f7b", "#c2b396", "#8d8170", "#a8987e", "#bda98b", "#94897a", "#ab9c86",
              "#a2907a", "#b6a893", "#8f8474", "#c8b89a"]
    ROOFS = ["#7a6d5c", "#6d6252", "#857763", "#5f564a"]
    MEGA = ["#8a8378", "#7f786d", "#948c80", "#736d64"]

    def put(ring, h, kind=None, colour=None, name=None, roof="f", minh=None):
        b = {"p": flat(ring), "h": round(h, 1), "r": roof}
        if kind:
            b["t"] = kind
        if colour:
            b["c"] = colour
        if name:
            b["n"] = name
        if minh:
            b["m"] = round(minh, 1)
        buildings.append(b)

    def line_w(i):
        return AVENUE if i % 6 == 0 else STREET

    def span(i):
        lo = i * PITCH + line_w(i) / 2 + 1.2
        hi = (i + 1) * PITCH - line_w(i + 1) / 2 - 1.2
        return (lo + hi) / 2, hi - lo

    # the sprawl: small footprints, packed, built up in pieces and never cleared
    for i in range(-n, n + 1):
        for j in range(-n, n + 1):
            bx, wx = span(i)
            bz, wz = span(j)
            if in_cursed(bx, bz) or max(abs(bx), abs(bz)) > HALF - 120:
                continue
            if on_apron(bx, bz):
                continue
            dense = R.random()
            cells = 3 if dense < 0.4 else (4 if dense < 0.8 else 5)
            cw, cd = wx / cells, wz / cells
            for a in range(cells):
                for b in range(cells):
                    if R.random() < 0.16:
                        continue
                    px = bx - wx / 2 + cw * (a + 0.5)
                    pz = bz - wz / 2 + cd * (b + 0.5)
                    w = cw * R.uniform(0.66, 0.96)
                    d = cd * R.uniform(0.66, 0.96)
                    h = R.uniform(6, 17)
                    if R.random() < 0.06:
                        h = R.uniform(24, 52)          # the odd taller block in the sprawl
                    put(rect(px, pz, w, d, R.uniform(-0.05, 0.05)), h, "apartments",
                        SPRAWL[R.randrange(len(SPRAWL))])
                    if R.random() < 0.3:               # water tanks, stairs, shacks on the roof
                        put(rect(px + R.uniform(-w * 0.2, w * 0.2), pz + R.uniform(-d * 0.2, d * 0.2),
                                 w * R.uniform(0.22, 0.4), d * R.uniform(0.22, 0.4)),
                            h + R.uniform(2, 5), "plant", ROOFS[R.randrange(len(ROOFS))], minh=h)

    # ---------- the Mega-Blocks ----------
    pois = []
    for idx, (cx, cz) in enumerate(SITES):
        name = BLOCK_NAMES[idx % len(BLOCK_NAMES)] + ("" if idx < len(BLOCK_NAMES) else " %d" % (idx // len(BLOCK_NAMES) + 1))
        is_peach = (idx == 0)
        w = 210 + R.random() * 90
        d = w * R.uniform(0.62, 0.92)
        H = 640 + R.random() * 220
        if is_peach:
            w, d, H = 246, 196, 728
        rot = R.uniform(-0.12, 0.12)
        col = MEGA[R.randrange(len(MEGA))]
        # the slab itself, in three stages, each a little narrower than the last
        put(rect(cx, cz, w, d, rot), H * 0.62, "megablock", col, name=name + " Block")
        put(rect(cx, cz, w * 0.9, d * 0.9, rot), H * 0.86, "megablock", col, minh=H * 0.62)
        put(rect(cx, cz, w * 0.78, d * 0.78, rot), H, "megablock", col, minh=H * 0.86)
        # the service cores standing proud of the two long faces
        for sd in (-1, 1):
            put(rect(cx + math.cos(rot) * 0 - math.sin(rot) * sd * d * 0.5,
                     cz + math.sin(rot) * 0 + math.cos(rot) * sd * d * 0.5, w * 0.16, 14, rot),
                H * 1.02, "core", "#6f6a61")
        # the balcony banding: finer than the comics city, and it is the only relief on the whole wall
        bands = int(H / 46)
        for k in range(1, bands):
            y = H * 0.98 * k / bands
            f = 1.03 if y < H * 0.62 else (0.93 if y < H * 0.86 else 0.81)
            put(rect(cx, cz, w * f, d * f, rot), y + 3.0, "balcony", "#6a6459", minh=y)
        # roof plant and the mast
        for k in range(R.randint(3, 6)):
            put(rect(cx + R.uniform(-w * 0.28, w * 0.28), cz + R.uniform(-d * 0.28, d * 0.28),
                     R.uniform(14, 30), R.uniform(12, 26), rot), H + R.uniform(8, 26), "plant", "#5f594f", minh=H)
        put(rect(cx, cz, 7, 7, rot), H + R.uniform(40, 70), "mast", "#4a453e", minh=H)
        # the apron: a bare concrete forecourt, a low perimeter wall and the ramp in
        for k in range(20):
            a = k / 20 * math.tau
            put(rect(cx + math.cos(a) * APRON * 0.82, cz + math.sin(a) * APRON * 0.82, 34, 5, rot + a),
                3.2, "wall", "#7b7468")
        put(rect(cx, cz + d * 0.72, w * 0.34, 34, rot), 9, "entry", "#666056")
        pois.append({"n": name, "x": q(cx), "z": q(cz), "k": "megablock", "ang": round(rot, 3)})

    # the city wall along the east, and the Yards
    for z in range(int(-HALF), int(HALF), 44):
        put([(WALL_X, z), (WALL_X + 18, z), (WALL_X + 18, z + 44), (WALL_X, z + 44)], 64, "wall", "#7d7669")
        if (z // 44) % 8 == 0:
            put(rect(WALL_X + 9, z + 22, 34, 34), 92, "tower", "#6e675b")
    for a in areas:
        if a["k"] != "industrial":
            continue
        xs = [a["o"][i] / 10 for i in range(0, len(a["o"]), 2)]
        zs = [a["o"][i] / 10 for i in range(1, len(a["o"]), 2)]
        for _ in range(16):
            ax = R.uniform(min(xs) + 40, max(xs) - 40)
            az = R.uniform(min(zs) + 30, max(zs) - 30)
            put(rect(ax, az, R.uniform(50, 120), R.uniform(30, 70)), R.uniform(9, 22), "industrial", "#8a7f6d")
    out["buildings"] = buildings
    out["trees"] = []
    out["pois"] = pois

    json.dump(out, open(OUT, "w"), separators=(",", ":"))
    t = out["terrain"]
    print(f"wrote {OUT}: {os.path.getsize(OUT)/1e6:.1f} MB; {2*HALF/1000:.1f} km across; "
          f"buildings {len(buildings)}; mega-blocks {len(SITES)}; roads {len(roads)}; "
          f"terrain {t['nx']}x{t['nz']} at {t['step']} m")


if __name__ == "__main__":
    main()
