// Kowloon Walled City: entry point for kowloon.html. A massing model of what stood on the site until 1994,
// generated by tools/make-kowloon.py from published descriptions; no survey, drawing or photograph is used.
// It runs on the shared engine in src/engine/, at a tenth of the scale every other city here is built at.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {build} from '../engine/build.js';
import {section} from './section.js';
import {kaitak} from './kaitak.js';
import {life} from './life.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({
  // What you read while it builds. See src/core/diag.js: these are shuffled and one of them is
  // shown at a time under the progress line.
  lines:[
    'Thirty-three thousand people in six and a half acres. It was the densest place on earth.',
    'Nobody planned it. Every floor was added by whoever needed a floor.',
    'There was no daylight below the third storey, and the alleys ran with water from the pipes above.',
    'It stopped at fourteen storeys because anything taller was in the way of the aircraft.',
    'The aircraft came over the rooftops at a hundred and forty feet and turned at a checkerboard painted on a hill.',
    'There were no building regulations here, and also no building collapses.',
    'It was pulled down in 1993. The park that replaced it keeps two of the old yamen buildings.',
    'The washing is strung across a gap that was measured: there has to be a real wall on each side of it.',
    'Every cage, pipe and sign on this model is attached to a wall the engine can actually find.',
  ],
  prefix:'raising the Walled City… ',labels:{'map-data':'reading the block plan',ground:'laying the lanes',buildings:'stacking the block',details:'wiring the roofs',landmarks:'finding the Yamen',el:'',traffic:'opening the streets',ui:'opening the windows'}});
// The section is this page's alone - no other place here is worth cutting open - and so is the aeroplane.
const ctx=window._iz={defaultCity:'kowloon',extras:[{name:'life',fn:life},{name:'kaitak',fn:kaitak},{name:'section',fn:section}]};
requestAnimationFrame(()=>setTimeout(()=>{build(ctx).catch(e=>{report('build',e);const l=document.getElementById('loading');if(l)l.remove();});},30));
