// Mega-City One (2012): entry point for dredd2012.html. Fan work — the city as the film has it, which is a
// different place from the comics one at /megacity. Judge Dredd belongs to Rebellion and the film to its rights
// holders; nothing from either is used. Generated by tools/make-dredd2012.py, on the Chicago engine.
import {report,LOAD,configureLoading,installErrorHandlers} from '../core/diag.js';
import {build} from '../chicago/build.js';
installErrorHandlers();window.LOAD=LOAD;
configureLoading({prefix:'raising the sprawl… ',labels:{'map-data':'reading the sector plan',ground:'laying the streets',buildings:'raising the sprawl',details:'fitting out the roofs',landmarks:'placing the blocks',traffic:'starting the traffic',ui:'opening the windows'}});
const ctx=window._iz={defaultCity:'dredd2012'};
requestAnimationFrame(()=>setTimeout(()=>{build(ctx).catch(e=>{report('build',e);const l=document.getElementById('loading');if(l)l.remove();});},30));
