// Lightweight project probe; verify.py remains the unmodified Ancients harness.
// Showcase budget sized for the full 39-building sheet (with sun shadows each call is drawn twice).
const BUDGET={showcase:{tris:3000000,calls:1600},cls:{small:60000,medium:250000,mega:700000},type:{jj_helper_gallery:'mega',jj_palace:'mega',jj_temple_sun:'mega',jj_fortress:'mega',jj_caravanserai:'mega',jj_amphitheater:'mega'}};
function jjProbePoints(){const jjPts=[],jjM=new THREE.Matrix4(),jjPos=new THREE.Vector3(),jjQ=new THREE.Quaternion(),jjSc=new THREE.Vector3(),jjBB=new THREE.Box3();scene.traverse(jjO=>{if(jjO.userData&&jjO.userData.probeSkip)return;if(jjO.isInstancedMesh){for(let jjI=0;jjI<jjO.count;jjI++){jjO.getMatrixAt(jjI,jjM);jjM.decompose(jjPos,jjQ,jjSc);jjPts.push([jjPos.x,jjPos.y,jjPos.z]);}return;}if(!jjO.isMesh)return;jjBB.setFromObject(jjO);if(!isFinite(jjBB.min.x)||!isFinite(jjBB.max.x))return;jjPts.push([(jjBB.min.x+jjBB.max.x)/2,(jjBB.min.y+jjBB.max.y)/2,(jjBB.min.z+jjBB.max.z)/2]);for(const jjX of [jjBB.min.x,jjBB.max.x])for(const jjY of [jjBB.min.y,jjBB.max.y])for(const jjZ of [jjBB.min.z,jjBB.max.z])jjPts.push([jjX,jjY,jjZ]);});return jjPts;}
function regOccupancy(){const jjBy={},jjBucket=100;REG.forEach((jjR,jjI)=>{const jjA=Math.floor((jjR.z-jjR.r)/jjBucket),jjB=Math.floor((jjR.z+jjR.r)/jjBucket);for(let jjK=jjA;jjK<=jjB;jjK++)(jjBy[jjK]||(jjBy[jjK]=[])).push(jjI);});const jjN=new Array(REG.length).fill(0);for(const jjP of jjProbePoints()){const jjCandidates=jjBy[Math.floor(jjP[2]/jjBucket)];if(!jjCandidates)continue;for(const jjI of jjCandidates){const jjR=REG[jjI],jjDX=jjP[0]-jjR.x,jjDZ=jjP[2]-jjR.z;if(jjDX*jjDX+jjDZ*jjDZ<=jjR.r*jjR.r&&jjP[1]>=jjR.y-2&&jjP[1]<=jjR.y+jjR.h+5)jjN[jjI]++;}}return REG.map((jjR,jjI)=>({name:jjR.name,type:jjR.type,n:jjN[jjI]}));}
function nanSweep(){const jjBad=[];scene.traverse(jjO=>{if(!jjO.isMesh||(jjO.userData&&jjO.userData.probeSkip))return;const jjP=jjO.geometry&&jjO.geometry.attributes&&jjO.geometry.attributes.position;if(!jjP)return;for(let jjI=0;jjI<jjP.array.length;jjI++)if(!isFinite(jjP.array[jjI])){jjBad.push({geo:jjO.geometry.type,at:jjI,n:jjP.array.length});break;}});return{meshes:jjBad.length,first:jjBad.slice(0,8),instances:TSTAT.bad.length,firstInstances:TSTAT.bad.slice(0,8)};}
function typeStats(){const jjOut={};for(const jjK in TSTAT.by){const jjT=TSTAT.by[jjK],jjBase=jjK.split('/')[0],jjClass=BUDGET.type[jjBase]||'medium';jjOut[jjK]={tris:jjT.tris,inst:jjT.inst,meshes:jjT.meshes,cls:jjClass,limit:BUDGET.cls[jjClass],over:jjT.tris>BUDGET.cls[jjClass]};}return jjOut;}
function tagAudit(){const jjBad=REG.filter(jjR=>!jjR.cls||!jjR.tags||!jjR.tags.culture||!jjR.tags.type||!jjR.tags.wealth||jjR.tags.lit===undefined);return{bad:jjBad.length,first:jjBad.slice(0,6).map(jjR=>jjR.name)};}
// Solstice sightline: a ray from the temple observer's eye (JJ_TEMPLE_OBS, stored by the temple builder in world
// space) along the solstice sunset direction must cross the arch planes (front face, centre, back face) inside
// the opening and hit nothing (instanced meshes included) within 200 m. clearance = metres from the crossing
// to the nearest edge of the opening (sides, threshold, round head), smallest over the three planes.
function jjSolsticeCheck(){if(typeof JJ_TEMPLE_OBS==='undefined'||!JJ_TEMPLE_OBS||typeof JJ_SOLSTICE==='undefined')return{ok:false,note:'no solstice temple placed'};
 const jjS=jjTempleSolve(),jjO=JJ_TEMPLE_OBS,jjEye=new THREE.Vector3(...jjO.eye),jjDir=KratorSky.sunDir(jjS.hour,jjS.day).normalize();
 const jjN=new THREE.Vector3(...jjO.archNormal),jjR=new THREE.Vector3(...jjO.archRight),jjA0=new THREE.Vector3(...jjO.archOrigin),jjPlanes=[];let jjInside=true,jjClear=Infinity;
 for(const jjF of [-.5,0,.5]){const jjC=jjA0.clone().addScaledVector(jjN,jjF*jjO.depth),jjDen=jjDir.dot(jjN);if(Math.abs(jjDen)<1e-6){jjInside=false;continue;}
  const jjT=jjC.clone().sub(jjEye).dot(jjN)/jjDen,jjP=jjEye.clone().addScaledVector(jjDir,jjT),jjD=jjP.clone().sub(jjC),jjU=jjD.dot(jjR),jjV=jjP.y-jjC.y;
  const jjTop=jjO.spring+Math.sqrt(Math.max(0,jjO.radius*jjO.radius-jjU*jjU)),jjIn=jjT>0&&Math.abs(jjU)<jjO.halfW&&jjV>0&&jjV<jjTop;
  const jjCl=Math.min(jjO.halfW-Math.abs(jjU),jjV,jjV>jjO.spring?jjO.radius-Math.hypot(jjU,jjV-jjO.spring):Infinity);
  jjPlanes.push({face:jjF,dist:+jjT.toFixed(2),u:+jjU.toFixed(3),v:+jjV.toFixed(3),openingTop:+jjTop.toFixed(2),inside:jjIn});if(!jjIn)jjInside=false;jjClear=Math.min(jjClear,jjCl);}
 const jjRc=new THREE.Raycaster(jjEye,jjDir,.05,200);jjRc.camera=camera;const jjObjs=[];
 scene.traverse(jjX=>{if(!jjX.isMesh||jjX.isSprite)return;for(let jjP=jjX;jjP;jjP=jjP.parent)if(jjP.userData&&(jjP.userData.probeSkip||jjP.userData.isGround))return;if(jjX.material&&jjX.material.type==='ShaderMaterial')return;jjObjs.push(jjX);});
 const jjHits=jjRc.intersectObjects(jjObjs,false).map(jjH=>({dist:+jjH.distance.toFixed(2),mesh:jjH.object.isInstancedMesh?(Object.keys(KIT.meshes).find(jjK=>KIT.meshes[jjK]===jjH.object)||'instanced'):(jjH.object.geometry&&jjH.object.geometry.type)||'mesh',instance:jjH.instanceId,point:jjH.point.toArray().map(jjQ=>+jjQ.toFixed(2))}));
 return{ok:jjInside&&jjHits.length===0,azimuthDeg:+jjS.azimuthDeg.toFixed(3),altitudeDeg:+jjS.altitudeDeg.toFixed(3),hour:+jjS.hour.toFixed(4),day:jjS.day,ryDeg:+(jjS.ry*180/Math.PI).toFixed(3),
  clearance:+jjClear.toFixed(3),throughOpening:jjInside,planes:jjPlanes,hits:jjHits.slice(0,12),nHits:jjHits.length,eye:jjO.eye.map(jjQ=>+jjQ.toFixed(2))};}
window._api={BUDGET,REG,get totals(){let jjTris=0,jjInst=0,jjMeshes=0;for(const jjK in TSTAT.by){jjTris+=TSTAT.by[jjK].tris;jjInst+=TSTAT.by[jjK].inst;jjMeshes+=TSTAT.by[jjK].meshes;}return{tris:jjTris,inst:jjInst,meshes:jjMeshes,registered:REG.length,types:Object.keys(TSTAT.by).length};},typeStats,regOccupancy,nanSweep,tagAudit,setView:(jjX,jjY,jjZ,jjTX,jjTY,jjTZ)=>setView(jjX,jjY,jjZ,jjTX,jjTY,jjTZ),views:()=>Object.keys(VIEWS),defs:()=>JJ.order.map(jjKey=>{const jjD=JJ.defs[jjKey];return{key:jjKey,name:jjD.name,family:jjD.family,tags:jjD.tags,w:jjD.w,d:jjD.d,h:jjD.h};}),furniture:()=>JJFURN.order.map(jjKey=>{const jjD=JJFURN.defs[jjKey];return{key:jjKey,name:jjD.name,tags:jjD.tags,w:jjD.w,d:jjD.d,h:jjD.h};}),flora:()=>JJFLORA.order.map(jjKey=>{const jjD=JJFLORA.defs[jjKey];return{key:jjKey,name:jjD.name,tags:jjD.tags,w:jjD.w,d:jjD.d,h:jjD.h};}),solsticeCheck:jjSolsticeCheck};
